### ISSUE TITLE
Help,Island protection and islands.yml problem

### ISSUE THREAD

**Issue by weekendsama** [tastybento/ASkyBlock-Bugs-N-Features#101]
My island server got a disk full problem .
First players tell me they have no island any more,then I stop the server and solved the disk full problem and I found my islands.yml is empty.
    so I deleted it and start my server and I get a quarantine folder and a new islands.yml. But players still have no island and players on their island the plugin tell them the island protection.
I need some help XD,I'm always running in offline mode by the way.

**Comment by tastybento** [comment]
When you delete the islands.yml, it uses the player files to rebuild it. If those too were unsaved or messed up, then maybe that is the reason the islands.yml is incomplete. Also check that the config.yml file has the correct settings as you had originally. You may need to do a world reset...

**Comment by weekendsama** [comment]
Thanks for your reply. I checked my config.yml file it has the correct settings. I don't know what's wrong with my islands.yml I think it's uuid problem,is there any way to check the uuid? And I want know why there is a quarantine folder.

**Comment by tastybento** [comment]
The quarantine folder is where player files are put if they are corrupted somehow. The console log will tell you, but they can be for example when the player file says they have an island, but there is no location in the file. Or if the island has been imported already and assigned to someone and another player has the same island location. This can happen if you moved from uSkyBlock or if the files are wrecked. In the last case, it tries to give the island to the most recent player.
