### ISSUE TITLE
ISLAND_CHALLENGE_LEVEL doesn't show up in chat

### ISSUE THREAD

**Issue by ponoyoshi** [tastybento/ASkyBlock-Bugs-N-Features#102]
Hi, just asking why the Island challenge level isn't showing for me... I can see the level but not the challenge level and everything is fine in my config I think

**Comment by tastybento** [comment]
Ok, we need more info. What chat plugin? What is the config string for the chat plugin and in the config.yml? What version of the plugins? What server version? Did it used to work but now doesn't? What changed? Does this happen to everyone or just some?

**Comment by ponoyoshi** [comment]
- I'm using PEX with an old version of ASkyblock.

-   ``` 
User:
   permissions:
    - venturechat.globalchat   
    options:
      default: true
      rank: '100'
      suffix: '[&7-&f] [{ISLAND_CHALLENGE_LEVEL}]'
```

Server version : craftbukkit-1.10.2-R0.1-SNAPSHOT-latest.jar

For the version I have of Askyblock I didn't remember which one is ..

This never worked fine for the ISLAND_CHALLENGE_LEVEL, just show nothing

This happens to everyone, every groups etc...

PS : If you know which permissions plugin I can use with Askyblock that could be nice for me

Thanks.

**Comment by tastybento** [comment]
Answer:

This is tricky. What i've found is that putting the tags into PEX does not work. PEX actually has to work in tandem with a chat plugin, e.g. Essentials Chat to show anything. The tags need to go into that plugin's config. For example, with Essentials Chat I use:

```
format: '&7<{DISPLAYNAME} &r({ISLAND_LEVEL})&7{ISLAND_CHALLENGE_LEVEL}>:&r {MESSAGE}'
```

This seems to work.

**Comment by ponoyoshi** [comment]
Yeah but the reason that I prefer to have prefix with a permission plugin is cause I already have a chat plugin fully configured and working, also I don't really want to remake a config for essentials Chat :[. there's really no permission plugin who can use this formats ?

**Comment by tastybento** [comment]
I don't know any other permissions plugins, sorry.  It's a pain that PEX does not expose the prefix/suffix to the API for it to be changed. I tried a lot of different ways but it doesn't. Sorry.
