### ISSUE TITLE
/is expel all - to expel every visitors from the island

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#105]

**Comment by tastybento** [comment]
Good idea, however, there is one player called "all"!

**Comment by tastybento** [comment]
Maybe /is expelall?

**Comment by Poslovitch** [comment]
Okay, no problem ;)

**Comment by tastybento** [comment]
or haw about **/is expel!** <- with the exclamation point?

**Comment by Poslovitch** [comment]
It's a bit unusual I think, but why not? :)

**Comment by tastybento** [comment]
Let's do it!
