### ISSUE TITLE
Add limits to (sticky) pistons

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#106]
As they may cause a lot-et-garonne of lags

**Comment by tastybento** [comment]
There is no way to quickly count non-entity blocks. You'll have to do it manually every time a player places a sticky piston. That will cause a lot of lag...

**Comment by Poslovitch** [comment]
Argh...
I think we should keep this and the others limits ideas, and wait&see.
