### ISSUE TITLE
Problem with the Chat on Skyblock

### ISSUE THREAD

**Issue by Mxtt5** [tastybento/ASkyBlock-Bugs-N-Features#108]
Hello.
I downloaded the "ASkyBlock" Plugin for 1.11.
But as I typed /is and went to my Island, the Chat has been spammed with:

"Title Befehl ausgeführt"    <--- sorry I'm German xD 
like there:

![2017-04-10_14 08 31](https://cloud.githubusercontent.com/assets/27211723/24861432/039fe90a-1df9-11e7-92fc-ba1f6ce83475.png)

Please help me as soon as possible!

Thank you for your support

**Comment by Mxtt5** [comment]
"Title- Befehl ausgeführt" means something like
"Title-Command performed"

**Comment by Poslovitch** [comment]
Yep. I think this is due to the title command that is executed to display «Entering on island» in action bar.
The question is : why it is sent multiple times?

What version of ASkyBlock are you using?

**Comment by Mxtt5** [comment]
Hello.I am using the newest Version Of ASkyBlock.My Server Version is 1.11.2.
I Solved the Problem w9ith /gamerule commandblockoutput false, So the Players cant see the message in the Chat.

But I think that it lsnt so Good for the Server Performance because it runs in the background.
I also have another question:Is bungeecord required to use the pluginbecause There is following situation:
If i leave the Server and join again, I fall into the void and die.Then I respawn at the normal spawn in the normal world.
Sorry for mistakes because I am German xD










-------------------------------------------Vom Smartphone gesendet--------------------------------------------------- Ursprüngliche Nachricht --------Von: "Florian C." <notifications@github.com> Datum: 10.04.2017  23:13  (GMT+01:00) An: tastybento/ASkyBlock-Bugs-N-Features <ASkyBlock-Bugs-N-Features@noreply.github.com> Cc: Mxtt5 <maxoette@sofortstart.de>, Author <author@noreply.github.com> Betreff: Re: [tastybento/ASkyBlock-Bugs-N-Features] Problem with the Chat on
  Skyblock (#108) 
Yep. I think this is due to the title command that is executed to display «Entering on island» in action bar.

The question is : why it is sent multiple times?
What version of ASkyBlock are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tastybento/ASkyBlock-Bugs-N-Features","title":"tastybento/ASkyBlock-Bugs-N-Features","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tastybento/ASkyBlock-Bugs-N-Features"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Poslovitch in #108: Yep. I think this is due to the title command that is executed to display «Entering on island» in action bar.\r\nThe question is : why it is sent multiple times?\r\n\r\nWhat version of ASkyBlock are you using?"}],"action":{"name":"View Issue","url":"https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/108#issuecomment-293080861"}}}

**Comment by tastybento** [comment]
Maybe these notifications were turned on on your server at some point? These notifications are also only ever visible to Ops and not normal players. They have no effect on performance.

Bungeecord is not required. It sounds like another plugin is reseting the login location. Try to find out which one by removing them one by one until it stops.

**Comment by tastybento** [comment]
I think all the questions have been answered so I'll close this now.
