### ISSUE TITLE
Limit mobs per island with permissions

### ISSUE THREAD

**Issue by google32465** [tastybento/ASkyBlock-Bugs-N-Features#109]
I think it would be really awesome to add a limit of mobs per island that we can set in the config that will be used by default

and then use a permission like askyblock.limit.mobs.100 to increase the mob limit to 100
Another example would be askyblock.limit.animals.20 to increase the animals limit to 20
And this should be each island

Thanks

**Comment by Poslovitch** [comment]
This isn't working with «mobs» or «animals» but with entity type (ZOMBIE, PIG, ...).

This is a good idea

**Comment by tastybento** [comment]
What will happen if players in the team have different permission limits?

**Comment by Poslovitch** [comment]
We will take the leader ones, as always ;)

**Comment by tastybento** [comment]
Won't be done. Perms are only available when the player is logged in. This is not a good approach.
