### ISSUE TITLE
Extra item when use give command on item-drop denied island

### ISSUE THREAD

**Issue by SaitDev** [tastybento/ASkyBlock-Bugs-N-Features#110]
When use `/give` item to player that is on a island has item-drop be disallowed, they will get an extra item (1 become 2, 50 become 51), also a Island Protected message appear for that player.

Tested when use give command by console, not sure when run by op.
Tested on spawn island, not sure when on player's island.

Latest release version: 3.0.6.2

**Comment by tastybento** [comment]
Hi - you are correct, this happens with the vanilla /give command. If you use Essentials, you don't see this problem.
The vanilla version works by actually forcing the player to drop items and pick them up again. This is very weird and there's no way to detect that this is going on. Also, if the island setting to allow visitors to pick up items is allowed, there is no problem. i.e., it's not the item-drop setting, but the item-pickup setting that causes it.
As there is no way to fix this, I must decline it for now. Sorry.

**Comment by SaitDev** [comment]
Thanks for the info. I will try some plugin that can add item to player's inventory
