### ISSUE TITLE
Question: What happens if players change their username?

### ISSUE THREAD

**Issue by YouGamePlayHD** [tastybento/ASkyBlock-Bugs-N-Features#111]
Hey,
I want to create a huge server network and for that, I need Nickname Change Support. So when a player changes his name on Mojang, he doesn't own his island any longer. Is there a possibility of adding a support of Name Changing? Or is there already some?
Info: My Server is on CRACKED mode.

**Comment by tastybento** [comment]
If the player changes their name on an offline server, then their UUID changes (their UUID is created based on their name on offline servers). There is nothing to help this - sorry. 
For online servers, the UUID says the same even though the name changes on Mojang.
