### ISSUE TITLE
un-cooped players able to get to island still

### ISSUE THREAD

**Issue by alexmarkey** [tastybento/ASkyBlock-Bugs-N-Features#112]
Using build 3.0.6,
Do not see any changes in 3.0.6.1 or 3.0.6.2 which indicate a fix in this.

How to replicate bug
#1 - Invite a player to your island
#2 - Cooped player logs off
#3 - Island owner removes the cooped player from the island
#4 - Team member logs back on and they get the notification that the island owner has removed me
#5 - Team member does /is and ends up on the island they were removed from
#6 - Team meber does /is coop (name) and is able to invite other players to the Island to inside / grief / do whatever they wish

**Comment by tastybento** [comment]
Good catch!

**Comment by imphases** [comment]
Fucking fit already, because of this shit I have lost over 2000 island levels. get your shit together ffs
