### ISSUE TITLE
Cannot create island at first install on a server

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#113]
It says "You cannot reset your island again".
Need to /asadmin clearreset before being able to create island.

**Comment by tastybento** [comment]
I cannot replicate this. Can you help identify the steps to replicate it?

**Comment by Poslovitch** [comment]
Create an empty server, put ASkyBlock 3.0.6.2 & required dependencies in plugins
launch server and try to create an island.

But I tried again today and it worked well... Weird.

**Comment by tastybento** [comment]
So, I don't know if it is related, but on 3.0.6 (not the latest), if an admin updates without fixing the island resets setting in config.yml, then their resets are set at zero because that was the default. i.e., the reset limit is now in the island: section. Maybe that was causing this?

**Comment by Poslovitch** [comment]
The setting is in the island section.
And so, maybe should we edit this default value? I'm sure it's because of that

**Comment by tastybento** [comment]
In the latest version, the default value is 2.

**Comment by Poslovitch** [comment]
Hum... Maybe this was due to updating.
Let's close this issue now.
