### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by pascalgoedeke** [tastybento/ASkyBlock-Bugs-N-Features#114]
Hello everyone,
the console displayed an error while starting ASkyBlock v3.0.6.2. I'm using Spigot 1.9.

> [12:32:58] [Server thread/WARN]: [ASkyBlock] Task #52 for ASkyBlock v3.0.6.2 generated an exception
> java.lang.NoClassDefFoundError: org/bukkit/potion/PotionData
> 	at com.wasteofplastic.askyblock.commands.Challenges.getPotion(Challenges.java:670) ~[?:?]
> 	at com.wasteofplastic.askyblock.panels.MiniShopItem.<init>(MiniShopItem.java:109) ~[?:?]
> 	at com.wasteofplastic.askyblock.panels.ControlPanel.loadShop(ControlPanel.java:126) ~[?:?]
> 	at com.wasteofplastic.askyblock.panels.ControlPanel.<init>(ControlPanel.java:66) ~[?:?]
> 	at com.wasteofplastic.askyblock.ASkyBlock$1$1.run(ASkyBlock.java:437) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
> 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
> 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
> 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
> 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
> 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
> Caused by: java.lang.ClassNotFoundException: org.bukkit.potion.PotionData
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
> 	... 12 more

Sorry for my bad englisch, I'm from germany.

**Comment by tastybento** [comment]
Update your server to a newer version and that will fix the problem.

**Comment by pascalgoedeke** [comment]
Thanks, which version it should be?
It's 1.9 now.

**Comment by tastybento** [comment]
Well, I'd upgrade to 1.11.2, but if you really want to stay on 1.9.x for some reason, at least update to 1.9.4. That should fix it. There were bugs in 1.9 and this potion class was missing.

**Comment by pascalgoedeke** [comment]
Thanks so much, it works. I've updated to 1.9.4.
