### ISSUE TITLE
[name] placeholder sometimes send player displayname, sometimes player name

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#117]
Replicated on 3.0.6.2

Should only send player name.

ex: "[!] {ADMIN} Pseudo is banned from the island"
but it should be "[!] Pseudo is banned from the island"

**Comment by tastybento** [comment]
You need to tell me the chat plugin and provide the settings for it.

**Comment by Poslovitch** [comment]
It's from ASkyBlock's locale

**Comment by tastybento** [comment]
Ah, okay I understand. What you are saying is that sometimes displayName is used, and sometimes just the player name. I'll check it.

**Comment by tastybento** [comment]
@Poslovitch Please check the commit and if you agree with it, close the issue.

**Comment by Poslovitch** [comment]
@tastybento This looks good. Thanks :)
