### ISSUE TITLE
Void problem.

### ISSUE THREAD

**Issue by im4g1n4t1onsX** [tastybento/ASkyBlock-Bugs-N-Features#118]
So i have the ASkyblock plugin and me and my friends liked it.
but when we fall in to the void we keep respawning over and over in the void. we have to quikly type /is home. Do you know a fix?

**Comment by tastybento** [comment]
Two options :

Set config.yml so you spawn on your island

Or

Set a spawn point. Use Essentials Soawn or set up an island spawn using /asadim setspawn
