### ISSUE TITLE
Maven deploy the new version for IslandPostLevelEvent

### ISSUE THREAD

**Issue by games647** [tastybento/ASkyBlock-Bugs-N-Features#119]
Could you please deploy the new version to the maven repository. I want to make use of the new event  IslandPostLevelEvent for resolving the ticket https://github.com/games647/ScoreboardStats/issues/194

**Comment by tastybento** [comment]
It is there already - 3.0.6.2 has it in.

**Comment by games647** [comment]
Sorry confused by the directory listening order.
