### ISSUE TITLE
Enable spawner types to have different level contribution values

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#12]
_From @tastybento on March 25, 2017 3:58_

Also enable Extreme spawners to contribute to level values.

_Copied from original issue: tastybento/askyblock#579_

**Comment by Poslovitch** [comment]
What are «Extreme» Spawners?

**Comment by Poslovitch** [comment]
_From @tastybento on March 27, 2017 5:6_

It's a (paid) plugin that enables spawners to be merged into one. Basically, if a player gets two spawners of the same type, they can squash them together into one that will spawn twice as often.

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#13
