### ISSUE TITLE
Limit nether portals

### ISSUE THREAD

**Issue by MineTheCube** [tastybento/ASkyBlock-Bugs-N-Features#122]
Hi,

I don't use the nether world of ASkyblock, but players can still create nether portals to spawn pigmen. But they are abusing by creating a huge amount of nether portals, so it could be great if we could limit to X portals per island.

You could use [PortalCreateEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/world/PortalCreateEvent.html) to monitor them.

Thanks!

**Comment by TheWranger** [comment]
Here's a possible/temporary fix:
Go into spigot.yml and change
enable-zombie-pigmen-portal-spawns: true
to
enable-zombie-pigmen-portal-spawns: false

**Comment by MineTheCube** [comment]
Well then no pigmen will spawn :/

**Comment by tastybento** [comment]
I don't see the abuse. If players are able to make portals (how do they get obsidian), why not let them? What's the down side?

**Comment by TheWranger** [comment]
You do realize that the chance of a pigman spawning from a nether portal is 1/2000 right?

**Comment by MineTheCube** [comment]
The issue behind this is that the server seems to spawn pigmen in priority over other monsters, so people with huge nether portals farms have a lot of mobs, while other mob farms have less.

Also obsidian isn't that hard to get, so it allows people to make pigmen spawn (and collect gold), but it was a bit unexpected that some would build so many nether portals that every other players are affected.

Adding a portal limit would still allow players to get pigmen, while prevent them from abusing it.
It could be either a portal limit (e.g. limit to 5 nether portals) or a portal block limit (e.g. limit to 100 nether portal blocks), or both.

**Comment by tastybento** [comment]
Hmm, this should be able to be handled by the zombie pigman entity limit. I'm not sure it prevents "natural" spawning due to portals, but it might.

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#80
