### ISSUE TITLE
Can i set limit villager per island

### ISSUE THREAD

**Issue by kit8379** [tastybento/ASkyBlock-Bugs-N-Features#126]
Now the setting is per team, if 4 player in the island the value will be 4 times.
Can i set limit per island?

**Comment by tastybento** [comment]
Yes. I think you can just set that in the entities limit section.

**Comment by kit8379** [comment]
I think it is not ok. I added a "VILLAGER: 70" in the entities limit section but player can still making a lot of villagers in the island.

**Comment by tastybento** [comment]
No, it does work. I just tested it. With VILLAGER: 70, they will be able to make up to 70 villagers but no more. This includes when villagers mate with each other.

**Comment by kit8379** [comment]
I cant do it, i tried already can i see your config settings ?

**Comment by tastybento** [comment]
I'm on my phone right now, but what version of the plugin are you using?

**Comment by kit8379** [comment]
the least version
