### ISSUE TITLE
Islandfly in nether

### ISSUE THREAD

**Issue by PixelatedHighDef** [tastybento/ASkyBlock-Bugs-N-Features#127]
Would love for askyblock.islandfly to work in the nether as well, as far as im aware and has been reported that this is not occurring

**Comment by Poslovitch** [comment]
Feature request accepted

**Comment by tastybento** [comment]
This is actually a bug. Island fly should work in the nether, and actually if a player logs out and back in, it does work. The issue is with the teleporting between the islands. I'm now fixing.
