### ISSUE TITLE
AcidIsland schematic error on startup

### ISSUE THREAD

**Issue by TheWranger** [tastybento/ASkyBlock-Bugs-N-Features#131]
https://pastebin.com/q0WA9ezf
No idea why it's supplying me with this error. None of my schematics have 'GUNPOWDER' in them.

**Comment by Poslovitch** [comment]
None of your schematics, but your chestItems have GUNPOWDER.
Replace it with SULPHUR, it's how it's called on bukkit

**Comment by TheWranger** [comment]
I don't have GUNPOWDER set as a chestitem

**Comment by tastybento** [comment]
This is fixable. Can you share the schematic so I can test ?

**Comment by tastybento** [comment]
Done in https://github.com/tastybento/askyblock/commit/4ee7c1e5d63c644777850665b059e8a26ff220dc
