### ISSUE TITLE
Islands do not get completely deleted

### ISSUE THREAD

**Issue by tastybento** [tastybento/ASkyBlock-Bugs-N-Features#133]
When players restart own island sometimes like this happen;
http://prnt.sc/ewx6z8

I have requested the following info because I think it is coordinate related:

1. Island distance
2. Island protection size
3. The coords for the island in the picture

**Comment by Poslovitch** [comment]
Same problem here : https://www.spigotmc.org/threads/askyblock.30325/page-201#post-2429867

**Comment by tastybento** [comment]
I just think the chunks don't get written by the server. Maybe the NMS isn't working so well on that server version, or the server craps out for some reason. The reporter said it got better with a smaller island.
