### ISSUE TITLE
Islands deleting

### ISSUE THREAD

**Issue by CrazyCroGamer** [tastybento/ASkyBlock-Bugs-N-Features#135]
After the server is online for like 1 - 2hours this happens
http://prntscr.com/exsqc9 ( Half islands gone )

Ofcourse before the restart we saved-all
In the log it says that the signs were removed, like maybe 5-6 players . (probbably because the world has some errors)
We tryed deleting " AskyBlock " folder and " ASkyBlock " world and start all over more than few times , but still, same problem.

Spigot: 1.8.8 latest
Ram: 6gb

**Comment by CrazyCroGamer** [comment]
Thanks for your shit report 0!

**Comment by CrazyCroGamer** [comment]
You reply to others, dont reply to me.

**Comment by tastybento** [comment]
I will close this if you dare swear again. I deleted your offending comment.

I do not know why this is happening. I expect it is your server or another plugin. What plugins do you run and what happens if you run ONLY Vault and ASkyBlock.
