### ISSUE TITLE
How do you fly at islands?

### ISSUE THREAD

**Issue by Zelkam** [tastybento/ASkyBlock-Bugs-N-Features#137]
I found the permission node askyblock.islandfly however how do you fly at islands? I can find no command to enable you to actually fly once at your island.

**Comment by dangerORclose** [comment]
askyblock.islandfly:
        description: Allow player to fly inside his island boundaries
        default: false

**Comment by tastybento** [comment]
There is no command. If you have the permission, you just double tap the space bar like in Creative Mode.
