### ISSUE TITLE
Idea for a feature

### ISSUE THREAD

**Issue by VikingOmu** [tastybento/ASkyBlock-Bugs-N-Features#138]
- Can you make the GUI from the starting island customizable?
I would like to be able to set the slot of the items, not just their order, if not, at least let us put some glass between them without having to put a schematic on them(Already tried that, it doesn't work).

- Compatibility with essentials chat.
I want to be able to put the island level into the motd message from essentialsx, could you maybe speak with them and try to fix? Thanks!

Idea by: BudderM4n14c, found in spigot commentaries:
- Compatibility with crates. (CratesPlus)
"Hi I was wondering if you could make it so we can up island level with a command, cause for crates I wanna make 1 slot so if it lands on it then it increases the island level, please :)"

**Comment by dangerORclose** [comment]
I think that level thing is allready possible, no?
Look for any placeholder that you can use.
I think it's allreaddy possible. Let me know :)

**Comment by tastybento** [comment]
I created #142 for your first point. 
Second request is already possible if you are talking about chat, I'm not sure motd can be changed.
For #3, I don't know. It'll need some checking.
