### ISSUE TITLE
Extend /is settings to both coop & visitors

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#14]
_From @Poslovitch on March 24, 2017 22:58_

Old idea: A menu to select what will the coop player be able to do

New idea: Like Landlord 
![ss 2017-03-26 at 03 44 54](https://cloud.githubusercontent.com/assets/20014332/24331775/47344d10-123b-11e7-93a0-80ec139ae92f.png)

In the /is settings, the leader will be able to select what the cooped players and the visitors can do.
(Purpose: avoid destruction while coop)

_Copied from original issue: tastybento/askyblock#573_

**Comment by Poslovitch** [comment]
_From @tastybento on March 25, 2017 3:24_

I don't like this - too complicated.

**Comment by Poslovitch** [comment]
Please check again: I edited this idea

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#15
