### ISSUE TITLE
Unable To Add Modded Items To Block Values

### ISSUE THREAD

**Issue by DragaoNimhe** [tastybento/ASkyBlock-Bugs-N-Features#140]
Hello, as my title states I've noticed that the config file for block values does not allow the addition of modded items. Since we are using this plugin on SkyFactory I would like to be able to do that. Any chance of that functionality being added? Thanks for taking the time to make this plugin, I love how easy it is to work with!

**Comment by CathalCraft** [comment]
Would love this feature to be added!

**Comment by Rttlr316** [comment]
Yeah my server has the same problem, would love to be able to do this for it

**Comment by morfie78** [comment]
I certainly agree!  I've been having the same issue.  The island values on my server don't include the SF items.  This would be great!

**Comment by tastybento** [comment]
How would the modded items be defined? Are they just integers, like 456? Maybe with durability/damage settings, like 456:45? Or are they something else?

**Comment by DragaoNimhe** [comment]
minecraft's items are defined by "minecraft:itemname". I would like the ability to choose what prefix to use, instead of the plugin assuming that prefix is "minecraft:". For example, "BigReactors:itemname".

**Comment by morfie78** [comment]
They have IDs and sub-IDs, (ie. 4591  and 4703:34) as well as corresponding names "BigReactors:itemname".

**Comment by DragaoNimhe** [comment]
It says support for numbered ID's will be removed in the future, not sure how seriously to take that though. Adding support for a different word ID prefix would work better with the way your config is set up currently for sure, though; since it uses itemname ID's already. :)

**Comment by morfie78** [comment]
The only issue with that @DragaoNimhe, is that some items in modded SF don't have item ID names, only numbers.

**Comment by DragaoNimhe** [comment]
Ooh, you are correct, some of the mods seem to have many of their items named the same thing. Perhaps numbers would be easier to use then.

**Comment by morfie78** [comment]
@tastybento Programmatically, when you read in the config (or maybe the first time an Item ID is used), could you check if the first character is a number, and if so, treat it as a numerical item ID, otherwise treat it as a string item ID and prepend the "minecraft:"?

**Comment by tastybento** [comment]
This commit allows ID numbers to be used and doesn't try to covert them into Bukkit Materials. That should work. 
https://github.com/tastybento/askyblock/commit/a6f32c72864be92c5d937d126aaa3b4542402748
