### ISSUE TITLE
Problem with Island Settings

### ISSUE THREAD

**Issue by AconTM** [tastybento/ASkyBlock-Bugs-N-Features#141]
I Have Change the Config.yml to this:
http://i.epvpimg.com/EvQecab.png

But "/island settings" still look like this:
http://i.epvpimg.com/vbXMdab.png

I do:
- Restart Server
- /asadmin settingsreset all

but it doesnt work :( pls help

**Comment by dangerORclose** [comment]
And after you do that setting, and then you do /asadmin reload. ?
Also, are you editing config.yml and not colfig.old.yml.
Is that file removed?

**Comment by AconTM** [comment]
yes i do /asadmin reload & no im not Editing the old :/

**Comment by Poslovitch** [comment]
These permissions won't work : you must put the setting in uppercase : 
askyblock.settings.FURNACE

**Comment by AconTM** [comment]
but the Settings Work :D Only the GUI doesnt work

**Comment by tastybento** [comment]
Yes, the GUI does not change. This needs investigation.

**Comment by tastybento** [comment]
@AconTM Thanks for the report. This is fixed and will be in 3.0.6.3.
