### ISSUE TITLE
Add option to disable plugin's protection

### ISSUE THREAD

**Issue by HeberonYT** [tastybento/ASkyBlock-Bugs-N-Features#144]
**Hello!**
I have a request for you.
I currently have a very active public server, it is kcauldron in minecraft 1.7.10
I am administering the protections to the middle of the system of chunks that incorporates FTBUtilities, is ideal to protect anti griefing, of the caused by machines and tools of other mods.
But it is annoying and complicated for new players, having to explain to everyone that to share their island with friends, they should add them to the FTBUtilities system and also invite them to the island with the / island invite or / island coop command.
It's twice as much work to have two protections on top.
I ask you to include in your plugin settings file an option to disable the protection of the islands, this will allow you to manage it with some other plugin or mod.
_**Regards!**_

**Comment by Poslovitch** [comment]
This is a good idea, but I should remember you we will officially drop support for 1.7.X in our next major release : 4.0.

**Comment by tastybento** [comment]
All protections can be switched off in the config.yml. Just set them to false or true as appropriate.
