### ISSUE TITLE
Plugin doesn't take care of (tile) entity limits in the Nether

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#147]
Replicated on 3.0.6.2 : (tile) entity limits are not applied in the Nether.
E.g :
MOB_SPAWNER: 6 ; in the config
The player can place up to 6 MOB_SPAWNER in the Overworld
The player can place as much MOB_SPAWNER as it wants in the Nether

**Comment by tastybento** [comment]
Note that if the entity limit is 6, then the player can place 6 in each world. It works for entities, but not the block entities (like MOB_SPAWNER). Fixing now...

**Comment by tastybento** [comment]
Fixed with tastybento/ASkyBlock#63f0bf0
