### ISSUE TITLE
Disable "island history" messages sent to players on join

### ISSUE THREAD

**Issue by Coolguy3289** [tastybento/ASkyBlock-Bugs-N-Features#148]
Hello! 

I am wondering if there is a way to disable the ASkyblock news message that appears when you join the server?

**Comment by Poslovitch** [comment]
This message is only sent to the OP or players who have askyblock.admin perms.
You can disable it by setting "checkupdates" to false

**Comment by Coolguy3289** [comment]
The News message I am talking about isn't about the plugin itself. It is stemming from events that have happened in the ASkyblock world (Islands Leveling Up, People Dying, etc.).

**Comment by Poslovitch** [comment]
I don't understand what you're talking about.
Can you send a screenshot?

**Comment by Coolguy3289** [comment]
Interesting, I just logged on for the first time today, and it didn't appear. But the messages I am talking about are actually being sent from the messages.yml file. I will post a snippet as an example.
`  d4353054-b8ff-4be6-877b-406f10fe405f:
  - §a(10 died!)
  - §a(10 died!)
  - §a(10 died!)
  - §a(10 died!)
  - §a(10 died!)
  f0024437-adf1-4c04-a9c7-5fb57cc86322:
  - §a(10 died!)
  - §aIsland level is §f828
  - Jokers§r unlocked the island
  - Jokers§r locked the island
  - §a(10 died!)
  - §aIsland level is §f825
  - Jokers§r unlocked the island
  - Jokers§r locked the island
  - §aIsland level is §f1159
  - §aConstantHits is banned from the island!
  - §aJBubba15 is banned from the island!
  - §aCrytrax is banned from the island!
`

**Comment by Poslovitch** [comment]
Ah I see!
Why would you like to disable them?

**Comment by Coolguy3289** [comment]
Yes!
