### ISSUE TITLE
Enchanted stuff in Challenges

### ISSUE THREAD

**Issue by Affekaffe** [tastybento/ASkyBlock-Bugs-N-Features#149]
So, the title says much, an update where you could ask for enchanted stuff in the Challenges would be really appreciated. Unless I've missed something (which I do often) you can't take items in Challenges right now, would be a good feature! 
Thanks

**Comment by Poslovitch** [comment]
This is handled in #10 ;)
Closing

**Comment by Affekaffe** [comment]
Yep, said it, I missed something again :P
