### ISSUE TITLE
Support numeric IDs for everything (chestItems,...)

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#15]
_From @Poslovitch on March 24, 2017 21:38_

Will be easier to use ;)

_Copied from original issue: tastybento/askyblock#571_

**Comment by Poslovitch** [comment]
_From @tastybento on March 25, 2017 3:24_

How do you mean? Numerical IDs are deprecated vs Materials. Also, where are they not supported?

**Comment by Poslovitch** [comment]
The numerical IDs are deprecated, but still supported in Spigot. I received this suggestion and they also told me that when you have to edit every items from the challenges it is really long

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#17
