### ISSUE TITLE
wasteofplastic listener

### ISSUE THREAD

**Issue by SlimeDog** [tastybento/ASkyBlock-Bugs-N-Features#151]
Spigot 1.11.2, aSkyBlock-3.0.6.3

Several of these on start-up. Began with 3.0.6.2.

> [20:53:34] [Server thread/WARN]: [ASkyBlock] "ASkyBlock v3.0.6.3" has registered a listener for com.wasteofplastic.askyblock.events.IslandLevelEvent on method "public void com.github.games647.scoreboardstats.variables.defaults.ASkyBlockVariables.onLevelUp(com.wasteofplastic.askyblock.events.IslandLevelEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Tastybento].

**Comment by tastybento** [comment]
This is just a deprecation warning and not an issue. I assume you use the plugin scoreboardstats? The error is weird though because it is that plugin that should be called out for making the call.

**Comment by SlimeDog** [comment]
I try to go after warnings. I'll post to ScoreboardStats.

**Comment by SlimeDog** [comment]
Is this in the expansion? Who is responsible for keeping that up-to-date?

**Comment by tastybento** [comment]
I'm pretty sure the ScoreboardStats guy contacted me so I think there should be an update soon that removes the warning.

**Comment by Poslovitch** [comment]
ASkyBlock calls IslandLevelEvent in 3.0.6.x. I didn't remove the call in order to avoid breaking instantly all the plugins that use this deprecated event.
I totally removed IslandLevelEvent in pull request 629.

**Comment by tastybento** [comment]
We fire the event, but we don't register a listener for it. I think that's not causing the error reported.

**Comment by Poslovitch** [comment]
Well, that is strange. Maybe this feature from Bukkit is buggy?
