### ISSUE TITLE
Customisable Island

### ISSUE THREAD

**Issue by MrFluffySpine** [tastybento/ASkyBlock-Bugs-N-Features#152]
Can you make it so people can build their own skyblock then worldedit it and type /setmap skyblock
This would be very helpful if people wanted to make different sections to their skyblock world

**Comment by tastybento** [comment]
This is possible right now except you have to define the schematic in config.yml. There are a number of settings that need to be set. Have a look through the schematicsection at the end of config.yml. Does that answer your question?
