### ISSUE TITLE
Levers/Buttons

### ISSUE THREAD

**Issue by SjakeCraft** [tastybento/ASkyBlock-Bugs-N-Features#153]
I can't turn off lever and button use by visitors. It is turned off in the config.

**Comment by tastybento** [comment]
The setting in the config is for new islands. You need to do /asadmin settingsreset (name of setting). Hit Tab in the console to see the options.

**Comment by Poslovitch** [comment]
I know what is the problem.
Levers/button are not in the "island" category, so it isn't displayed.

I will add it and clarify a bit the comments
