### ISSUE TITLE
Nether + flymode

### ISSUE THREAD

**Issue by paran001k** [tastybento/ASkyBlock-Bugs-N-Features#154]
Can u fix the problem with Nether and flymode?
Basicly flymode is work v.well, but when u tp on nether, flymode will off. For activate is back, need tp on hub server and go on server again - its turn on flymode. But if use portal or "/is go" - flymode on main island will be offlane againe.

**Comment by Tissandre** [comment]
What is the version do you use ?
The version of the plugin.

**Comment by paran001k** [comment]
ASkyBlock V3.0.6.3
and server use 1.10-1.11.2 minecraft versions. On all versions of minecraft bug is work =(

**Comment by Tissandre** [comment]
Mmmmh strange,
Do you use another plugin with fly command/enchant like "crazy-enchantements" ?

Because I had the same problem but with version 3.0.6.3 this was corrected.

**Comment by Poslovitch** [comment]
This is not a bug, this is just not implemented ;)

**Comment by Poslovitch** [comment]
Duplicate of #127, closing
