### ISSUE TITLE
Needing more points for each Island level?

### ISSUE THREAD

**Issue by alexmarkey** [tastybento/ASkyBlock-Bugs-N-Features#155]
I am unable to find any documentation for this change.

I have been using ASkyBlock for well over 3 yeras now.  After recently updating to the latest build, from a much older build, I have noticed that now as players level up, they require more than 100 points per level.

For example - Level 5 I need 104 points to get to level 6.
We have some players needing 2000+ points to get to the next level.

I can not find any documentation on this change, nor the algorithm on how the levelling works now.  From what I see in the blockvalue.yml, it still has the option to define how many points per level, which is extremely misleading as it no longer works.

Not sure if this is a bug or feature?

**Comment by alexmarkey** [comment]
Played around with it for a bit, and I am noticing really strange behaviour.

I got my island to level 505 with 6 points remaining for level 506.
After waiting 1 minute, without placing nor destroying any blocks, I now require 32 points for level 506

The longer i wait, the more points I require for the next level.

**Comment by tastybento** [comment]
That is very strange behavior! The level system hasn't changed for a long time except to add an indication of how many blocks are required until the next level. 

I recommend you run the island level command in the console for your player. This will give you a full breakdown of the calculation and then you can compare the difference. Let me know!

**Comment by tastybento** [comment]
Btw, I mean /asadmin level (name)

**Comment by SaitDev** [comment]
Got this bug on my sever too. Not all people got it. He is a member in an island. If he run /is level himself will give the result -40lv and need 5xxxx point to reach -39lv. But when we run /is level <otherMember> it works fine and gives same lv. I suggested him tried reset death by rejoin the team but not much change, the level just increase from -89 to -40.

**Comment by tastybento** [comment]
If the player is in a team, the level depends on the team leader's deaths. If sumteamdeaths is true, then the death penalty is determined by all the team member's deaths. As the level improved when he left and rejoined, it sounds like the setting teamjoindeathreset is true. What settings do you have in blockvalues.yml?

**Comment by SaitDev** [comment]
yes sumteamdeaths is true, but it doesnt cause by deaths. when other member or leader run /is level the result level of island is over 450. the problem only appear when that play run /is level or run by other people /is level [thatbuggyplayer]
my blockvalues.yml https://pastebin.com/a3CghDSS

**Comment by tastybento** [comment]
Okay, just to be clear, what @SaitDev is reporting is different to the OP.

Just to clarify: If player runs /is level himself, he gets a different result to when other team members or the leader run the command.

In the console, do as **admin level <team leader name>** and then do as **admin level <thatbuggyplayer>** and share the results of both of them.

**Comment by SaitDev** [comment]
the leader: https://pastebin.com/7UTnf4Wm
the buggy member: https://pastebin.com/6a56e9U3
Tried it on 3.0.6.5. Should i try on latest 3.0.6.6?

With ur suggestion, i realize it calculates another island for buggy member. here is the island info after re-calculate the level of leader: https://pastebin.com/ugfgkcVe

**Comment by SaitDev** [comment]
Check the islands.yml got the island that belong to the buggy player 
`- -5700:115:600:100:300:6242f0fc-4acd-3909-8cc6-cb0514df951b:false:false:10000000000001100010100000000100111000110000111:PLAINS:3`
though he have already joined another island at `6300-115-4200`?

**Comment by tastybento** [comment]
Ah, interesting. I bet if you look at the player's file in players/6242f0fc-4acd-3909-8cc6-cb0514df951b.yml he will be listed in the wrong team.
The latest version tries to fix broken teams like this. Alternatively, you can edit his file directly when he is offline.

**Comment by SaitDev** [comment]
His data file is correctly though https://pastebin.com/kDkBzni2. I will try the latest version and delete the island at -5700:600 in island.yml when my server is in maintance

**Comment by tastybento** [comment]
What an happen is that another team leader still has him listed as a member. This is the bug I think.

**Comment by SaitDev** [comment]
Update: Deleted the old island at `-5700:115:600` in islands.yml then everything works fine for the bugged player now. I still wonder why it wasnt deleted when him joined another island

**Comment by tastybento** [comment]
Okay thanks. Closing this for now.
