### ISSUE TITLE
Island visual border - Suggestion

### ISSUE THREAD

**Issue by blijgozertje** [tastybento/ASkyBlock-Bugs-N-Features#157]
Could you make an option to set a visual world border around every island that would look awesome (some servers already have this but idk how to do it)

**Comment by VikingOmu** [comment]
Try with a schematic, modify the default schematics and add a border at the end of the island area. Try placing a 1 block height wall made by, maybe red wool, as your "border" then copy the schematic and save it.

**Comment by tastybento** [comment]
I don't know how to do this...

**Comment by Poslovitch** [comment]
NMS. Display an "fake" worldborder around the island.

**Comment by blijgozertje** [comment]
I googled and some people said this?
https://github.com/ysl3000/WorldBorderAPI1.8-

**Comment by blijgozertje** [comment]
Ups didnt mean to close it.

**Comment by Poslovitch** [comment]
Looks good, but we'll have to implement it in the plugin itself, using an external API isn't so good.

**Comment by Poslovitch** [comment]
@tastybento ?

**Comment by tastybento** [comment]
I've done it in the past with barrier blocks (see Beaconz) but they were transparent. Making it shimmer will probably require NMS like you say @Poslovitch . Let's look into it.

**Comment by Poslovitch** [comment]
I think barrier blocks are too much «spammy» for eyes. A fake worldborder would be better, the player will see it and will be able to go through.
Sure, it will be optionnal ^^

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#34

**Comment by MrDarkness462** [comment]
Or you can use my customised plugin:
https://www.spigotmc.org/resources/island-border-askyblock-bentobox-uskyblock-acidisland.56320/
