### ISSUE TITLE
Commands executed for the old leader after /is makeleader

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#159]
It executes commands like the old leader left/joined an island. It shouldn't

**Comment by tastybento** [comment]
Can you explain more? I don't understand.

**Comment by Poslovitch** [comment]
It seems that commands (startcommands, leavecommands or others) are executed when a leader do /is makeleader. Nothing is executed for the new leader, but it's like the old one joined or left the island.

**Comment by tastybento** [comment]
Ah, okay. That makes sense. It uses the some similar methods. I'll look into it.

**Comment by tastybento** [comment]
It also looks like leaders lose a reset when they give up the island.
