### ISSUE TITLE
Visitors can place blocks on islands. [Bug]

### ISSUE THREAD

**Issue by Wekylend** [tastybento/ASkyBlock-Bugs-N-Features#161]
I'm currently having an issue with visitors being able to place blocks on islands. I read the FAQ, looked to see if it was a permissions problem (which it isn't) and there is no indication of an error in the console. 
I've tried everything I could think of to fix this problem including re-setting up ASkyBlock from scratch and changing the WorldGuard version multiple times (idk if the protection is handled by WorldGuard). 

I'm running ASkyBlock on Spigot 1.8.8.

**Comment by Poslovitch** [comment]
ASkyBlock handles protection itself, it doesn't need WG.
If visitors are able to place blocks on islands, that's because the default config or the island owner allow them to.
Please send the "island" section from your config.yml

**Comment by Wekylend** [comment]
Here is the "island" section from my config.yml: https://pastebin.com/6TbXjPrh
Here is the other "island" section from my config.yml regarding the island settings: https://pastebin.com/v1SjgPBr

I forgot to specify that when a visitor places a block, in chat it says "Island Protected" but the block is allowed to be placed.

**Comment by tastybento** [comment]
There must be another plugin that is overriding the Askyblock protection. You can confirm this by running a server on your own machine and just running Askyblock and Vault. Then add plugins one by one until you see the issue.

**Comment by Wekylend** [comment]
So it seems that versions: worldguard-6.0.0-beta-05 and worldguard-6.1 can override the Askyblock plugin protection. I tested until version worldguard-6.0.0-beta-04 and that doesn't seem to override the Askyblock protection.

**Comment by tastybento** [comment]
@Wekylend That's useful information - thanks!
