### ISSUE TITLE
NumberFormatException with invalid numeric permission

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#166]
https://www.spigotmc.org/threads/askyblock.30325/page-192#post-2384101
https://pastebin.com/f6T2z0Ys

This error is thrown because there is no check to see if the argument is a number.

I'm working on it.

**Comment by tastybento** [comment]
All the numerical permissions did not have checking on them, so errors would occur with for example: 

- askyblock.team.maxsize.abc
- askyblock.island.maxhomes.abc
- askyblock.island.range.abc
- askyblock.island.multiplier.abc

**Comment by tastybento** [comment]
Interesting, if the player has permission askyblock.island.range.abc then their protection range will be set to zero! This could be why some admins are seeing players lose their ability to use their islands.
