### ISSUE TITLE
Feature: Preserve Island Protection Range on Reset

### ISSUE THREAD

**Issue by fordross** [tastybento/ASkyBlock-Bugs-N-Features#167]
Sorry if I'm totally missing it, but the protection range specified in config.yml is automatically applied to islands when reset.  Might it be possible to either offer an option to preserve the user's range when they reset their island, or keep that range automatically?

**Comment by tastybento** [comment]
If the user has their range defined by permission, they will keep it. So the trick is to use that.

**Comment by fordross** [comment]
Perfect, thanks!
