### ISSUE TITLE
Some islands bugged

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/ASkyBlock-Bugs-N-Features#170]
Since last days, users have complained about island lost. Some of them have two islands (if I do /asadmin info user it shows the location of island 1 and if I do /asadmin info on another island, it shows me that the same player owns de island). Others islands have no owners. And other strange things.

**Comment by tastybento** [comment]
Assuming nothing else changed - like island distance - it sounds like islands.yml is out of sync with player files. Take back ups but you can try stopping server, deleting islands.yml and restarting. Look for errors in the console. You will need to recreate spawn if you used setspawn.

**Comment by YellowZaki** [comment]
I've deleted islands.yml, I got these errors, I don't know if they are significant:
https://pastebin.com/3rXAXmWV

**Comment by tastybento** [comment]
Could you share a zipped copy of your players folder? Maybe dropbox it? I'd like to see what's going on here.

**Comment by YellowZaki** [comment]
https://www.dropbox.com/s/79qzh0f3obxnq1h/players.rar?dl=0

**Comment by tastybento** [comment]
Strangely, that worked perfectly. I'm not sure why those errors occurred. Hmm.

**Comment by YellowZaki** [comment]
Since I deleted islands.yml, /is settings doesnt work anymore. "The command can be done at this moment"
Any error in console

**Comment by tastybento** [comment]
What version of the plugin are you using?

Is your config.yml up to date? Did you update it to the new 3.0.6.x version? There's a section on protection: at the end where each protection setting is listed for the world and the island. Please share your config.yml to confirm.

**Comment by YellowZaki** [comment]
I'm using 3.0.6.3.
Here is my config: https://pastebin.com/Pkerehi2

**Comment by tastybento** [comment]
I get the same errors with that config. I'll work out why it's happening.

**Comment by YellowZaki** [comment]
That will fix the island loss issue?

**Comment by tastybento** [comment]
If you delete islands.yml and restart, it should rebuild islands.yml properly now. That should fix the issue. Let me know.

**Comment by YellowZaki** [comment]
It rebuilt islands.yml successfully :D 
There are +28.000 userfiles with no island, how much I would like to remove them.
One question, an userfile is in a folder named quarantine, can I safely remove it?

**Comment by tastybento** [comment]
Understood on the user files. With 4.0, purge will remove them.

The Quarantine could be removed, it's there just in case a player complains.
