### ISSUE TITLE
Tons of issues

### ISSUE THREAD

**Issue by augesrob** [tastybento/ASkyBlock-Bugs-N-Features#171]
01.05 11:14:32 [Server] ERROR [FeatherBoard] Error in placeholder: {askyblock_island_level}
01.05 11:14:32 [Server] ERROR [FeatherBoard] Error in placeholder: {askyblock_team_leader_name}

/island does nothing but show /island help

**Comment by Poslovitch** [comment]
There are currently no placeholders in ASkyBlock.
These errors come from FeateherBoard

About /island, it is supposed to display the control panel (if enabled), create an island (if player doesn't have) or teleport to the island.
What version are you using?

**Comment by AntiSpace1** [comment]
me too i just started a server in 1.8 and i play in extremecraft when i use any askyblock command it says /island help even when i do / island help

**Comment by augesrob** [comment]
@Poslovitch I honestly don't know the cause, Downgraded to previous spigot build works just fine now.

**Comment by Poslovitch** [comment]
@AntiSpace1 Are you using 3.0.6.4?

@augesrob Tastybento compiled 4.0 in 3.0.6.4, resulting in a plugin desactivation at startup. That's why there is errors.

**Comment by AntiSpace1** [comment]
i use the latest version

**Comment by AntiSpace1** [comment]
is it a problem

**Comment by augesrob** [comment]
Do i need to reset everything skyblock to make this work? Or is there a guide to fix config?

**Comment by AntiSpace1** [comment]
i reseted the server
it is new

**Comment by AntiSpace1** [comment]
@Poslovitch

**Comment by AntiSpace1** [comment]
what i need to do

**Comment by Poslovitch** [comment]
Just use 3.0.6.3.
3.0.6.4 is not functionnal at all. This is not the good version.

**Comment by Poslovitch** [comment]
3.0.6.4 fixed :
https://www.spigotmc.org/resources/askyblock.1220/update?update=159847
