### ISSUE TITLE
Add modded items to minishop

### ISSUE THREAD

**Issue by HeberonYT** [tastybento/ASkyBlock-Bugs-N-Features#172]
In the minishop.yml file how can I sell items and blocks of mods? I tried to add the ID or the name but it does not appear in the market, I hope your help, thank you.
![screenshot_6](https://cloud.githubusercontent.com/assets/13698597/25585549/cf57b98e-2e60-11e7-832e-130fbd9294f9.png)

**Comment by Poslovitch** [comment]
This is currently not supported.
I'm working on that

**Comment by HeberonYT** [comment]
Perfect!!
Thank you
