### ISSUE TITLE
Visitors can open chests on islands when holding item

### ISSUE THREAD

**Issue by Svennohz** [tastybento/ASkyBlock-Bugs-N-Features#173]
If you left-click a chest a few times and right-click it at the same time with an item in your hand you can just open the chest on other peoples islands
 
ASkyBlock V3.0.6.4

Video: https://youtu.be/adx2r4rLJBs

(don't mind the hacked client, it has nothing to do with it)

**Comment by Svennohz** [comment]
Chest use is disallowed everywhere

**Comment by Poslovitch** [comment]
This does not make any sense, but we'll have a look

**Comment by Svennohz** [comment]
http://prntscr.com/f3a41r - my plugins list if it has something to do with that

**Comment by Svennohz** [comment]
It's also happening for furnaces and hoppers.

**Comment by Svennohz** [comment]
I can provide everything you want if needed, maybe it's because I changed the Skyblock world from ASkyblock to Skyblock in the config.yml. I don't know tbh

**Comment by Svennohz** [comment]
Closed the issue as this was caused by another plugin.
