### ISSUE TITLE
Challenges not working?

### ISSUE THREAD

**Issue by philman247** [tastybento/ASkyBlock-Bugs-N-Features#177]
Okay, so i've setup everything working and in order. But when i try to use /asc or /challenges, it opens the menu but when i click on a challenge, it does nothing but re-places the item back into its slot. Help?

**Comment by tastybento** [comment]
What does it say in the chat? Usually, if you don't have what is required, it'll say something. Or have a look in the console log for errors. Unless you give us more info, we can't help.

**Comment by philman247** [comment]
it just doesnt say anything.. would you mind jumping on the server? 162.223.8.171

**Comment by philman247** [comment]
nothing in the console either.

**Comment by tastybento** [comment]
I could have a look, but it'd be better for you to share your challenges.yml file and tell me which challenge is not working.

**Comment by philman247** [comment]
its the default challenges.

**Comment by tastybento** [comment]
I went to his server and this is a bug with 1.8. It works fine with 1.8.8. He will use a later server version.

**Comment by philman247** [comment]
one more thing! Controlling monster spawning... they spawn too frequent.

**Comment by tastybento** [comment]
It seems that the equality check of ItemStack in 1.8 is not working. I don't think we're going to fix this one.
