### ISSUE TITLE
Command to reset player death count

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#179]
"resetdeaths <player>" - set to 0 for the specified player
"resetdeathsall" - set to 0 for every player

**Comment by tastybento** [comment]
Shouldn't be too difficult - setdeaths <player> <number> already exists. I recommend using the same method for resetting all players as with cleareset all.

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#76
