### ISSUE TITLE
Temp permission in spawn

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#18]
_From @SaitDev on March 19, 2017 21:18_

Since 3.0.6 bring new feature that can give player temp permissions when they are in their island.
It would be great if we can grant player some temp permissions when they are in spawn too

_Copied from original issue: tastybento/askyblock#556_

**Comment by Poslovitch** [comment]
_From @tastybento on March 19, 2017 22:24_

Not a bad idea.

**Comment by Poslovitch** [comment]
Add this for 4.0?

**Comment by SaitDev** [comment]
a bit wonder why should move bug and feature issues to here?

**Comment by Poslovitch** [comment]
It is due to how "permissions" work on Github : all or nothing.
Having this repo dedicated to issues will make Tasty able to "recruit" issues managers, like me, without giving them by the way the "god mode" on the official repo.

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#20
