### ISSUE TITLE
Question about 4.0

### ISSUE THREAD

**Issue by DragaoNimhe** [tastybento/ASkyBlock-Bugs-N-Features#181]
Hello, my apologies if this is not the correct place to post this as it is not an issue with your current plugin, though I suppose it could count as a feature request. Myself and my fellow staff members have recently created a SkyFactory server that runs on 1.7.10. After thorough investigation of all island plugins, we decided on yours because of your high activity and far superior config options. We are EXTREMELY happy with the plugin and I was absolutely devastated when I read today that you will be removing support for 1.7.10 in your next update (which we already have another feature request included in). Our server is thriving after less than a month of uptime and I strongly believe it is partially due to your amazing island plugin. Switching to a different plugin at this point would not only be potential death for our server (as we would have to reset all islands), but I feel it would greatly lower the quality of our server as yours is by far the best. I understand that this is a LOT to ask, but is there any way you would consider keeping support for 1.7.10 in your 4.0 update? A lot of servers that use your plugin are still on that version of MC, I can't imagine I'm the only one who feels this way! Thank you for taking the time to make and maintain this incredible plugin, and know that we appreciate all your hard work!

**Comment by tastybento** [comment]
So, we're not going to explicitly remove support, but we're going to stop testing on 1.7.x because only 3% of the installed base use it (about 42 servers) and it's a lot of work for us. Going forward things *should* work, but with the newer versions out, we can't keep up with the testing. Maybe you could track 4.0 progress when we start releasing beta's and you can test them to see if there are any problems. If there are, file a bug and we'll look at fixing them.

**Comment by DragaoNimhe** [comment]
You guys are truly incredible. Thanks so much for this, and I would be happy to assist you in any way possible. I'm the newest on our team to the server management game but I am having a blast learning and I have people with a lot more experience helping me out; so hopefully through our combined efforts we can actually be of assistance!

**Comment by Poslovitch** [comment]
@DragaoNimhe Join our Discord server (https://discordapp.com/invite/ur8EPYS), we might need your help when testing 4.0
