### ISSUE TITLE
Schematics loading errors in console

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#182]
https://www.spigotmc.org/threads/askyblock.30325/page-196#post-2397089

https://hastebin.com/gagagudilu.md

**Comment by tastybento** [comment]
This is not our bug. This is where the schematic is corrupted somehow. I've seen this a lot with players who have servers that don't have UTF-8 on them. See the error ¦RON_¦NGOT - the I is being replaced by the | character. I've no idea why that happens.
