### ISSUE TITLE
Add option to disable island level

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#191]

**Comment by tastybento** [comment]
It's askyblock.island.info permission.

**Comment by Poslovitch** [comment]
The idea is to disable everything about the level : commands, blockvalues, etc...

**Comment by tastybento** [comment]
Hmm, maybe but those can be blocked by perms too. When do perms need to become config settings?

**Comment by Poslovitch** [comment]
As it will become an addon, this will be disabled if it isn't installed
