### ISSUE TITLE
Make island enter/exit message in action bar colorable

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#194]

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#23

**Comment by mikroskeem** [comment]
Can I open PR implementing this feature?

**Comment by Poslovitch** [comment]
Not on ASkyBlock, we don't allow new features as of 3.0.7.
You probably can do that on BSkyBlock, however, the config handling has not been fully implemented yet.

**Comment by mikroskeem** [comment]
Alright, then I'll leave this up to maintainers of BSkyBlock and continue with my fork :smile:
