### ISSUE TITLE
Prevent people from changing the Language

### ISSUE THREAD

**Issue by google32465** [tastybento/ASkyBlock-Bugs-N-Features#198]
Hiya

Currently, you can set the default language. But there isn't a way to disable people from using the /is setlang command.

Can you add a option whether you want people to be able to allow people to change their language

Thanks

**Comment by Poslovitch** [comment]
Just give them the permission -askyblock.island.lang

**Comment by tastybento** [comment]
Or delete the language files from the locale folder.
