### ISSUE TITLE
Console error when call API

### ISSUE THREAD

**Issue by SaitDev** [tastybento/ASkyBlock-Bugs-N-Features#199]
When [Depenizen](https://github.com/DenizenScript/Depenizen) called some ASkyBlock API got this error
https://pastebin.com/Gq0Q8BWp

And the player that depnizen used to call api doesnt have island
Latest release of ASkyBlock 3.0.6.5

**Comment by tastybento** [comment]
Yes, if the player doesn't have an island, then that method will return null. Depenizen needs to do a null check.
