### ISSUE TITLE
Purge team islands

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#20]
_From @Kryniowesegryderiusz on March 17, 2017 13:54_

Is it possible to enable purging islands, where are more than 1 player assigned? Original purge command removes only islands, where players are playing alone ;c

_Copied from original issue: tastybento/askyblock#550_

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#5

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#6
