### ISSUE TITLE
Problem with coop command.

### ISSUE THREAD

**Issue by Tim2709** [tastybento/ASkyBlock-Bugs-N-Features#200]
I have a problem with the coop command.
I added the coop permission ( askyblock.coop ( same problem with the island lock command -> I think it's a problem with the permissions plugin )) to my default group in PermissionEX, but
I'm not allowed to use the command /island coop NAME on my server.
I'm searching since two days now, but it seems like nobody has the same problem.
I don't know what I can do. I already checked the whole config, but nothing ( also restarted the server several time).

Maybe you can help me. 
I really like aSkyBlock, it's the best Skyblock plugin i have ever seen. :D

Server & ASkyBlock version:
- craftbukkit 1.11 and latest aSkyBlock version

What plugins are you using on your server?
- Essentails, EssentailsSpawn, NoCheatPlus, PermissionEX

Did you update/install a plugin?
- Yes.

**Comment by tastybento** [comment]
If the command is not visible, then it is a permissions problem. If you can see it when Op, then it's a permissions problem.

For pex, do /pex user (your name) add askyblock.coop

Make sure you're using a new version of PEX. You may need to do /pex reload

Check your permissions.yml file in the pex folder. You may just need to delete it and start again if it's too messed up.

**Comment by Tim2709** [comment]
Okay, I'm going to test it later but thanks for the fast help! :D

**Comment by Tim2709** [comment]
I think it was a problem with PermossionsEX. I restartet the server a few times and one time i found something in the console.

PermissionsEX1.23.4 is now disabled ( I think that was what i found)

So I deleted every file that was connected to PEX and restartet.
After that I installed PEX again and it worked.

I still dont really know what the problem was but I'm happy it's working now.

**Comment by tastybento** [comment]
Great!
