### ISSUE TITLE
Error appearing in console when loading up the plugin

### ISSUE THREAD

**Issue by MCFISHERMANPRO** [tastybento/ASkyBlock-Bugs-N-Features#202]
When loading up the server this error appeared and the plugin seemed to be disabled, anyone know how to fix it? 
ERROR Cannot load plugins/ASkyBlock/challenges.yml
07.05 16:21:07 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
07.05 16:21:07 [Server] INFO in 'string', line 202, column 7:
07.05 16:21:07 [Server] INFO friendlyname: 'Paper Maker'
07.05 16:21:07 [Server] INFO ^
07.05 16:21:07 [Server] INFO expected <block end>, but found Scalar
07.05 16:21:07 [Server] INFO in 'string', line 209, column 20:
07.05 16:21:07 [Server] INFO itemReward: 'DIRT:5 CLAY:15'
07.05 16:21:07 [Server] INFO ^
07.05 16:21:07 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
07.05 16:21:07 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
07.05 16:21:07 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
07.05 16:21:07 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
07.05 16:21:07 [Server] INFO at com.wasteofplastic.askyblock.commands.Challenges.reloadChallengeConfig(Challenges.java:1993) [askyblock.jar:?]
07.05 16:21:07 [Server] INFO at com.wasteofplastic.askyblock.commands.Challenges.<init>(Challenges.java:88) [askyblock.jar:?]
07.05 16:21:07 [Server] INFO at com.wasteofplastic.askyblock.ASkyBlock.onEnable(ASkyBlock.java:315) [askyblock.jar:?]
07.05 16:21:07 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
07.05 16:21:07 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
07.05 16:21:07 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
07.05 16:21:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
07.05 16:21:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
07.05 16:21:07 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
07.05 16:21:07 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
07.05 16:21:07 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
07.05 16:21:07 [Server] INFO Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
07.05 16:21:07 [Server] INFO in 'string', line 202, column 7:
07.05 16:21:07 [Server] INFO friendlyname: 'Paper Maker'
07.05 16:21:07 [Server] INFO ^
07.05 16:21:07 [Server] INFO expected <block end>, but found Scalar
07.05 16:21:07 [Server] INFO in 'string', line 209, column 20:
07.05 16:21:07 [Server] INFO itemReward: 'DIRT:5 CLAY:15'
07.05 16:21:07 [Server] INFO ^
07.05 16:21:07 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
07.05 16:21:07 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
07.05 16:21:07 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
07.05 16:21:07 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
07.05 16:21:07 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]

**Comment by MCFISHERMANPRO** [comment]
I can provide the plugin files if necessary

**Comment by Poslovitch** [comment]
Put your challenges.yml in this website http://yaml-online-parser.appspot.com/
It will help you to fix the errors

**Comment by MCFISHERMANPRO** [comment]
Sorry forgot to close this, shortly after i just ended up redownloading the challenges.yml file and replacing the broken one, thanks for the response though!
