### ISSUE TITLE
Invincible visitors can die and possible inventory duplication

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#203]
Even if visitors are invincible, they receive fall damage.

When they hit the ground, their inventory is dropped, but they keep it at respawn (so it duplicates the inventory)

Config : https://hastebin.com/ukerutigux.php

**Comment by tastybento** [comment]
Works fine for me. Are you sure this happens? I tried this config.yml and it worked okay. No fall damage.

**Comment by Poslovitch** [comment]
I will ask the server owner to do some checks

**Comment by tastybento** [comment]
Closing for now.
