### ISSUE TITLE
[Suggestion/info] Swap island

### ISSUE THREAD

**Issue by xion87** [tastybento/ASkyBlock-Bugs-N-Features#206]
Hi, actually i got a plugin that trying to swap owner island but it work bad by creating double owner on island, there is a api for change the island owner? (also without need to kick all party members)
Thank you

**Comment by Poslovitch** [comment]
I'm both working on a more efficient API, and fixing the island leader changing.
This will come in 4.0 ;)

**Comment by xion87** [comment]
You replied 1 second after that i opened this xD,  good to heart that!
