### ISSUE TITLE
Horses not protected, mules too

### ISSUE THREAD

**Issue by FrankHeijden** [tastybento/ASkyBlock-Bugs-N-Features#207]
The animals from above aren't protected from visitors, they can ride them. using latest version on latest spigot 1.11.2

**Comment by tastybento** [comment]
I cannot replicate this right now. Do visitors see "Island Protected" in chat? Or not?

Was this a upgrade you did from a previous version of ASkyBlock? If it was an upgrade, try **/asadmin settingsreset HORSE_INVENTORY**  and **/asadmin settingsreset HORSE_RIDING**.

If that doesn't help, maybe there's another plugin that's interfering with the island protection.

**Comment by FrankHeijden** [comment]
thanks, they don't see a message at all when they ride someone else's horses. I tried the commands above, but unfortunately they didn't work for me. Im completely new to ASkyBlock, so I didn't upgrade from a previous version.

The only plugins that 'could' 'be' messing around with protection are essentialsspawn, essentialsprotect, essentialsantibuild and worldguard.

**Comment by tastybento** [comment]
The last three look like prime candidates. Temporarily remove them to see if they are responsible.

**Comment by SaitDev** [comment]
@tastybento for me, horse_riding works fine but it doesnt protect skeleton horse. Please add this.
server 1.11.2, asb latest release 3.0.6.6
