### ISSUE TITLE
Confiq help please.

### ISSUE THREAD

**Issue by ericsonm** [tastybento/ASkyBlock-Bugs-N-Features#209]
Hi.
Can anyone help me go over the whole confiq.yml, I'm a newb and I need help with everything. 
We can call on discord or Skype to make it faster.
Thanks guys :)

**Comment by tastybento** [comment]
It's best to ask the community on https://www.spigotmc.org/threads/askyblock.30325/page-199. Or try the community Discord https://discord.gg/ur8EPYS. Say what parts you don't understand.

**Comment by ericsonm** [comment]
hi TastyBento :) ty for responding. can i pls have the disccord channel? and sure ill go back to spigot and try to keep learning on my own. thx

**Comment by tastybento** [comment]
Just click on the discord link - it should get you there.

**Comment by ericsonm** [comment]
OMG i am a newb and blind. sorry and thanks
