### ISSUE TITLE
Progress Bar for Challenges

### ISSUE THREAD

**Issue by ChavitaHD** [tastybento/ASkyBlock-Bugs-N-Features#210]
Hello, I was wondering if you would be able to add a progress bar to the challenges menu.

http://prntscr.com/f62epq

As you can see there, under the required tab, it tells them what they need, but would you be able to implement a placeholder we can place here, that would show the progress, possibly a progress number as well.

It would look something like.

http://prntscr.com/f62gq9

This would be placed where it says required, under which items are needed.

**Comment by Poslovitch** [comment]
I like the idea.
Merging it to #10
