### ISSUE TITLE
Hoppers not counted correct

### ISSUE THREAD

**Issue by Sckaletz** [tastybento/ASkyBlock-Bugs-N-Features#211]
Hi

There seem to be a bug with the counting of hoppers. Example: When I do /asadmin info on an island it would say 693 but there's only 505 hoppers placed. How come? Is there a way to update the info somehow?

Using the latest 1.11.2 build from Spigot and your latest update of ASkyblock.

**Comment by tastybento** [comment]
Sorry, I can't replicate this. I just tried with World Edit and made a bunch of them and it counted perfectly. How did you count them to make sure it wasn't correct?
