### ISSUE TITLE
Mobs not spawning

### ISSUE THREAD

**Issue by TheGamingCats** [tastybento/ASkyBlock-Bugs-N-Features#212]
Mobs not spawning naturally in my skyblock world. I also cant spawn em myself. It only happens in skyblock and when I deleted the plugin i can spawn em. Please help, thanks :)

**Comment by tastybento** [comment]
Did the FAQ answer help?
https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#after-updating-mobs-and-animals-dont-spawn

If not, can you try this debug build and see what the debug logs say in the console?
https://github.com/tastybento/askyblock/releases/tag/3.0.6.6debug

**Comment by dwgr8ergolfer** [comment]
Hello.

I could use some help on this topic. I followed your previous instructions and this is what my console looks like. 

0.07 21:08:56 [Server] INFO Natural monster spawn cancelled.
20.07 21:08:56 [Server] INFO on Mob spawnCreatureSpawnEvent
20.07 21:08:56 [Server] INFO WITCH
20.07 21:08:56 [Server] INFO SPAWNER
20.07 21:08:56 [Server] INFO Villager spawn event! CreatureSpawnEvent
20.07 21:08:56 [Server] INFO Not an animal
20.07 21:08:56 [Server] INFO WITCH
20.07 21:08:56 [Server] INFO SPAWNER
20.07 21:08:56 [Server] INFO Animal spawn event! CreatureSpawnEvent
20.07 21:08:56 [Server] INFO Natural monster spawn cancelled.
20.07 21:08:56 [Server] INFO on Mob spawnCreatureSpawnEvent
20.07 21:08:56 [Server] INFO WITCH
20.07 21:08:56 [Server] INFO SPAWNER
20.07 21:08:56 [Server] INFO Villager spawn event! CreatureSpawnEvent
20.07 21:08:56 [Server] INFO Not an animal
20.07 21:08:56 [Server] INFO WITCH
20.07 21:08:56 [Server] INFO SPAWNER
20.07 21:08:56 [Server] INFO Animal spawn event! CreatureSpawnEvent
20.07 21:08:56 [Server] INFO Natural monster spawn cancelled.
20.07 21:08:56 [Server] INFO on Mob spawnCreatureSpawnEvent
20.07 21:08:56 [Server] INFO WITCH
20.07 21:08:56 [Server] INFO SPAWNER
20.07 21:08:56 [Server] INFO Villager spawn event! CreatureSpawnEvent
20.07 21:08:56 [Server] INFO Not an animal
20.07 21:08:56 [Server] INFO WITCH
20.07 21:08:56 [Server] INFO SPAWNER
20.07 21:08:56 [Server] INFO Animal spawn event! CreatureSpawnEvent
20.07 21:08:24 [Server] INFO Natural monster spawn cancelled.
20.07 21:08:24 [Server] INFO on Mob spawnCreatureSpawnEvent
20.07 21:08:24 [Server] INFO WITCH
20.07 21:08:24 [Server] INFO SPAWNER
20.07 21:08:24 [Server] INFO Villager spawn event! CreatureSpawnEvent
20.07 21:08:24 [Server] INFO Not an animal
20.07 21:08:24 [Server] INFO WITCH
20.07 21:08:24 [Server] INFO SPAWNER
20.07 21:08:24 [Server] INFO Animal spawn event! CreatureSpawnEvent
20.07 21:07:47 [Server] INFO Natural monster spawn cancelled.
20.07 21:07:47 [Server] INFO on Mob spawnCreatureSpawnEvent
20.07 21:07:47 [Server] INFO WITCH
20.07 21:07:47 [Server] INFO SPAWNER
20.07 21:07:47 [Server] INFO Villager spawn event! CreatureSpawnEvent
20.07 21:07:47 [Server] INFO Not an animal
20.07 21:07:47 [Server] INFO WITCH
20.07 21:07:47 [Server] INFO SPAWNER
20.07 21:07:47 [Server] INFO Animal spawn event! CreatureSpawnEvent
20.07 21:07:47 [Server] INFO Natural monster spawn cancelled.
20.07 21:07:47 [Server] INFO on Mob spawnCreatureSpawnEvent
20.07 21:07:47 [Server] INFO WITCH
20.07 21:07:47 [Server] INFO SPAWNER
20.07 21:07:47 [Server] INFO Villager spawn event! CreatureSpawnEvent
20.07 21:07:47 [Server] INFO Not an animal
20.07 21:07:47 [Server] INFO WITCH
20.07 21:07:47 [Server] INFO SPAWNER
20.07 21:07:47 [Server] INFO Animal spawn event! CreatureSpawnEvent
20.07 21:07:35 [Server] INFO Natural monster spawn cancelled.
20.07 21:07:35 [Server] INFO on Mob spawnCreatureSpawnEvent
20.07 21:07:35 [Server] INFO WITCH
20.07 21:07:35 [Server] INFO SPAWNER
20.07 21:07:35 [Server] INFO Villager spawn event! CreatureSpawnEvent
20.07 21:07:35 [Server] INFO Not an animal
20.07 21:07:35 [Server] INFO WITCH
20.07 21:07:35 [Server] INFO SPAWNER
20.07 21:07:35 [Server] INFO Animal spawn event! CreatureSpawnEvent
20.07 21:07:16 [Server] INFO Natural monster spawn cancelled.
20.07 21:07:16 [Server] INFO on Mob spawnCreatureSpawnEvent
20.07 21:07:16 [Server] INFO WITCH
20.07 21:07:16 [Server] INFO SPAWNER
20.07 21:07:16 [Server] INFO Villager spawn event! CreatureSpawnEvent
20.07 21:07:16 [Server] INFO Not an animal
20.07 21:07:16 [Server] INFO WITCH
20.07 21:07:16 [Server] INFO SPAWNER
20.07 21:07:16 [Server] INFO Animal spawn event! CreatureSpawnEvent
20.07 21:07:16 [Server] INFO Natural monster spawn cancelled.
20.07 21:07:16 [Server] INFO on Mob spawnCreatureSpawnEvent
20.07 21:07:16 [Server] INFO WITCH
20.07 21:07:16 [Server] INFO SPAWNER
20.07 21:07:16 [Server] INFO Villager spawn event! CreatureSpawnEvent
20.07 21:07:16 [Server] INFO Not an animal
20.07 21:07:16 [Server] INFO WITCH
20.07 21:07:16 [Server] INFO SPAWNER
20.07 21:07:16 [Server] INFO Animal spawn event! CreatureSpawnEvent
20.07 21:07:13 [Server] INFO (SkyIsland) Complete island challenges with /c for awesome rewards!
20.07 21:06:56 [Server] INFO Natural monster spawn cancelled.
20.07 21:06:56 [Server] INFO on Mob spawnCreatureSpawnEvent
20.07 21:06:56 [Server] INFO WITCH
20.07 21:06:56 [Server] INFO SPAWNER
20.07 21:06:56 [Server] INFO Villager spawn event! CreatureSpawnEvent
20.07 21:06:56 [Server] INFO Not an animal
20.07 21:06:56 [Server] INFO WITCH
20.07 21:06:56 [Server] INFO SPAWNER
