### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by AMinecraftDev** [tastybento/ASkyBlock-Bugs-N-Features#213]
Hey, so I have a modified version of ASkyblock on a server I co-own, and I had to add a nullchecker to some parts of the code because one of the players is null, and was causing most of the plugin to break, and we couldn't remove the player, we tried, but it would keep re-generating his files. This is the code I added, the class, the section, blah blah:

IslandCmd (onCommand ((split case 2): https://hastebin.com/hejirudetu.coffeescript
Util (tabLimit): https://hastebin.com/abibukequv.php

If you could add this to the next update it would save me a lot of time adding it to each new update, and also it might help fix a problem with some other players.

Thanks,
AMinecraftDev.

@tastybento

**Comment by BoostedNetwork** [comment]
@tastybento This was the issue TheJackLC reported on SpigotMC Forums, and you believed it was a corrupted jar.

**Comment by Poslovitch** [comment]
Next version (4.0) is currently under full rewriting.
As everything is changed, the fix you are suggesting won't be applied, but thanks for your report, it's helpful to see what I have to care about.

**Comment by AMinecraftDev** [comment]
I am aware of that, however if you do decide to put anymore 3.0 updates out, please apply this to them.

**Comment by tastybento** [comment]
What I can't understand is why the player has a null uuid? If this player can get one, how about others? Null is not unique. Are you offline? What is the player's name? We shoul find the root cause, not band aid it (yet).

**Comment by AMinecraftDev** [comment]
I'm not sure if the uuid was null, I just added both null checks to be safe :P

**Comment by tastybento** [comment]
Okay, I'll add code around and about to make sure no nulls exist.

**Comment by BoostedNetwork** [comment]
We believe it was linked to when we had a memory crash on Skyblock, (Server ran out of memory) the player must have joined and created an island during that period, I had a suspicion it was a certain player, so I deleted all his UUID files I could find within aSkyblock and other files but it did not fix the issue.

**Comment by BoostedNetwork** [comment]
I was searching for Null files within aSkyblock files and found within the islands.yml file we have 15 null's E.g.
- -9200:115:2000:150:400:null:false:false:00000000000001100010100000000100111000110000111:FOREST:0
I was wondering could that be the cause and If so what are the safe things to do? Just down Skyblock and remove all the Null files and load it back up?

**Comment by tastybento** [comment]
@BoostedNetwork - no - those are just unowned islands. Check out V3.0.6.6 - I added a lot of null UUID check code. It should help.
