### ISSUE TITLE
Admin Create Island (feature request)

### ISSUE THREAD

**Issue by ResqDiver1317** [tastybento/ASkyBlock-Bugs-N-Features#214]
I would like the ability as an admin to create a new island in a specific spot. Had a few players want to start their islands over but when they reset, the end up somewhere else instead of where they were. Most of them wanted to be able to restart but stay by their neighbors. 

A command like "/asadmin create" to create a new island in a section where there isn't one at the time (such as where a players island used to be) assigned to "null" (I noticed when we had issues before with unassigned islands they were registered to null) then we could use existing commands in ASkyBlock to give them the new island that we created.

**Comment by tastybento** [comment]
You can use **/asadmin reserve (player name)** when in the location where they want their island. Then, when they reset their island, or start it, they will start there.

**Comment by ResqDiver1317** [comment]
Oh! I totally missed that command! Thanks!!

**Comment by ResqDiver1317** [comment]
Do I need to be in the exact spot where the island needs to go (ie, the block where the bedrock should go) or just in the section of map that the island would be in and the plugin will place it proper?

**Comment by tastybento** [comment]
Just the section. Use F3 to make sure you're in the rough location and /asadmin info to confirm no-one else's island is there.

**Comment by ResqDiver1317** [comment]
that is awesome!!! Just tried to get someone back where they wanted (them resetting is what spurred me asking) and it worked great!! Thanks for all you do!!
