### ISSUE TITLE
Sponge Version?

### ISSUE THREAD

**Issue by ResqDiver1317** [tastybento/ASkyBlock-Bugs-N-Features#215]
I am currently using ASkyBlock to manage the islands on our SkyFactory 2.5 server (I'm not a fan of the Garden of Glass mod that is intended to manage the islands on there). Using your plugin makes my life as an admin so much easier on there. I am in the process of building our replacement for 2.5 using SkyFactory 3.0, which is based on MC 1.10.2 and requires SpongeForge (which doesn't support Bukkit plugins :(  ). I was wondering if you had any plans to release a Sponge plugin of ASkyBlock? I have seen some attempts done by others but from reading the info on them, they are nowhere near as good as ASkyBlock.

Keep up the awesome work :)

**Comment by tastybento** [comment]
Ah, Sponge. I had a look at it once, but we don't have the resources, sorry!

**Comment by ResqDiver1317** [comment]
lol worth a shot :)  I love the ASkyBlock plugin and was really let down by my options on Sponge but I definitely understand not having the time/resources to do it. I've gotta learn how to work with Sponge myself and am not looking forward to it

**Comment by tastybento** [comment]
Good luck!
