### ISSUE TITLE
Spawn Protection

### ISSUE THREAD

**Issue by MaximumDesigns** [tastybento/ASkyBlock-Bugs-N-Features#217]
Hi there.

I'm using ProQuests, and would like people to right click villagers, and access quests.
For some reason, players can't access the villagers, saying 'This island is protected'.

I've checked all of the flags, and can't find the issue.

**Comment by Poslovitch** [comment]
It's VILLAGER_TRADING flag

**Comment by tastybento** [comment]
Make the island spawn (as admin setspawn) and then use the GUI to enable villager trading.
