### ISSUE TITLE
World Generation

### ISSUE THREAD

**Issue by projdarkmoon** [tastybento/ASkyBlock-Bugs-N-Features#218]
Some reason when plugin was inserted and it generated a world it generated a flat land below rather then a void. This is with default configs. Anything that I can do to fix this?

**Comment by tastybento** [comment]
The plugin must have not started correctly. Check your console logs, it probably says that it is disabled. Then by going to the world, the default generator kicked in (flat). Once you work it out, you can either delete the world, or use the super flat recovery setting in config.yml to erase the flat blocks.

**Comment by projdarkmoon** [comment]
So this superflat setting will remove the flat world below the island?

**Comment by tastybento** [comment]
Yes, it's a recovery option. But if the plugin isn't running, it won't obviously work. In other words, find out why the plugin didn't start and then run this.

**Comment by projdarkmoon** [comment]
The plugin is actually running, And i tried setting down a chunk loader to keep chunks loaded, it seems in an infinite loop on regenerating land in the console. same chunks over and over again.
