### ISSUE TITLE
Minecraft 1.12-pre2

### ISSUE THREAD

**Issue by TheChampTF** [tastybento/ASkyBlock-Bugs-N-Features#219]
Hey

On latest version (Pre version released from Spigot) I'm getting http://paste.yu8.me/?6aec4e569cbc18b2#nxUgl2zzpXg6tl0H8ikecN5GgSEbd6AGDox1gvh+yTY=

Just giving you a heads up before 1.12 is released

**Comment by Poslovitch** [comment]
It's normal. 1.12 is not officially supported, because it is not released yet. The error says ASB fallbacks to a default NMS Handler, because none exists for 1.12.

**Comment by tastybento** [comment]
I'll try and make it work in 3.0.6.6.

**Comment by tastybento** [comment]
Hmm - requires Java 8. Looks like we'll need to pull that Java 8 requirement into 3.0.6.6...

**Comment by tastybento** [comment]
Done. The plugin is still compiled with Java 7.
