### ISSUE TITLE
Count chest content in Island Level

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#22]
_From @Lion048 on March 8, 2017 23:49_

Is there a way I can enable to have island level be counted in chest?

_Copied from original issue: tastybento/askyblock#539_

**Comment by Poslovitch** [comment]
_From @tastybento on March 10, 2017 2:24_

You mean have items in a chest count towards island level?

That is not supported right now. It could be in the future maybe.

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#26
