### ISSUE TITLE
Adjust island-level by a static value

### ISSUE THREAD

**Issue by ghacproductions** [tastybento/ASkyBlock-Bugs-N-Features#220]
Hey,

I've checked both the plugin-site on spigotmc.org and the source-code (atleast a quick check) and could not find a (possible) feature:

Adjusting the island-level of a player(his island) by a static value (setting, adding or removing an amount of levels).
This would be very useful for giving whole levels for specific challenges as the challenges could simply execute an "island leveladd" command to give a specifc amount of levels (points). Additionally, other plugins could hook into the system and execute commands to give islandlevel.

If this is an appreciated feature, I'ld happily create a PR for this feature.

Greetings
ghac

**Comment by Poslovitch** [comment]
I see.
I will implement it in 4.0 rewrite, thanks for the suggestion

**Comment by ghacproductions** [comment]
Great!
Will this become a part of the milestone for 4.0? Do you need help with it?

**Comment by Poslovitch** [comment]
Yes, I'm on mobile I can't register it now.
I don't think I will need help for 4.0. But if you want, you can join ASkyBlock's Discord server : 
https://discord.gg/rFsHKQ

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#69
