### ISSUE TITLE
Island MiniShop disbled Issue

### ISSUE THREAD

**Issue by VikingOmu** [tastybento/ASkyBlock-Bugs-N-Features#221]
As long as I wait (more or less patiently) for the 4.0 milestone, I disabled the minishop in my config file.
The only problem is that when I do "/is ms" and the minishop is _disabled_ it says:
"Minishop is disabled."
"Unknown command."
Can you remove one of them? I want either "Minishop is disabled." either "Unknown command."...
Thanks.

**Comment by Poslovitch** [comment]
It should say Minishop is disabled.
Investigating

**Comment by tastybento** [comment]
Thanks - it's fixed and will be in the next bug fix release.
