### ISSUE TITLE
Dispenser issue

### ISSUE THREAD

**Issue by obiku19** [tastybento/ASkyBlock-Bugs-N-Features#222]
All, I used to use a dispenser to fire up my portal. Until version 3.0.6 it was no issue. I recently updated skyblock to 3.0.6.6, (today) and now each time I try to fire up the portal, only a bit of smoke comes out of the dispenser.
When lighting up the portal manualy with one of the flint & steels out of the dispenser, everything is OK.

I'll revert back to version 3.0.6 for now

**Comment by Poslovitch** [comment]
I think it's due to the null prevention in BlockIgniteEvent (null= dispenser). @tastybento ?

**Comment by tastybento** [comment]
Make sure FIRE is set to true in the world protection section of config.yml. Run **/asadmin settingsreset FIRE** to make sure that it applies to all current islands. Flick the lever on the dispenser and the portal will light.

**Comment by Poslovitch** [comment]
But i will allow visitors to use flint and steel to spaw fire, won't it?

**Comment by tastybento** [comment]
Ah, okay, I see what the ask is. Let me check some more.

**Comment by tastybento** [comment]
Players will need to switch on FIRE as a setting on their island to make this work for now. The dispenser lighting sparks into air, which isn't possible to track. It could be checked with a search for obsidian around the air block.

**Comment by obiku19** [comment]
Sorry to interrupt, switch FIRE on? I can't find that option in the /is settings GUI. Setting FIRE to true in the config makes it able for players to set things on fire at the spawn too....
(But I guess because FIRE_SPREAD is off, that doesn't matter.....

**Comment by tastybento** [comment]
@obiku19 You can move FIRE into the island settings so players can decide if they want it on or not.

**Comment by obiku19** [comment]
Ok, I'll give it a try :)
Thanx for the feedback
