### ISSUE TITLE
Default language in configuration

### ISSUE THREAD

**Issue by BirkhoffLee** [tastybento/ASkyBlock-Bugs-N-Features#224]
Hey there. I have translated askyblock myself and named the new language file to `zh-TW.yml`. I went to the configuration file and set `general.defaultlanguage` to `zh-TW`. But I found that new players joining in are still using the default language. Any ideas?

**Comment by tastybento** [comment]
It works for me okay. Weird. There is already a zh-TW.yml file. Are you using the latest version of the plugin?

**Comment by BirkhoffLee** [comment]
Yes.

```
[Sat, 27. May 2017 20:41:47 INFO] ASkyBlock version 3.0.6.6
[Sat, 27. May 2017 20:41:47 INFO] A SkyBlock Plugin
[Sat, 27. May 2017 20:41:47 INFO] Author: Tastybento
```

**Comment by tastybento** [comment]
When you do /asadmin reload in the console, do you see:

>asadmin reload
[13:45:37 ERROR]: [ASkyBlock] 'zh-TW.yml' not found in /locale folder. Using /locale/en-US.yml

What files do you have in the /locale folder?

You can try this:

1. rename the ASkyBlock/locale file to ASkyBlock/locale.old
2. Do /asadmin reload - the locale folder will be recreated
3. Copy your zh-TW.yml file over the default one.
4. Do /asadmin reload.

You should be good.

**Comment by BirkhoffLee** [comment]
I'm sorry, I didn't have time to test. I'll reply to this issue after the test.
