### ISSUE TITLE
Trust command

### ISSUE THREAD

**Issue by BirkhoffLee** [tastybento/ASkyBlock-Bugs-N-Features#225]
Hey there. I think having a command like `/is trust` which gives a player permanent coop is a good idea, so people can play actively on multiple islands, the game would be much more interesting.

**Comment by Poslovitch** [comment]
/is coop does the job, set 'persistentcoops' to true in config

**Comment by BirkhoffLee** [comment]
@Poslovitch yeah, I think we can let players decide whether they want to give permanent or temporary coops. e.g. having `/is coop` and `/is trust` at the same time

**Comment by TylerrrV** [comment]
Bumping this cause it would be a cool addition, players have requested it

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#67
