### ISSUE TITLE
Toggle mob-spawning with /is settings

### ISSUE THREAD

**Issue by BirkhoffLee** [tastybento/ASkyBlock-Bugs-N-Features#227]
Hey there, some players(like me) don't like mobs spawning on their islands cuz it can be actually very annoying. What about implementing a toggle in /is settings that enables/disables mob-spawning on the player's island?

**Comment by Poslovitch** [comment]
It already exists : MOB_SPAWN and MONSTER_SPAWN.
Add them in protection.island to allow them to change it

**Comment by BirkhoffLee** [comment]
Thank you very much! May I know when was this implemented?

**Comment by Poslovitch** [comment]
I'm not sure. Probably 3.0.6
