### ISSUE TITLE
Askyblock.island.fly in the nether

### ISSUE THREAD

**Issue by Keisyoo** [tastybento/ASkyBlock-Bugs-N-Features#231]
Hey,

I am currently using your Plugin on my Skyblock server and as a perk for donors we have the fly permission.

It works perfectly fine on the overworld islands but it does not seem to work in the nether. I have googled this issue and read all of the FAQ's but I cannot seem to find a solution.

I hope you can help me :)

Greetings,
Keisyoo

**Comment by Poslovitch** [comment]
See #127.
IslandFly will be released as an addon when 4.0 will be out.
