### ISSUE TITLE
Island level in chat not working

### ISSUE THREAD

**Issue by CodaMacroft** [tastybento/ASkyBlock-Bugs-N-Features#232]
Ok so, I have AskyBlock plugin, and Herochat plugin installed. I want the Island level to be in the chat. I tried to use the "{ISLAND_LEVEL}" but when I type something it just shows "{MyPrefix} '{ISLAND_LEVEL}' {MyName}: {MyMessage}" and it isn't showing my is level. I have tried changing the Prefix in the config, then restarting it still doesn't work. Please help. I would like to release SkyBlock on my server Network very soon but I can't seem to figure this one out. If you need a picture or any more info please inform me. I am using the latest version of ASkyBlock too. Thanks - Coda

**Comment by CodaMacroft** [comment]
Here is a picture. Note that I changed the island level prefix to "{ISLEVEL}" in the config and then restarted.
![image](https://cloud.githubusercontent.com/assets/24403178/26180101/616227a2-3b35-11e7-8e57-35f6ff2fad64.png)

**Comment by xFireblade** [comment]
This issue has affected me as well- thought it was just me. +1

**Comment by CodaMacroft** [comment]
Lol. I was hoping it wasn't only me too. I thought I was just doing something stupid... XD.

**Comment by xFireblade** [comment]
Well, it worked for me when I used 3.0.0 lmao- I don't know how I managed to continue using that version for so long XD. But when I updated the chat features just stopped working.

**Comment by CodaMacroft** [comment]
Ikr, I have had this issue since I installed the plugin. It just won't work no matter what I do or try. It's really annoying too because I have a pretty big server and people are constantly bugging me about it and I can't fix it. R.I.P me. XD.

**Comment by xFireblade** [comment]
I could recommend using a version before the config update to do with the chat features (3.x.x I think). But saying it is a big network, this could **cause massive issues**. Welp, anyways that's all I can offer. Let's hope for a fix or reply of some sort

**Comment by CodaMacroft** [comment]
Yeah, I don't think I'll downgrade. I can only hope the darn author replies now. Well, thanks for your help.

**Comment by xFireblade** [comment]
No problem, and thanks for yours.

**Comment by Poslovitch** [comment]
Investigating

**Comment by tastybento** [comment]
@xFireblade @CodaMacroft What chat plugin are you using? It depends on that.

**Comment by xFireblade** [comment]
@CodaMacroft is using Herochat, as stated wayyy above, as for me- essentials chat.

**Comment by tastybento** [comment]
@xFireblade  - I just tested EssentialsChat using ASkyBlock 3.0.6.6 and I can't replicate your problem, sorry. 

Essentials config:

```  # Chat formatting can be done in two ways, you can either define a standard format for all chat.
  # Or you can give a group specific chat format, to give some extra variation.
  # For more information of chat formatting, check out the wiki: http://wiki.ess3.net/wiki/Chat_Formatting
  format: '&7<{DISPLAYNAME} &r({ISLAND_LEVEL})&7{ISLAND_CHALLENGE_LEVEL}>:&r {MESSAGE}'`

Screenshot: https://i.gyazo.com/6bddb635ecbc86bda6a1832d65b71dd7.png
[https://i.gyazo.com/6bddb635ecbc86bda6a1832d65b71dd7.png](url)

>plugins
[08:04:21 INFO]: Plugins (6): WorldEdit, Essentials, Vault, EssentialsChat, ASkyBlock

Using the latest EssentialsX from https://dev.bukkit.org/projects/essentialsx?gameCategorySlug=bukkit-plugins&projectID=93271

**Comment by xFireblade** [comment]
Oh okay, must be my end- thanks for the help.

**Comment by tastybento** [comment]
I do see a problem with Herochat though. I need to study it more - got to head to work now!

**Comment by tastybento** [comment]
Cannot get hero chat to work right now so I've removed support for it. Tried for hours, but it just doesn't take. Maybe another plugin/placeholder API will work.

**Comment by FrankHeijden** [comment]
Same problem with herochat. What do you suggest using then @tastybento ? Because PlaceHolderAPI doesn't work for herochat unfortunately, asked kainzo for support but still waiting on a response.

**Comment by tastybento** [comment]
@FrankHeijden As I wrote above, I can't get HeroChat to work at all with placeholders. I've used Essentials Chat and that works. Apart from that, I don't know, sorry.

**Comment by Ace-Monkey-Ilium** [comment]
YO

**Comment by Ace-Monkey-Ilium** [comment]
https://github.com/Ace-Monkey-Ilium/UHC-functions/invitations
