### ISSUE TITLE
Bug with built-in island fly

### ISSUE THREAD

**Issue by Tyloonie** [tastybento/ASkyBlock-Bugs-N-Features#233]
Hi,

If players relog in the nether world, they are able to fly after logging back in again - even though they are not supposed to. Please re-check if there are no errors.

**Comment by Poslovitch** [comment]
We'll do a fix in 3.0.6.7, but when 4.0 will be out, we will release IslandFly as an addon.

**Comment by tastybento** [comment]
@Tyloonie I've tried this and I cannot replicate it. What version of the plugin are you using?

When logging in, do you see any message on the chat about flying?

**Comment by tastybento** [comment]
@Tyloonie By the way, if you have Essentials installed and a player logs out and then another player removes the block the player was standing on, when the player logs in again they will be put into fly mode. You can remove that by giving the negative permission -essentials.fly.safelogin

**Comment by tastybento** [comment]
Sorry, can't replicate.
