### ISSUE TITLE
Island Challenge Level prefix randomly appearing

### ISSUE THREAD

**Issue by nymphisios** [tastybento/ASkyBlock-Bugs-N-Features#236]
Hello,

When a player has just won a new Challenge rank, the rank's prefix shows next to his name. But when server reloads or restarts, it disappears. Sometimes it can shows randomly for some players after a reload.
I'm using ASkyBlock on Spigot 1.10.2 **with the following plugins:**

> EssentialsX, WorldEdit, PermissionEx, Vault, MultiverseCore, AsyncWorldedit, CratesPlus, DiceFurniture, EmptyWorldgenerator, EssentialsXChat/EssentialsXSpawn, FurnitureLib, JSONAPI, KeepItems, MoreHearts (outdated), Trading v3.2, ServerListPlus, Vault, VoxelSniper, WorldGuard, XPModifier.

Dependencies looks up to date.
I've put in Essentials Chat config the following line:

> format: '&7[{ISLAND_LEVEL}] &r{ISLAND_CHALLENGE_LEVEL} {DISPLAYNAME}: {MESSAGE}'

I've tried to change this line way much times but nothing's change.
When I do a global reload, prefix may show for some players **but** when I only reload chat plugin it does nothing, actual prefix stay and hidden ones keep hidding.

Others informations:
I'm using BungeeCord. The problem is always happening, since ASkyBlock was installed on the server. I think screenshots are useless, just imagine players without the prefix. ^^
And... I'm using the last version of ASkyBlock.
I've seen a similar request but he was using PEX without EssentialsChat, seems different as me.
I hope I've not forgotten anything.

I think you could help me out. Thank you so much if you do.
Sincerely, Joey T.

PS: Sorry I'm not English native.

**Comment by tastybento** [comment]
Weird. Tough one. I'll see if I can replicate.

**Comment by nymphisios** [comment]
Hi,

looks like when I do a /reload, prefixes appear to connected players, but if someone join the server after he does not have his prefix.
It may be due to a non-refreshing ASkyBlock because of another plugin... ?

**Comment by tastybento** [comment]
Cannot replicate, sorry.
