### ISSUE TITLE
Multiple biomes per island

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#24]
_From @Poslovitch on February 10, 2017 5:57_

Allow player to have multiple biomes on their island : /is biome [biome] [radius].
Useful to set precisely where slimes should spawn and others...

_Copied from original issue: tastybento/askyblock#504_

**Comment by Poslovitch** [comment]
_From @evernife on February 21, 2017 21:27_

I think its easier to change a chunk biome, not a specific radius.

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#27
