### ISSUE TITLE
Locale: {islandProtected: ""}

### ISSUE THREAD

**Issue by FrankHeijden** [tastybento/ASkyBlock-Bugs-N-Features#242]
Heya when im using the **islandProtected: ""** section and i set it to "" it will not give any message when a player breaks a block, which is good 👍 but when they try to break an armor-stand it will give a message to them with completely nothing. chat background appears, but no message in it.

screenshot:
![2017-05-22_18 04 28](https://cloud.githubusercontent.com/assets/22407829/26317800/ffc0f5c2-3f18-11e7-9273-e5d2b62c5ac5.png)

Hope this is fixable.

**Comment by Poslovitch** [comment]
This is fixable, we just missed it when we did the change to avoid sending blank message.

**Comment by FrankHeijden** [comment]
Thanks :D any raw dates for the 4.0 release?

**Comment by Poslovitch** [comment]
Any. We're working on a full rewrite. Expecting a first pre release in one month

**Comment by Poslovitch** [comment]
Hum... I cant replicate it on 3.0.6.6. What version are you using?

**Comment by FrankHeijden** [comment]
3.0.6.6 im using also holographicdisplays and armorstandtools, maybe thats the reason?

**Comment by Poslovitch** [comment]
Maybe. Try removing them

**Comment by tastybento** [comment]
I found a few places where the new line was still showing - mainly around projectiles/shooters.

**Comment by FrankHeijden** [comment]
I hope they may fix my issue in a very weird way xD

Thanks anyway!
