### ISSUE TITLE
Cobblegen breaking/not working with stone gen

### ISSUE THREAD

**Issue by Goatii** [tastybento/ASkyBlock-Bugs-N-Features#244]
The magical cobble gen does this:
https://www.youtube.com/watch?v=lT5bB_HBago&feature=youtu.be
My settings are:
   usemagiccobblegen: true
   magiccobblegenonlyatspawn: false
     default:
       STONE: 100.0
     10:
       STONE: 75.0
       COAL_ORE: 20.0
       IRON_ORE: 5.0
     50:
       STONE: 60.0
       COAL_ORE: 30.0
       IRON_ORE: 13.0
       DIAMOND_ORE: 5.0
       EMERALD_ORE: 2.0

**Comment by tastybento** [comment]
I assume your island level is >50? You can check the cobble stats using /asadmin cobblestats in the console. Some generators make cobblestone and that cannot be detected by bukkit, so you may always see some cobble in there.

**Comment by Goatii** [comment]
The island level is 65, as you can see at [1:39 in the video](https://youtu.be/lT5bB_HBago?t=1m39s).
When I do /asadmin cobblestats, I see this:
![2017-05-24_15 23 45](https://cloud.githubusercontent.com/assets/28890834/26385674/59352970-4095-11e7-97a6-d3c0c7295401.png)

**Comment by tastybento** [comment]
So the cobble gen is working correctly. It just that not all cobble can be detected depending on the generator type. Sorry, there's nothing that can be done right now.
