### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by SilverHuskey** [tastybento/ASkyBlock-Bugs-N-Features#245]
How The Heck Do You Get A Schematic That Has Entities.? (Stuff In The Chests/Signs) I have Tried WorldEdit And FAWE And Neither Do This. Do I Need MCEDIT??

**Comment by Poslovitch** [comment]
You don't need everything. Just configure properly the schematics in the config.yml : "chestItems" "companion" and "schematicsection"

**Comment by tastybento** [comment]
You need to make sure your version of WorldEdit matches your server version too. If you don't then those things will not be saved in the schematic.
