### ISSUE TITLE
Island Protection

### ISSUE THREAD

**Issue by xXSKILLS2015Xx** [tastybento/ASkyBlock-Bugs-N-Features#246]
Changed Island protection in the config.yml to zero. Added askyblock.* to default rank. Changed server.properties to 0 spawn protection. Still getting the "island protected" error.

**Comment by Tuckersteward** [comment]
I am having the same issue.  I was just wondering what version your server is running and if your running ViaVersion or what.

**Comment by xXSKILLS2015Xx** [comment]
We run 1.8.8 with viaVersion

**Comment by tastybento** [comment]
> Changed Island protection in the config.yml to zero. 

That will mean that all players have zero space to do anything. If you want island protection to cover their whole island, make it the same size as the island distance.
