### ISSUE TITLE
Lost a quarter of island

### ISSUE THREAD

**Issue by leduyquang753** [tastybento/ASkyBlock-Bugs-N-Features#247]
I am having a problem with the created island. When I left the island and re logged in, or when I restart the server, a quarter of my island was lost and had been replaced with water!
![2017-05-26_09 29 48](https://cloud.githubusercontent.com/assets/26449060/26478387/1ed8d724-41f6-11e7-812c-0184f3f70fd3.png)

**Comment by YellowZaki** [comment]
You have a world save problem.
Try to create the island, do /save-all and re log in.

**Comment by leduyquang753** [comment]
Oh it worked. Thanks so much.
