### ISSUE TITLE
TNT Dupe glitch

### ISSUE THREAD

**Issue by wasder** [tastybento/ASkyBlock-Bugs-N-Features#250]
On 1.9.4 Spigot server (not sure about others) there is a TNT dupe glitch which helps players create fully automated cobblestone farms.
We did a small fix prevent it on our server. I think it сould be a good idea to include it in ASB.
``` 
@EventHandler(priority=EventPriority.LOW)
    public void onEvent(BlockPistonExtendEvent event)
    {
        if (event.getBlocks().stream().anyMatch(it->it.getType()==Material.TNT))
            event.setCancelled(true);
    }

    @EventHandler(priority=EventPriority.LOW)
    public void onEvent(BlockPistonRetractEvent event)
    {
        if (event.getBlocks().stream().anyMatch(it->it.getType()==Material.TNT))
            event.setCancelled(true);
    }
```

**Comment by Poslovitch** [comment]
Can you send us how we can reproduce this glitch?

**Comment by wasder** [comment]
https://www.youtube.com/watch?v=PRegK6OvhAA

**Comment by Poslovitch** [comment]
Thanks.
We will fix that in the next bug fix release ;)

**Comment by tastybento** [comment]
Thanks!

**Comment by tastybento** [comment]
Java 8 code - nice, but I'll need to rewrite to Java 7 for this version...

**Comment by tastybento** [comment]
So, the only issue I see here is that it makes TNT unpushable by pistons. Is there any legitimate reason to allow TNT to be pushed? @Poslovitch

**Comment by Poslovitch** [comment]
I don't know... We should add an option just in case ^^

**Comment by tastybento** [comment]
Agreed.
