### ISSUE TITLE
Problem with the nether creation

### ISSUE THREAD

**Issue by Eclixal** [tastybento/ASkyBlock-Bugs-N-Features#256]
Good evening,

I have a problem with the creation of the nether world, there are missing chunks. Here's some screen:

http://prntscr.com/ff7f7f
http://prntscr.com/ff7fdj

The server is in 1.10.2.

There is no error in the console.

Thank you for your help

**Comment by tastybento** [comment]
It looks like there is a mix between the ASkyBlock nether, which is a void and the standard Nether. Which one do you want? Standard nether or ASKyBlock nether? Either way, after making your choice in config.yml, you will need to stop the server, delete the ASkyBlock_nether world folder completely and let it regenerate when the server restarts.

**Comment by Eclixal** [comment]
The nether standard. But when I start the server without the map it generates normally it is after another restart that bug!

**Comment by tastybento** [comment]
Hmm. Pastbin.com your config.yml and share the link so I can look at it.

**Comment by Eclixal** [comment]
https://pastebin.com/cQEkjLbz

**Comment by tastybento** [comment]
The config looks fine. Sorry, I cannot replicate this issue. I expect your server could not save chunks or there is another plugin interfering.
