### ISSUE TITLE
Flying Bug

### ISSUE THREAD

**Issue by Fluxty** [tastybento/ASkyBlock-Bugs-N-Features#258]
Using latest aSkyBlock, PaperSpigot 1.8.8, flying will occasionally move the player down as if they pressed the sneak button. It's been getting a lot of complaints and was not an issue using versions prior to 3.0.6.x

**Comment by Poslovitch** [comment]
Maybe an anti-cheat ? Or the server moves back the player like he moved too fast.

**Comment by Fluxty** [comment]
We're using AAC, but as an OP I can reproduce the issue, everyone on the server is having the problem. We're MC.Good-Gaming.com, the issue is exclusively on the 3rd SkyBlock server: Pandora.

Weird thing is that it's not glitching anyone back like Spigot's movement check, it's disrupting their flight and knocking them down a couple of y coordinates as if they had just pressed the sneak button.. I dunno, it has me stumped. We also have allow-flight: true in server.properties.

**Comment by tastybento** [comment]
Just to clarify, you say you're using "Clip's NoFlyZone"? If so, then that's a question for Clip.

**Comment by Fluxty** [comment]
Wait what? He will just send me here. We use Clip's NoFlyZone on ALL of our servers, but this issue is only on our server with the latest ASkyBlock.

**Comment by tastybento** [comment]
Okay, maybe. With the latest ASkyBlock nothing happens regarding fly if the players do not have that permission. So, officially, I'd make sure no-one has it. But let's see how it goes.

**Comment by Fluxty** [comment]
Okay, @tastybento giving the permission has resolved the problem for us. Turns out we are using the version from Monday, not the one you just put out on Thursday. Going to update and see how that works in turn without the permission.

**Comment by Fluxty** [comment]
Yeah, on latest version I can confirm adding the permission for island fly fixed the issue. I do really like the island fly feature built into aSkyBlock and we'll probably just end up using that anyways to cut back on stuffs :+1:
