### ISSUE TITLE
Luckperms incompatible

### ISSUE THREAD

**Issue by voodootje0** [tastybento/ASkyBlock-Bugs-N-Features#259]
Permissions (especially is settings) don't work with the luckperms plugin, luckperms only support lower case,  but according to the developer of luckperms that should matter. Could you guys add support for luckperms? 

- voodootje0

**Comment by tastybento** [comment]
Yes, settings permissions are not case sensitive. They used to be, but that was changed and the config.yml was not updated. You can use askyblock.settings.eggs for example.
