### ISSUE TITLE
Players with askyblock.commands.newexempt still have commands run on them

### ISSUE THREAD

**Issue by tastybento** [tastybento/ASkyBlock-Bugs-N-Features#260]
askyblock.commands.newexempt is not working.

**Comment by tastybento** [comment]
Actually, reset commands and new island commands are being run at the wrong time. So if items are given, they are immediately removed.

**Comment by Fabbyz** [comment]
Hello there is a bug, when a player reach around 21 Milion of island level (I do a custom skyblock) the number go to -21 M please help me i have a skyblock server with 200 players it's an emergency!
