### ISSUE TITLE
Are there any plans to rework challenges on 1.12 advancements?

### ISSUE THREAD

**Issue by wasder** [tastybento/ASkyBlock-Bugs-N-Features#262]

**Comment by Poslovitch** [comment]
1.12 advancements are client-side. We cannot use them as challenges :(

**Comment by wasder** [comment]
Actually you can.
https://www.spigotmc.org/threads/advancementapi-create-custom-advancements.240462/

**Comment by wasder** [comment]
The only problem that you can not give items on click.

**Comment by Poslovitch** [comment]
We could do a workaround for that. Thanks!

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#83
