### ISSUE TITLE
Need help. Chunk not saved/broken

### ISSUE THREAD

**Issue by SaitDev** [tastybento/ASkyBlock-Bugs-N-Features#268]
Pass few days ago the server run into a problem that cauz some chunks cant be saved. It doesnt cauz by ASkyBlock, not sure if I can ask help here, sorry if bother you.

The result now is everyone cant create new island. Every time run /is to create new island console print a error like this: https://pastebin.com/dKBPSmye

Maybe i should delete these corrupted chunks. Is there anyway to know that the where is next island ASkyBlock will create for new player? 

Thanks in advance

**Comment by Poslovitch** [comment]
It seems even ASkyBlock's data is corrupted. Can you send us your **islands.yml** file ?

**Comment by tastybento** [comment]
@Poslovitch - It's his world file - it's corrupted. The region file itself probably needs deleting and regenerating. It'll probably cause loss of quite a few islands. One thing you can do is shift the startx and startz to somewhere else in the world, like 500000, 500000. That'll move all new islands and resets far away from the corrupted chunks. The setting is in the config.yml.

**Comment by SaitDev** [comment]
@Poslovitch ASkyBlock works well, it doesnt cause my issue
@tastybento thank for your suggestion, I should use it. But anyway I spent a whole day to download the worlds, fix region files by McEdit, compare what region files were deleted by McEdit, then delete them on the server too.
New island can be created now. Thank for your help 👍
