### ISSUE TITLE
Extend teamchat to include coop members

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#27]
_From @tastybento on January 31, 2017 6:53_

_Copied from original issue: tastybento/askyblock#492_

**Comment by Poslovitch** [comment]
May add a config option?

**Comment by Poslovitch** [comment]
_From @tastybento on February 1, 2017 2:23_

Yes, it should be optional.

**Comment by Poslovitch** [comment]
I'll try to do thid for 4.0

**Comment by tastybento** [comment]
Keep issue open until you're sure it works okay.

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#38
