### ISSUE TITLE
Expanding the Island distands between islands

### ISSUE THREAD

**Issue by LazyDkk** [tastybento/ASkyBlock-Bugs-N-Features#271]
Hey there

I Wanted to expand the distance between the islands on the server but I don't know how. I went to the config.yml and found the "distance: 200" part. I tried to change it to 600 because I wanted more distance between the islands and it says that I would have to delete the world folder. I wasn't sure if it was the regular World folder or the Skyblock world folder but even after deleting the Skyblock world folder it still didn't work. When people write /is in the chat to make a new island they get teleported to an island but if they try to break or place blocks on the island it says "Island Protected". 
I really don't know how to fix this problem plz send in if you got any know how to fix this problem. Thank you for reading.

- LazyDk

**Comment by Poslovitch** [comment]
You cannot change island distance in mid-game. You must reset everything : remove the skyblock worlds (if you didn't rename it, they are called «ASkyBlock» and «ASkyBlock_nether»), take backups of your ASB config and remove ASB folder.

**Comment by LazyDkk** [comment]
But does that mean that I have to change the config before creating an island or do I have to upload the ASkyblock plugin folder and not only the askyblock.jar?

**Comment by tastybento** [comment]
Read the FAQ on how to reset. Basically, stop the server, delete everything except for config.yml from the ASkyBlock plugin folder and the ASkyblock world folders.
