### ISSUE TITLE
IslandDeleteEvent and IslandResetEvent should be called before the island is deleted/resetted

### ISSUE THREAD

**Issue by xLoGiiKzZo** [tastybento/ASkyBlock-Bugs-N-Features#272]
The IslandDeleteEvent and IslandResetEvent should be called before the island is deleted/resetted or else the events are practically useless as all the data from the island is already deleted and therefore nothing can be done with the events.

**Comment by tastybento** [comment]
Yes, these are just notification events right now. Makes sense. I can shift them.

**Comment by Poslovitch** [comment]
Done. https://github.com/tastybento/bskyblock/commit/59a63975369d3b92283b072171369b7d41bfcc3b (4.0)
