### ISSUE TITLE
Generator Problem (Priority)

### ISSUE THREAD

**Issue by MinerRaftdude** [tastybento/ASkyBlock-Bugs-N-Features#275]
[17:04:42] [Server thread/INFO]: Trying to register generator with Multiverse
[17:04:42] [Server thread/INFO]: Multiverse already knows about 'ASkyBlock'!
[Server thread/INFO]: Success! Property generator was set to ASkyBlock
[Server thread/INFO]: Multiverse already knows about 'ASkyBlock_nether'!
[Server thread/INFO]: Success! Property generator was set to ASkyBlock
[Server thread/ERROR]: [ASkyBlock] ********* The Generator for ASkyBlock is not registered so the plugin cannot start ********
[Server thread/ERROR]: [ASkyBlock] If you are using your own generator or server.properties, set useowngenerator: true in config.yml
[Server thread/ERROR]: [ASkyBlock] Otherwise:
[Server thread/ERROR]: [ASkyBlock] Make sure you have the following in bukkit.yml (case sensitive):
[Server thread/ERROR]: [ASkyBlock] worlds:
[Server thread/ERROR]: [ASkyBlock] # The next line must be the name of your world:
[Server thread/ERROR]: [ASkyBlock] ASkyBlock:
[Server thread/ERROR]: [ASkyBlock] generator: ASkyBlock

I have the latest version of askyblock, vault, and Multiverse.
NO clue why this is going on, I have been having problems for awhile, and can't seem to find the reason behind it.

Thank you for listening,

-CrystalMine Network

**Comment by Poslovitch** [comment]
I'm quoting the error explanation above:

> [Server thread/ERROR]: [ASkyBlock] If you are using your own generator or server.properties, set useowngenerator: true in config.yml
[Server thread/ERROR]: [ASkyBlock] Otherwise:
[Server thread/ERROR]: [ASkyBlock] Make sure you have the following in bukkit.yml (case sensitive):
[Server thread/ERROR]: [ASkyBlock] worlds:
[Server thread/ERROR]: [ASkyBlock] # The next line must be the name of your world:
[Server thread/ERROR]: [ASkyBlock] ASkyBlock:
[Server thread/ERROR]: [ASkyBlock] generator: ASkyBlock

**Comment by tastybento** [comment]
@MinerRaftdude Do you see this error if you start the server from scratch?

Where did you get Multiverse from? It looks like it is not working correctly. Sometimes this can be from a bad build.

**Comment by MinerRaftdude** [comment]
Can you tell me if there is anything wrong with the plugins, I'm using?
Clean install worked without certain plugins with my versions, but with the other plugins, NADA
Plugins:
AdvancedBan
Arconix
askyblock
AsyncWorldEditInjector
AsyncWorldEdit
BuycraftX
ChestCommands
Crazy Crates[v1.7.1.2]
Crazy Envoy[v1.2.7.1]
CS-CoreLib v1.5.14
CustomJoinItems
DeluxeTags
Elixirs
EpicSpawners 3 R4
EssentialsX-2.0.1
EssentialsXChat-2.0.1
EssentialsXSpawn-2.0.1
EZPrestige
EZRanksPro
Factions
GadgetsMenu
GKits
GroupManagerX
HeadHunter
iConomy
JoinAnnouncer1.9
LibsDisguises-9.1.2
MarriageMaster
MassiveCore
Multiverse-Core-2.5.0
Nick
NoCheatPlus
PermissionsEx-1.23.4
PlaceholderAPI
PrisonRankup_v2.7
ProtocolLib
ProtocolSupport
QuickSell_v1.6.1
RealisticBackpacks
Skellett[1.8-1.11]
SkinsRestorer-v13.0.2
SkQuery[1.8-1.11]
skRayFall[1.8-1.11]
Skript[1.8-1.11]
skUtilities[1.8-1.11]
TokenEnchant
TopLite
TuSKe[1.8-1.11]
VanishNoPacket
Vault
VoidWorld
VoteParty-1.2.3
VoxelSniper-5.170.0-SNAPSHOT
WildSkript
worldedit-bukkit-6.1
worldguard-6.1
WorldGuardFix

**Comment by MinerRaftdude** [comment]
Clean install/Certain Versions, being the pertinent plugins for askyblock

**Comment by tastybento** [comment]
I'm sorry, I don't know enough about all those plugins. If a clean install works, then just add plugins one by one until you hit a problem. By the way, the Multiverse Core version looks fine. This version works fine: https://www.spigotmc.org/resources/multiverse-core.390/

Other than that, there's not much we can do, sorry.

**Comment by StewySaucer** [comment]
I am also having this issue was this problem resolved I am running all the right versions for ASkyblocks, vault, and Multiverse
