### ISSUE TITLE
Still need help with the island distance...

### ISSUE THREAD

**Issue by LazyDkk** [tastybento/ASkyBlock-Bugs-N-Features#276]
Yea I still need some help.
After taking backups of the files and deleting the whole plugin then I would have to upload the plugin again. But how do I avoid changing the distance in mid-game? By changing the distance before making an island or do I have to upload the backup file I took and restart the server to load the askyblock.jar end the config at the same time. I don't wanna start trying to fix it if I can get told how to do it cause it would be a waste of time if I could get the answer here. 

Thanks for reading!
-LazyDkk

**Comment by tastybento** [comment]
Answered in another ticket. 

Stop server. Edit config.yml. Delete everything else in the ASkyBlock plugin folder. Delete ASkyBlock worlds, restart.
