### ISSUE TITLE
Player keeps dying and dying and dying BUG!

### ISSUE THREAD

**Issue by LimTheLime** [tastybento/ASkyBlock-Bugs-N-Features#277]
ok so recently my players keeps dying when they get killed or they fall of the island. the player death message keeps poping out like crazy. only way they can get out of the player death is to type /spawn. 

Player Fell out of the world
player died
player died
player died
player died
player died

 i cant find any solution on the internet, is this a bug or glitch of the plugin? 
i tested it many times players keeps dying on their island whenever they fall off or killed by mobs. 

but some players if they fall off the island they dont get the multiple death message or repeatedly dying glitch. 

i hope this has a fix to it. i hope for someones reply and thank you in advance friend :D

**Comment by tastybento** [comment]
Where a player spawns after death is up to the server unless you have the respawn on island option true in config.yml. It sounds like you haven't defined a respawn point. Use Essentials Spawn plugin to set your global spawn point or switch on island respawning.
