### ISSUE TITLE
"Protected Island" Problem

### ISSUE THREAD

**Issue by Manu5656** [tastybento/ASkyBlock-Bugs-N-Features#280]
Hello,
I have a problem in my server with the AcidIsland plugin. Many players after creating their own island (with the / is command) can not build or they can build up to a certain point and not for all the radius I set in config.yml. This plugin is done really well and deserves a lot but this thing ruins it because many players abandon the server because of this problem. I've already tried to set (and still so) in the server.properties file the spawn protection at 0 but that's not the problem apparently.

Another problem, less important but which creates discomfort is that players after arriving by boat near someone's island and trying to get down are spawned far from the island, in the middle of the water instead of going down to the position where they were.

I hope there is a solution to both problems, especially the first one. I also leave my config.yml.

https://pastebin.com/UiugicVz

**Comment by tastybento** [comment]
What server are you using?

When players cannot build, do they see an error? Does it say "Island protected?"

Your island distance is set as 300 - has it always been 300 from the very start? Or did you change it after a while? It could be that there are overlapping islands for some reason.

One thing you can try is to stop the server, move islands.yml to islands.old and restart. Look in the console for errors or comments on what is happening. It will rebuild the file from player files. 

Your issue with unsafe boat exit is very surprising. There is explicit code to make sure players exit onto the land and it hasn't changed for years. This makes me think there is something new going on with your server or something, so let me know what you're running on.

**Comment by Manu5656** [comment]
The distance has not always been set to 300 but has been changed later. If I follow the move to move islands.yml to islands.old and reboot is sure i will not lose data or the like?

**Comment by tastybento** [comment]
Leave it where it is. Changing the island distance should never be done mid-game. That is why you are having these problems. Different islands are on different grids.

I recommend you make startx and startz some very big numbers so new island are made far away from the current ones. That will help prevent overlapping.

**Comment by Manu5656** [comment]
And if I tried to set the distance as it was set by default? Would anything change?

**Comment by tastybento** [comment]
All the islands made since you set it to be 300 will not work right. So it's a trade off - some islands no matter what are going to be affected.
