### ISSUE TITLE
Disable flytimeoutside?

### ISSUE THREAD

**Issue by ItsMennyo** [tastybento/ASkyBlock-Bugs-N-Features#281]
Hello,

I just use Essentials fly and I would like these players to fly everywhere. Now, when they go to another island, they have to do /fly again or players die because their escape goes out of their island protection range.

So you can create an option that allows this option to be completely disabled.

Thanks in advance!

# **_Priority: HIGH_**

**Comment by tastybento** [comment]
I'm assuming you're using the latest version of the plugin. Make sure your players do not have the permission **askyblock.islandfly**. If they do not have that permission, ASkyBlock will not do anything to interfere with flying.

**Comment by ItsMennyo** [comment]
Thank you for the reply.

For all players who could fly it is now resolved but for my staff team not everyone. Some have askyblock.* permission and if I try -askyblock.islandfly, it does not work.

Any idea?

**Comment by tastybento** [comment]
What permission plugin are you using?

**Comment by ItsMennyo** [comment]
PermissionEx

**Comment by tastybento** [comment]
I can't replicate this problem right now. Here's one of my admin players -

>pex user mukumuku13
[17:20:21 INFO]: 'ee910ddf-19e2-4c93-9740-460a954db3de/mukumuku13' is a member of:
[17:20:21 INFO]:    Guest (not ranked)
[17:20:21 INFO]: mukumuku13's permissions:
[17:20:21 INFO]: 1) -askyblock.islandfly (own)
[17:20:21 INFO]: 2) askyblock.* (own)
[17:20:21 INFO]: 3) askyblock.settings.eggs (own)
[17:20:21 INFO]: 4) -askyblock.island.minishop (own)
[17:20:21 INFO]: mukumuku13's options:
[17:20:21 INFO]:   name = "mukumuku13"

With essentials /fly enabled, she can fly out of the protection area and not have it canceled. Can you check the player's permission and say in what circumstance the problem occurs?

**Comment by ItsMennyo** [comment]
That's strange, I'm in a hurry in the same way...
