### ISSUE TITLE
[warp] signs

### ISSUE THREAD

**Issue by SjakeCraft** [tastybento/ASkyBlock-Bugs-N-Features#282]
Hello Tastybento, 
I have a problem with the [warp] signs. Whem sombody creates a sign with [warp] it says ''no permission'' but what is the permission?

**Comment by Poslovitch** [comment]
It's not [warp]. It's the «welcomeLine» specified in the default locale file

**Comment by SjakeCraft** [comment]
When a OP place a sign with [warp] it work. On a normal player it says: No permission!

**Comment by tastybento** [comment]
These are the perms for warps - they are normally given by default:

```askyblock.island.warp:
            description: Let the player use /island warp to warp to a players island
            default: true
          askyblock.island.addwarp:
            description: Let the player place a Welcome warp sign`

**Comment by SjakeCraft** [comment]
Also with permissions it not work...

**Comment by tastybento** [comment]
What error do you see @SjakeCraft now? If players are still seeing "No permission" then the permissions are wrong. What perm plugin do you use and how are you adding perms? If the players see another error then post it.

**Comment by SjakeCraft** [comment]
http://prntscr.com/fos30e those are the permissions.

**Comment by SjakeCraft** [comment]
The players see no permission

**Comment by tastybento** [comment]
I think the issue is like Postlovich said - it is not [warp] it is [welcome].

**Comment by SjakeCraft** [comment]
With [welcome] nothing happen.

**Comment by SjakeCraft** [comment]
And in the config it's also [warp]

**Comment by tastybento** [comment]
Sorry, I've no idea. Maybe another plugin is interfering. Try on a test server on your own PC. Just put ASkyBlock and Vault only as plugins. Then check to make sure warp signed work. You should be able to use them immediately (if you have island level >10). Then once you have it working, add other plugins until it matches your setup. That's all I can offer right now.
