### ISSUE TITLE
Feature - IS Top Based on Island Members

### ISSUE THREAD

**Issue by Fluxty** [tastybento/ASkyBlock-Bugs-N-Features#284]
Islands with less than the max members are at a disadvantage on /is top, due to larger teams being able to make more progress. This is particularly challenging for solo islands and becomes increasingly demotivating to play on servers that are not freshly reset. 

I'm proposing alongside the global /is top there could also be island top leaderboards based on the team members, so a separate is top for teams of 1, 2, 3, etc. exclusively.

**Comment by tastybento** [comment]
I like this.

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#72
