### ISSUE TITLE
Not able to add Island

### ISSUE THREAD

**Issue by Elementkingaming** [tastybento/ASkyBlock-Bugs-N-Features#287]
Hey, i have tried to customize my config.yml so that none of the other islands dont show in the gui, but none of my changes are taking effect, the only change that is taking effect is that i replaced the island.schematic with my own custom island, but the chest stays the same as normal, and everything else but my island blocks arent there. HELP!

https://pastebin.com/Qw0pLmfw (My Config.yml file)

**Comment by Poslovitch** [comment]
Check your config.yml file with the YAML parser below and fix it. There are errors.
http://yaml-online-parser.appspot.com

**Comment by Elementkingaming** [comment]
while parsing a block mapping
  in "<unicode string>", line 26, column 4:
       distance: 200
       ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 118, column 18:
       - "&9[player]'s cow"
                     ^

Thats what came out, what does it mean??

**Comment by tastybento** [comment]
It means your file is incorrect YAML formatting. YAML requires you to carefully space everything. You cannot use tabs and spaces count. I recommend you copy the config.yml from [here](https://github.com/tastybento/askyblock/blob/master/config.yml) and restart your editing. Before you copy it over, check with the syntax checked.
