### ISSUE TITLE
Cant Customize Islands

### ISSUE THREAD

**Issue by Elementkingaming** [tastybento/ASkyBlock-Bugs-N-Features#288]
Hey, i have tried to customize my config.yml so that none of the other islands dont show in the gui, but none of my changes are taking effect, the only change that is taking effect is that i replaced the island.schematic with my own custom island, but the chest stays the same as normal, and everything else but my island blocks arent there. HELP!

https://pastebin.com/Qw0pLmfw (My Config.yml file)

**Comment by Poslovitch** [comment]
Duplicate #287
