### ISSUE TITLE
Island size not updating with permission

### ISSUE THREAD

**Issue by iDirtniverse** [tastybento/ASkyBlock-Bugs-N-Features#291]
When a player have the permission for more than default please update the changes and apply them because the player have to reset Island to do so :(

**Comment by Poslovitch** [comment]
It applies on the island after a relog, and only if the player is the island leader.

**Comment by iDirtniverse** [comment]
Alright. Thank you! I will commit testing now :)

**Comment by iDirtniverse** [comment]
It works but, I hook the plugin up with BossShop now my, Admins, they can't purchase it because they're opped basically they have the upgrades all unlocked but they havnt. since they have '*' perms, but the island size is still 100x100 :/

**Comment by tastybento** [comment]
That's a problem with BossShop and how it gives permissions. If your admins have everything then they can just give themselves bigger islands using /asadmin setrange (their name).
