### ISSUE TITLE
Askyblock Scoreboard glitch!

### ISSUE THREAD

**Issue by Snaily9** [tastybento/ASkyBlock-Bugs-N-Features#292]
You may know that Askyblock doesn't have a ScoreBoard! your right, but, I have a plugin called CTNS+ it's a scoreboard and tab plugin! But, bad thing is, Askyblock plugin is overlapping it! the owner of CTNS+ told me to give him a photo of the log, so I did. After I did, he said this "There we go, now can I help you. It seems like an error with ASkyBlock variables. You can disable the variable in the Variables.yml, this will fix the problem for now." But, there isn't a Variables.yml! How do I fix this glitch? Here is the log

https://gyazo.com/0c7d7057c936b652621cccfb51fd3801

**Comment by Poslovitch** [comment]
Yep, there is no Variables.yml in ASB. Is there one in CTNS+?

**Comment by Snaily9** [comment]
Sorry, I fixed the issue there is one in the CTNS+
