### ISSUE TITLE
Problem with islands saying "Island Protected" 

### ISSUE THREAD

**Issue by Keo1711** [tastybento/ASkyBlock-Bugs-N-Features#294]
Hello,

I am trying to setup ASkyblock on my server,
I have removed both the 2 ASkyblock worlds and the plugin folder,

I am setting the values to these:
   distance: 250
   protectionRange: 200

Yet when i join the server, i get Island Protected, i have the right permissions set.

Thanks Keo,

I want the islands 200 blocks x 200 Blocks with around 50 blocks gap so people can see each other.
 Thanks

**Comment by Keo1711** [comment]
The IP is

play.keomc.net

If you want to check the problem out

**Comment by tastybento** [comment]
Follow these instructions after setting your config.yml:
https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#reset-but-keeping-configyml

**Comment by Keo1711** [comment]
Thanks it worked, i cant seem to get an 1 center block though, if i use either 199 or 200 for island protection, i always end up with a 2 block center. Thanks
