### ISSUE TITLE
Cant enable Join/Leave Messages on Islands :/ 

### ISSUE THREAD

**Issue by AconTM** [tastybento/ASkyBlock-Bugs-N-Features#295]
I have Disable this Feature and now i woud enable it again.. But after:

- Config Change
- asadmin reload
- Server restart
- asadmin settingsreset all
- asadmin settingsreset ENTER_EXIT_MESSAGES

it is no there :/

Pls help

**Comment by Poslovitch** [comment]
Please send us your config.yml file.

**Comment by AconTM** [comment]
https://hastebin.com/gumijuroma.php

**Comment by AconTM** [comment]
so? :/

**Comment by tastybento** [comment]
I can't replicate this issue right now. Do you have the text in your locale file? Look for **nowentering** and **nowleaving**.

**Comment by AconTM** [comment]
Thanks for your help ^^ i have "nowleaving" empty >.< now it works
