### ISSUE TITLE
Make the custom nether roof unbreakable

### ISSUE THREAD

**Issue by Mickooo** [tastybento/ASkyBlock-Bugs-N-Features#296]
I've recently started a server and have used ASkyBlock for my skyblock, the problem I'm having is that when you create a nether island, you can easily build up and destroy the "roof" (the glowstone and netherrack), I don't want my players to be able to do this as it will ruin the look of the "roof" and they'll be able get free glowstone which I don't want. 
Is there a way to stop them from being able to edit the top?

Thanks in advance for the help!
~Micko

**Comment by tastybento** [comment]
There isn't, but you can just remove it (config setting). It was originally placed there to enable players to obtain glowstone which is not in the nether island.

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#32
