### ISSUE TITLE
Basic commands

### ISSUE THREAD

**Issue by WinterFellium** [tastybento/ASkyBlock-Bugs-N-Features#298]
Good morning/afternoon. I wanted to know if it's possible to change de basic commands such as /island create to /island new for example. All the same with the other commands such as /challenge, etc. I'm a  Spanish member of GitHub so this will really help me out with my server. Thank you a lot. I've tried to change them at the section un plugin.yml where it says commands but i can't

**Comment by WinterFellium** [comment]
I dont really know how to edit te previous message so i've tried to change them at the section un plugin.yml where it says commands but i can't

**Comment by tastybento** [comment]
Sorry, no, you will need to change the source code to do that. You can add aliases in plugin.yml to the main commands, but the sub commands are hard-coded.

**Comment by WinterFellium** [comment]
ok thanks
