### ISSUE TITLE
Monsters dont' spawn

### ISSUE THREAD

**Issue by haugsvar** [tastybento/ASkyBlock-Bugs-N-Features#299]
After upgrading to 3.0.6.8 i have no monsters spawning. This relates both to "natural" spawns in dark spots and the spawners in the nether.

Then removing the ASkyBlock.jar file, both spigot and paperspigot spawns monsters as normal. Once the server starts with the ASkyBlock.jar file, monsters are not spawning at all.

> ver
[14:28:15 INFO]: This server is running CraftBukkit version git-Spigot-b78586d-f3356f1 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

>ver ASkyBlock
[14:29:21 INFO]: ASkyBlock version 3.0.6.8
[14:29:21 INFO]: A SkyBlock Plugin
[14:29:21 INFO]: Author: Tastybento

Console outout seems normal at startup, difficulty is set to 3 in the server.properties file. Can't see anything in the askyblock config.yml that would block monsters from spawning like this? 

askyblock config.yml at https://pastebin.com/FNDf6uSb

**Comment by tastybento** [comment]
Please read the FAQ.

**Comment by haugsvar** [comment]
It worked straight away then following the FAQ. Feeling stupid now...

Thank you very much for your great work with this solid plugin.
