### ISSUE TITLE
Accessing the Level of an island from another plugin is a pain

### ISSUE THREAD

**Issue by Rsl1122** [tastybento/ASkyBlock-Bugs-N-Features#300]
Hello.
I had a request to include data from this plugin in my plugin [Player Analytics](https://www.spigotmc.org/resources/plan-player-analytics.32536/)

Unfortunately getting the level of a player's island would require either rewriting the level calculation code of yours, or extending CommandSender & parsing the message sent to that.

It doesn't help that the code doing the calculation is not divided into multiple smaller methods as per [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle)

Is there an alternative to [LevelCalcByChunk](https://github.com/tastybento/askyblock/blob/f8beec9860f9c25432715446bd3a19214511e036/src/com/wasteofplastic/askyblock/LevelCalcByChunk.java)?

**Comment by Poslovitch** [comment]
Well, that's in part why we're completely rewriting ASkyblock (https://github.com/tastybento/bskyblock).
Island level will be handled by an addon, and I'll take on board your need.

**Comment by Rsl1122** [comment]
Great!

**Comment by tastybento** [comment]
@Rsl1122 There is an API you can use. The call you want is:

http://tastybento.github.io/askyblock/com/wasteofplastic/askyblock/ASkyBlockAPI.html#getIslandLevel(java.util.UUID)

Please don't try and call internal classes directly. We have an API so you don't have to worry about class names changing underneath you.

There is a way to call the level **calculation** in the API too:

http://tastybento.github.io/askyblock/com/wasteofplastic/askyblock/ASkyBlockAPI.html#calculateIslandLevel(java.util.UUID)

then wait for the events to trigger. However, calculating levels is extremely computationally intensive (especially with large island spaces) and has to run in background mode.

**Comment by Rsl1122** [comment]
Sounds good, thanks!
