### ISSUE TITLE
Can't Spawn in my island, Respawn PROBLEM

### ISSUE THREAD

**Issue by LimTheLime** [tastybento/ASkyBlock-Bugs-N-Features#303]
everytime i die in void i get tped to my island and just when i move
i get tped to "/island spawn"
my configuration is this 

_# Have player's respawn on their island if they die
   respawnonisland: true_

it still spawn me on "/island spawn". 
i tried it vice-versa see if it works, and i did was

_# Have player's respawn on their island if they die
   respawnonisland: false_

still spawned me on that "/island spawn"
i dont even know if this is a glitch or a bug or
did do something wrong with the config. 

i need help. :(

**Comment by tastybento** [comment]
What other plugins are you using that are to do with spawn? It looks like there's some kind of clash going on.
