### ISSUE TITLE
Pets can be nametagged on other islands by not owner.

### ISSUE THREAD

**Issue by wasder** [tastybento/ASkyBlock-Bugs-N-Features#304]

**Comment by Poslovitch** [comment]
Parrots are currently not protected by the plugin. We'll release a fix asap.

**Comment by wasder** [comment]
Ah sorry wrong bug report. The core problem is that anyone can nametag your pets if you are with them on others islands.

**Comment by tastybento** [comment]
This should be protected. Investigating.

**Comment by tastybento** [comment]
Ah, this is possible with the offhand. Fixing...

**Comment by tastybento** [comment]
Fixed with commit d04466e
