### ISSUE TITLE
Admin don't get hungry

### ISSUE THREAD

**Issue by FilidDamhsoir** [tastybento/ASkyBlock-Bugs-N-Features#305]
Only in our skyblock world, our players with the Admin and Owner ranks can receive damage, but never lose saturation/hunger. This only happens in skyblock, we also have other worlds where saturation and hunger work as normal. 
Is there an option in the configs that I'm missing? 

They only perms they have that other ranks lack in this world are:
      skyblock:
        permissions:
        - -askyblock.islandfly
        - -askyblock.island.minishop
        - -askyblock.command.challengeexempt

**Comment by tastybento** [comment]
By Admin, I assume they have the askyblock.* permission. 

Make sure they have -askyblock.nohunger too.

You can see all the perms here:
https://github.com/tastybento/askyblock/blob/master/plugin.yml

**Comment by FilidDamhsoir** [comment]
Thank you. That's exactly what it was. I swear I read that list twice and still missed it, knew it was going to be something dumb
