### ISSUE TITLE
Permission Required for Challenge Feature?

### ISSUE THREAD

**Issue by AaronStrange3** [tastybento/ASkyBlock-Bugs-N-Features#306]
It would be very useful if a challenge could REQUIRE a certain permission for completion.  If this is already a feature, I apologize for my arrogance.

**Comment by tastybento** [comment]
Not arrogant. This is actually a planned feature, but it got tied up in the challenges rewrite, which then got tied up in the whole plugin rewrite (bskyblock) so it's planned!

**Comment by AaronStrange3** [comment]
Thanks for the quick reply!

**Comment by Poslovitch** [comment]
See #10
