### ISSUE TITLE
Some ideas to greatly improve the ASkyBlock plugin.

### ISSUE THREAD

**Issue by nasorus** [tastybento/ASkyBlock-Bugs-N-Features#308]
Hi TastyBento,

i've been playing skyblock since 3 years, always using your great plugin, only things i regret about it is the fat that the challenges aren't flexible, let me explain myself.
The challenge creation isn't intuitive, you get the hold on it after some time, and it still takes a lot of time to make.
So here are some propositions i have for making it better:
- Make an in-game edit mode for challenges, (i'm not really a java dev but i guess it's a code that would detect materials that enter a certain inventory wioth their numbers and append them to a list??) it would be so so helpfull.
- Challenges don't support either detection or reward of enchanted items, i guess this is a bukkit limitation with its materials and the complex minecraft ID's but i hope it's possible.
- Make challenge level for only some people who donate. (i guess this is possible for us to make by just making a challenge impossible to normal users etc.. but it wouldn't be reallly great).
- Be able to custom the multiple repeatable rewards, say i want to reward for the first achievement item A, for the second completion item B, but not for the third, i would want item C, and then it would give item C until it runs out of times of repeating the challenge, and the last one would be item D.
- Have islands for only people with certain permissions, let's say he has bought a custom island on the shop, i'd be able to give him the permission and he would get access to it, this would also allow for challenges to reward custom islands.

These are all the improvements i could think about right now, please answer me and tell me wich are possible and wich aren't, and if you'll consider making any of these improvements.

**Comment by Poslovitch** [comment]
Thanks for your ideas. Some of them were already in the todo list -> see #10 and all the related issues.

We'll probably do an editor for challenges. However, I'm not sure if it will be a software or directly IG. One thing is certain : it will be hard and time-consuming.
