### ISSUE TITLE
Idea for Island-Level

### ISSUE THREAD

**Issue by AconTM** [tastybento/ASkyBlock-Bugs-N-Features#309]
is there any Option for Calculate players Island Level in a time-loop? every 10 seconds or Instand 

Thats rly Important for Magic Cobble, because when i make /is level with Island Level 50 and then
i go and break the Blocks.. The Island level is still there on 50

Sorry for my bad bad english >.<

**Comment by Poslovitch** [comment]
Well, even if the island level is calculated async, running it every 10 seconds or at every block place/delete/move will just kill the CPU. At least, I suggest you to toggle level calculation on join (loginlevel).
