### ISSUE TITLE
Multi-world

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#31]
_From @Poslovitch on January 24, 2017 6:45_

Make ASkyBlock, once island limit in the world reached, can create another world.

_Copied from original issue: tastybento/askyblock#476_

**Comment by Poslovitch** [comment]
_From @tastybento on January 27, 2017 19:56_

What would be the benefit?

**Comment by Poslovitch** [comment]
May not be really useful as I originally said, but we can make ASkyBlock handles both spawn world and islands world.

**Comment by tastybento** [comment]
I don't think we're going to do this.
