### ISSUE TITLE
Unable to get a center block of 1

### ISSUE THREAD

**Issue by Keo1711** [tastybento/ASkyBlock-Bugs-N-Features#310]
I have set my island to both

   distance: 230
   protectionRange: 199

and

   distance: 230
   protectionRange: 200

Yet both times i get a center block when i go around the edges with cobblestone and then do //center goldblock to find the middle.

is it possible to have a 1 center block, preferable the logs on the tree? Thanks

**Comment by Poslovitch** [comment]
Protection range doesn't affect the center block. Try edit the distance instead.

**Comment by Keo1711** [comment]
Will it break if i make the distance an odd number?

**Comment by Poslovitch** [comment]
Well, I forgot about that. Let us investigate this problem.

**Comment by tastybento** [comment]
You cannot use odd numbers. (It says so in the config). The protection distance must be even because it is divided by two and goes outward from the center block. So 199 or 200 is the same. The island center is the bedrock block.
