### ISSUE TITLE
Problem with Item ID 44:3

### ISSUE THREAD

**Issue by AconTM** [tastybento/ASkyBlock-Bugs-N-Features#311]
i cant Limited this ID in blockvalues.yml because the Type "STONE_SLAB" is not there.. 

pls help ;o

**Comment by Poslovitch** [comment]
In Bukkit, slabs are generally named «_STEP».

**Comment by AconTM** [comment]
[ASkyBlock] Unknown material (STONE_STEP) in blockvalues.yml Limits section. Skipping...

**Comment by Poslovitch** [comment]
You should have a look at Spigot material javadoc.

**Comment by tastybento** [comment]
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
