### ISSUE TITLE
Missing artifact using Maven

### ISSUE THREAD

**Issue by TheZopo** [tastybento/ASkyBlock-Bugs-N-Features#312]
I have downloaded the source code of ASkyBlock, but there is missing artifacts : 
`craftbukkit-1.7.9-R0.3-20140705.002733-4.jar 
spigot-1.9.2.jar 
spigot-1.9.4.jar 
spigot-1.12-pre2.jar 
spigot-1.10.jar 
spigot-1.11.jar 
spigot-1.9.jar 
spigot-1.8.jar 
spigot-1.8.3.jar 
spigot-1.8.4.jar 
spigot-1.8.6.jar 
spigot-1.8.8.jar 
spigot-1649.jar `

At worst, where wan we donwload all theses dependencies without Maven ?

**Comment by Poslovitch** [comment]
With Maven, we just download the latest spigot version. That's useless to download older versions in order to avoid errors about not found NMS classes.

There is plenty of websites that provide older spigot versions to download.

**Comment by tastybento** [comment]
@TheZopo The binaries of the past servers are something we cannot distribute unfortunately. Please find them yourself, or just delete the support for the server in the NMS files so they are not dependencies.
