### ISSUE TITLE
Constant death

### ISSUE THREAD

**Issue by solsquinox** [tastybento/ASkyBlock-Bugs-N-Features#313]
I AFKed on my island and died to most likely a mob, I logged out afterwards.
Now whenever I try to go to my island, I constantly die.

https://youtu.be/mvITDlA0_K8 Here's a video of the problem.

I don't know if there are any conflicts with plugins but here are the major ones.
Towny, Craftbook, Multiverse, McMMO, LWC, ChestShop, PreciousStones.

P.S. Changing to God mode and Creative did not help the situation.

**Comment by Poslovitch** [comment]
Firstly, check by removing plugins one by one.

**Comment by tastybento** [comment]
It says "Flying is disabled in the world" when you teleport, looks like some kind of anti-cheat thing going on. Definitely another plugin.
