### ISSUE TITLE
Customizing "Nether tree"

### ISSUE THREAD

**Issue by rickiewars** [tastybento/ASkyBlock-Bugs-N-Features#314]
Is it possible to customize the nether tree? I want to replace the gravel of the tree with netherrack and maybe the glowstone with quartz ore. This because gravel is practicaly useless and you can get glowstone already from witches. Is there a way to customize that? If not can this future be added?

Great thanks in advance
Rickiewars

**Comment by Poslovitch** [comment]
That's a good idea !

**Comment by rickiewars** [comment]
Wow fast respond! I tought it to! thnx!

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#24
