### ISSUE TITLE
Problem with God

### ISSUE THREAD

**Issue by Manu5656** [tastybento/ASkyBlock-Bugs-N-Features#316]
Even though a player in "God" mode takes anyhow from acid, how come? How can I do that with the active God do not get harm?

**Comment by Poslovitch** [comment]
Is this player supposed to be an OP player? Or is it a normal player that bought god mode?

**Comment by Manu5656** [comment]
A normal player who bought the God mode

**Comment by Poslovitch** [comment]
Well, this sounds like a "bug". Let us investigate it and we'll probably add an option to toggle that.
As a temporary fix, you can give him the `askyblock.mod.noburn` permission.

**Comment by Manu5656** [comment]
I had also thought about temporarily putting this permission but at that point it would not make sense to turn the god on or off but at least for now I think I will do so. Thanks for the attention.

**Comment by tastybento** [comment]
God mode is a mode provided by Essentials and not a vanilla or spigot mode so this isn't a bug. I've looking into this in the past, and I cannot find a way to tap into "god mode". Please use the noburn permission.
