### ISSUE TITLE
Unable to complete a challenge

### ISSUE THREAD

**Issue by xToxicAngel** [tastybento/ASkyBlock-Bugs-N-Features#317]
Recently I have found that the Map Challenge under Expert no longer works since upgrading the server to 1.12. I have already completed it when the server was 1.11, but now it no longer works for other players and as a repeat challenge. When clicked, it does nothing and no errors are found in the console. Do you have any suggestions? Thanks in advance.

**Comment by Poslovitch** [comment]
No errors in the console? Anyway, can you send us your logs?

Can you send us your challenges.yml file?

**Comment by xToxicAngel** [comment]
I'm only an admin so I'll have to wait for the owner's response. Reporting this for him since he's busy. Will get back to you soon hopefully :)

**Comment by xToxicAngel** [comment]
Here's today's log: https://pastebin.com/HFDBqCjg

And here's the challenges.yml file: https://pastebin.com/EGVmFpBf

On the log, [09:03:48] is when I started trying to get the challenge to work but it seems like nothing shows apart from the /challenges command

**Comment by tastybento** [comment]
I just tested the Pioneer challenge (I assume that's what you mean by map challenge) on 1.12 and I don't find a problem. You do need to look at the map to change it from an empty map to a map, but that was always the case.

**Comment by xToxicAngel** [comment]
I managed to find the issue. When upgrading to 1.12, the ID of the icon in the challenges menu had changed, and the server couldn't recognize it which made it unclickable. Thanks for trying to help though :)
