### ISSUE TITLE
Challenge completion state not written in player file

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#318]
Reported by Heliosard, from hyparia.fr server.

When a player completes a challenge, he gets the rewards. However sometimes, the plugin doesn't save he has completed the challenge, even though the rewards have been given. This results in potential repeatable unrepeatable challenges, or just causes a problem to get to the next challenge tier.

According to Heliosard, this problem seems to happen for 6 months or more. It happens about 1 / 50 times a player completes a challenge.

--------------------------------------------

I suspect ASkyBlock or another plugin that might use ASB's files (see the potential interfering plugins list below) to overwrite the player file. Maybe during the backup?

Plugins:
Leaderheads
| FeatherBoard
| AnimatedNames
-> (these two plugins are linked with MvdwPlaceholderAPI)

TacoSpigot 1.8.8 (latest version for 1.8.8)

**Comment by tastybento** [comment]
I added explicit saving of the player data immediately after the player does a challenge. Previously the data was just kept in RAM and if the server restarted without properly shutting down, maybe the data could be lost. I don't see any other reason why this could happen. So, let's try this and if it still happens, reopen.
