### ISSUE TITLE
Rewards custom items

### ISSUE THREAD

**Issue by willywanka** [tastybento/ASkyBlock-Bugs-N-Features#320]
I wanted to make a reward where they get a sword that is named and comes with some enchantments but when I tried to do the give [player] command on the reward it gave a error followed by a massive list of the bukkit materials here is an example of the code I wrote any suggestions to fix it. 

itemReward: 'give [player] minecraft:wooden_sword 1 0 {Lore:["Not much noise but likes to spark"],Name:"Creeper slayer sparky"},ench:[{id:16,lvl:1},{id:19,lvl:1}]}'

**Comment by Poslovitch** [comment]
Just put your code in "rewardcommands" or "commandreward" section (forgot the exact name).

**Comment by willywanka** [comment]
your meaning this?
 Commands are:
#    rewardcommands:
#      - command1
#      - command2

**Comment by Poslovitch** [comment]
Yep
