### ISSUE TITLE
No downside level on chat

### ISSUE THREAD

**Issue by PanKlipcio** [tastybento/ASkyBlock-Bugs-N-Features#327]
Add the ability (to set in configuration) to the minus level rounded to 0

_(Polish version: Dodać zdolność (do ustawienia w konfiguracji) by minusowy level wtyczka zaokrąglała do 0)
(translated by google translate)_

Is what I wrote is understandable? xD

**Comment by PanKlipcio** [comment]
#265

**Comment by Poslovitch** [comment]
Related to #235. Thanks for suggesting.
