### ISSUE TITLE
Light bug after pasting in new island ; lit furnaces / redstone lamps arent paste

### ISSUE THREAD

**Issue by FrankHeijden** [tastybento/ASkyBlock-Bugs-N-Features#328]
Heya,

Lighting is very weird when you restart your island and/or start a new island. It shows weird dark black spots. Maybe add a hook into FastAsyncWorldEdit to handle pastes, so it can paste even faster and with 0 lagg. 

Frank

**Comment by FrankHeijden** [comment]
+ redstone lamps are not pasted as "ON", however they were on with creating the schematic. Also when pasting it directly from WorldEdit its fine.

**Comment by FrankHeijden** [comment]
+minecraft:lit_furnace is pasted as a default furnace

**Comment by Poslovitch** [comment]
The island pasting works faster as FAWE, however lightning bugs are result of Minecraft bugs. We can't do anything more for that.

For lit furnaces and redstone lamp, we'll have a look.

**Comment by tastybento** [comment]
I'll look into the lamps and furnaces.

**Comment by tastybento** [comment]
Redstone lamps are working okay (although lighting doesn't always calculate - this is a won't fix issue).

Burning furnaces are fixed with the commit, as are all other inventory holders, like dispensers and hoppers.
