### ISSUE TITLE
Solid block found during long search - adding to islands.yml

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#330]
Hi, i converted my uSkyBlock data to ASkyBlock data. When i try to restart my island i get this information spam and server crashing after a while. 

Can you do that process async? So it can handle it without crashing.

**Comment by Poslovitch** [comment]
You forgot the logs. ^^

**Comment by UnioDex** [comment]
There is no crash report or log errors. Taking the header message spam and server is killing. I checked htop when this process is going and saw that RAM is hitting highest value (8GB). Seems like the data that will adding to islands.yml keeping in memory.

**Comment by Poslovitch** [comment]
I see. UASkyblockConverter has been developped by @tastybento a long time ago. It may not work correctly now. Report this bug on UASkyblockConverter's bug tracker. However, I'm not sure that Tastybento  will update the converter, as it probably took and will take again a lot of time.
