### ISSUE TITLE
Co-Op to grind / pick up items.

### ISSUE THREAD

**Issue by ArcheonKhan** [tastybento/ASkyBlock-Bugs-N-Features#331]
https://paradise-mc.net/threads/permissions-on-other-peoples-islands.4239

This is basically my issue with the plugin, I'm not sure what to do here or if that there is an option (could not find it if there is one).

**Comment by Poslovitch** [comment]
Please send us your config.yml.

**Comment by ArcheonKhan** [comment]
I'm sorry, it seems that the issue has been fixed today, sorry for opening up this ticket.
