### ISSUE TITLE
"This island is protected" Players can't edit own island

### ISSUE THREAD

**Issue by MysticParadox** [tastybento/ASkyBlock-Bugs-N-Features#332]
Players create their own island with /is and then once they arrive at their island and try to build anything.
It literally just says "Island protected" in red text.  I tried both deleting the player's island and deleting their player file data with no luck. They have all the correct permissions.

**Comment by MysticParadox** [comment]
EDIT: I can give them the admin bypass permission but that's the only way to get it to work.

**Comment by MysticParadox** [comment]
10.07 19:12:51 [Server] INFO KeyLimePaiii issued server command: /is
10.07 19:12:54 [Server] WARN [ASkyBlock] *** Duplicate or overlapping islands! ***
10.07 19:12:54 [Server] WARN [ASkyBlock] Island at (-200, -200) conflicts with (-200, -200)
10.07 19:12:54 [Server] WARN [ASkyBlock] Accepted island is owned by Ibiza
10.07 19:12:54 [Server] WARN [ASkyBlock] 0f076e56-63b0-45c2-8a3c-390316fe8378.yml
10.07 19:12:54 [Server] WARN [ASkyBlock] Denied island is owned by KeyLimePaiii
10.07 19:12:54 [Server] WARN [ASkyBlock] ea157b8b-af10-4000-904e-16d17e956da2.yml
10.07 19:12:54 [Server] WARN [ASkyBlock] Recommend that the denied player file is deleted otherwise weird things can happen.

**Comment by tastybento** [comment]
Stop server, delete islands.yml, restart. It looks like some config changes were made after the server was created.
