### ISSUE TITLE
Config?

### ISSUE THREAD

**Issue by PyraFox** [tastybento/ASkyBlock-Bugs-N-Features#333]
Ok, So what I'm wanting to do is allow players to build to each others islands (Will have a secondary plugin to counteract a portion of it). I need to know if it's possible to do this currently or if it could be added?

If it's possible with just the config, could I get a copy of that done properly? Obviously certain things would probably need changing too such as item limits. If that's possible for someone to do that'd be freaking awesome.

Thankyou <3

**Comment by Poslovitch** [comment]
Check coop.

In BSkyBlock, we'll completely improve it, but now it is a bit limited.

**Comment by PyraFox** [comment]
There is nothing in "coops"
Is coop part of another file or something?

**Comment by Poslovitch** [comment]
What I meant is to check «coop» options in config.yml

**Comment by tastybento** [comment]
Give players the askyblock.coop permission and they'll be able to add coop players to their island. It's all fully supported already. :-)

**Comment by PyraFox** [comment]
I'm sorry, I don't think you fully understood me haha, I mean I want players to be able to build TO other islands, not just on them.

**Comment by tastybento** [comment]
In that case, just make the protection distance the same as the island distance and players will be able to make their islands meet.

**Comment by PyraFox** [comment]
So islands will spawn directly next to each other??
I want it to be like islands are 3-400 blocks apart but players can build to each other. 
There's gonna be a factions plugin installed for claiming.
It's like basically essential for this to work
If that can't work yet, could you guys add it to an update?

**Comment by tastybento** [comment]
There are two settings, island distance and island protection. Make them the same and a player will be able to build right up to the edge of their zone. Make them 400 or whatever. You can't change the island distance mid-game. 

But what you're saying is you want some kind of free for all where there is no protection. In that case turn off all the protection settings (allow visitors to do everything)

Now, it's your turn. Install the plugin and start trying stuff out. Once you've got it all running and you've played with the settings and if then you still have a question let us know.  Good luck.
