### ISSUE TITLE
1.12 blocks in blockvalues.yml

### ISSUE THREAD

**Issue by FrankHeijden** [tastybento/ASkyBlock-Bugs-N-Features#334]
Heya,

could you maybe add the 1.12 blocks to the config file? I made the list up to date for you;
https://pastebin.com/Vmh0pC48

(added concrete, concrete_powder, and *_glazed_terracotta). Values have been set to 1.

**Comment by FrankHeijden** [comment]
I mean, as default

**Comment by Poslovitch** [comment]
Thanks

**Comment by FrankHeijden** [comment]
I see one mistake, GRA_GLAZED_TERRACOTTA should be ofc GRAY_GLAZED_TERRACOTTA.

**Comment by tastybento** [comment]
Thanks!
