### ISSUE TITLE
ASkyBlock Questions

### ISSUE THREAD

**Issue by sonofachilles9** [tastybento/ASkyBlock-Bugs-N-Features#335]
I am setting up a skyblock server and don't want island levels as a base for peoples skyblock island. I want people to be free on their island and there be no "top island" or have to place emerald blocks etc to improve their island level. Please tell me how i can fully disable this feature.
Also i want people to do /visit <name> and even when they are offline they can still visit someones island and look around. No "Welcome" signs. Just 1 global spawn for owner and players when they go their island and you can visit anyones island at any point with /Visit <name> can this please be possible. If it is please teach me the ways to set this up

**Comment by Poslovitch** [comment]
There is, for your 2 wills, no way to do that in ASkyBlock. However, for the island level, our indev version called "bSkyblock" may fulfil your need, but it is still under heavy development.

For your second will, we may provide another warp way to visit islands, but it will still be warps, because we need the players to tell us where is the entry to visit their island. 
If you want your command, you'll need to code it by yourself.

**Comment by sonofachilles9** [comment]
Skyrealms has it if you have heard of them? Where you do /visit and the island has 1 area where it cannot be mined by players and a bridge walking over to the main island where you build. Would you know how to go about doing this? 

Also you mean there is no way to disable the [welcome] and instead SET where the players spawn on our own custom schematic and /visit teleports them to that spawn on that persons island?

Also is there a seperate command to bring up the "select island" gui as i wanna set an alias for /claim which brings that interface up. and have a seperate /unclaim to remove your island? I cant see a /is create or anything like that command on the plugin

**Comment by Poslovitch** [comment]
I never heard of this server. And I think they created their own plugin. The ideas you are talking of are not compatible with ASkyBlock's behaviour. I can only give you some possible workarounds with the actual version.

We cannot create more commands like /visit, /claim ect. We can only add arguments to our exisiting commands like /is about, /is warp...

You can use our API (ASkyBlockAPI) to create the visit command by getting the island owner's spawnpoint. And disable warps by setting warplevel (not sure of the exact name) to a high amount.

Finally, there is no /is create command currently in the plugin. It will come in bSkyblock. In fact, the island selection GUI only appears when a player types /is and hasn't an island.

Hope it helped you.

**Comment by sonofachilles9** [comment]
What is the schematic permission to give players so they have a choice based on the ranks they have what island they can choose? 

And

How do you offset the island in the build area?

**Comment by tastybento** [comment]
@sonofachilles9 You can choose any permission you want for each schematic. Just read config.yml schematic section for instructions. Just add the permission: line to the schematic config.

The bedrock block always goes where the island center is. Use that to "shift" the island around, but there's no frame of reference, so players will not know the difference really.

**Comment by sonofachilles9** [comment]
Where do i find this ASkyBlockAPI?

**Comment by Poslovitch** [comment]
This is a class in ASkyBlock. Just download the latest version and add it to the librairies of your own plugin to be able to use it.

**Comment by tastybento** [comment]
Google "Askyblock API"

**Comment by sonofachilles9** [comment]
Btw you say we can set our warps really high so then players cannot make a warp sign. Is there a possibility we can get around it and still have the warp signs really high but instead be able to do /visit <name> and visit a players island without the welcome signs? Because we want people to go to someones island to visit using the same spawn as the owner but without the need of silly [welcome] signs

please help us witht his as we relly want to be able to visit other peoples islands without the damn sign lol

**Comment by tastybento** [comment]
Give players the **askyblock.mod.tp** permission, then they'll be able to do /asadmin tp (name). You may be able to find a remapping plugin to change that command, or just change the source code yourself.

**Comment by sonofachilles9** [comment]
Thanks very much mate :)
