### ISSUE TITLE
[Server] INFO Title command successfully executed

### ISSUE THREAD

**Issue by FrankHeijden** [tastybento/ASkyBlock-Bugs-N-Features#336]
Heya, this is a bit spammy in the console whenever a player goes to their island,

13.07 20:10:02 [Server] INFO FrankHeijden issued server command: /is go
13.07 20:10:02 [Server] INFO Title command successfully executed
13.07 20:10:02 [Server] INFO Title command successfully executed
13.07 20:10:15 [Server] INFO Title command successfully executed

is there a way to fix this? as I already had an island, and the title only needs to show up at the start of your island?

**Comment by Poslovitch** [comment]
This is due to the subtitle sesent when entering/leaving an island.

In bSkyblock, we'll replace this to a NMS-handled title sending.

**Comment by FrankHeijden** [comment]
Btw a question, you're adding the 4.0 milestone, ive seen that one before xd

is there a ~ date for the release of 4.0? :D

**Comment by Poslovitch** [comment]
None. 4.0 = bSkyblock. We are planning to release an alpha version in about a month, but it will be significantly "light", compared to ASkyBlock.

Maybe a full release for the end of the year? We currently don't know.

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#85
