### ISSUE TITLE
Increase entities/tile entities limits by island level

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#34]
_From @Poslovitch on January 20, 2017 19:52_

https://www.spigotmc.org/threads/a-skyblock.30325/page-167#post-2176809

Add per-island-level limits for entities and tile entities.

_Copied from original issue: tastybento/askyblock#465_

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#40
