### ISSUE TITLE
How to protect the chests of the mods?

### ISSUE THREAD

**Issue by Westus** [tastybento/ASkyBlock-Bugs-N-Features#345]
Guests can open chests from mods on other islands.

**Comment by Poslovitch** [comment]
Spigot doesn't allow us to get items/blocks from mods. We can't protect them.
However, we can probably add a config file where you could put the ids of blocks you want to protect.
Let's see what @tastybento thinks of this idea.

**Comment by tastybento** [comment]
What's the mod and what is the block id?
