### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sonofachilles9** [tastybento/ASkyBlock-Bugs-N-Features#346]
We have added our own schematics for islands into the plugin and once we upload them and fully restart the server we get this issue https://gyazo.com/4e371d49f4521705b3bcacdfe82c7c5d both commands typed to get this appearing is /is and the last one was /asadmin reload there is 0 errors showing on the console

We did first rename the schematics because we thought it was the fact that the plugin doesn't like Capitals on the start of the schematic file this fixed the original issue of /aasareload error in reloading message. But then when we fixed that by making the schamtic names all small letters we get this issue and no errors and cannot create island or anything anymore related to the plugin. Please help

**Comment by sonofachilles9** [comment]
17.07 07:48:53 [Server] INFO ... 15 more 17.07 07:48:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-de459a2-51263e9] 17.07 07:48:53 [Server] INFO at com.wasteofplastic.askyblock.commands.AdminCmd.onCommand(AdminCmd.java:727) ~[?:?] 17.07 07:48:53 [Server] INFO at com.wasteofplastic.askyblock.commands.IslandCmd.loadSchematics(IslandCmd.java:276) ~[?:?] 17.07 07:48:53 [Server] INFO at com.wasteofplastic.askyblock.schematics.Schematic.<init>(Schematic.java:410) ~[?:?] 17.07 07:48:53 [Server] INFO Caused by: java.lang.NullPointerException 17.07 07:48:53 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111] 17.07 07:48:53 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [Spigot.jar:git-Spigot-de459a2-51263e9] 17.07 07:48:53 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [Spigot.jar:git-Spigot-de459a2-51263e9] 17.07 07:48:53 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot.jar:git-Spigot-de459a2-51263e9] 17.07 07:48:53 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [Spigot.jar:git-Spigot-de459a2-51263e9] 17.07 07:48:53 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [Spigot.jar:git-Spigot-de459a2-51263e9] 17.07 07:48:53 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111] 17.07 07:48:53 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111] 17.07 07:48:53 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-de459a2-51263e9] 17.07 07:48:53 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot.jar:git-Spigot-de459a2-51263e9] 17.07 07:48:53 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot.jar:git-Spigot-de459a2-51263e9] 17.07 07:48:53 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193) [Spigot.jar:git-Spigot-de459a2-51263e9] 17.07 07:48:53 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358) [Spigot.jar:git-Spigot-de459a2-51263e9] 17.07 07:48:53 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[Spigot.jar:git-Spigot-de459a2-51263e9] 17.07 07:48:53 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-de459a2-51263e9] 17.07 07:48:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-de459a2-51263e9] 17.07 07:48:53 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'asadmin' in plugin ASkyBlock v3.0.6.9 17.07 07:48:53 [Server] ERROR null 17.07 07:48:53 [Server] INFO Loading schematic §bStarter (starter.schematic) for all players, order 4 17.07 07:48:53 [Server] INFO Player will spawn at the BEDROCK

**Comment by sonofachilles9** [comment]
First custom schematic loaded and worked fine. 2nd one caused that error. What could it be?

**Comment by TheSnoozer** [comment]
Looks related to this: https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/340

In ASkyBlock v3.0.6.9 it currently depends if the schematic has been created with world edit or schematica (the plugin).
Can you try to load in the schematic with world edit and save it with world edit again?
This should fix this issue with ASkyBlock v3.0.6.9

**Comment by sonofachilles9** [comment]
Starter Island (custom) was made using Schematica - starter.schematic (Works perfectly) 2nd island knight.schematic also made using Schematic (does not work) causes error on /asadmin reload.

**Comment by sonofachilles9** [comment]
We are currently making Knight islands into a worldedit schematic and see if this will fix the issue. I don't think it is that at all because if it was the knight schematic would be working as our custom starter island is made using it

**Comment by sonofachilles9** [comment]
Issue fixed. 💃

**Comment by Poslovitch** [comment]
@sonofachilles9 was it related to Schematica?

**Comment by sonofachilles9** [comment]
Yes
