### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sonofachilles9** [tastybento/ASkyBlock-Bugs-N-Features#347]
If another player has an island and i invite them to mine can they still teleport to their OWN island as well as the island they are invited too? I want to make a GUI where it shows all the islands a player is invited too to click and go to that island. I have tested with my mate and it automatically changes his home to my island and cannot get back to his own.
The max number of islands and homes is set to 10 and yet the island still gets deleted when joining the party?

**Comment by tastybento** [comment]
If a player is invited to join a team, when they accept they lose their old island - it is deleted. If you want a player to work with you on your island and he wants to keep his island, use coop. You will need to give players the askyblock.coop permission. Then in config.yml you can decide if coops should be temporary (just for that login session) or permanent.
