### ISSUE TITLE
Nether island count in level calculation

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#35]
_From @Poslovitch on January 20, 2017 14:20_

This would be a config option that will make the nether island count in the global level calculation.
Maybe with customized values? (e.g: dirt values 10 in overworld, 2 in nether).

_Copied from original issue: tastybento/askyblock#464_

**Comment by Poslovitch** [comment]
_From @tastybento on March 6, 2017 3:57_

@Poslovitch Any chance of a pull request for this? :-)

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#47
