### ISSUE TITLE
Could not save islands.yml! plugins/ASkyBlock/islands.yml (Permission denied)

### ISSUE THREAD

**Issue by Joeripoes** [tastybento/ASkyBlock-Bugs-N-Features#351]
When I restart the server it give me this error"[Server] ERROR [ASkyBlock] Could not save islands.yml! plugins/ASkyBlock/islands.yml (Permission denied)

Then when I join all island sizes are set to 100x100 (standard) and islands that are suppost to be 150x150 are also set to 100x100. This will be updated as soon as the island leader relogs. 

I used to be able to download the island.yml file from my host website but now when I click to download it doesn't work. This happened since I changed something in the islands.yml file I think.

How do I fix this error

**Comment by MaximumDesigns** [comment]
Try stopping your server first.

**Comment by Poslovitch** [comment]
"Permission denied" may mean that ASkyBlock can't write/read the file. Do some researches about that.

**Comment by Joeripoes** [comment]
I tried stopping my server, gives the same error. As soon as I joined, island size set to 100x100,
-> rejoin showed a message saying: 1: Island range updated to 250x250

**Comment by FrankHeijden** [comment]
try chmod 777 on the config.yml

**Comment by Joeripoes** [comment]
What is chmod 777

**Comment by FrankHeijden** [comment]
If you're using a FTP client, right click on the config.yml, search for something like "info or permissions" and type in after "unix permissions" 777

**Comment by Joeripoes** [comment]
with right click do you mean edit the file. In the config file I could not find anything about info or permission

**Comment by FrankHeijden** [comment]
What FTP client are you using

**Comment by Joeripoes** [comment]
I am using multicraft

**Comment by tastybento** [comment]
The server is set up incorrectly and the user running the Minecraft server does not have permission to write to that file. Complain to your server host. Sorry, there's nothing much more we can do for you.
