### ISSUE TITLE
Disabling challenges

### ISSUE THREAD

**Issue by MaximumDesigns** [tastybento/ASkyBlock-Bugs-N-Features#353]
Is there a way to totally disable challenges?

**Comment by Poslovitch** [comment]
No, not actually. It will be possible in bSkyblock.

**Comment by MaximumDesigns** [comment]
Don't you mean uSkyblock?

**Comment by MaximumDesigns** [comment]
Ah, I see..

How do I get the JAR? Do I just rename the ZIP into .jar?

**Comment by Poslovitch** [comment]
bSkyblock is not released yet. It is currently under heavy development. ETA: end of the summer.
I suggest you to join our Discord server. You will be informed more easily of the progress of this new version. https://discord.gg/ur8EPYS

**Comment by MaximumDesigns** [comment]
So,

There is no way to disable, or remove the permission from users?

**Comment by Poslovitch** [comment]
Check the permissions, I'm not sure, but I think there is one that may disable access to /c

**Comment by tastybento** [comment]
It's possible, just give players the negative askyblock.island.challenges permission. For example, with PEX:

**pex group default add -askyblock.island.challenges**
