### ISSUE TITLE
Changing from New Nether to Old Nether

### ISSUE THREAD

**Issue by dwgr8ergolfer** [tastybento/ASkyBlock-Bugs-N-Features#356]
Hello,

I tried to switch to the old nether from the new nether. When I did the nether did not generate correctly. The nether portal from an island takes the player to a nether world but there is nothing in this world except for the nether portal. 

I followed the guide and made sure I deleted the ASkyBlock_Nether world to allow it to regenerate correctly. 

Many thanks!

**Comment by tastybento** [comment]
Did you put anything in bukkit.yml regarding worlds and generators? If so, remove that.

I assume the config.yml has new nether as false? You may need to share your config.yml file.

**Comment by dwgr8ergolfer** [comment]
I did. Once I removed the world generation it worked. Many thanks! This can be closed :)

**Comment by tastybento** [comment]
Great!
