### ISSUE TITLE
Magic Cobble Generator doesn't work with auto cobble geneterator.

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#36]
_From @wasder on January 11, 2017 13:51_

![](http://i.imgur.com/iixfQZD.png)
But if I break the block by hand, it will generate "magic"
![](http://i.imgur.com/FZsQVqR.png)

_Copied from original issue: tastybento/askyblock#455_

**Comment by tastybento** [comment]
Here's code for a magic cobble gen that may be something we can use (I received the link off a player and I have not tried it or looked at it)
https://github.com/mastercake10/CustomOreGen

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#35
