### ISSUE TITLE
Nether Help.

### ISSUE THREAD

**Issue by ItsCursed** [tastybento/ASkyBlock-Bugs-N-Features#361]
I'm using the plugin ASkyblock but if I go on my island and create a nether portal it takes me to a premade nether world with 2 buildings with spawners and one bridge to cross but there's nothing else like Lava below, Glowstone above etc.

Any help?
-Carl, Developer.

**Comment by tastybento** [comment]
This is correct operation. It is the "island nether". Each player gets a nether island - it's defined by the nether schematic in the schematics folder. If you don't want the nether islands, then you need to set the newnether option in config.yml to false and delete the ASkyBlock_nether world so it can be regenerated as a standard Nether.

By the way, with the island nether, there is a ceiling, way up high with glowstone. That can be turned off if it causes too much lag too.

**Comment by ItsCursed** [comment]
Thanks for the response, will do it and inform you back.

**Comment by ItsCursed** [comment]
Ok so I tried that but the thing is that, I can't go to the nether
My ASkyblock world is not letting me go to the nether and when I do /spawn which takes me back to the "SkyBlock spawn world" it takes me the nether. ;-;

**Comment by tastybento** [comment]
/spawn is an Essentials Spawn plugin command. It sounds like you set it to take you there. 
How is "ASkyblock world is not letting me go to the nether"? In what way?

**Comment by Poslovitch** [comment]
No answer, closing.
