### ISSUE TITLE
Rain acid does not cause damage

### ISSUE THREAD

**Issue by Kiwis2451** [tastybento/ASkyBlock-Bugs-N-Features#362]
Why is my rain acid not causing damage?
I've set the raindamage in config.yml to 2 , helmetprotection and fullarmorprotection was false

**Comment by tastybento** [comment]
Possible reasons are:

- You are dead
- You are in Spectator or Creative mode
- You are Op and the _damage-Ops_ settings in config.yml is not true
- You have the **askyblock.mod.noburn** permission, or the **askyblock.mod.*** permission
- You have the **askyblock.admin.noburn** permission, or the **askyblock.admin.*** permission
- You have an active _Water Breathing_ potion
- You are in a dry biome, so there isn't actually any rain here
- You are underneath something

**Comment by Kiwis2451** [comment]
solve
