### ISSUE TITLE
IS Levels - Stacked Spawners + Spawner Types

### ISSUE THREAD

**Issue by op-Hen** [tastybento/ASkyBlock-Bugs-N-Features#364]
Would it be possible to add support for spawner stacking plugins in is-level as well as different types of spawners?

So for example, an iron golem could have an is contribution of 50 points whilst a cow spawner 5 points.

Could you also hook into the main spawning stacking plugins so that if islands have stacked spawners these are taken into account?

Thank you.

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/bskyblock#91
