### ISSUE TITLE
Friendly mobs not spawning?

### ISSUE THREAD

**Issue by Redstonetorch** [tastybento/ASkyBlock-Bugs-N-Features#365]
cant get a single friendly mob to spawn, what could be the cause of this? didnt see anything in the configs and there's nothing in the rg flags or anything like that... please helpppppp cant progress until i can get them to spawn ):

**Comment by Poslovitch** [comment]
First of all, you should not use WorldGuard with ASkyBlock. ASB has its own protection built-in.

You should also read the FAQ.

**Comment by tastybento** [comment]
https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#after-updating-mobs-and-animals-dont-spawn
:-)
