### ISSUE TITLE
Locale colors

### ISSUE THREAD

**Issue by tastybento** [tastybento/ASkyBlock-Bugs-N-Features#366]
https://www.spigotmc.org/threads/askyblock.30325/page-213#post-2557461

Im changing or trying to change all msgs in color but some seem unable to be done.

When checking how many challenges till a new set unlocks msgs like: Complete 7 more Novice challenges to unlock this level! how can i color the Novice? If able

This i tried: toComplete: "&3Complete&9 [challengesToDo] &3more&9 [thisLevel] &3challenges to &3unlock this level!"

It colors all but the [thislevel]

And in the helpfile aswell under Select Language remains white:
helpSelectLanguage: "&3Select Language"

**Comment by Scorpionvssub** [comment]
Another note: In the gui on the books you have Novice, competent elite and such, those names are yellow is there a way to color those too?
