### ISSUE TITLE
Island warps // Internal error (i have no single clue)

### ISSUE THREAD

**Issue by GreenSheepYTT** [tastybento/ASkyBlock-Bugs-N-Features#367]
Hi i'm a manager of a network 'RandomCraft' server SkyBlock, and i came to this weird sittuation

I'll try to explain quick

Basically i deleted/restarted islands and deleted all possible files except the world, the old islands got deleted by command /asadmin purge unowned. Now when people create their new islands they can't use the /is warp (can't teleport to others) And the problem is the OLD warps got saved but i have no idea how to delete them.

Yes i did delete warps.yml but it just generated a new one with the old registrated warps.

Is there any way to fix this?

![image](https://user-images.githubusercontent.com/30407880/28521162-0e8c2a66-707b-11e7-864b-02abb360c973.png)

^^^ Need to get rid of that somehow (not the menu but the players, but the fact nobody has islands :?)

Spigot 1.8.3 / Askyblock version 3.0.6.8

**Comment by Poslovitch** [comment]
Delete the file, without doing any /reload or /asadmin reload. So, delete it when server is off.

**Comment by GreenSheepYTT** [comment]
Gold mate, thanks.
