### ISSUE TITLE
Imported ASkyBlock but creation of island does now work?

### ISSUE THREAD

**Issue by ItsComits** [tastybento/ASkyBlock-Bugs-N-Features#368]
Hello, I am using the program ECLIPSE IDE and have come across a problem when I imported the repository. First I right-clicked on the project > Import > File System. I then choose the askyblock-master folder which I extracted from the .zip. For the options section. I unticked them both. I then clicked the finish button. For the build paths. I choose to put in all of the spigot versions from spigot apart from 1.6.4 and lower. Finally, I put in vault. After I added the build path there were no errors and I proceeded to export the file to my local server. This is where the issue occurs. When the player does /is. The island creation message is shown. (Creating an island for you..). There is also a menu that pops up. 

There are no errors in the console. The menu should open and the player should select an island type. I don't know why this happens. I think this bug/error is happening because of a number of versions I used. Any help is appreciated.

**Comment by tastybento** [comment]
When you export the jar, I suspect the schematics folder (and the locale) folder are missing from the jar. If you use Maven, these will be included. I can't remember how to include them if you do Export from Eclipse, but I think you may need to specifically checkbox them.

Upload the jar file you created to this ticket so we can look at it.

**Comment by ItsComits** [comment]
Hello, Thanks for the reply. Here is the jar.

**Comment by tastybento** [comment]
It works great! Are you sure the plugin is loading? Do you have Vault installed? Also, I recommend you manually change the version number in plugin.yml to whatever the correct version is.

**Comment by ItsComits** [comment]
Hello. I have got vault installed and the plugin is working correctly. I think this has to do with the version in plugin.yml. How do I find what version of askyblock this is? I got the source of here: https://github.com/tastybento/askyblock

**Comment by ItsComits** [comment]
I have fixed this issue. For some reason, I had to put a version number in the plugin.yml. Is this suppose to happen? Also thanks for your help. Your a legend <3 :D

**Comment by ItsComits** [comment]
So I have got it to work, But I am wanting to change the island command. I changed all of the island commands in the plugin.yml and in the ASkyblock main class. But soon I do /<command>. The schematic menu pops up. I click one and I get 'Creating an island for you..' After that, I get 'Unknown Command. Type '/help' for help.

**Comment by tastybento** [comment]
Look in Settings.java - there are some command settings there too.
For the schematic menu - you'll need to mark the skull as having an owner. Look at the TopTen panel for an example.

**Comment by ItsComits** [comment]
Thanks for the reply. The command is now working. yippee. But I do not know how to approach adding custom skulls to the schematic panel.

**Comment by tastybento** [comment]
You would need to change the code for the SchematicsPanel. Look in the TopTen for how to make skulls show a particular head. I'll close this for now.
