### ISSUE TITLE
Use Spawneggs & Disable Animal Spawn?

### ISSUE THREAD

**Issue by AconTM** [tastybento/ASkyBlock-Bugs-N-Features#369]
I have this problem:

I have disabled the option "MOB_SPAWN" because, on my Island spawn cows usw ^^ But i want 
it that users can use Spawneggs to make Animals on their Islands. Is there any way to make this
possible? 

Sorry for my bad English :/ 

I Want:  Mobs cant spawn naturally but Spawneggs work

**Comment by AconTM** [comment]
`   world:
     ACID_DAMAGE: true
     ANVIL: false
     ARMOR_STAND: false
     BEACON: false
     BED: false
     BREAK_BLOCKS: false
     BREEDING: false
     BREWING: true
     BUCKET: false
     COLLECT_LAVA: false
     COLLECT_WATER: false
     CHEST: false
     CHORUS_FRUIT: false
     CRAFTING: true
     CREEPER_PAIN: true
     CROP_TRAMPLE: false
     DOOR: false
     EGGS: false
     ENCHANTING: true
     ENDER_PEARL: false
     ENTER_EXIT_MESSAGES: true
     FIRE: false
     FIRE_EXTINGUISH: false
     FIRE_SPREAD: false
     FURNACE: false
     GATE: false
     HORSE_INVENTORY: false
     HORSE_RIDING: false
     HURT_MOBS: false
     HURT_MONSTERS: true
     LEASH: false
     LEVER_BUTTON: false
     MILKING: false
     MOB_SPAWN: false
     MONSTER_SPAWN: false
     MUSIC: false
     NETHER_PVP: false
     PLACE_BLOCKS: false
     PORTAL: false
     PRESSURE_PLATE: false
     PVP: false
     REDSTONE: false
     SPAWN_EGGS: true
     SHEARING: false
     VILLAGER_TRADING: true
     VISITOR_ITEM_DROP: true
     VISITOR_ITEM_PICKUP: true`

**Comment by tastybento** [comment]
I understand. This should be fixed in the next version.
