### ISSUE TITLE
Allow mini shop to be used in other worlds

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#37]
_From @tastybento on January 7, 2017 3:45_

Requested by LukaRuso https://www.spigotmc.org/members/lukaruso.37655/

_Copied from original issue: tastybento/askyblock#450_

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#37

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#42
