### ISSUE TITLE
Protection

### ISSUE THREAD

**Issue by sonofachilles9** [tastybento/ASkyBlock-Bugs-N-Features#371]
Not sure if I have asked this before or not so I'll ask anyway to be sure.

Basically I want to have a section of the island people spawn at which is completely protected from building,breaking etc and then they walk over a bridge (still protected) and bridge leads to their island. So they basically spawn walk across bridge and arrive at their island to then do the work. 

Ik this is a possibility as I've been on other skyblock servers using ASkyBlock an they have a protected area which is automatically loaded upon creation of the island. (Believe from the schematic itself) 

Just wondering if you know how this is done we have tried to make a world guard region around a section of the island schematic but it doesn't load upon creation of the island. Can you possibly help us and explain how this is done if possible? Or if it's not possible know of a way we can implement this? Maybe by using another plugin of some sort? Not replacing ASkyBlock but working along side of it.

Thanks

**Comment by sonofachilles9** [comment]
P.S mobs are not burning in daylight on the standard ASkyBlock world. Not sure how to fix this as it's using Default mobs and there is no default setting to make mobs burn in daylight. I thought it may be because we did change to a Void world as flstworld was generating below the island but we have double checked and reset a lot since then an we are in fact using ASkyBlock default world

**Comment by tastybento** [comment]
For the first question - you could to do this by using a schematic that pastes both inside and outside the protected area. Say that the protected area is 100 blocks and the island distance is say 400. The island center is where the bedrock block is. So you could create a schematic where the protected part is at least 50 blocks away from the bedrock. Then place a spawn block where you want the player to start (e.g., SPONGE) and use the spawn block option in the config for that schematic. If you don't want to have an island go all the way to the bedrock block, just leave it floating in space, or disguise it with an island of sand or something. Good luck!

**Comment by tastybento** [comment]
For the second point, no idea, sorry. There's nothing at all in the code to stop mobs from burning in daylight and I've never hear of this issue ever before so I suspect it's either the server code or some other plugin having an affect. The quick way to check is to temporarily remove plugins and restart and see if mobs burn. If you see this issue on a clean server install with just ASKyBlock and Vault it'll be my issue. :-)

**Comment by sonofachilles9** [comment]
We use a visual border plugin how can that idea be done using that? Because the visual borders would kill the player.  Thanks for your help on this really appreciate it. Feel free to join our server and see for yourself how we have it and see if it can be done :)

On 26 Jul 2017, at 03:07, tastybento <notifications@github.com<mailto:notifications@github.com>> wrote:


For the second point, no idea, sorry. There's nothing at all in the code to stop mobs from burning in daylight and I've never hear of this issue ever before so I suspect it's either the server code or some other plugin having an affect. The quick way to check is to temporarily remove plugins and restart and see if mobs burn. If you see this issue on a clean server install with just ASKyBlock and Vault it'll be my issue. :-)

**Comment by sonofachilles9** [comment]
Btw would of been nice to of been informed that the new ASkyBlock generates a new config file.. EVERYTHING on our already released server now messed up and have to shut server down and re config a lot of shit

Sent from my iPhone

On 26 Jul 2017, at 03:07, tastybento <notifications@github.com<mailto:notifications@github.com>> wrote:


For the second point, no idea, sorry. There's nothing at all in the code to stop mobs from burning in daylight and I've never hear of this issue ever before so I suspect it's either the server code or some other plugin having an affect. The quick way to check is to temporarily remove plugins and restart and see if mobs burn. If you see this issue on a clean server install with just ASKyBlock and Vault it'll be my issue. :-)

**Comment by Poslovitch** [comment]
ASkyBlock generates a config.new.yml file when changes have been made in the config, and in case it doesn't find a setting in the config, it uses a default value that is defined to avoid most of the problems that can occur when upgrading.

And, when updating, you should take backups and do tests and update config using a test server.
We try to do our best to avoid problems due to an incorrect configuration or updating, but we can't handle user-side problems.

Now, for your first point : ASkyBlock handles protection. No need of WorldGuard, CoreProtect...
Check the config and the comments in it. They're written to help you. Check the protection section in config.

For visual worldborder, this is basically doable by sending to the client via NMS a fake worldborder that meet this protection range of the island you can get using our API.

**Comment by sonofachilles9** [comment]
1) We are using a seperate plugin to produce the borders

2) Please explain then how I use the "protection" in the config to produce and area on each island that's being created that cannot be interacted with or placed or break blocks. I don't think you fully understand what we are asking about and the border plugin we have. Which is why I also suggested to come on the server and see for yourself. Ik what I'm asking IS possible with ASKYBLOCK because I've been on multiple servers with ASkyBlock that does the feature I'm asking about

**Comment by tastybento** [comment]
@sonofachilles9  What's your server address? What border plugin do you use? I already explained how you could do it using a schematic, other than that, sorry. We're developers, not admins.

**Comment by sonofachilles9** [comment]
Play.medievalskies.games and I know you explained it but that other dude came in and was talking about something else something else that he didn't really understand what I was asking where as you did. And I didn't fully understand how you was explaining it to be done. I explained it to my server partner and he said it couldn't be done because of our visual borders. Which is why I re replied. We are using

http://www.mc-market.org/resources/3993/

 I just wanted a protected spawn region on these islands that can be placed in the Center of our world borders and work lol. I do appreciate your help bento

On 28 Jul 2017, at 04:01, tastybento <notifications@github.com<mailto:notifications@github.com>> wrote:


@sonofachilles9<https://github.com/sonofachilles9> What's your server address? What border plugin do you use? I already explained how you could do it using a schematic, other than that, sorry. We're developers, not admins.

**Comment by tastybento** [comment]
Hmm, I can only think that they are running some commands after island creation to create a WorldGuard region somehow, or they have edited the source code (the source code is freely available and developers do fork it). I can't think of a stock built-in way to do it if the protected region must be inside the world border. If you didn't have the world border, or the world border wasn't lethal, just visual, then it could be done how I say easily. This image can explain a bit more:

https://i.gyazo.com/6b3b2dad826e992262dda2fc4884d8dd.png

By the way, thanks for sharing that link to that site and plugin. I didn't know there was such a plugin. It's nice to see the ecosystem profiting. $8.99 and over 100 sold.

**Comment by sonofachilles9** [comment]
It is a border that kills. Also with that method they would not be able to get back to spawn. Is there no way being able to have the island in the Center and have a protected region around our spawn we build them and they can't place items? Or break blocks etc. Because I know it can be done but that method just won't suit at all. You mentioned about 2 schematics pasting ontop of each other one being the world guard region how would we do it this way?

Sent from my iPhone

On 28 Jul 2017, at 16:45, tastybento <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm, I can only think that they are running some commands after island creation to create a WorldGuard region somehow, or they have edited the source code (the source code is freely available and developers do fork it). I can't think of a stock built-in way to do it if the protected region must be inside the world border. If you didn't have the world border, or the world border wasn't lethal, just visual, then it could be done how I say easily. This image can explain a bit more:

https://i.gyazo.com/6b3b2dad826e992262dda2fc4884d8dd.png

By the way, thanks for sharing that link to that site and plugin. I didn't know there was such a plugin. It's nice to see the ecosystem profiting. $8.99 and over 100 sold.

**Comment by tastybento** [comment]
There's no stock way to do it, sorry. Maybe those servers changed the code to enable it.

**Comment by sonofachilles9** [comment]
Yea but you had already explained that method...? So I was just wanting to know a more indeph meaning of that?

Sent from my iPhone

On 29 Jul 2017, at 02:12, tastybento <notifications@github.com<mailto:notifications@github.com>> wrote:


There's no stock way to do it, sorry. Maybe those servers changed the code to enable it.

**Comment by tastybento** [comment]
Here's how I would do it: I'd make another plugin that taps into the [ASkyBlock API](http://tastybento.github.io/askyblock/). It would listen for [new islands to be created](http://tastybento.github.io/askyblock/com/wasteofplastic/askyblock/events/IslandNewEvent.html) or [reset](http://tastybento.github.io/askyblock/com/wasteofplastic/askyblock/events/IslandResetEvent.html) and then grab the [location of the island](http://tastybento.github.io/askyblock/com/wasteofplastic/askyblock/events/IslandNewEvent.html#getIslandLocation()).

Once I have that info, I'd use the WorldGuard API to create a region and protect it. If the region was always going to be in the same place every time, I would not need to delete it, but it would also be best to listen to the IslandDeleteEvent to remove the region too.

I don't know much about the WorldGuard API, but you can work it out.

Good luck!

**Comment by sonofachilles9** [comment]
Ok well thanks anyway. Btw apparently I hear you are bringing visual borders to ASkyBlock? The Dev of the border plugin I linked to you has taken his plugin down and is not fixing an issue for us when the border plugin breaks on 1.12 even though he specified it to work on 1.12. He said "Because you updated your server to 1.12 I will not be offering any support or fixes for you" Now he's taken his plugin down and told me your updating ASkyBlock. A chargeback will be issued against him as I'm not having paid for a plugin that he takes down like a week later and says he offers no support or fixes for us. Pathetic service from a Dev.

On 29 Jul 2017, at 17:56, tastybento <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's how I would do it: I'd make another plugin that taps into the ASkyBlock API<http://tastybento.github.io/askyblock/>. It would listen for new islands to be created<http://tastybento.github.io/askyblock/com/wasteofplastic/askyblock/events/IslandNewEvent.html> or reset<http://tastybento.github.io/askyblock/com/wasteofplastic/askyblock/events/IslandResetEvent.html> and then grab the location of the island<http://tastybento.github.io/askyblock/com/wasteofplastic/askyblock/events/IslandNewEvent.html#getIslandLocation()>.

Once I have that info, I'd use the WorldGuard API to create a region and protect it. If the region was always going to be in the same place every time, I would not need to delete it, but it would also be best to listen to the IslandDeleteEvent to remove the region too.

I don't know much about the WorldGuard API, but you can work it out.

Good luck!

**Comment by tastybento** [comment]
Huh!

Anyway, ASkyBlock is not adding any new features anymore, so that's not the case. We're doing a rewrite called BSkyBlock that is based around a core plugin and add-ons. 

I'm going to close this ticket for now as we've pretty much talked everything out. Good luck with your server.
