### ISSUE TITLE
Animals cant Breeding?

### ISSUE THREAD

**Issue by AconTM** [tastybento/ASkyBlock-Bugs-N-Features#375]
Hi again :D Now the other Problem is fixed, but now i cant Breeding (?) my Animals :/
Settings are correct but it does not work.

Pls help me ;D

**Comment by Poslovitch** [comment]
Can you please send us your config.yml?

**Comment by AconTM** [comment]
did you mean this?

   world:
     # Acid causes damage above sea-level (if acid is active)
     ACID_DAMAGE: true
     # Allow anvil use
     ANVIL: false
     # Allow armor stand use (1.8+ only)
     ARMOR_STAND: false
     # Allow beacon use
     BEACON: false
     # Allow bed use
     BED: false
     # Players can break blocks or generally damage things
     BREAK_BLOCKS: false
     # Allow animal breeding
     BREEDING: true
     # Allow use of cauldrons and brewing stands
     BREWING: true
     # Allow use of buckets, either fill or dump them
     BUCKET: false
     # Collect Lava (overrides BUCKET setting for collecting lava)
     COLLECT_LAVA: false
     # Collect water (overrides BUCKET setting for collecting water)
     COLLECT_WATER: false
     # Allow access chests of any kind, droppers, dispensers and hoppers
     CHEST: false
     # Allow eating or use of chorus fruit
     CHORUS_FRUIT: false
     # Allow use of crafting benches
     CRAFTING: true
     # Allow creepers to hurt players (but not damage blocks)
     CREEPER_PAIN: true
     # Allow crop trampling
     CROP_TRAMPLE: false
     # Allow use of doors or trapdoors. Not including redstone activations.
     DOOR: false
     # Allow chicken egg throwing
     EGGS: false
     # Allow use of enchanting tables
     ENCHANTING: true
     # Allow enderpearl throwing
     ENDER_PEARL: false
     # Enable or disable join/leave messages from the player's island
     ENTER_EXIT_MESSAGES: true
     # Allow fire (flint & steel use, TNT priming) Making portals is allowed.
     FIRE: false
     # Can extinguish fires by punching them
     FIRE_EXTINGUISH: false
     # Allow fire spreading
     FIRE_SPREAD: false
     # Allow furnace use
     FURNACE: false
     # Allow gate use
     GATE: false
     # Allow horse/llama inventory use - only works when riding is enabled     
     HORSE_INVENTORY: false
     # Allow riding of horses/llamas
     HORSE_RIDING: false
     # Allow friendly mob hurting(cows etc.)
     HURT_MOBS: false
     # Allow monsters hurting
     HURT_MONSTERS: true
     # Allow leash use
     LEASH: false
     # Allow lever or button use
     LEVER_BUTTON: false
     # Cows can be milked
     MILKING: false
     # Animals, etc. can spawn naturally
     MOB_SPAWN: false
     # Allow monsters to spawn naturally
     MONSTER_SPAWN: false
     # Allow use of jukeboxes and note blocks
     MUSIC: false
     # Allow PVP in the nether world
     NETHER_PVP: false
     # Players can place blocks
     PLACE_BLOCKS: false
     # Allow portal use
     PORTAL: false
     # Allow pressure plate activation by players
     PRESSURE_PLATE: false
     # Allow PVP in the overworld
     PVP: false
     # Allow adjustment of diodes or comparators
     REDSTONE: false
     # Spawn eggs can be used
     SPAWN_EGGS: true
     # Allow sheep shearing
     SHEARING: false
     # Allow trading with villagers
     VILLAGER_TRADING: true
     # Allow item drop
     VISITOR_ITEM_DROP: true
     # Allow item pickup
     VISITOR_ITEM_PICKUP: true

**Comment by Poslovitch** [comment]
Yup.

Try to do /asadmin settingsreset all.

**Comment by AconTM** [comment]
still not work

**Comment by Poslovitch** [comment]
Is there errors in console?

There may be another plugin interfering with that. Try removing your plugins one by one 'til you can breed again your animals.

**Comment by AconTM** [comment]
No i dont have Errors & bevor i updating to the newest version it works :/

**Comment by Poslovitch** [comment]
You updated from which version? 3.0.6+?

**Comment by AconTM** [comment]
i updated from the version V3.0.6.9

**Comment by Poslovitch** [comment]
Did you try to remove plugins one by one 'til you can breed again your animals like I said earlier?

**Comment by AconTM** [comment]
i have try to downgrade aSkyblock to V3.0.6.9 and there breed works ^^ so i think it

i have the point btw, breeding does not working if "MOB_SPAWN" is disabled

**Comment by Poslovitch** [comment]
Okay, let us investigate if this should be a normal behaviour or not.

**Comment by tastybento** [comment]
Yeah, the mob_spawn and animal_spawn flags should only affect natural spawning really.
