### ISSUE TITLE
Bug in pvp: fishing rod

### ISSUE THREAD

**Issue by Zoiter7** [tastybento/ASkyBlock-Bugs-N-Features#377]
There is a small bug, also if you have in your islands settings the value of pvp in off, you can hit a player with fishing road .

**Comment by tastybento** [comment]
@Poslovitch Did we fix this in the 4.0 code?

**Comment by Poslovitch** [comment]
No idea, I didn't fully check the protection code :/
I'm really not.sure we did.

**Comment by tastybento** [comment]
@Zoiter7 How can you hit the player? I can hook the player but it doesn't hurt...

**Comment by Poslovitch** [comment]
@tastybento
Hook damage has been removed in 1.9. Try in 1.8.8

**Comment by Zoiter7** [comment]
@tastybento

With the right click,  the string of the road hit the player and push it.

**Comment by tastybento** [comment]
Yes, you can pull the player a bit with the rod. Hmm, I'm not sure whether this is worth fixing...

**Comment by Zoiter7** [comment]
I think yes, because one player is in island border and comes other player and push it with the road while the pvp is disable..

**Comment by Poslovitch** [comment]
I think we should too, if this doesn't need 10k lines of code.
If we don't, we may receive other issues related to that.

**Comment by Zoiter7** [comment]
Hello, I tested in the latest version and the problem continues.

**Comment by tastybento** [comment]
@Zoiter7 What version of the server do you have?

**Comment by Zoiter7** [comment]
Spigot 1.1.2

**Comment by tastybento** [comment]
@Zoiter7 Do you mean 1.11.2?
Also, what do you see that doesn't work? It should not be possible to pull players with the rod. You can hook them, but if you try to pull them, it doesn't do anything. Same with animals.

**Comment by Zoiter7** [comment]
Sorry, spigot 1.12*

I test it with a player, I pull to the other player and the player recedes

**Comment by tastybento** [comment]
You're probably Op? Or have the askyblock.mod.bypass permission? I just tested it, it works. If the island allows PVP then there is no protection as well.

**Comment by Zoiter7** [comment]
I'm not OP and I don't have this permission. 

Here a video https://youtu.be/XG5sy1nABL0
In the chat when I pull show "Pvp is disabled on this island", I hide the chat for the video

**Comment by tastybento** [comment]
How do you hit people like that with the rod? When I hook a player it reels them in, not out. How come your rod is giving knock back?

**Comment by tastybento** [comment]
@Zoiter7 How do you hit people so they are knocked back (not reeled in)? If you can tell me this I can try and stop it.

**Comment by Zoiter7** [comment]
Sorry I forgot answer.  I hit player and it hooks but also player goes back.

**Comment by tastybento** [comment]
You sure you're using server 1.12? I thought fishing rod kickback was removed in 1.9. Do you have another plugin that adds knock back to rods? Either way, I'm not sure there's much I can do here.

**Comment by Zoiter7** [comment]
Aah yes I have a plugin,  it reverts the pvp to 1.8 and I'm using ProtocolSupport.

**Comment by tastybento** [comment]
Let me see if it's possible to cancel the knockback. It may not be depending on when that other plugin kicks in.

**Comment by tastybento** [comment]
It doesn't look like I can fix easily because it's the other plugin setting the velocity. I'm going to close this for now.

**Comment by Zoiter7** [comment]
Finally I fixed this problem, thank you anyway.
