### ISSUE TITLE
/is player execute

### ISSUE THREAD

**Issue by daddy69420** [tastybento/ASkyBlock-Bugs-N-Features#379]
If I have a command setup to target a player and make the player execute (/is) it will not do it.
It just comes up with a message saying "creating island..." but it doesn't actually do it.

Such as in ChestCommands and AdvancedPortals. I want the player to be able to click an item in chestcommands that opens the island GUI and I want the same for advanced portals.

**Comment by tastybento** [comment]
This isn't the right forum to ask about how to use ChestCommands or AdvancedPortals - sorry. If you think there's a bug with ASKyBlock, please explain more.

> If I have a command setup

Where do you have this command set up? Please provide an example. What plugin is executing this command? What does it look like?

If this is another plugin, I recommend you ask on that plugin's forum.

**Comment by daddy69420** [comment]
I think it's ASkyBlock.

And I mean in a command as in a command block and stuff like that too.  I have the command setup on a block so that when a player clicks the block it is just "/is" so when the player clicks it it makes it initiate on the player. But ASkyBlock won't open the GUI.

**Comment by tastybento** [comment]
Hmm, I wonder if you need to use /island, which is the official command and not an alias. It may also be that the command is not being run as the player themselves and is just being run in the console.

**Comment by daddy69420** [comment]
Doesn't work for /island either.

Which is why I was wondering what can I do to run it FOR them?

**Comment by tastybento** [comment]
You will need Essentials because it has a command that enables you to use command blocks to run commands for someone. Place your command block and this will be the command:

**/sudo @p island**

Command blocks only allow you to run console commands, so that's why you need to use the Essentials sudo command.

Source: https://bukkit.org/threads/can-the-command-block-work-with-bukkit-commands.121685/

**Comment by daddy69420** [comment]
Still doesn't work, it says it's creating the island but doesn't. And I want it to bring up the GUI not just make an island.
