### ISSUE TITLE
Tipped arrows

### ISSUE THREAD

**Issue by B4nG3R1** [tastybento/ASkyBlock-Bugs-N-Features#380]
Would be a coul feature if you could check for tipped arrows in the challanges like it is with all the potions
POTION:NAME:<LEVEL>:<EXTENDED>:<SPLASH/LINGER>:QTY
Example:
TIPPED_ARROW:NAME:<LEVEL>:<EXTENDED>:<SPLASH/LINGER>:QTY

Kind regards,

Johannes

**Comment by Poslovitch** [comment]
Feature request, and already handled in https://github.com/tastybento/bskyblock/issues/12
