### ISSUE TITLE
ASkyBlock API request

### ISSUE THREAD

**Issue by timderspieler** [tastybento/ASkyBlock-Bugs-N-Features#381]
Hey, here are some ideas that would be very helpful for developers:

List<String> islandowners = getAllSkyBlockPlayers()
(returns all island owners, coop players, team mates)
(Very helpful to create temporary whitelist for all players with an island)

List<[String, Itemstack, Enum? I dont know what you use for challenges]> challenges = getAllSkyBlockChallenges()
(returns all challenges)
(Very helpful to make a special challenge plugin (or another challenge gui)

(void) setmaxAnimals(String uuid, int amount)
(manually set the max amount of animals on an island)
(Very helpful for shop systems, so players can buy the max amount of animals on an island)

(void) setmaxCreatures(String uuid, int amount)
(manully set the max amount of creatures on an island)
(same as setmaxAnimals)

and a question: Is it planned to add end islands?

thanks
~tim

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/bskyblock#94
