### ISSUE TITLE
Cooped players does not get removed on logout

### ISSUE THREAD

**Issue by Johandrex** [tastybento/ASkyBlock-Bugs-N-Features#382]
When players are added to the coop list they are not removed after logging out. This appears to happen in both V3.0.6.11 and V3.0.6.10.

**Comment by tastybento** [comment]
Ah, the text is wrong - it should say "until you logout". This has been a long-standing bug.

Inviter logs out - coop ends
Invitee logs out - coop stays

Quick fix - change the text.
