### ISSUE TITLE
i kEEP DIEING??

### ISSUE THREAD

**Issue by ZayBlockBugLine** [tastybento/ASkyBlock-Bugs-N-Features#384]
hey so there is a problem whenever i rejoin my server or fall in the void i keep falling in the void all the players are rly anoied with this plz help!!!

**Comment by tastybento** [comment]
Good question - I added this to the FAQ.

Set your server's respawn point or world's spawn point. You can do that with plugins like Essentials Spawn, or Multiverse. Also, you can set ASkyBlock to respawn players on their own island in config.yml.

**Comment by ZayBlockBugLine** [comment]
ok
