### ISSUE TITLE
/is teleports to island while usecontrolpanel is true

### ISSUE THREAD

**Issue by Bobobaal** [tastybento/ASkyBlock-Bugs-N-Features#386]
Hello

/is still teleports me to my island instead of showing me the control panel while usecontrolpanel in the config is true

Sincerely

Bobobaal

**Comment by Bobobaal** [comment]
Version is 3.0.6.11

**Comment by Poslovitch** [comment]
The setting in config only applies to new players.
You'll need to manually do : **/is cp on**

**Comment by Bobobaal** [comment]
But I edited the config before I even created an island? But it seems to be working new after I deleted every player related file from askyblock

**Comment by Poslovitch** [comment]
But your player file was already generated ^^.

Anyway, there will be an automatic update in bSkyblock that will prevent this kind of "bugs".
