### ISSUE TITLE
PvP issue

### ISSUE THREAD

**Issue by Zoiter7** [tastybento/ASkyBlock-Bugs-N-Features#391]
Hello, I found a other issue.

The island has pvp disabled, later the owner actives the pvp and anyone can hit to owner but the owner can't do it. If owner give you a coop, owner can hit you.

**Comment by tastybento** [comment]
I can't replicate this. When the owner cannot hit other players, what error does the owner see?

**Comment by Zoiter7** [comment]
Sorry, I wrote it bad. 

The island has pvp disabled, later the owner of the island actives the pvp and everybody can hit to owner of the island, but the owner of island can't hit to anyone. If owner gives you a coop, owner can hit you.

**Comment by Poslovitch** [comment]
Does it tell the owner "Target is in a no-PVP area" ?

**Comment by Zoiter7** [comment]
If the island have pvp activated the visitors can hit the owner of the island,  but owner  of the island can't hit the visitors at least the owner of island give coop to the visitor, so can hit it without problems.

**Comment by Poslovitch** [comment]
I'm asking my question back : 

Does it tell to the owner when trying to hit a visitor : "Target is in a no-PVP area" ?

**Comment by Zoiter7** [comment]
Sorry, before I didn't understand the question.

No, not appears any message.

**Comment by tastybento** [comment]
Then the protection is coming from elsewhere. It might be the server, or another plugin. Other plugins sometimes give protection against PVP.

**Comment by Zoiter7** [comment]
Well, I solved this, there are a problem in the config in "invinciblevisitors"

Sorry,

Regards,
