### ISSUE TITLE
Custom Skyblock Island Schematic Spawning at Max Limit!

### ISSUE THREAD

**Issue by triggmysta** [tastybento/ASkyBlock-Bugs-N-Features#395]
Hello Support Members and ASkyBlock Author.

I have made my own personal Skyblock island Schematic at it is tall. Once I added it and tested it with /is and created the Skyblock schematic I created it was chopped in half, I am wondering if it is at all possible to edit where the Island is positioned? So the height so then I can fit this Island into the world so then it works? Please help me if this is already a feature but also notify me if Its not and its a bug or up coming feature.

Thank! Regards Triggmysta

**Comment by Poslovitch** [comment]
Hi :)

Make sure you have a bedrock block in your schematic : this will be the center of the island, and so it defines the y-position.

The y-position is set in the config by `islandlevel`
