### ISSUE TITLE
can not go back to novice challenge

### ISSUE THREAD

**Issue by Future-Force** [tastybento/ASkyBlock-Bugs-N-Features#400]
i completed the first challenges and get new ones .
but i can not go back to the novice challenges do do some of them again

**Comment by tastybento** [comment]
There's a book and quill you can select that shows them.

**Comment by Future-Force** [comment]
i know the book is there but if i click it it dosn't do anything. wont show the Novice Challenges

**Comment by tastybento** [comment]
Did you customize challenges.yml? If so, please share your challenges.yml file - drag and drop it here (you may need to zip it).

**Comment by angiechin** [comment]
I can confirmed this as I have the same issues.  I did not changed anything or customise challenges.yml.

**Comment by tastybento** [comment]
I can't replicate this right now. I can only imaging another plugin interfering. Does this happen with just ASkyBlock (and Vault) installed?

**Comment by tastybento** [comment]
No answer...

**Comment by JessKalamity** [comment]
Hi there, I hope you can help I'm actually also having the same problem on my friends server we play on. We do have multiple plugins and he has not changed anything in the challenges.yml any help you can offer would be appreciated

**Comment by tastybento** [comment]
I'd need your challenges.yml, your server type and version, your ASkyBlock plugin version to investigate. I may need a copy of the ASkyBlock plugin folder (zipped up). You can share it via DropBox or elsewhere.

**Comment by JessKalamity** [comment]
Thank you so much for getting back to me so quickly, here is the challenges.yml file
[challenges.zip](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1976809/challenges.zip) our server type and version 
![server](https://user-images.githubusercontent.com/38965996/39664928-8478863e-5059-11e8-941e-4f7bbeddbd5c.png) and our ASkyBlock version is 3.0.8.6 if you need any further information at all please just let me know. Thank you so very much

**Comment by tastybento** [comment]
I think the challenge file is the same as the standard one. In that case, I actually need your player file so I can try to replicate this. It's in the players folder under your UUID.

**Comment by JessKalamity** [comment]
not a problem, here is my player file. I'm not certain if this helps but it's everyone who is on the server that has this issue. 
[79573fec-66e6-4f59-ba4a-ebaa5286fe2c.zip](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1981780/79573fec-66e6-4f59-ba4a-ebaa5286fe2c.zip)

**Comment by VoidLock92** [comment]
Any info on a fix for this?

**Comment by tastybento** [comment]
I tried the player file and challenges file on 3.0.8.6 with server 1.11.2 and found no problem. :-(

I can only think it is another plugin interfering. What plugins do you have running? Maybe if we compare @JessKalamity and @VoidLock92 plugin list we can spot something. You can also try removing plugins until you see the book and quill work.
