### ISSUE TITLE
Mobs not spawning

### ISSUE THREAD

**Issue by Ancienty** [tastybento/ASkyBlock-Bugs-N-Features#401]
Hi,

When I upgraded the plugin to the newest version, it came with a problem.
Mobs don't spawn.
I tried /asadmin settingsreset all
I downloaded the debug version

and these didn't work,
When I try to summon an animal or a monster it says

[ASkyBlock] Animal spawn event! CreatureSpawnEvent
[ASkyBlock] SPAWNER_EGG
[ASkyBlock] PIG
[ASkyBlock] No limit on breeding or spawning
[ASkyBlock] Villager spawn event! CreatureSpawnEvent
[ASkyBlock] SPAWNER_EGG
[ASkyBlock] PIG
[ASkyBlock] on Mob spawnCreatureSpawnEvent
[ASkyBlock] Natural animal spawn cancelled.

in the console
Help me please.

**Comment by tastybento** [comment]
Share your config.yml (drag and drop it to this ticket - you may need to zip it). It's most likely you don't have it up to date.

**Comment by Ancienty** [comment]
I updated it from an old version, I didn't delete anything I just changed the askyblock.jar file.
Here is my config (my askyblock.jar is not up-to-date right now because of this problem):

**Comment by tastybento** [comment]
Yes, that's an old config.yml. This is your problem.

Delete config.new.yml if it exists and restart with the new plugin. A new config.new.yml will be created for your reference. Then port all your various settings from config.yml to config.new.yml. Then rename config.new.yml to config.yml. Take backups beforehand so if you make a mistake you can go back. Also, you should delete the locale folder so all the language files can be regenerated.

**Comment by Ancienty** [comment]
Okay, thanks for your help. I'm gonna try it.
