### ISSUE TITLE
Thaumcraft Golem Animation Core:Use not work properly

### ISSUE THREAD

**Issue by arnesacnussem** [tastybento/ASkyBlock-Bugs-N-Features#402]
the golem just hold the sapling,and i can hear the sound that the sapling been placed,
but the thaumcraft golem do not have the right to place the sapling,so there nothing happens.

where can i change the fake-player settings of the island  ?  or how can I make it work?

![image](https://user-images.githubusercontent.com/9441546/29001334-0f160d82-7aba-11e7-8d71-66958d7aa362.png)

some additional info: this problem most appears when Thaumcraft with Authme,but authme gives the way in config file to corect this problem 

>     unrestrictions:
>         # Below you can list all account names that AuthMe will ignore
>         # for registration or login. Configure it at your own risk!!
>         # This option adds compatibility with BuildCraft and some other mods.
>         # It is case-insensitive! Example:
>         # UnrestrictedName:
>         # - 'npcPlayer'
>         # - 'npcPlayer2'
>         UnrestrictedName:
>         - FakeThaumcraftBore
>         - FakeThaumcraftHungryNode
>         - FakeThaumcraftGolem

**Comment by arnesacnussem** [comment]
i'm sure it is caused by this plugin:
              removed all plugin and start the server , the golem works correctly
              only add this plugin , the golem do not work.

**Comment by Poslovitch** [comment]
Sounds okay and easy to do, I'll try to push a fix in 3.0.6.12 today.

**Comment by arnesacnussem** [comment]
there's many other mod has this design. 


Refer to this post!: https://www.google.com/amp/s/amp.reddit.com/r/feedthebeast/comments/2xd1jw/mod_fakeusers/
