### ISSUE TITLE
changing Island protection requires island reset

### ISSUE THREAD

**Issue by PapaBoom128** [tastybento/ASkyBlock-Bugs-N-Features#405]
How can I set a new protection range for an island without having the player to reset their island?

 

My protection is 200. I added the permission askyblock.island.range.250 and it didn't work until I reset the island. Is there a way to do this without having to reset the island?

**Comment by Poslovitch** [comment]
They just need to relogin.

Note that it only works for the island leader.

**Comment by PapaBoom128** [comment]
Alright, Thanks!
