### ISSUE TITLE
(Right) clicking on soil says "Island Protected" twice

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#406]
https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/listeners/IslandGuard.java#L1495

It should not listen to a click action on this block, only jump (PHYSICAL?).

**Comment by tastybento** [comment]
I still see a double message sometimes when hitting long grass. I'm not sure why...
