### ISSUE TITLE
BreakBlocks FLAG

### ISSUE THREAD

**Issue by bobbosit** [tastybento/ASkyBlock-Bugs-N-Features#407]
Hi, I am using TokenEnchant and I need to disable the flag BREAK BLOCKS, if not the plugin doesen't work, but if I disable it on world (not on island) players can grief other islands. Can you resolve it?

**Comment by tastybento** [comment]
I don't know much about how TokenEnchant works, but you can create an island in the ASkyBlock world and then allow breaking blocks just for that island using /is settings. Then unregister it from yourself and have players teleport there. Alternatively, set up the enchantment signs on a spawn island and do the same.

**Comment by bobbosit** [comment]
Can you set on the config a flag that allows block breaking only on world and not in the island world?

**Comment by tastybento** [comment]
I do not understand, sorry!

ASkyBlock's protection on protects the Island World. It does not protect other worlds.
