### ISSUE TITLE
PlaceHolderAPI by clip

### ISSUE THREAD

**Issue by PizzaMC** [tastybento/ASkyBlock-Bugs-N-Features#409]
Hello,
I want to create a custom /is menu with DeluxeMenus using PlaceHolderAPI and Deluxemenu' priority/view requirements features. What I want to do it check a placeholder which can be %askyblock_hasisland% and if the result is true/yes then I would have different items in the Menu (for example, an item to redirect to the schematics panel).

In summary, can you add a placeholder for either placeholdersapi or mvdwplaceholders which act like %askyblock_hasisland% a placeholder that checks if the player has an island.

Thanks,
PizzaMC

**Comment by Poslovitch** [comment]
Please contact directly clip or MVdW. The expansions aren't made by us.
