### ISSUE TITLE
Mob Spawners and the MS!

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#41]
_From @Mutim on December 13, 2016 17:5_

Hey tastybento, I have a problem when trying to create a line on my /is ms that sells spawners. I don't know if this is possible, it may be, I just may be doing it wrong. Could you either help, or maybe consider adding it as an option in a future update? This is the error I get in console when making the Item: MOB_SPAWNER and the Data: PIG (I think it's data, the same thing that changes potion effects)

[12:02:52 ERROR]: [ASkyBlock] Problem parsing shop item from minishop.yml so skipping it: MOB_SPAWNER
[12:02:52 ERROR]: [ASkyBlock] Error is : For input string: "PIG"

Thank you for consideration, and help!

EDIT: It was Extra: PIG. This is the exact file>>>
      material: MOB_SPAWNER
      quantity: 1
      extra: PIG
      description: '&f&nPig Spawner&r|&3Spawn eggs not enough?|Want something more consistant?'
      price: 20000
      sellprice: 1000

_Copied from original issue: tastybento/askyblock#405_

**Comment by Poslovitch** [comment]
_From @tastybento on December 14, 2016 16:6_

Hi! This will have to be added so we'll look at doing it.

**Comment by Poslovitch** [comment]
_From @Mutim on December 14, 2016 16:8_

Thank you so much for replying. You know how it is, so many problems. I
have 3 very important plugins that are giving me problems, and you're the
only dev who's contacted me back. I'll let them sit in suspense then 😉. I
can't wait for the update!

**Comment by tastybento** [comment]
This is a lot harder than it looks. Spawner types cannot be defined in the inventory, so I'm having to use some tricks with lore to do this.
