### ISSUE TITLE
Villager limit

### ISSUE THREAD

**Issue by kit8379** [tastybento/ASkyBlock-Bugs-N-Features#410]
Still not work. I still can see people breeding up to 91 villagers etc.

**Comment by tastybento** [comment]
Sorry, I can't replicate this. If there's any players with the askyblock.mod.bypass permission then they won't be limited.

**Comment by kit8379** [comment]
I think it is ok now. Also, I want to ask can set the limit of Minecart?

**Comment by tastybento** [comment]
Yes, in the entities limit section.
