### ISSUE TITLE
Askyblock pluggin doesnt create a folder and wont load

### ISSUE THREAD

**Issue by NightPhoenix66** [tastybento/ASkyBlock-Bugs-N-Features#415]
I made a local spigot server and a few other plugins run and have made folders but askyblock doesn't. it just lays around being lazy.... how do I fix that? its a 1.12 server and the other plugins that do work are world edit marriage master and custom enchants.... please help...

**Comment by NightPhoenix66** [comment]
[10:40:39 ERROR]: Could not load 'plugins\askyblock.jar' in folder 'plugins'

also I get this error message in the command prompt thingy

**Comment by Poslovitch** [comment]
ASkyBlock needs Vault in order to function.

**Comment by NightPhoenix66** [comment]
vault? is that another plugin or?

**Comment by NightPhoenix66** [comment]
nevermind thankyou very much!

**Comment by Poslovitch** [comment]
This is a plugin to allow us to gather information about economy and permissions.

Vault is a required dependency. Without it, the plugin will simply not launch.

**Comment by Poslovitch** [comment]
Glad to have been helpful!

Don't hesitate to check the FAQ, there : https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions
It may help you a lot.
