### ISSUE TITLE
lag when create/restart island

### ISSUE THREAD

**Issue by Feerko** [tastybento/ASkyBlock-Bugs-N-Features#416]
Hello,

When the player creates or restarts the island there is a lag. 
I'm using updated plugins to the newest version: FAWE, WorldEdit and ASkyblock V3.0.6.11 on PaperSpigot

I use small island schemas. The server is running on a dedicated server. The problem occurs even with a small number of online players.
There is no such problem in PlotSquared. Does ASkyBlock use Async WorldEdit?

I care about your plugin, thank you!

**Comment by Poslovitch** [comment]
ASkyBlock doesn't use FAWE, neither WorldEdit.
Our island deletion (as well as the island level calculation) are designed to be the fastest and the most lightweight possible.
If you're encountering some lags, maybe have you toggled some settings in the config, like `recoversuperflat`.

Can you send us a timings when an island is being create / removed? This may help us for troubleshooting.

**Comment by Feerko** [comment]
recoversuperflat is disabled.
https://timings.spigotmc.org/?url=fisukudixu

**Comment by Feerko** [comment]
I added these flags. This fault still exists.

**Comment by Poslovitch** [comment]
And did you increase your -Xmx ?

What are the technical specifications of your dedicated server?

**Comment by Feerko** [comment]
Intel  i7-7700K OC - 4/8t - 4.7GHz/5GHz 64GB DDR4 2400 MHz. Why askyblock doesn't using async world edit?

**Comment by Poslovitch** [comment]
We tried to do an implementation for FAWE, however it appeared that our own island paste/deletion was far faster than FAWE, and lightweight.

I don't really understand what's happening there. We'll have to wait @tastybento to come back. He may be able to help you.

**Comment by tastybento** [comment]
From the timings report, I looks like it is actually SafeSpotTeleport that is having a problem finding a safe spot to teleport. You may want to set an explicit spawn block for the schematic so the plugin doesn't have to guess where the best spot is. Also, can you upload the schematic to this ticket so I can examine it?

**Comment by Feerko** [comment]
`schematics:
    default:
      icon: SAPLING
      order: 1
      name: "&aLesna Wyspa #1"
      biome: forest
      description: "&7Biom: &eLas|&7Cena: &eDarmowa||&aKliknij, aby wybrac"
      filename: lesna_1.schematic
      useDefaultChest: true
      partnerSchematic: nether
      usephysics: false
      spawnblock: SPONGE
      pasteentities: false
      levelHandicap: 9`

[lesna_1.schematic.zip](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1226549/lesna_1.schematic.zip)

**Comment by tastybento** [comment]
Can you share the timings report when the sponge schematic is used?

**Comment by Feerko** [comment]
Nevermind. It was caused by Skript using event 'on chunk generate'. It works fine after delete it. Really sorry and thanks for you time :)

**Comment by tastybento** [comment]
Oh, okay, that's great to know!
