### ISSUE TITLE
Cobble Ore Generator Won't spawn all types of blocks

### ISSUE THREAD

**Issue by PapaBoom128** [tastybento/ASkyBlock-Bugs-N-Features#417]
I am trying to use different block variants in the cobble-ore generator probability, for example, STONE:1, STONE:2, but whenever I do it, it breaks the generator.

**Comment by Poslovitch** [comment]
It isn't implemented and it won't be on ASkyBlock, since we are now only doing bug fixes, not new features implementations.

It will be in an addon for bSkyblock.
