### ISSUE TITLE
Mobs cannot hurt players in spawn (I want them to)

### ISSUE THREAD

**Issue by PapaBoom128** [tastybento/ASkyBlock-Bugs-N-Features#418]
Hello,

I have a plugin which spawns a mob in a pit which players will have to kill for some reward. The pit is located in the spawn island. The problem is that the mobs spawned (also vanilla mobs) are not able to hurt the players in the spawn island (aSkyblock Spawn). **I want them to hurt players in spawn island**. The mobs can hurt players just fine outside the island spawn. I looked through the config and couldn't find any way to allow the mobs to hurt players in the spawn island.

I also heard somewhere that you can register an island and then unregister it. If I do something like this, is the island going to be deleted later on?

Thanks!

**Comment by tastybento** [comment]
You most likely have invincible visitors set to true in config.yml.

For reg/unreg, no the island won't be deleted. It'll just not be owned by anyone.

**Comment by PapaBoom128** [comment]
Yes, I do have them on invinsible. Is there a way I can keep them on invinsible on islands but not on spawn?

**Comment by tastybento** [comment]
No... that's not an option, sorry. You could remove the ENTITY damage type from the set. That should allow mobs to hurt you while still keeping other types of damage to a minimum.
