### ISSUE TITLE
monster spawners are default spawners in 1.12.1

### ISSUE THREAD

**Issue by darkstrayer** [tastybento/ASkyBlock-Bugs-N-Features#419]
Setting up and testing a new server with Spigot 1.12.1 and ASkyBlock V3.0.6.11 and noticed spawners on the nether island are not working.

steps to replicate:
1. create new spigot server Spigot 1.12.1 (R01)
2. install latest vault
3. install ASkyBlock V3.0.6.11
4. start the server
5. create new island
6. create nether portal
7. enter nether and check the spawners, all default pig spawners that do not spawn mobs.

**Comment by tastybento** [comment]
Thanks!
