### ISSUE TITLE
A bug when the player open the warps GUI

### ISSUE THREAD

**Issue by luzhenbin** [tastybento/ASkyBlock-Bugs-N-Features#423]
Sorry for my poor english.
The plugin's version is 3.0.7
The Server's version is paperspigot-1.12
When the player type /is to open the GUI and switch to the warps GUI th player can move the players' hands to his bag.
When the player open the warps' GUI he can move his items to the GUI and When he close the GUI the items can not vanish.
When the player is sleeping the player can type the /is to open the GUI and move the GUI's items.
So please fix it.

**Comment by luzhenbin** [comment]
And When you use 1.12 to enter the Server the items can not be moved.
I thins is the Game version's error.
The plugin ViaBackwards

**Comment by Poslovitch** [comment]
Please check if it's not caused by an other plugin that poorly handle GUIs.

**Comment by tastybento** [comment]
Please read the FAQ. https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions
