### ISSUE TITLE
Mob & Animal Spawning is false and they spawn :/

### ISSUE THREAD

**Issue by AconTM** [tastybento/ASkyBlock-Bugs-N-Features#424]
i have the newest Version and now Skeletons & Chickens spawn naturaly ... i have Monster & Animal Spawn on false :/

**Comment by Poslovitch** [comment]
Where do they spawn? Does the island have the related settings on, instead of false?
Did you correctly update the plugin (by following step by step the changelog) ?

**Comment by AconTM** [comment]
i follow the changelog step by step & this is my Config:     
____________________________

     ACID_DAMAGE: true
     ANVIL: false
     ARMOR_STAND: false
     BEACON: false
     BED: false
     BREAK_BLOCKS: false
     BREEDING: true
     BREWING: true
     BUCKET: false
     COLLECT_LAVA: false
     COLLECT_WATER: false
     CHEST: false
     CHORUS_FRUIT: false
     CRAFTING: true
     CREEPER_PAIN: true
     CROP_TRAMPLE: false
     DOOR: false
     EGGS: false
     ENCHANTING: true
     ENDER_PEARL: false
     ENTER_EXIT_MESSAGES: true
     FIRE: false
     FIRE_EXTINGUISH: false
     FIRE_SPREAD: false
     FURNACE: false
     GATE: false
     HORSE_INVENTORY: false
     HORSE_RIDING: false
     HURT_MOBS: false
     HURT_MONSTERS: true
     LEASH: false
     LEVER_BUTTON: false
     MILKING: false
     MOB_SPAWN: false
     MONSTER_SPAWN: false
     MUSIC: false
     NETHER_PVP: false
     PLACE_BLOCKS: false
     PORTAL: false
     PRESSURE_PLATE: false
     PVP: false
     REDSTONE: false
     SPAWN_EGGS: true
     SHEARING: false
     VILLAGER_TRADING: true
     VISITOR_ITEM_DROP: true
     VISITOR_ITEM_PICKUP: true

**Comment by AconTM** [comment]
But its not overpowerd, only 3 - 4 Skeletons spawn at night

**Comment by tastybento** [comment]
If you change the config, you need to flush the settings out to all existing islands by doing **/asadmin settingsreset all**
(@Poslovitch I'm getting really fed up of telling people this. I wish I'd never let islands have their own settings and just kept global settings.)

**Comment by tastybento** [comment]
https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions

**Comment by AconTM** [comment]
i have do this bevor i post this thread ^^

**Comment by tastybento** [comment]
What version of the plugin? Can you share your config.yml? Zip it and drop it into this ticket.
