### ISSUE TITLE
Negative levels

### ISSUE THREAD

**Issue by Mikgreg** [tastybento/ASkyBlock-Bugs-N-Features#426]
Hello,

I'm currently having an issue where people are going into negative island levels, there's no death penalty set up or negative block values so I'm not too sure where the issue is coming from. This is my configs:

config.yml:
https://hastebin.com/uluwedemex.php

blockvalues.yml:
https://hastebin.com/mexetogipu.makefile

Any help appreciated, thanks.

**Comment by Poslovitch** [comment]
`levelHandicap` in the schematic sections is probably the cause of these negative levels, due to player breaking their island.

We are no longer add new features in ASkyBlock, so the option to disallow negative levels will be added in BSkyBlock instead.

**Comment by Mikgreg** [comment]
@Poslovitch is there any number I can put into the handicap to make it stay at 0 and above?

**Comment by Poslovitch** [comment]
None, actually.
At least, set it to 0 would help.
