### ISSUE TITLE
Players can break block, place blocks, and pvp on eachothers islands

### ISSUE THREAD

**Issue by PattrickMC** [tastybento/ASkyBlock-Bugs-N-Features#427]
So I have a problem, visitors to others players islands can pvp, break, and place blocks on other peoples islands. In the config block placing isn't allowed, so I have no idea how to fix it.

Config: https://pastebin.com/DcS01Fzb

Plugins: https://gyazo.com/81f7b38bf4be77ed4e35c759f5e87c66

Permissions: https://pastebin.com/yLxEcX1j

**Comment by tastybento** [comment]
Try this:

1. Go to an island where people are placing or breaking blocks or PVPing.
2. Type /is settings
3. Check to see if these activities are allowed or not.
4. If they are allowed, do /asadmin settingsresetall
5. if they are not allowed, find a player who can do these things as a visitor (they are not cooped and not on the team). Check their individual permissions. What do they have?

If all else fails, I'd stop the server, take a backup of the ASKyBlock folder, delete islands.yml and restart the server.

**Comment by PattrickMC** [comment]
My issue has been fixed. Thanks for that. However, now mobs aren't spawning.

**Comment by tastybento** [comment]
Read the FAQ on that. Probably just need to run /asadmin settingsreset all
