### ISSUE TITLE
Reset limit

### ISSUE THREAD

**Issue by Mikgreg** [tastybento/ASkyBlock-Bugs-N-Features#429]
Hi there,

It seems that whatever I set the reset limit to, it's always at 2. I've set it to -1 and to 100, nothing changes:

   #How many resets a player is allowed (override with /asadmin clearreset <player>
   #Value of -1 means unlimited, 0 means hardcore - no resets.
   #Example, 2 resets means they get 2 resets or 3 islands lifetime
   resetlimit: 100

http://i.imgur.com/ryq8QaU.png

**Comment by tastybento** [comment]
Your YAML might be screwy. Or try /asadmin clearreset (name) or /asadmin clearresetall.

**Comment by Mikgreg** [comment]
Clear reset brings it back to 2 not the configured number. Not sure what else to try :/

**Comment by tastybento** [comment]
The default is 2 if the value cannot be read from the config.yml. I suspect you are using an old config.yml file. The resets are in the island: section:

https://github.com/tastybento/askyblock/blob/master/config.yml#L56

**Comment by Mikgreg** [comment]
Ah! Mine was in the island section. Guess it's old.
Thanks so much.
