### ISSUE TITLE
Players are able to bypass island lock

### ISSUE THREAD

**Issue by xBMAN88** [tastybento/ASkyBlock-Bugs-N-Features#430]
Wanted to open a formal query about this glitch, posted it on the ASkyBlock thread and got a reply but I figured it would also help to post it here.

Basically, a player can bypass an island lock or island ban by using anti-knockback hacks to fly through and glitch into another player's island.

This has caused a few concerns with players, as players can grief another player's nether portal by turning the obsidian back into lava or by using another player's private mob grinder.

**Comment by tastybento** [comment]
Hmm, let me think about this.

**Comment by SaitDev** [comment]
For security problems like anti hack/cheat you r better to use anti hack/cheat plugins. I recommend you NoCheatPlus

**Comment by xBMAN88** [comment]
The problem is, is that we're running the latest NoCheatPlus (3.15) with ProtocolLib.

**Comment by tastybento** [comment]
Obi shouldn't be possible to make into lava if you have a portal. It only works if there's one obi alone.

Anyway, I'm thinking of just making a teleport happen if the player gets too far in to the island.
