### ISSUE TITLE
Island Level not working in chat.

### ISSUE THREAD

**Issue by CodaMacroft** [tastybento/ASkyBlock-Bugs-N-Features#434]
Hello, I am using the VentureChat plugin and the latest ASkyBlock version. I can't seem to get the Island Level to show up in chat. I even downloaded the ASkyBlock pack with PlaceHoldersAPI and it still doesn't work. I really don't know what to do.

![image](https://user-images.githubusercontent.com/24403178/29677522-5b5fe588-88c9-11e7-9a1a-f981ae0553be.png)

**Comment by tastybento** [comment]
I've never tried VentureChat, it appears not to be compatible. There are other plugins that do placeholder replacement, so you may want to try those instead. They use other placeholders like %island_level%, etc.

**Comment by CodaMacroft** [comment]
Do you know of any other of these "placeholder replacement" plugins that I could try?

**Comment by tastybento** [comment]
PlaceholderAPI is one of the more famous, but Featherboard also exists. I just googled ASkyBlock Placeholders - I don't endorse any particular one, but they do seem to work.
