### ISSUE TITLE
think i found a bug

### ISSUE THREAD

**Issue by cooklover** [tastybento/ASkyBlock-Bugs-N-Features#438]
so i love your plugin so much and so do my players but i found out people can take stuff from othere peoples furnace so i look to see if i could turn it off http://prntscr.com/ge2dk1 and i set it to false but players can still open them same with gates players can open them even tho i set it to false and people can rid othere peoples horse and even open open the chest on them idk if i did somthing worng or not my server is 1.12.1

**Comment by tastybento** [comment]
I answered on Spigot.
