### ISSUE TITLE
Dropping items says Island Protected

### ISSUE THREAD

**Issue by kadenmohr** [tastybento/ASkyBlock-Bugs-N-Features#439]
We want to make it so when a Island is started people can drop items to other players, right now it just pops up a message "Island protected"

**Comment by tastybento** [comment]
Change the setting in config.yml in the world protection section (# Allow item drop VISITOR_ITEM_DROP: true) and the push it out to all the islands using **/asadmin settingsreset VISITOR_ITEM_DROP**.
