### ISSUE TITLE
Make MagicOreGen can work with both island levels and permissions

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#44]
_From @Poslovitch on December 12, 2016 14:52_

https://www.spigotmc.org/threads/a-skyblock.30325/page-155#post-2082177

It should be quite hard to do... 

_Copied from original issue: tastybento/askyblock#399_

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#50
