### ISSUE TITLE
Monsters still spawning if mob_spawn is off - not confirmed

### ISSUE THREAD

**Issue by tastybento** [tastybento/ASkyBlock-Bugs-N-Features#442]
https://www.spigotmc.org/threads/askyblock.30325/page-223#post-2639856

**Comment by jodo1** [comment]
[https://youtu.be/DQRPh14KzAQ](url)

**Comment by tastybento** [comment]
The settings will only stop natural mob spawning, not from spawners.

**Comment by jodo1** [comment]
I have not any spawners in the askyblock world. Nevermind, mobs not too much.

**Comment by jodo1** [comment]
This is probably not a problem with askyblock plugin. Monsters spawning in another world, with peacefull difficulty.

**Comment by tastybento** [comment]
Okay, weird. I'll close this for now then.
