### ISSUE TITLE
Why setrange command can run only in-game?

### ISSUE THREAD

**Issue by SaitDev** [tastybento/ASkyBlock-Bugs-N-Features#446]
Is there anything that require /asadmin setrange must be run in-game?

**Comment by tastybento** [comment]
/asadmin setrange <value> by itself refers to the island you are on, so it must be run in-game.
/asadmin setrange <playername> <value> can be run in console.

**Comment by SaitDev** [comment]
Thank for the info. There isnt any help about setrange while run /asadmin from console. So I thought cant run. Figure it out now /asadmin setrange <player> <range>

**Comment by tastybento** [comment]
Ok!
