### ISSUE TITLE
Feature Request (Acid Damage Knock Back)

### ISSUE THREAD

**Issue by CoolLord22** [tastybento/ASkyBlock-Bugs-N-Features#447]
Hey there, I have a feature request for the acid damage. Is there any way we could do an indicator that the player is taking damage? For my server the health is just draining, it only plays the TNT fuse sound. Any way to have it have the knockback animation (like where the player gets actual damage, not just heart drainage?)

**Comment by tastybento** [comment]
Yes, this was missing. I've added it - good catch.
