### ISSUE TITLE
Command run order is incorrect

### ISSUE THREAD

**Issue by HLF-Raideer** [tastybento/ASkyBlock-Bugs-N-Features#448]
Hey.

We're using your plugin a long time ago, now started to use AAC (+AACAdditionPro) as anticheat and just notified that your AcidIsland plugin closes the GUI AFTER running the commands (island warp, etc.)

The AAC kicked players for InventoryRotation hacks (so moving, teleporting, interacting when a GUI is opened). We tested it, and that is the only one plugin with GUI that cause the trouble.

Can you please close the GUI before run commands in GUI?

**Comment by tastybento** [comment]
Hmm. So, what you say is not technically true, see [here](https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/panels/WarpPanel.java#L304) - the inventory is clearly closed before the command is run. However, maybe AAC needs a tick to pass before the command is run. I'll make a debug build you can try.

**Comment by tastybento** [comment]
Try this one and let me know if you still see an issue:
https://github.com/tastybento/askyblock/releases/tag/3.0.7.1b

**Comment by HLF-Raideer** [comment]
Thank you for the great, profound work! Yes, it is working now!

**Comment by tastybento** [comment]
WOW! That's great news!
