### ISSUE TITLE
Add the End to ASkyBlock

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#45]
_From @tastybento on December 11, 2016 2:7_

This has been requested a few times. 

_Copied from original issue: tastybento/askyblock#396_

**Comment by Poslovitch** [comment]
_From @wasder on February 9, 2017 15:12_

Any ETA?

**Comment by Poslovitch** [comment]
_From @tastybento on February 9, 2017 15:26_

@wasder no not right now.

**Comment by Poslovitch** [comment]
_From @friishon on March 10, 2017 21:46_

When are you going to add end?
I would like to have the end world and put level for going

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#45
