### ISSUE TITLE
Players can take heads from the inventory

### ISSUE THREAD

**Issue by DirtyKDPlayer** [tastybento/ASkyBlock-Bugs-N-Features#453]
Hello,

normal players can remove the heads from the island warps and the island TOP players with the plugin ACIDIsland. OP people can not.

Sry for my english, im german....

**Comment by tastybento** [comment]
https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#i-can-take-the-itemsheads-out-of-the-challengessettingscontrolwarps-guis-why

**Comment by DirtyKDPlayer** [comment]
I deleted all plugins except ACID.
The problem still persists

**Comment by Behoston** [comment]
Same problem, before it was fixed but...
https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/339

**Comment by tastybento** [comment]
I cannot replicate this.

What methods do players use to remove the heads? Which buttons/keys/mouse do they use? 

You say Op cannot remove a head, but normal players can. Share way permissions the players have.

In both the Warps and the Top Ten GUI, clicking the head will warp you if a warp exists. Do players have warps? Or not?

**Comment by Behoston** [comment]
Permission of default group:
https://paste.ofcode.org/wkC7t6SdABCZ6pAphKXnGp
Players (and ops) can just click drag'n'drop heads to it's own inventory.
I will check this without other plugins.

**Comment by Behoston** [comment]
All my plugins:
https://paste.ofcode.org/34uK7Exx6YuvwvgnBEesbsQ
It looks like other plugin crashes askyblock GUI

**Comment by tastybento** [comment]
Yeah, one of them will be doing it. If you find out which, let me know.

**Comment by Behoston** [comment]
Works properly after reboot
