### ISSUE TITLE
Cake removes food units from player

### ISSUE THREAD

**Issue by Mikgreg** [tastybento/ASkyBlock-Bugs-N-Features#454]
Hi there

When eating cake on an island that doesn't belong to you the cake removes food levels from you each time you right click it.

**Comment by QualityNodeNet** [comment]
Just replicated it on my server which is running 1.12.1 with the latest aSkyblock Build. I even tested if it was a visual glitch by eating steak, and throwing it down etc.

**Comment by tastybento** [comment]
Yes, on older servers even if the cake-break was cancelled, you'd still get food from it, so I had to remove it. It looks like this is fixed on newer servers. I'll investigate more.

**Comment by tastybento** [comment]
@Mikgreg @QualityNodeNet Thanks!
