### ISSUE TITLE
/Is Top Not Display Top Ten Islands.

### ISSUE THREAD

**Issue by QualityNodeNet** [tastybento/ASkyBlock-Bugs-N-Features#455]
Occasionally on both my Network's I'll have an issue with /is top not displaying all "Top Ten" islands in the GUI, even though there are thousands of players and islands already created. I've just checked my topten.yml and it is empty even though it's reading a file size of "478kb". I've provided a GIF of what it looks like when it occurs. I'm getting zero errors regarding to this issue though.
https://i.gyazo.com/fcc7767cab155f67eae8a45aae56e6e5.gif

**Comment by tastybento** [comment]
If topten.yml is empty, but reading a file of 478KB, then that is very weird.
Stop the server, move topten.yml to topten.old and restart. Then in the **console**, do **asadmin topten** to regenerate the top ten. Or you can just leave it to be created naturally when people do /is level.

**Comment by QualityNodeNet** [comment]
That did fix the issue then, but it randomly occurs and fixes itself normally. Thanks for the tip though on how to instantly fix the issue, do you know what's causing it in the first place?

**Comment by tastybento** [comment]
No idea. If you have the file, then drag and drop it here so I can look at it.

**Comment by QualityNodeNet** [comment]
It's working now, since I deleted and it's showing:
`topten:
  4e58ec9a-8494-4626-8a89-4336ede1f667: 1432920
  e6929511-d1fc-45e4-b98e-6c58676db8c9: 1074042
  a199fda3-5c5a-4153-b4b0-b09f23610373: 1023151
  75c4b6b7-1356-4a1b-b68a-b88d8bf66b62: 792003
  1ca00a00-d601-4216-a6c8-5d256d05515f: 721878
  8a01e3e4-f688-456a-97e1-c5b93a1e0129: 461046
  aac52e4f-25f6-4ade-a1a0-86ca5727df5f: 347111
  e2a8cb1b-4b8c-46ad-8efc-afe29b1bfdcc: 331852
  2097a5b7-bea6-429e-865e-a8e0fa509f86: 212640
  04dc465b-5883-4577-9b91-20dfdac3fd93: 211224`

**Comment by tastybento** [comment]
Okay. That's how it should look.

**Comment by UnioDex** [comment]
I'm having the same issue. My 4th and 6th topten heads were not showing. I deleted topten.yml and restart the server not 5th and 9th heads are not showing.

**Comment by tastybento** [comment]
Weird. Heads are downloaded from Mojang so I wonder if they didn't make it in time and as they are cached they are not requested again. If the server restarts do the missing heads change? Or always the same?

**Comment by UnioDex** [comment]
Always same. I don't think it is about head getting. Because when i open gui at first every head is Alex head and after 1-2 seconds heads are replacing. But even heads were Alex missing heads not showing.

You can try getting heads from https://mcapi.de or gameapis.net . But im not sure it is about heads.

**Comment by tastybento** [comment]
Okay. Can you paste your topten.yml file? Id like to see if the uuid's are in there or not. I expect they are, but let's see.

**Comment by UnioDex** [comment]
Here:
`topten:
  518fd659-3c81-392e-8451-f740fe13eda2: 5108792
  58095ab8-9d58-3a21-a369-fd62745f7178: 3241248
  0b3e5985-f4db-3065-b84d-ec040f1d9722: 3011986
  0308daa0-d001-39f7-98c3-aee3e425e147: 2694948
  62f706db-402b-3e75-aa3a-efba6413bf3a: 1866229
  3208ff4f-e255-3bb9-bc86-820d3ba4423b: 1725919
  5eeaf195-e337-382d-a422-04f06032baa5: 1717883
  16398ef1-45dc-31be-bc82-744734637638: 1595565
  984b1538-6e06-369e-bd91-c567159bf464: 1317820
  8e33ece7-7a3a-3f6f-8f5c-32f5d14f892e: 1303433
`

**Comment by tastybento** [comment]
I found the issue. The GUI top ten uses the server cache to find the player names instead of the plugin's own store. What's most likely happened is that the players on your server no longer are in your server cache (they have probably stopped playing). I'll make a new version with a fix so you can try it.

**Comment by tastybento** [comment]
https://github.com/tastybento/askyblock/releases/tag/V3.0.7.2

**Comment by UnioDex** [comment]
9 player head showing but 1 is still not showing :/
