### ISSUE TITLE
Island Lock Message

### ISSUE THREAD

**Issue by QualityNodeNet** [tastybento/ASkyBlock-Bugs-N-Features#456]
Basically the "Island is locked to visitors" is occurring to normal players when they fly in and out of there island, I've found zero errors in console when we were attempting to re-create this and it is occurring on the latest build. They do not have perms to bypass island locks either, even tested it with other islands to make sure. Video Proof: https://www.youtube.com/watch?v=tDlxvKFwn7w

**Comment by tastybento** [comment]
This is not a bug - they are being told that the island is locked to visitors.
