### ISSUE TITLE
/Is Team Broken

### ISSUE THREAD

**Issue by QualityNodeNet** [tastybento/ASkyBlock-Bugs-N-Features#457]
Since the latest update, we haven't been able to do /island team or /is team, it isn't showing up as a command. We've found zero errors in console and is occurring on both my Network's, it is preventing people from seeing who's on there island.

**Comment by tastybento** [comment]
Can you see the command in help if you are Op? If so, then it's a perm issue. Make sure the players have askyblock.team.create or askyblock.team.*.

**Comment by QualityNodeNet** [comment]
Can't see the command even when I'm OP'ed.

**Comment by tastybento** [comment]
Huh. Let's check some things:

1. Type /is help - do you see commands /island team, /island invite <player>, and /island leave?
2. Is AskyBlock actually running? (Sorry, had to ask!)
3. Do you have the permission askyblock.team.create, even if you are Op?
4. What permissions plugin are you using?
5. What version of the plugin did you update from?
6. If you type /is team and you are **not** on a team what error message do you see?

**Comment by tastybento** [comment]
I also wonder if you locale file is correct. Can you drag and drop it to this ticket? Make sure it's the one you are using.

**Comment by QualityNodeNet** [comment]
1. Yes
2. Yes
3. Yes
4. PermissionsX
5. I update every update.
6. Nothing, no command
7. https://pastebin.com/MiVCuawu I update the config.yml every update but haven't touched the en-US.yml in months, if there is anything missing can you inform me as well please.

**Comment by tastybento** [comment]
So, perms are correct then.

For #6, Can you clarify - do you see nothing at all, or an error "no command"? 

If you type **/is team** and you are not on a team, you should see: "You do not have a team!" from here:

kick:
  errorNoTeam: "You do not have a team!"

That is in your locale file, so you should see it. if you are in a team, obviously you should see the team members. I assume you are actually using the US language file of course. You may want to do /is lang and select US english to make sure.

This code has not changed for 2 years, so I don't know why you're suddenly having a problem. Weird...

**Comment by QualityNodeNet** [comment]
This is me doing /is team when I have no-one on my island and I've made sure we were on US English, by changing it too it again.
[https://i.gyazo.com/aaf4b951eca303b8e9fa3f76563694df.gif](url)

**Comment by tastybento** [comment]
It is actually saying "Unknown command"

What happens if you do /island team?

**Comment by QualityNodeNet** [comment]
Exact same thing which is shown in the Gif, I sent you.

**Comment by tastybento** [comment]
If you type /island team, and you get the "Unknown command, type "/help" for help" that error is being given by the server and not the plugin. It indicates that the server does not know about the /island command. You can try it, type some junk command, like "/asdfgh" and you will see that error.

So, why is this happening? I don't know. Either your plugin file has been corrupted, or maybe another plugin is interfering with the command. 

In the GIF, you showed that /asadmin is working, but do other /is or /island commands work?
