### ISSUE TITLE
DeluxeChat Support

### ISSUE THREAD

**Issue by QualityNodeNet** [tastybento/ASkyBlock-Bugs-N-Features#458]
I saw DeluxeChat support was added for /is teamchat awhile back, but when I enable:

```
   # e.g : [23.5k] instead of [23562]
   fancylevelinchat: true
```

It still displays island levels as 23562 and haven't found if there is another placeholder required, or if it's a aSkyblock issue or if you just don't support DeluxeChat with "fancylevelinchat".

**Comment by tastybento** [comment]
Sorry, it's not supported.
