### ISSUE TITLE
Still can't drop items

### ISSUE THREAD

**Issue by kadenmohr** [tastybento/ASkyBlock-Bugs-N-Features#461]
I asked a while ago how I can make it so players can drop items to each other without it saying "Island Protected" all my settings for it are set to **_true_**, please help me, heres my config! I really need this!!! https://hastebin.com/ikuhiqiyen.php

**Comment by tastybento** [comment]
Once you change a config, run **/asadmin settingsreset all**, to have the config settings apply to all the islands. You may need to restart too.
