### ISSUE TITLE
Not issue, just question

### ISSUE THREAD

**Issue by ResqDiver1317** [tastybento/ASkyBlock-Bugs-N-Features#462]
We are wanting to allow a couple of our players to help work on our spawn island. I have a permission group I can add to the helpers, but wanted to know for sure what permission node I needed to include in that group so they can help build there. From looking over the permissions, I am thinking it's the "askyblock.mod.bypassprotect" but just wanted to make sure. 

Thanks :)

**Comment by tastybento** [comment]
Yes, that would probably work well. It would enable them to grief any island though, so you may want to make sure you trust them. :-)
The other way to do it is to temporarily make the island your island be registering it to yourself and then cooping the players to it. Once you are done, uncoop everyone, unregister it and make it the spawn island.
