### ISSUE TITLE
Issue with control panel

### ISSUE THREAD

**Issue by Oskarst2001** [tastybento/ASkyBlock-Bugs-N-Features#464]
Hey, I have a problem with the Island control panel. So I added my member group permissions the permissions: "askyblock.island.contorlpanel" and it should give him the ability to open the control panel by typing "/is" but it won't work, it simply just don't type nothing in chat or console so I can't see where is this problem coming from. Op's can open the control panel but other players cannot open it even if they have the permission.

**Comment by tastybento** [comment]
Set **usecontrolpanel: true** in config.yml

Also, make sure the permission is correct - you spelt it wrong above.

**Comment by Oskarst2001** [comment]
Its already set to true

and I added them this permission : "askyblock.island.controlpanel"

**Comment by Oskarst2001** [comment]
also Is there a way to change the prices of the upgrades?

**Comment by tastybento** [comment]
Your config.yml might not be spaced correctly so it is using the default. Other than that, I don't know, sorry. 

For upgrades I'm not sure what you mean, the mini shop has its own yml file. Just look at the various yml files for settings.
