### ISSUE TITLE
No permission when right clicking ender chest

### ISSUE THREAD

**Issue by bertek41** [tastybento/ASkyBlock-Bugs-N-Features#468]
Hey i have crate chest (ender chest) in spawn and when players right click it plugin says you don't have permission how can i fix this?

**Comment by Poslovitch** [comment]
By reading FAQ :)

**Comment by bertek41** [comment]
I know craft permission but i don't want players craft it

**Comment by tastybento** [comment]
That's the only option. You either enable enderchests or not.
