### ISSUE TITLE
Players able to bypass Island Protect by placing blocks

### ISSUE THREAD

**Issue by TuaCarnifex** [tastybento/ASkyBlock-Bugs-N-Features#471]
I have edited all the settings in the config to my liking however some of them aren't "active" I guess you could say. I receive no errors in the console. Also I try setting it so players cant build on others islands unless they're co-oped and what not. However players can break anything or open anything but they can place blocks.. It's a serious problem and a lot of my players are complaining as it isn't anti grief like this plugin should be. I have world guard however I have the most recent version. And need the world guard plugin as I use it to protect spawn in a different world. I have tried disabling world guard in the ASkyBlock world and it doesn't work, Please help as soon as you can, Thanks.

**Comment by tastybento** [comment]
Read the FAQ, that should help.

Use **/asadmin settingsreset all** to push out settings changes to established islands.
ASkyBlock doesn't use WorldGuard at all. You can use it for spawn if you like though in addition.

During setup, did you change the island distance? If you did, then maybe some islands are not on the "grid" anymore and the protection area is not aligned. The only answer here is to do a full reset if that's the case.
