### ISSUE TITLE
Can't TP to world spawn and everytime I change config it breaks it!

### ISSUE THREAD

**Issue by GHOSTBOY246** [tastybento/ASkyBlock-Bugs-N-Features#472]
I cant go back to world spawn, or other commands. And everytime I change config nothing works. i cant even create my island! Please help! My friend and I are trying to build a really cool server!![bitmoji](https://render.bitstrips.com/v2/cpanel/10223160-313207943_3-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by tastybento** [comment]
I'm sorry, but you haven't given me any information that could help me help you other than "it doesn't work". 
You've probably added a plugin that is messing things up. I recommend you remove all plugins except for Essentials, AskyBlock and Vault. Then make sure everything works okay. Then add Essentials Spawn so you can set spawn. Then add Multiverse Core so you can do multiple worlds. After that, it's up to you, but you may want to add WorldEdit so you can easily make stuff.
Good luck!

**Comment by GHOSTBOY246** [comment]
I deleted everything except for what you wanted me too
![proof](https://user-images.githubusercontent.com/32186683/30758325-c5ffff08-9f86-11e7-9115-215e45a0253d.PNG)

then this happens when i try to go to world spawn
 ![2017-09-22_11 08 47](https://user-images.githubusercontent.com/32186683/30758272-82f2f288-9f86-11e7-9e78-9f86d3b723a9.png)
please get back to me as soon as you can!

**Comment by tastybento** [comment]
What do you mean exactly when you say "go to world spawn"? What command are you trying to run?

**Comment by Wreeper** [comment]
Same as me, but i'm trying to make a challenge

**Comment by GHOSTBOY246** [comment]
The command, go to world spawn

**Comment by tastybento** [comment]
What is the command? **/spawn**? **/gotoworldspawn**? **/is spawn**? **/somethingelse**?

If it is any command other than /is spawn, then that is nothing to do with this plugin.

IF you are trying /is spawn and you are getting "Unknown command" then that's probably because you have not actually set a world spawn! To set up the ASkyBlock spawn, you need to go to a location and then do /asadmin setspawn. So, try that.

**Comment by Wreeper** [comment]
Haha.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-10-22 23:32 GMT+03:00 tastybento <notifications@github.com>:
