### ISSUE TITLE
Warps aren't working for me

### ISSUE THREAD

**Issue by Oskarst2001** [tastybento/ASkyBlock-Bugs-N-Features#477]
Hey, so as the title says Warps aren't working for me. I make a sign [WELCOME] and it says:
"Welcome sign placed successfully!"
But when I type /island warps, I can't see any warps at the list:
"There are no warps available yet!"
What can it be?

**Comment by tastybento** [comment]
What happens if you type /is warp (your name)?

Also what is in the warps.yml file after you stop the server?

**Comment by Oskarst2001** [comment]
when I type /is warp (My name) its saying: 
"There are no warp available yet!"
"Create a warp by placing a sign with [WELCOME] at the top."

In warps.yml: 
"warps: {}"

**Comment by Oskarst2001** [comment]
????

**Comment by tastybento** [comment]
I don't know why that would be happening. I assume you only have ASkyBlock and not the WelcomeWarpSigns plugin as well?

**Comment by Oskarst2001** [comment]
No, I have both plugins installed.

**Comment by Oskarst2001** [comment]
any ideas?

**Comment by Poslovitch** [comment]
You should remove WelcomeWarpSigns.
This is what Tastybento meant by saying : 
> I assume you only have ASkyBlock and **not** the WelcomeWarpSigns plugin as well?

**Comment by tastybento** [comment]
Don't use Welcome Warp signs in ASkyBlock world. It already has it built in.
