### ISSUE TITLE
Island create cost (default island)

### ISSUE THREAD

**Issue by xXIOSCARIXx** [tastybento/ASkyBlock-Bugs-N-Features#481]
on my server players have to pay for new plots > islands etc, exept.. you cant set create price for the default island

i dont want there to be any new islands unless the user pay for it

whenever new players join they may just join and claim a plot > island and leave, thats why im doing this

**Comment by tastybento** [comment]
Answered on spigot - just add a cost: line to the default island definition in config.yml. It works fine. :-)

**Comment by xXIOSCARIXx** [comment]
Oh this works now, i dident realise i had to use the schmatics panel..
thank you <3

2017-09-30 1:36 GMT+02:00 tastybento <notifications@github.com>:
