### ISSUE TITLE
other players cant interact with the commands

### ISSUE THREAD

**Issue by BipolarNinja** [tastybento/ASkyBlock-Bugs-N-Features#485]
Other players on my server cant do /is it keeps saying creating a new island for you... you are not allowed to interact with this

**Comment by tastybento** [comment]
It sounds like another plugin is blocking the island creation or teleporting. Are there any errors in the console when you run the /is command?

**Comment by BipolarNinja** [comment]
Here is a list of the pluvins that i am using
Antibuild
Bettershops
ChatManager
Checkpoint
Clearlag
Coreprotect
Essentials
EssGroupMgrTeams
EtwTickets
GroupManagerPex
IDisguise
Ip-check
Jobs
Kits
LeakParkour
MarriageMaster
MCCore
Openinv
Oregenerator
PermissionsEX
PluginMetrics
Plugman
ProtocalLib
PunishmentGUI
RBuy
SimpleTrading
Spawner
SpawnMob
SupperVanish
UColor
update
Updater
Worldedit
WorldGuard
Yourspy

**Comment by BipolarNinja** [comment]
But the this is it works for as an oped player but not an oped player and i
even gave them the permissions to do so

**Comment by tastybento** [comment]
The error is being generated by AntiBuild.
