### ISSUE TITLE
Portal use in /is settings is still broken

### ISSUE THREAD

**Issue by Zaino60** [tastybento/ASkyBlock-Bugs-N-Features#486]
Even in latest ASkyBlock version, the bug that has been around for months still isn't fixed :(
Basically if you do /is settings and turn off "Portal Use", visitors still can use your nether and end portals, making the setting completely useless.
Example gif reproducing the bug: https://gyazo.com/96b5d3d6981f26b3111ff3ee1abcf04f
Spigot Version: 1.8.8
ASkyBlock version: 3.0.7

**Comment by tastybento** [comment]
I did exactly as you show in your video and I get an Island Protected error when the visitor tries to jump through the portal. I'm using 1.8.8 server and everything is exactly the same. I don't know why your character can do that. Clearly other protections are working, but the portal is not. I've made a release with Nether Portal debugging switched on. Could you try and do what you did in the gif and take the logs? It'll tell you why the other player is allowed to go through the portal. The release is here:
https://github.com/tastybento/askyblock/releases/tag/3.0.7.1.nether

**Comment by Zaino60** [comment]
Done.
New Gif: https://gyazo.com/6e033efa138001cb6ad45df3145dd177
Full Server Log while doing that: https://pastebin.com/D3EZWNrH

**Comment by tastybento** [comment]
Can you share your config.yml? (Drag and drop a zip of it to the reply box). From looking at the logs it looks like the most obvious reason is that the **createnether** setting in config.yml is false. Is it?

I've made a slightly different build to improve the logs. Please try it and share again:

[askyblock.jar.zip](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1364160/askyblock.jar.zip)

Also, by the way, there is a plugin mentioned in the log called EndPortalMine v1.0 that is causing a lot of errors. I recommend you remove it. I don't think it's causing this issue, but it might be related.
