### ISSUE TITLE
Challenge objective item lore line not breaking

### ISSUE THREAD

**Issue by Zaino60** [tastybento/ASkyBlock-Bugs-N-Features#487]
Before ASkyBlock 3.0.7, if the "objective" line in the challenges menu was too long, the plugin would automatically make line breaks so the "item lore" explaining the challenges at /c would be readable.
This is no longer the case, as you can see an example here https://gyazo.com/c4d678c5ce2d4c8d69c675eee5be5c63 this is how it now looks for all challenges in the latest ASkyBlock version 
Spigot Version: 1.8.8
ASkyBlock version: 3.0.7

**Comment by tastybento** [comment]
This is not a bug. Auto line chopping was removed because it was unreliable and arbitrary. You need to use the | character in your descriptions to do your own new line. Then also add color codes.
