### ISSUE TITLE
How to Reset all islands at once?

### ISSUE THREAD

**Issue by RarelyRoger** [tastybento/ASkyBlock-Bugs-N-Features#489]
HI would like to know the command / file that contains all the islands that can be deleted for a season restart, I have been looking all over the web and I can not seem to find the correct answer I need. thank you for helping :)

**Comment by tastybento** [comment]
Have a look in the FAQ: https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#how-do-you-completely-reset-the-plugin

**Comment by RarelyRoger** [comment]
Thank you so much.
