### ISSUE TITLE
Please Help me!!

### ISSUE THREAD

**Issue by wizdamrisby** [tastybento/ASkyBlock-Bugs-N-Features#494]
i cant seem to get the plugin working in my server please help with with solutions!! and if you can please help me on discord if you have a server

**Comment by RarelyRoger** [comment]
Hey I can help you when I get home from school just send me an email of your discord and I will add you when I get home.

**Comment by RarelyRoger** [comment]
RarelyRoger@gmail.com

**Comment by RarelyRoger** [comment]
You can Also Add me on Discord RarelyRoger#0097
