### ISSUE TITLE
Remove old messages.yml

### ISSUE THREAD

**Issue by MineTheCube** [tastybento/ASkyBlock-Bugs-N-Features#497]
Hi,

Some players will likely never return on my server, so it would be great if we could remove offline messages (those stored in messages.yml) older than X days via a config option.

Or maybe add an option to disable this feature?

**Comment by tastybento** [comment]
There's no timestamp on the messages to do that. If the file's becoming too big, just delete it. The messages are hardly that important.

**Comment by MineTheCube** [comment]
Maybe add an admin command to lookup UUID → OfflinePlayer, and then use `getLastPlayed` to delete messages of players that didn't came more than X days.
But it's maybe too much work for what it worth.

But adding a timestamp to delete old messages could be a great feature though, should I suggest in `bskyblock` repo?
So you could have:
`offline-messages-keep: <value>`
Where value could be:
- `0` to keep them indefinitely (default)
- `-1` to prevent messages from being saved
- `x` to keep them `x` days

**Comment by tastybento** [comment]
I won't be adding to ASkyBlock. You can add it to BSkyBlock list.
