### ISSUE TITLE
Item Drop / Pickup Problem in Visitors

### ISSUE THREAD

**Issue by TheDGOfficial** [tastybento/ASkyBlock-Bugs-N-Features#499]
`     # Allow item drop
     VISITOR_ITEM_DROP: true
     # Allow item pickup
     VISITOR_ITEM_PICKUP: true`

I enabled this options and do /asadmin reload, and my players still can't pickup and drop items from a other player's island.

**Comment by tastybento** [comment]
Do /asadmin settingsreset VISITOR_ITEM_DROP, asadmin settingsreset VISITOR_ITEM_PICKUP

It's a FAQ.

**Comment by tastybento** [comment]
Linked to #502
