### ISSUE TITLE
Again bug

### ISSUE THREAD

**Issue by Wreeper** [tastybento/ASkyBlock-Bugs-N-Features#500]
Hello. It's again me (bug https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/478).

The YAML is edited due to your information, everything i think is correct, but why it's giving me this error?
Code:     
wreeper:
      friendlyname: 'Hungry Wree'
      description: 'Bake a cake, 2 breads, one milk and get a water bucket! Don't ask why.'
      icon: STONE_HOE
      level: 'Elite'
      type: inventory
      requiredItems: 'CAKE:1 BREAD:2 MILK_BUCKET:1 WATER_BUCKET:1'
      takeItems: true
      itemReward: 'DIAMOND_BLOCK:320'
      rewardText: '320 DIAMOND_BLOCK'
      moneyReward: 250000
      expReward: 3000
      permissionReward: ''
      repeatable: true
      repeatItemReward: 'DIAMOND_BLOCK:2 DEADBUSH:2 SAND:2 GLASS:30'
      repeatRewardText: '2 DIAMOND BLOCK , 2 DEADBUSH , 2 SAND, 2 GLASS'
      repeatMoneyReward: 15000
      repeatExpReward: 150
      # Max times limits how many times a challenge can be done. Comment out to make unlimited
      maxtimes: 

![image](https://user-images.githubusercontent.com/30046331/31306080-0e66bb44-ab51-11e7-9f48-ee2abdda8276.png)

**Comment by nickdoran** [comment]
Your issue;

Original: `description: 'Bake a cake, 2 breads, one milk and get a water bucket! Don't ask why.'`
Error: `Don't`
Fix: `Don''t`
The apostrophe inside Don(')t breaks the line.
