### ISSUE TITLE
Fishing Rod Bug

### ISSUE THREAD

**Issue by Zaino60** [tastybento/ASkyBlock-Bugs-N-Features#501]
Basically, when you hit yourself with a rod (and according to some players it happens randomly too), it doesn't let you to fish anymore, spamming the error "PvP is disabled on your island!" when you right click your fishing rod.
Gif reproducing the bug: https://gyazo.com/b64386e95633a9548a6ea81a124c624b
No Console Errors

**Comment by tastybento** [comment]
Thanks for the report.
