### ISSUE TITLE
Users Cannot Interact With Island on 1st generation

### ISSUE THREAD

**Issue by ChrisIsHD** [tastybento/ASkyBlock-Bugs-N-Features#503]
Ok iv got an issue where users cannot interact with there skyblock level when they generate it, They can then interact with it if they reset the island :/ any ideas as its driving me nuts

[SPOILER="Plugins"]FixFreecam, AsyncWorldEditInjector, LuckPerms, WorldEdit, HungerKeeperPlus, Essentials, PlaceholderAPI, ClearLag, NametagEdit, tpLogin, Votifier, ProtocolLib, WorldGuard, ChatReaction, AAC, MVdWPlaceholderAPI, AsyncWorldEdit, TopTenHeads, EssentialsChat, DeluxeMenus, FeatherBoard, ConditionalCommands, CustomCrates, Vault, GAListener, EssentialsSpawn, CommandBlockerUltimate, AACHider, NoFlyZone, Jobs, SilkSpawners, ASkyBlock, LockettePro, ShopGUIPlus, Multiverse-Core, HolographicDisplays[/SPOILER]

-------------------------------------------------------------------------------------------
Edit:

Ok so heres what iv done so far and still no fix....

Deleted the aSkyblock plugin folder & world... and installed latest version of aSB (No Fix) (still takes a island reset before a user can interact with there island)
Removed WorldGuard (still no fix)

Im literally lost as hell right now as to what to do.

This happens "WITH or WITHOUT" Worldguard installed
https://chrisis.live/s/1010174929_3.gif
Latest Version of aSB.

**Comment by tastybento** [comment]
Are you still having an issue? I thought this was answered on Spigot or somewhere. It's most likely to do with your server having spawn protection on so the first island, which is usually at 0,0 ends up being protected. The definitive proof is if they try to break a block and it disallows it without any error message. Only if it says "Island protected" is the protection being done by ASkyBlock.

**Comment by tastybento** [comment]
Closing for now.
