### ISSUE TITLE
ASkyBlock Suggestions

### ISSUE THREAD

**Issue by Zaino60** [tastybento/ASkyBlock-Bugs-N-Features#504]
- Add more ASkyBlock challenges types: Right now there's only "inventory", "island" and "level". There's a lot of potential to add more types, such as "if player reached top 10 or above X rank in the island level top", "experience level", vanilla stats such as "X mobs killed", and maybe other plugin compatibilities such as "mcmmo levels". 
- Expand the "inventory" challenge type, so it can support items with custom name, lore, and other NBT Tags. For example, if you have custom drops or items in your server, you could make ASkyBlock challenges for player to collect that item in specific in order to complete the challenge!
- Add a similar GUI to /is top that shows the top users who completed the most amount of challenges in Sky Block
- Add an option so if the leader of a team doesn't log in the server for X configurable amount of time (For example: 3 months), the island leadership would go to other team member
- Add an option to disable visitors using enderpearls in your island guard settings at /is settings
Some players are complaining that their visitors are using em to get to parts of their islands they aren't supposed to go
- For players who run out of resets, add an option so they can create a last island but it would be the default island and with no starting chest, so that way they can keep playing SkyBlock even though they used their last reset.

**Comment by obiku19** [comment]
Zaino60, you can add as many challenges as you want. Edit the challenges.yml to your needs. Keep the format as described. Challenges are mostly a server dependent feature. The current Challenges.yml, in my opinion, is only there to get started.

About the resets, that's where your admins/mods come in. With the correct permissions, they could set the amount of resets back to zero. What could be a feature is, that the amount of reset used will be cleared after an X amount of weeks/months to prevent players from resetting their island to frequently.

**Comment by Zaino60** [comment]
I know you can add as many challenges as you want, you didn't understand my suggestion :/ Currently when making new challenges you can only select 3 types of challenge "types", being "inventory" (requires an specific(s) item(s) in your inventory), "island" (requires specific(s) entity(s) in your island) and "level" (requires X island level). My suggest is to add more types, as you can read above, to allow us create more variety of challenges.
Regarding the resets, I know, we have something similar to that. Nevertheless, still it would be nice an option so if you run out of resets and you got no island, instead of being forced to join someone's, to be able to create a new default island without starting chest (so you can't abuse the free items), respecting the cooldown of course

**Comment by tastybento** [comment]
Not bad ideas. Please put them on https://github.com/tastybento/bskyblock/issues though because we're not adding new features to ASKyBlock right now, just bug fixing.

**Comment by Zaino60** [comment]
Done
