### ISSUE TITLE
Coop players can't drop items

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#507]
Coop players can't drop items where the island that he is cooped.

**Comment by tastybento** [comment]
Can't replicate. I'll need more info to know what is going. Server/plugin version, etc. I tested with visitor item dropping disabled and then cooped someone - before coop, they couldn't drop, after they could.

**Comment by UnioDex** [comment]
I'm waiting response from players. I can't replicate too but players are complaining about that.

**Comment by UnioDex** [comment]
I can't take any response. If i take i will reopen.
