### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#51]
_From @tastybento on November 13, 2016 2:10_

I'm working on adding MySQL database storage in a branch.

_Copied from original issue: tastybento/askyblock#354_

**Comment by Poslovitch** [comment]
It is a well-wanted enhancement. I hope you will succeed !
Why don't name this update ASkyBlock v4.0.0?

**Comment by Poslovitch** [comment]
_From @tastybento on November 14, 2016 1:14_

Yes, I think it will be, but I'm still working on it. I'm planning on calling this a "pro" version too. :-)

**Comment by Poslovitch** [comment]
"Pro" ? Does it mean the plugin will be charged?

**Comment by Poslovitch** [comment]
_From @tastybento on November 14, 2016 17:5_

Maybe, to help for support. The plugin will always be free to download though.

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#54
