### ISSUE TITLE
ASkyBlock Addon

### ISSUE THREAD

**Issue by BunnyMagic** [tastybento/ASkyBlock-Bugs-N-Features#511]
Hello I would like you to make an add-on or something that lets the worldborder for ASkyBlock be different like the /worldborder set 10 but for every island to be like that it could be a premium add-on or public one

**Comment by tastybento** [comment]
Understood - I'm not adding functions to ASkyBlock now though, so this would need to be done by someone else.

**Comment by BunnyMagic** [comment]
Please I will pay ;'(

**Comment by UnioDex** [comment]
@BunnyMagic you can open a thread in those forums:
https://www.spigotmc.org/forums/hiring-developers.55/
http://www.mc-market.org/forums/mc-development/

tastybento does not make custom work as he wrote here:
https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#do-you-do-custom-work-for-s
