### ISSUE TITLE
Island ranges

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#512]
Hi, why island ranges must be multiples of 2? I converted my server from uSkyBlock and i was using 107 protection range. Now when i set 107 it automatically turning to 106 and players cant break distance blocks. 

If it really must be multiples of 2 i can set my protection range to 108 but my distance is 110 will it be a problem?

**Comment by tastybento** [comment]
It's because there's some divide by 2's in the code. We're changing it in BSkyblock.

The answer to the last question: not a problem.
