### ISSUE TITLE
Island level -> permissions

### ISSUE THREAD

**Issue by Dodlur** [tastybento/ASkyBlock-Bugs-N-Features#514]
I was wondering if there is a way to let people from that level to be able to do certain things.
For exemple, if I want people with an island level > 100 to be able to have permission for /fly or to make them having a prefix. (not the same that the {ISLAND_LEVEL} thing.

I was also wondering if there was a way to put the island name of players as a prefix.
if people use /island name "Island" so there would have Island as a prefix.

**Comment by tastybento** [comment]
Those would be possible to add using the API but are not built into the plugin.
