### ISSUE TITLE
Mac unable to open .yml files (Mac OS Sierra 10.12.6)

### ISSUE THREAD

**Issue by xTwistedMelonx** [tastybento/ASkyBlock-Bugs-N-Features#516]
When I try to open any of the .yml files on my Mac, it comes up with a popup saying unable to open file due to no permission, however I am an admin on my Mac and have infinite permission for everything. I phoned Apple and they said to contact you?

**Comment by tastybento** [comment]
.yml files are text files.

Download TextWrangler from the Mac AppStore and install it. Then right click (or use two fingers to click on the touchpad) on the .yml files and select Open with... then select Text Wrangler.
