### ISSUE TITLE
Visitors are able to switch any heads to skeleton skulls by using anvil

### ISSUE THREAD

**Issue by mikesonchan** [tastybento/ASkyBlock-Bugs-N-Features#518]
This is how it works: https://www.youtube.com/watch?v=if24XX2q0LU

**Comment by tastybento** [comment]
I'm not sure there's much I can do about this because it looks like a limitation with the server/API. But let me know what version of the server you are using and what version of the plugin.

**Comment by tastybento** [comment]
Okay, I replicated this on 1.12.2. I'll see if I can stop it. It may be impossible.

**Comment by tastybento** [comment]
Okay, I stand corrected - I fixed it!

**Comment by tastybento** [comment]
Thanks by the way!
