### ISSUE TITLE
Allow loss of items if death at spawn

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#52]
_From @tastybento on October 14, 2016 6:41_

if the config option "allowvisitorkeepinvondeath" is set to true players don't loose their inventory when visiting other's islands AND in spawn. Is there a way to make it so they keep inventory if they die while visiting other's islands but they loose it if they die in spawn? Because I have a PvP arena at the Skyblock spawn and the idea is players to actually loose their items if they die there, but I don't want to disable this entire feature because of trolls killing visitors with lava and stealing their items

_Copied from original issue: tastybento/askyblock#327_

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#53
