### ISSUE TITLE
[ASkyBlock] Plugin ASkyBlock v3.0.8.1 has failed to register events for class com.wasteofplastic.askyblock.listeners.IslandGuard1_9 because org/bukkit/event/entity/LingeringPotionSplashEvent does not exist.

### ISSUE THREAD

**Issue by filiperose** [tastybento/ASkyBlock-Bugs-N-Features#520]
help me
https://www.mx7.com/i/077/ybqUHq.png

**Comment by tastybento** [comment]
What version of the server do you have? (Do /version and paste the result). You probably have an old version.

**Comment by filiperose** [comment]
> my server is 1.9

**Comment by filiperose** [comment]
and i have new problem 
https://youtu.be/u-am_DIxu3o

**Comment by tastybento** [comment]
Pure 1.9 is not supported because it is missing this library. Can you update to 1.9.2 or later?

**Comment by tastybento** [comment]
Taking things out of the GUI's are usually due to another plugin interfering. Try with a server with just ASkyBlock and Vault running and confirm you cannot remove items. Then add plugins until the problem occurs.

**Comment by filiperose** [comment]
> Pure 1.9 is not supported because it is missing this library. Can you update to 1.9.2 or later?

i wanna open 1.9 - 1.11.2 skyblock server how can i do that?

**Comment by tastybento** [comment]
Install the latest Spigot (1.12.2) and then install ViaBackwards - https://www.spigotmc.org/resources/viabackwards.27448/
