### ISSUE TITLE
Lock the island will kick all NPC who on the island

### ISSUE THREAD

**Issue by NelsonHD** [tastybento/ASkyBlock-Bugs-N-Features#523]
My server is running on Spigot 1.12.2, ASkyBlock 3.0.7, Citizens 2.0.22. After i type "/is lock", the npc(s) who on my island will be disappear. Even i unlock the island, they wont appear again. How can i solve this ? :(
Thx for reading :)

**Comment by tastybento** [comment]
The NPC's are being considered as players and expelled from the island when it is locked. There is no workaround right now.

**Comment by Poslovitch** [comment]
There is one : Citizens add a metadata "NPC" to its entities. Check if the entity has it.

**Comment by tastybento** [comment]
Yes, I mean there's no workaround for the reporter until we check for the NPC metadata. :-)

**Comment by Poslovitch** [comment]
Oh okay :)
