### ISSUE TITLE
Schematic not working?

### ISSUE THREAD

**Issue by TewMuch** [tastybento/ASkyBlock-Bugs-N-Features#524]
Hello I am currently having an issue with the schematic I recently purchased one and put it into my schematic folder and the name is large.schematic and I put that into config. but it's not working it just instantly created the 1st island (I deleted the other 2) and when I deleted the default island and changed the schematic name to island.schematic it said there was an internal error if you have any suggestions it would mean a lot
[New Text Document (4).txt](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1435553/New.Text.Document.4.txt)

**Comment by tastybento** [comment]
Does the schematic have a bedrock block in it? It must have to show the center of the island.

You are also missing the schematic section at the bottom of the config.yml. Stop the server. Make sure your config.yml looks like this: https://github.com/tastybento/askyblock/blob/master/config.yml 
Place the new schematic in the schematic folder and rename it to island.schematic. The start the server. Then do /asadmin reload and see what it says.

**Comment by TewMuch** [comment]
It was the bedrock thanks for responding fairly quick!
