### ISSUE TITLE
/is warp internal error

### ISSUE THREAD

**Issue by Tyguh** [tastybento/ASkyBlock-Bugs-N-Features#526]
Hey, players and I are reciving an error when trying to /is warp to other's islands. Every of the other related commands work apart from /is warp.

Stack trace: https://hastebin.com/fibadaxivo.vbs
Warps.yml: https://hastebin.com/reworahibu.css
Server Version: Paperspigot 1.7.10
ASkyBlock Version: 3.0.8.1

**Comment by tastybento** [comment]
For some reason, when the plugin tries to get the name of the warp owner by using the UUID in warps.yml it gets a null. I don't know one of the players would have a null name. I recommend you take a copy of the warps.yml file and remove a line at a time and reload until the error stops. Then that line/player must be causing the issue. Let me know what happens.
