### ISSUE TITLE
Nether Islands not contained within protectionRange

### ISSUE THREAD

**Issue by fordross** [tastybento/ASkyBlock-Bugs-N-Features#529]
Using default values for island.distance and island.protectionRange of 200 and 100 respectively, when generating a new nether island the large island with the spawners is generated partially beyond the island's protection range, preventing players from placing or removing blocks on it, as well as from accessing one of the chests.

Installed new 1.12.2 spigot build with AcidIsland 3.0.8.1 to verify that this is an issue with default configuration and/or schema.

**Comment by tastybento** [comment]
Huh. Okay, somehow an alternative schematic got in there. That was just for testing. The correct schematic is attached. Alternatively, you can adjust the protection range to be bigger to allow access (give a default perm of acidisland.island.range.xxx where xxx is a number)
[nether.schematic.zip](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1449491/nether.schematic.zip)

**Comment by fordross** [comment]
Fantastic!  Thanks so much.

Only shame is that I rather liked the three island configuration.  I had considered expanding protection range, but could not figure out how to expand the nether island only (island sizes were set specifically to allow one beacon to blanket the whole island as well as keep chunks from unloading as long as you idle the centre), so expanding protection range was not my preferred solution).

Thanks again.
