### ISSUE TITLE
Add support for meta data to items in chests in schematics

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#53]
_From @tastybento on October 11, 2016 0:17_

_Copied from original issue: tastybento/askyblock#325_

**Comment by Poslovitch** [comment]
Do you still need help?

**Comment by Poslovitch** [comment]
_From @tastybento on March 27, 2017 14:44_

Yes, but this is extremely difficult. Maybe if it is only supported on 1.11.2 and onwards it may be possible.

**Comment by Poslovitch** [comment]
I'll have a look, but I don't think i'll do it for 4.0

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#52
