### ISSUE TITLE
ASkyBlock & AcidIsland locale hu coding problem

### ISSUE THREAD

**Issue by montlikadani** [tastybento/ASkyBlock-Bugs-N-Features#530]
Welcome!
There is a problem with the file ...
The problem is that you need to switch from **hu_HU.yml** from UTF-8 to **ANSI encoding**, because now I'm testing and getting it:
![kep](https://user-images.githubusercontent.com/30026208/32416945-e915f856-c251-11e7-8fc2-391e7a6a2f1d.png)
**Before you start: Copy the original messages and switch over to ANSI encoding if you have switched it to see if it has been rewritten. Insert and save.**

**Comment by HLF-Raideer** [comment]
@montlikadani you probably experiencing this issue when using Windows operating system.
Windows require to use your config files in ANSI encoding.

**Comment by montlikadani** [comment]
@HLF-Raideer 
This is true. I want you to switch to ANSI encoding.

**Comment by tastybento** [comment]
Hmm, I'll have to check this. All the yml files are currently globally set as UTF-8 and I'm not sure I can package just one in the JAR as ASCII.

**Comment by tastybento** [comment]
Hungarian was updated in 3.0.8.3. Hopefully that'll fix this.
