### ISSUE TITLE
Anvil use, crafting, furnace

### ISSUE THREAD

**Issue by iPanem** [tastybento/ASkyBlock-Bugs-N-Features#535]
Hi. I am having problem with island procetion. 

I've dissabled every single permission to island protection to false, yet they still have permission to steal from furnaces etc.

Also have removed EVERY SINGLE PERMISSION, and yet they still have a permission to somehow open the furnace, crafting table etc..

I need seriuous help, Thanks

**Comment by tastybento** [comment]
If you make a change in the config, you need to push that change out to all islands. Check the wiki for a FAQ. Use /asadmin settingsreset all.

**Comment by iPanem** [comment]
Thank you so much!
