### ISSUE TITLE
 /asadmin purge is in trouble!

### ISSUE THREAD

**Issue by iMufasa** [tastybento/ASkyBlock-Bugs-N-Features#540]
When the purge process begins the islands do not go in sequence 1 for 1 example of 100 goes to is 280, and is not erasing the 500 islands as it should be deleting on average 15 to 30 islands

**Comment by iMufasa** [comment]
I would like to solve these problem as it will fill my island server!

**Comment by tastybento** [comment]
Run the command in the console only. Set the number of days in the purge request to be a small number. Then let the serve complete the deletion. It can take a while even after the console says it is done.

What is your island distance and protection setting distance?

**Comment by iMufasa** [comment]
distance is 200 blocks
