### ISSUE TITLE
Challenge Required a custom item

### ISSUE THREAD

**Issue by EnObliO** [tastybento/ASkyBlock-Bugs-N-Features#542]
Hi,

I need to set a custom item as a "requiredItems" in the challenges list, but I have no idea on how can I do that. Can you help me with the syntax please ?

The first one is:
/give @p minecraft:end_portal_frame 1 0 {display:{Name:"Morceau de portail",Lore:["Mais quel est cet objet ?","Indispensable a la quête \"vers une nouvelle dimension\""]},Unbreakable:1,HideFlags:5,ench:[{id:0,lvl:1}]}

And the second one is:
/give @p minecraft:emerald_ore 1 0 {display:{Name:"Relique fragmentée",Lore:["Relique rare servant pour une des quêtes du /c"]},Unbreakable:1,HideFlags:5,ench:[{id:0,lvl:1}]}

Best regards, 
EnObliO

**Comment by tastybento** [comment]
This is not possible. It's possible to give custom items as a reward, but not require them.
