### ISSUE TITLE
Visitors can build

### ISSUE THREAD

**Issue by iPanem** [tastybento/ASkyBlock-Bugs-N-Features#543]
I have a huge issue. 

Visitors can build on islands, but not break blocks.
Also, Island members can build way out their island border.

Please help!

**Comment by tastybento** [comment]
There's very little info to go on here...

I assume you are using the latest plugin version.

Check your protection settings for the world and islands in config.yml. Then do /asadmin settingsreset all. See if that works.

If not, did you update or change your island distance in config.yml mid-game? If so, you will need to reset.
