### ISSUE TITLE
 the /asadmin purge command is in trouble is not erasing like 500 islands that should

### ISSUE THREAD

**Issue by iMufasa** [tastybento/ASkyBlock-Bugs-N-Features#547]
The /asadmin purge I use with the time of 60 days, more than a few days, it is not erasing the 500 islands and I have over 3000 inactive islands that I need to erase to free up space! I would like you to solve this problem because I need it a lot!
![screenshot_1](https://user-images.githubusercontent.com/33561045/32791274-cef989b8-c947-11e7-9f23-5c743ddb4845.png)
![screenshot_2](https://user-images.githubusercontent.com/33561045/32791275-cf2cf9d8-c947-11e7-827e-6ab18546c10e.png)
![screenshot_3](https://user-images.githubusercontent.com/33561045/32791276-cf5b252e-c947-11e7-88a6-4f8d2c4cf4a7.png)

**Comment by tastybento** [comment]
Try /asadmin purge 1 to confirm that a few can be done. Trying to do a lot of islands at once may not work because the server chokes.

**Comment by iMufasa** [comment]
Ok, I will try

**Comment by iMufasa** [comment]
It has not helped, it is erasing less than 500 islands. what do I do?

**Comment by tastybento** [comment]
Okay, try to reduce the number of islands to delete in one go to say 30. Try /asadmin purge 120 to only pick up islands > 120 days old.
