### ISSUE TITLE
New commands - comment if you think they're useful

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#55]
_From @tastybento on September 28, 2016 2:6_

Got this request:

/Is allow (Allows players to go on your island even if it's locked.) [Re-doing command disallows them again/This can also be /is disallow]
/Is banlist (Lists the players you have banned from your island)
/Is bans (lists the islands you are banned from)

_Copied from original issue: tastybento/askyblock#318_

**Comment by Poslovitch** [comment]
I totally agree!

**Comment by Poslovitch** [comment]
_From @SwiftSwamp on March 19, 2017 20:27_

Would love to see these added.

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#71
