### ISSUE TITLE
Trying to get the members on an island

### ISSUE THREAD

**Issue by ChrisIsANubDev** [tastybento/ASkyBlock-Bugs-N-Features#554]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.8

**Plugin version:**
3.0.6.9
**What other plugins are you using? (do /plugins and paste here)**
Non that'll effect this
**Description of issue. What happened?**
I'm trying to get the amount of members that are apart of an island - https://gyazo.com/ec1b5b82d0130e64f7805d0b14cf7298
**Steps to make this happen**

1.  Island.this.getMembers().size() (It doesn't work withought the .size() either)
2.
3.

**What do you think should happen?**
I think people should be able to access the things from the Island class in the ASkyBlockAPI

**Comment by tastybento** [comment]
That is incorrect Java, sorry. Island is not a static class so you don't use it that way. You need to obtain an island object first, for example by the owner's UUID or the island location. Then you can get the members for the island. Like this:

```
ASkyBlockAPI api = ASkyBlockAPI.getInstance();
        Island island = api.getIslandOwnedBy(playerUUID);
        getLogger().info("Number of island team members: " + island.getMembers().size());
```

**Comment by ChrisIsANubDev** [comment]
Thank you so much! I'm pretty new to Java. I was just creating a scoreboard for my skyblock server! 
Thanks for the support 👍
