### ISSUE TITLE
Island Crash

### ISSUE THREAD

**Issue by MaximumDesigns** [tastybento/ASkyBlock-Bugs-N-Features#555]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**1.12.2**

**Latest.**

**Plugins (68): AcidIsland, ActionAnnouncer, AdvancedPortals, APT, ASkyBlock, AsyncWorldEdit, AsyncWorldEditInjector, BannerBoard, BossShopPro, BungeeTabListPlus, ChatColorGui, ChatControl, ChatReaction, ChopTree3, Citizens, CitizensCMD, ClearLag, ClientStats, CoreProtect, CrateReloaded, CrazyAuctions, DeluxeChat, DeluxeJoin, EasyBackup, Emotes, EnjinMinecraftPlugin, Essentials, EssentialsSpawn, Firework, HeadDatabase, HolographicDisplays, HungerKeeperPlus, ItemShops, LibsDisguises, LockettePro, LuckPerms, MGDeathRun, MinigamesLib, Multiverse-Core, MyCommand, NametagEdit, NoCheatPlus, PetBlocks, PlaceholderAPI, PlugMan, PointsAPI, ProQuests, ProtocolLib, ProtocolSupport, ProtocolSupportLegacySupport, ProtocolSupportStuff, Shop, SkyChests, SkyGlobalChat, Skywars, SSKits, SuperTrails, TitleManager, UltraCosmetics, VanishNoPacket, Vault, ViaBackwards, ViaVersion, VoteParty, Votifier, WorldBorder, WorldEdit, WorldGuard**

**Everytime a user goes near a monster on their island, the user crashes [05:55:46] [Server thread/INFO]: - lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown mob network type id -1.**

**Steps to make this happen**

 - Not sure.

**What do you think should happen?**

It shouldn't crash.

**Comment by tastybento** [comment]
Please see this:
https://github.com/CitizensDev/Citizens2/issues/1260

The issue is ViaVersion and Citizens are incompatible sometimes.
