### ISSUE TITLE
TPS Issues

### ISSUE THREAD

**Issue by bjunited** [tastybento/ASkyBlock-Bugs-N-Features#557]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
Spigot 1.12.2
**Plugin version:**
Most recent
**What other plugins are you using? (do /plugins and paste here)**
WorldEdit, VoidGenerator, Vault, Essentials, Essentials Spawn, Group Manager, EssentialsChat, WorldGuard, ASkyBlock, Multiverse-Core
**Description of issue. What happened?**
Very low TPS when using the plugin. 
**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**

**Comment by Poslovitch** [comment]
Can you send us a timings report?

**Comment by bjunited** [comment]
Hey!

Thanks for the speedy response. How would I go about doing that? Is it just /tps ?

**Comment by Poslovitch** [comment]
Do the following : 
1. /timings on
2. Wait at least 10 minutes. The more you wait, the more the timings results will be representative.
3. /timings paste
4. Copy here the link that it gave to you
5. /timings off

**Comment by bjunited** [comment]
https://timings.spigotmc.org/?url=kukuqorilu

**Comment by tastybento** [comment]
@bjunited The timings report you gave was 17 seconds long. You need to use the server for about 5 or 10 minutes and then submit the port report.

**Comment by bjunited** [comment]
I found out the issue, ended up being a failing disc drive on my hosts end.
Thank You anyway for the support
