### ISSUE TITLE
Fly setting

### ISSUE THREAD

**Issue by Nedjii** [tastybento/ASkyBlock-Bugs-N-Features#558]
Can you please add a new setting ? I would like a setting that deny ppl to fly on your island, thanks.

**Comment by tastybento** [comment]
Sorry, we're not accepting feature requests.

But, in this case, the built-in islandfly permission only works for players on their own island. Visitors shouldn't be able to fly. Now, if they are using essentials fly, then there's not much I can do about that.

**Comment by Nedjii** [comment]
How am i supposed to fly with the askyblock.islandfly permission ? it's not
actually working with /fly or /is fly so i don't know.

2017-12-05 1:18 GMT+01:00 tastybento <notifications@github.com>:

**Comment by Nedjii** [comment]
Ok i see how it's working, my bad but i need it to work in the nether and
i'm not using is nether, that's why i'm using essentials fly.

2017-12-05 7:57 GMT+01:00 jauffrey giraud <jauffrey.giraud@gmail.com>:
