### ISSUE TITLE
Support - Message Announcement and Permissions

### ISSUE THREAD

**Issue by bjunited** [tastybento/ASkyBlock-Bugs-N-Features#559]
Hello,

I am wondering how I stop it announcing that a player has completed a challenge to everyone on the server. Also, how to change permissions to not be default so I can manually assign them to the ranks. 

Thank You Very Much!
- Ben

**Comment by bjunited** [comment]
Hello, 

I am having two issues. I am still unable to figure out how to stop permissions from being Default. Also I am now having issues with the range permission. I have the permission "askyblock.island.range.50" added to my default group. And my players are still able to build to the full 400 blocks I have specified in the configuration. 

Thank You!
- Ben

**Comment by bjunited** [comment]
Seem to have got it working, I am adding the permission to the user askyblock.island.range.70, and made the config file have a range of 50. But I seem to have to make people relog, is that the case. Or is there a command to do this when creating an upgrade menu system?

**Comment by tastybento** [comment]
There's a setting in challenges.yml to stop challenge completion announcements.

Players will need to relog to have the perm change their island setting, yes.
