### ISSUE TITLE
How to set PVP per Island

### ISSUE THREAD

**Issue by Max604** [tastybento/ASkyBlock-Bugs-N-Features#560]
Hello, I know it is possible to set pvp globally for every island.

Is there a way for users to turn pvp just on for their specific island?

Thanks,
Max

**Comment by Poslovitch** [comment]
Give them access to the PVP setting using config.

Read comments in config.yml for more information.

**Comment by Max604** [comment]
"Give them access to the PVP setting using config."

That boolean setting changes the default true/false value for all newly created island. I already added the perm askyblock.settings.* and askyblock.settings.pvp to allow them to set pvp settings in /is settings but it still does not appear there.

**Comment by Poslovitch** [comment]
As it is written in config.yml, l.781

```yaml
# -- Island Settings --
   # Settings for islands. Some are for visitors, some for the island itself.
   # If setting is not listed, it will not show in GUI and the world default will be used.
   # Add settings here to give the player the ability to see them in the GUI. Give the
   # player the permission for the setting for them to be able to change the setting.
island:
```

**Comment by Max604** [comment]
Thank you! Didn't get it at first because we had to add the PVP line ourselves. Bit confusing, but all good now!

Thanks.

**Comment by Poslovitch** [comment]
It was nice helping you. :)
