### ISSUE TITLE
custom Schematic chest in Item Name and enchant.

### ISSUE THREAD

**Issue by tarak5371** [tastybento/ASkyBlock-Bugs-N-Features#561]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12.2

**Plugin version:**
V3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**
AskyBlock

**Description of issue. What happened?**
Please understand my poor English.
I made schematic and I made my own item in chest
The name of the item I set is the name of the item, but it is returned to the default value.
item name and enchantment All

**Steps to make this happen**

1. Creating a schematic, chest in my custom item Put.
2. Askyblock setting and open server
3. /is command Input next open chest
4. wow! my where did I set up? Go back to the default value

**What do you think should happen?**
Should be fix this

**Comment by tastybento** [comment]
The schematic paster we use is simple and does not support this, sorry.

**Comment by tarak5371** [comment]
why does not support this?
schematic can't save itemmeta? or itemmeta schematic paster is hard task?

I think this is pretty important feature

**Comment by Poslovitch** [comment]
Then it should go to BSkyBlock.
