### ISSUE TITLE
uuid problem

### ISSUE THREAD

**Issue by projay11** [tastybento/ASkyBlock-Bugs-N-Features#562]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version: 1.8**

**Plugin version:latest**

**What other plugins are you using? 
RankVouchers, CustomOreGen, PlugMan, FakeTrollPlus, AdvancedPets, OreGenerator, AdvancedLogger, TimePlayed, ChatReaction, MultiWorld, SuperTrails, ViaVersion, BetterAlias, CoreProtect, WorldEdit, AdminFun, OpenInv, Essentials, ClearLag, UltraLogger, ChatControl, BuycraftX, MessageAnnouncer, Votifier, KitAdder, iDisguise, EssentialsChat, TrollCommandsPlusPlus, PermissionsEx, FeatherBoard, CustomCrates, UltraCommand, AntiBotAttack, Vault, GAListener, Admin360, SimpleRename, HolographicDisplays, SignShop, WorldGuard, ASkyBlock, Duels, PlayerVaults, EssentialsSpawn, LiteBans, SilkSpawners, SkyBlockOreGen, CrazyAuctions, Pets, SuperVanish, ChestShop, ShopGUIPlus)**

**Description of issue. What happened? The uuid for one player is messed up on /is top it doesnt display their name. In the players folder when i click on the uuid where it says playername it just says their uuid and even if i change this it has no effect in game**

**Steps to make this happen**
No steps, it didnt it auto.
**What do you think should happen?**
I need some help on a way of fixing this might be something in the plugin but not sure why it is only happening with one person

**Comment by tastybento** [comment]
Have a look at the top ten config file in the ASkyBlock folder. It's called topten.yml. You may want to remove the weird line and then do /asadmin level <their name> to recreate their entry.
