### ISSUE TITLE
Every three seconds the water is trying to cite, but it is canceled

### ISSUE THREAD

**Issue by montlikadani** [tastybento/ASkyBlock-Bugs-N-Features#565]
The problem is that every 3 seconds the water you are trying to cite is effected, but it is canceled. **Check out the GIF all the way!**

**Server version:** 1.12

**Plugin version:** I do not know because I found it on a server

**plugins:** I can not list because I'm on a server

**GIF:**
https://media.giphy.com/media/xT0xeASYHh3d91IFW0/giphy.gif

**Comment by tastybento** [comment]
I don't know what this is and I don't think it's anything to do with ASkyBlock. If the server owner thinks it's a problem tell them to file a bug report. Thanks!

**Comment by montlikadani** [comment]
But it's not an ASkyBlock plugin, it's AcidIsland.

**Comment by Poslovitch** [comment]
ASkyBlock = AcidIsland, and AcidIsland = ASkyBlock. Same code, only one variable changes.

**Comment by tastybento** [comment]
@montlikadani By the way, what does "the water you are trying to cite" mean? I think Google Translate did not work well there. Can you ask in your own language? "cite" is a very strange verb.

**Comment by montlikadani** [comment]
@tastybento 
Oh, sorry.
So, try to play a bubble effect, but stop it.

**Comment by tastybento** [comment]
Okay, I understand. Actually AcidIsland does not do any animations of the water. Maybe it’s a server side texture pack or something.

**Comment by montlikadani** [comment]
This water effect has also happened on my own server and I used the latest version, but the same problem. It can not be the problem that acid water generates some effect in a small place?

**Comment by tastybento** [comment]
No, we really do nothing to water animations. Nothing at all.

**Comment by montlikadani** [comment]
Then I do not know what the problem is. There may be something wrong with Minecraft 1.12.
