### ISSUE TITLE
Vanish support

### ISSUE THREAD

**Issue by voodootje0** [tastybento/ASkyBlock-Bugs-N-Features#567]
If you're vanished (Essentials vanish) players can still see that you are online by doing ``/is coop <username>``. Would be great if you add support, so it displays the player is offline while the player is in vanish.

**Comment by Poslovitch** [comment]
This bug should have been fixed in 3.0.6.X.

We'll investigate that.

**Comment by tastybento** [comment]
I cannot replicate this on the latest version. Everything works great. @voodootje0 What version are you using?
