### ISSUE TITLE
Bypass permissions

### ISSUE THREAD

**Issue by voodootje0** [tastybento/ASkyBlock-Bugs-N-Features#568]
Currently, there are 3 bypass permission (askyblock.mod.bypassprotect, askyblock.mod.bypassexpel and askyblock.mod.bypasslock).

The issue we are experiencing is that ``askyblock.mod.bypassprotect`` will give all island protection bypass, from pvp to destroying blocks. The thing is that we only want moderators to break blocks (to remove sign shops) and not to let them pvp others on islands. 

Would it be possible to add some new permissions so that you can specify the island protection what should be bypassed? Or at least add a flag for only breaking blocks.

**Comment by Poslovitch** [comment]
This is a feature request, not a bug report. Please repost it there : https://github.com/tastybento/bskyblock/issues.

As said in the README of this repository : 

> ASkyBlock & AcidIsland Issues
> This repository is for handling issues related to ASkyBlock or AcidIsland.
> Feature Requests
> ASkyBlock is NO LONGER ACCEPTING FEATURE REQUESTS
> File all feature requests on BSkyBlock: https://github.com/tastybento/bskyblock/issues
