### ISSUE TITLE
Players able to fly after dying

### ISSUE THREAD

**Issue by PaulHotel** [tastybento/ASkyBlock-Bugs-N-Features#570]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

1.12.2

3.0.7

Whenever a player dies who has the flight permission they can fly in spawn. If they do /spawn they can't. **Spawn is in a separate world**

1. Give player askyblock flight permission
2. Go to island
3. Die in game
4. Try to fly 

**What do you think should happen?**
The player shouldn't be able to fly.

**Comment by tastybento** [comment]
Do you use Essentials Spawn plugin? I just want to set up my server like yours so I can check it.

**Comment by PaulHotel** [comment]
Yeah and Mutiverse

Sent from my iPad

On Dec 11, 2017, at 8:48 PM, tastybento <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you use Essentials Spawn plugin? I just want to set up my server like yours so I can check it.

**Comment by tastybento** [comment]
I can't replicate on 3.0.8.2 (or 3.0.7). Weird. Are you using spigot? Can you share your config.yml? (Zip it up and drag and drop into the reply box.

**Comment by tastybento** [comment]
Closing, no answer.
