### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by DerpDays** [tastybento/ASkyBlock-Bugs-N-Features#573]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.7.10 Thermos
**Plugin version:**

**What other plugins are you using? (do /plugins and paste here)**
Plugins (31): Itemizer, ForgottenGUI, WorldEdit, GroupManager, ClearLag, IP-Check, AdvancedBan, BuycraftX, Votifier, ProtocolLib, WorldGuard, ChatReaction, MVdWPlaceholderAPI, cShortcut, FeatherBoard, ServerListPlus, Vault, GAListener, ChatColor, Essentials, HolographicDisplays, Citizens, AuctionHouse, EssentialsXMPP, ASkyBlock, EssentialsProtect, EssentialsGeoIP, EssentialsChat, CommandNPC, EssentialsSpawn, CratesPlus
**Description of issue. What happened?**
Server crashes on island creation or tping to the world and portals dont work in the world
**Steps to make this happen**

1. TP Into the world/Make a island
2. Timed out
3. Server restarts

**What do you think should happen?**
Should work normally i used the plugin before it just doesnt work on this atm.

**Comment by tastybento** [comment]
What plugin version? Latest? paste a copy of the crash report too (use pastbin or something).

**Comment by DerpDays** [comment]
Version: Latest
Crash Report: Pastebin to big Im going to upload the log.gz as it wont let me upload the .log file
[2017-12-18-1.log.gz](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1569354/2017-12-18-1.log.gz)

**Comment by DerpDays** [comment]
I also did some testing and the server still crashes with
EssentialsX, Groupmanager, Vault, Askyblock
d

**Comment by tastybento** [comment]
The crash is occurring when BenjiK03 does an island reset and the crash is caused by a line where it tries to get a chunk in BenjiK03's old island. How big are the islands? How big is the protection area? Upload your config.yml. 

Also, by the way, you are getting a lot of Essentials errors. It looks like it isn't compatible with that older server version.

**Comment by DerpDays** [comment]
It's not just BenjiK03 its when we reset our islands as well islands are The ozone 2 garden of glass islands
and the protection area is 10000 and the islands are 5000  i tryed it without plugins and it still crashed


config: https://pastebin.com/8e5h4DPJ


i put on my test server only askyblock and vault and the server crashed in the same way the log is here

[latest.log](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1575381/latest.log)

**Comment by Poslovitch** [comment]
Wow, these are really, really, really huge values.
I mean, did you ever try to //cut a 5000*5000*256 area with WE? Crashing is the logical outcome of such an area check.

Try reducing your settings to more decent values. Island distance should not exceed 1000, I think.

**Comment by DerpDays** [comment]
ok ill reduce them

**Comment by tastybento** [comment]
Yes, this is the problem. The islands are too big.

**Comment by tastybento** [comment]
And by islands I mean protection size.

**Comment by tastybento** [comment]
Great!
