### ISSUE TITLE
Plugin Not Loading

### ISSUE THREAD

**Issue by ColorbombArtz** [tastybento/ASkyBlock-Bugs-N-Features#575]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:** Spigot 1.12.2 @ Java 8

**Plugin version:** V3.0.8.2

**What other plugins are you using? (do /plugins and paste here)** ItemEditor, SimpleCommandBlocker, WorldEdit, AdminFun, Essentials, PlaceholderAPI, VeinMiner, InstantHit, AutoSmelt, PerWorldPlugins, ClearLag, AdminPlayerMenu, CreateYourOwnMenus,  EpicRename, Scoreboard, NametagEdit, BuycraftX, ProtocolLib, WorldGuard, Multiverse-Core, LibsDisguises, LockettePro, IPortal, VoidGenerator, EssentialsGeoIP, EssentialsChat, TrollCommandsPlusPlus, PermissionsEX, PlayerVaults, MyCommand, ChatClor, LegendaryMessages, KitsCreator, CustomTab, Holographic Displays, SilkSpawners, CratesPlus, HolographicExtension, MinigamesLib, MGSkyWars

**Description of issue. What happened?** I downloaded askyblock,jar and put it in my plugins folder, when I restarted my server, it appeared that the plugin was not in my server.

**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?** The plugin should load.

**Comment by ColorbombArtz** [comment]
Logs: https://pastebin.com/raw/kQBddz8k

**Comment by Poslovitch** [comment]
Download and install Vault.
