### ISSUE TITLE
ASkyBlock ERROR

### ISSUE THREAD

**Issue by AirCraze** [tastybento/ASkyBlock-Bugs-N-Features#576]
when players make a island they can't build on it
it says island is protected even though they are the owner of it

Answers:
Errors in console = no
Messages to players = Island is protected

**Comment by Poslovitch** [comment]
Please provide your config.yml and your logs

**Comment by tastybento** [comment]
I just answered something on Spigot that looks the same so I'm closing for now. If not, reopen.
