### ISSUE TITLE
Island setrange bug

### ISSUE THREAD

**Issue by Zalbus** [tastybento/ASkyBlock-Bugs-N-Features#579]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

Server Verison: 1.8 

**Plugin version:** Most recent

**What other plugins are you using? (do /plugins and paste here)** https://gyazo.com/cc9c1a7a56650166295a7dad4605e266

**Description of issue. What happened?**
Basically whenever you do /is setrange (range) After the player logs off it goes back to default

**Steps to make this happen**

1. get a default player (non op)
2. /is setrange (range) on there island
3. tell them to log off
4. Tell them to log back on
5. boom, it's back to normal and if they build there it will be unplaceable or mineable.

**What do you think should happen?**

? You fix it?

**Comment by Poslovitch** [comment]
Aside the disrespect,

1. /is setrange doesn't exist
2. do the island leader have a protection range permission?

**Comment by Zalbus** [comment]
Aside that there is no disrespect,


(Asadmin setrange) - Sorry my bad

I have added the permission and it's fixed now. Thank you.
