### ISSUE TITLE
[Request/fix] When you kick anyone their items will be dropped.

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#58]
_From @voodootje0 on July 28, 2016 2:40_

Dear,

When you kick anyone from your island, their items will be dropped on the island. So the player that leaves the island will lose his items. Could you make a config option to enable and disable this?
- voodootje0

_Copied from original issue: tastybento/askyblock#277_

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#43
