### ISSUE TITLE
 Problem with the challenges!!

### ISSUE THREAD

**Issue by seb962** [tastybento/ASkyBlock-Bugs-N-Features#581]
hello, the menu of the challenges works but the challenges in itself when clicking it does not work, it does not show an error or something similar, since I saw in other servers that the challenges work, I do not know because in my case it does not give can you help me, please!!

![2017-12-28_08 23 51](https://user-images.githubusercontent.com/34877907/34412067-e3f9a4be-eba8-11e7-9da5-dd93bdf09407.png)

**Comment by tastybento** [comment]
I suspect it's another plugin interfering with the clicking. Remove other plugins one by one until it works.
