### ISSUE TITLE
How to add description for your is warp

### ISSUE THREAD

**Issue by Kinert** [tastybento/ASkyBlock-Bugs-N-Features#582]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**1.8

**Plugin version:**latest

**What other plugins are you using? (do /plugins and paste here)**ony askyblock

**Description of issue. What happened?**How to add description for your is warp

**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**How to add description for your is warp

**Comment by tastybento** [comment]
Write text on the welcome sign. :-)
