### ISSUE TITLE
[Bug] Topten

### ISSUE THREAD

**Issue by Typheonn** [tastybento/ASkyBlock-Bugs-N-Features#584]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12.1

**Plugin version:**
3.0.8.2

**Description of issue. What happened?**
Players can steal heads on topten board.

**Comment by tastybento** [comment]
Hi - do you know what key combo they use? If you click on a head can you just take it?
The code is very simple so I don't know why it wouldn't be cancelling. Usually this is from another plugin interfering.
