### ISSUE TITLE
Spawner schematics problem (modded 1.7.10)

### ISSUE THREAD

**Issue by mkrtes** [tastybento/ASkyBlock-Bugs-N-Features#586]
**Server version:**
modded Thermos-1.7.10

**Description of issue. What happened?**
Nether island schematic create with default pig spawner, but I save it with blaze/pigzombie spawners. WorldEdit copy/paste work correct. 
How can this problem be solved?

**Comment by Poslovitch** [comment]
1.7.10 is officially not supported by ASkyBlock as of 3.0.5.+.

The only thing we can do for you to get all the features fully working is recommending you to switch on a newer Minecraft version.

**Comment by mkrtes** [comment]
Problem was solved on version 3.0.5.5
I think the older version uses a different method of working with schems. The same thing happened with WE.

**Comment by Poslovitch** [comment]
Is your problem solved?

**Comment by mkrtes** [comment]
Yeah. Closed.
