### ISSUE TITLE
People can break another islands blocks

### ISSUE THREAD

**Issue by TheModz01** [tastybento/ASkyBlock-Bugs-N-Features#587]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.8.8
**Plugin version:**
V3.0.8.2
**What other plugins are you using? (do /plugins and paste here)**
https://gyazo.com/996e286cb2daad184c27fb38a73731ba
**Description of issue. What happened?**
People can brean another island blocks, and they doesn't have any permission
**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**

**Comment by Poslovitch** [comment]
Can you please send us your config.yml as well as the permissions your players are given?

**Comment by TheModz01** [comment]
Config.yml: https://hastebin.com/oribeqemob.php

Permissions.yml: https://hastebin.com/nagivedobu.php

**Comment by tastybento** [comment]
Oops. This is a bit old.

Are you still having this issue? If you made a config change to protections, then you should do **/asadmin settingsreset all** to push out the change.
