### ISSUE TITLE
Make reset number depend on a permission

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#59]
_From @tastybento on July 22, 2016 6:24_

For example, if player has askyblock.resetlimit.10, they can reset up to 10 times.

_Copied from original issue: tastybento/askyblock#273_

**Comment by Poslovitch** [comment]
It should be the last thing to do for 3.0.5 :D

**Comment by Poslovitch** [comment]
_From @tastybento on December 6, 2016 22:35_

Let's move to 3.0.6 so we can release 3.0.5.

**Comment by Poslovitch** [comment]
_From @tastybento on March 6, 2017 3:56_

Moving out of 3.0.6.

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#81
