### ISSUE TITLE
Problem with Skyblock/Acidisland and Player UUID's

### ISSUE THREAD

**Issue by TerestraEU** [tastybento/ASkyBlock-Bugs-N-Features#590]
Serverversion: 1.12.2
Server: PaperSpigot
Pluginversion: latest

Hello,

I found a little problem on my server, most likely due to your plugins "ASkyBlock" and "AcidIsland". I saw through everything in the config, but found nothing.
My UUID and that of the other players are stored in my permission system, but a second one is always added as soon as someone switches to SkyBlock or AcidIsland. See the screen: http://prntscr.com/hwl18y
I would therefore ask you to fix this, because otherwise we can not use your two plugins, even if we would like to :/ Unfortunately, it is completely excluded that this error is caused by other plugins.
Hope for an answer and thank you in advance.

Sincerely

**Comment by tastybento** [comment]
Fixed on Spigot PM. Was a PaperSpigot issue.
