### ISSUE TITLE
Nether world island bug

### ISSUE THREAD

**Issue by SirKappa** [tastybento/ASkyBlock-Bugs-N-Features#592]
**Server version: **1.12.2**

**Plugin version: **V3.0.8.2**

**What other plugins are you using?
**IMG**: https://ibb.co/kUdrgb

**Description of issue. What happened?: 
**After some time, players teleport to hell not on their island, but on a stranger.
It's only in nether world.**

Steps to make this happen

1. **Teletort to nether island**
2. **Wait for some time**
3. **When teleporting back, the island is not yours.**

**Comment by tastybento** [comment]
In step 3, "the island is not yours." <- which island? The overworld or the nether island? 
Do you mean that you teleport to the wrong place? Or that the island ownership is lost?

**Comment by SirKappa** [comment]
The portal has entered the alien island, but the players also could find their islands and continue to play on them, but the portal from the usual world leads again to a strange island.

**Comment by tastybento** [comment]
What is the island distance?
Please give coordinates of:

1. Location of the nether portal
2. Location of the exit portal (in the over world)
3. The location of the player's island

Thanks.
