### ISSUE TITLE
Not working at all ?!

### ISSUE THREAD

**Issue by AllKevinPlayz** [tastybento/ASkyBlock-Bugs-N-Features#593]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:** 1.12.2

**Plugin version:**ASkyBlock V3.0.8.2 | Nov 5, 2017 | 1.12,

**What other plugins are you using?
![image](https://user-images.githubusercontent.com/35208243/34657611-ab6c9200-f3dc-11e7-9b05-48f93b10da20.png)
**

**Description of issue. What happened?** Nothing worked at all i tried the video it still wouldn't work please help

**Steps to make this happen**

1. Hop on to my server PicklePvP.mcpro.io
2.try command
3. Nothing worked

**What do you think should happen?** It should work LoL
![capture](https://user-images.githubusercontent.com/35208243/34657623-e628a23a-f3dc-11e7-8477-3c92eb8145fe.PNG)

**Comment by AllKevinPlayz** [comment]
Please help asap

**Comment by tastybento** [comment]
Install Vault? It's required.

**Comment by AllKevinPlayz** [comment]
thank you
i will try
Your A Great Responder
