### ISSUE TITLE
Multiple Island Permission

### ISSUE THREAD

**Issue by RavaPollo** [tastybento/ASkyBlock-Bugs-N-Features#594]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version: 1.12.*

**Plugin version: 3.0.8.2

**What other plugins are you using? (do /plugins and paste here) http://prntscr.com/hxhvef

**Description of issue. What happened?** Can't remove the original island in /is

Suggestion/Question

Hi, 
So i have a problem where i can't get rid of the original island. it isnt in my config or anything but shows up. http://prntscr.com/hzrvob is what it looks like. Here is my config.yml https://pastebin.com/DNf4mgzr. I just want it so there is 4 islands. Also is it possible to put glass in like first few slots, andhave the islands in the 5th 6th etc, it looks better

Thanks,
RavaPollo

**Comment by tastybento** [comment]
Duplicate #599
