### ISSUE TITLE
Custom Islands

### ISSUE THREAD

**Issue by AngelStoyanov3** [tastybento/ASkyBlock-Bugs-N-Features#595]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
Spigot 1.8.8
**Plugin version:**
V3.0.8.2
**What other plugins are you using? (do /plugins and paste here)**
ViaVersion,aSkyBlock,Vault
**Description of issue. What happened?**
Can't use custom islands. I setted some islands that i've build and now i can use them. I tried to add them in the schematics folder and then replace in the config and it spawns me the default one. I've tried to replace the original island.schematic and know "The Original One" disappeared. I need your help.
**Steps to make this happen**

1. Add schematics in the schematics folder
2. Replace in the config
3.

**What do you think should happen?**
To Spawn DIfferent "Custom Islands"

**Comment by tastybento** [comment]
What does the console say?
Do /asadmin reload and look. I suspect your schematic doesn't have a bedrock block in it.
