### ISSUE TITLE
Challenges not working

### ISSUE THREAD

**Issue by FergusG123** [tastybento/ASkyBlock-Bugs-N-Features#596]
Server version: 1.8

Plugin version: 3.0.8.2

Plugins (54): HeadGUI, PlaceholderAPI, DeluxeJoin, DeluxeCommands, Arconix, vote_gui, ViaVersion, WorldEdit, TimTheEnchanter, Skript, Essentials, AutoSmelt, ClearLag, MessageAnnouncer, BuycraftX, Votifier, ProtocolLib, NightVision, NoCheatPlus, KitAdder, EssentialsChat, PermissionsEx, FeatherBoard, SkyblockOres, GAListener, Vault, OreGeneratorRevolution, UEAntiTab, CrazyCrates, WorldGuard, AuctionHouse, ASkyBlock, ActionAPI, EssentialsSpawn, TitleManager, PNCP, Jobs, Banknotes, LiteBans, SilkSpawners, Multiverse-Core, VoidSpawn, Citizens, TradeMe, KitPreview, DeluxeMenus, UltimateCasino, TAB, StackMob, ChestShop, HolographicDisplays, LeaderHeads, CommandNPC, ShopGUIPlus

The challenges are not working. I have got the requirements to complete it so I do /c and click on the challenge and nothing happens

I should be able to complete the challenges

**Comment by tastybento** [comment]
Not enough info. Which challenge? Did you customize them?

**Comment by FergusG123** [comment]
None of them are working and I have only customized the messages

**Comment by tastybento** [comment]
Okay, in that case, it is very likely another plugin is interfering with the GUI click. I recommend you remove plugins one by one (temporarily) until it starts working. Start with plugins that have GUI's or menus first because those are the most likely perpetrators.

**Comment by FergusG123** [comment]
Okay will do, thanks
