### ISSUE TITLE
Custom Nether Island Spawnblock problem

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#60]
_From @BiGUNMAN on July 5, 2016 2:18_

Hi, I recently setup a custom nether island but I seem to be spawning in a completely different area other then the configured spongeblock (there is only 1 spongeblock in the schematic, and it does get replaced with air, but the player (or atleast I when testing it) did not spawn where the sponge block was in the schematic. I'm in a completely different area.

Here's my config:
http://pastebin.com/pDdjmF8c

_Copied from original issue: tastybento/askyblock#262_

**Comment by Poslovitch** [comment]
_From @tastybento on July 5, 2016 5:48_

That is correct behavior. The SPONGE is only for the original starting island. So, if the nether island was visible as a choice, then players could start in the nether and they would start at the block. If the player just teleports to the nether, they will arrive at a "safe spot" near to the center of the island. If they build a portal in the nether and light it, they will teleport to that portal exactly.

**Comment by Poslovitch** [comment]
_From @BiGUNMAN on July 5, 2016 16:7_

Is there any way to specify exactly where the player should spawn when they first enter the nether without using bedrock? The nether island I constructed uses bedrock preventing me from using the center bedrock block to get the player in any good spawn location.

**Comment by Poslovitch** [comment]
_From @tastybento on July 6, 2016 14:24_

Not right now. You might try using a portal in the schematic. That may work.

**Comment by Poslovitch** [comment]
_From @BiGUNMAN on August 2, 2016 2:8_

I've tried making an island with a portal. Same results as before without portal.

**Comment by Poslovitch** [comment]
_From @tastybento on August 2, 2016 5:25_

If you have an active portal in the nether and a player goes through a portal in the overworld, they should appear in the nether portal. That's what I meant.

**Comment by Poslovitch** [comment]
_From @BiGUNMAN on August 2, 2016 21:44_

Yes, I've created an active nether portal in the nether schematic and saved it. Does not work. Their does seem to be a problem where when the schematic gets pasted the portal doesn't get pasted, which may be why it doesn't use the portal.

**Comment by Poslovitch** [comment]
_From @Steev93 on September 6, 2016 6:32_

~ Following

I have noticed this issue also. that when you do go through the portal you spawn anywhere in that area not the "Spawn_Point" in the Config.

**Comment by tastybento** [comment]
@BiGUNMAN 
@Steev93 
Done in 3.0.6.10
