### ISSUE TITLE
Set island Distance problem

### ISSUE THREAD

**Issue by EvoGR** [tastybento/ASkyBlock-Bugs-N-Features#600]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:*1.8.8*

**Plugin version:*V3.0.2.1*

**What other plugins are you using? (do /plugins and paste here)**

**Description of issue. What happened?**
I have delete the island yml to change the island protection from 100 to 150 blocks . I make it some how and after some minutes that's have come to console after i type to console asadmin info : Make sure you set island distance. If upgrading, set it to what it was before. . And also players in game they cant do /is
. How to fix it ? . Thanks in advance .  Please contact me asap . 

**Steps to make this happen**

1. I change the island protection from 100 to 150
2. I restart the plugin 
3. I delete the island.yml
4. I restart the server
**What do you think should happen?**
I don't have idea .

**Comment by tastybento** [comment]
Follow the reset instructions here:

https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#how-do-you-completely-reset-the-plugin

You haven't fully deleted everything.
