### ISSUE TITLE
High CPU usage!

### ISSUE THREAD

**Issue by Doc4oRHeaL** [tastybento/ASkyBlock-Bugs-N-Features#601]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:** - 1.10.2

**Plugin version:** - 3.0.8.

**What other plugins are you using? (do /plugins and paste here)** - AreaShop, ArmorStandTools/Edit, askyblock, auction haus, betterbowtrails, chaiitem, chestshop, chunkspawnlimiter, citizens, clearlag, crazy crates, dailybonus, custompayloadfixer, essentials, skript, featherboard, fastasyncworledit, healthbar, hidestream, holographicdisplay , kitpreview, leaderheads, multivers-core, nocheatplus, permissionex, playerparticles, protocolib , protocolsupport , safetrade , shopguiplus, shopkeeperes, simpleapi, simplepets, treasurechest, worldedit, worldguard, ushop

**Description of issue. What happened?** - Hi, sorry for my english.
I have server based on aSkyBlock plugin, everytking was ok, but since 5 days i have problem with HIGH CPU usage on my VPS, when i delete plugin aSkyBlock CPU is ok but when i load aSkyBlock plugin CPU is ~300%. I try create new config files or locale files but problem is still.

When i delete PLAYERS data folder bug is fixing.. Maybe it is problem with high database files?
In PLAYERS folder i have 14,797 files.

**Steps to make this happen**

1.  UP
2. UP
3. UP

**What do you think should happen?**

too many files? I have no idea ...

**Comment by Doc4oRHeaL** [comment]
Timings: https://timings.spigotmc.org/?url=mohadubara

**Comment by tastybento** [comment]
Timings look fine - good actually. There's nothing happening on the Minecraft thread, so if the CPU is high maybe it's garbage collection from the JVM. What memory do you have? Do you know what parameter the JVM is running (the -Xmx parameter)?
