### ISSUE TITLE
Players can destroy OP player islands

### ISSUE THREAD

**Issue by bocaratondev** [tastybento/ASkyBlock-Bugs-N-Features#602]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.11.2

**Plugin version:**
3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**

CrazyCrates, zPlayerFreeze, PlugMan, CustomJoinMessage, ChatReaction, LilyPad-Connect, Arconix, OldCombatMechanics, TopTenHeads, ViaVersion, ViaBackwards, AsyncWorldEditInjector, CustomHelpMessage, WorldEdit, HungerKeeperPlus, AnimatedNames, ClearLag, LilyPad-Portal, CloudCore, BuycraftX, CosmicVaults, MessageAnnouncer, Votifier, ProtocolLib, VotingPlugin, AsyncWorldEdit, VoidGenerator, PermissionsEx, CrayonConnect, Vault, SimpleRename, WorldGuard, AAC, AuctionHouse, ASkyBlock, ChatItem, RepairPlus, BossShop, SyncCraft, Essentials, MarriageMaster, AACAdditionPro, Banknotes, LiteBans, SilkSpawners, Multiverse-Core, OnTime, React, EssentialsChat, Multiverse-Portals, CombatTagPlus, HolographicDisplays, EssentialsProtect, EssentialsAntiBuild, EssentialsSpawn, TitleManager

**Description of issue. What happened?**
Any island owned by a player with OP is able to be destroyed by others. If a person does not have OP, they can go to a players island who does have OP and destroy blocks.

**What do you think should happen?**
Not sure if this is an error on my part (i.e., a permission error) or if this is a code error, however, It would be great if it was fixed ASAP. Could use any help. Thx.

**Comment by NikeStud** [comment]
Make sure you only have "__global__" as your region for your island world and make sure there is nothing to do with the flat "build" or "block-break". Second, I suggest you delete the EssentialsAntiBuild since you already have an protection plugin.

**Comment by Poslovitch** [comment]
Sounds like an error on your side.

Do players have a bypassprotect permission?
Do you have another protection plugin running in the ASkyBlock worlds?

Please send us your config by the way, this could have been done by setting the BREAK_BLOCK islandguardsettings to true.
Or this could have been done by the OP player himself, who would have set this IGS to true on his island.
