### ISSUE TITLE
/is level and other /is commands INSTANTLY crash the server!

### ISSUE THREAD

**Issue by NikeStud** [tastybento/ASkyBlock-Bugs-N-Features#603]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
Spigot 1,8
**Plugin version:**
Latest as on 1/14/18
**What other plugins are you using? (do /plugins and paste here)**
https://imgur.com/a/fBgXV
**Description of issue. What happened?**
Whenever any player does /is level and other /is commands it will INSTANTLY crash the server!
**Steps to make this happen**

1.  Join the game
2. Create an island
3. Execute a command

**What do you think should happen?**
I think the commands should do their purpose listed

**Comment by Poslovitch** [comment]
Please provide the following information, as a plugin *should not* be crashing your server, unless very specific requirements are met.

- The exact Java version your server is running (e.g : `java 8u151`)
- The exact Server version (print the full `/version`)
- The specifications of your dedicated server (CPU, RAM, eventually storage)
- The exact Vault version you're running
- ASkyBlock's config.yml file
- The logs of your serveur when it crashes

**Comment by NikeStud** [comment]
*The exact Java version your server is running (e.g : java 8u151)*
Not sure how to see this 
*The exact Server version (print the full /version)*
17.01 17:11:34 [Server] INFO This server is running CraftBukkit version git-Spigot-59b08be-0899683 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
17.01 17:11:34 [Server] INFO You are 1224 version(s) behind
*The specifications of your dedicated server (CPU, RAM, eventually storage)*
Instant Setup, Full FTP Access, Free MySQL,Standard Unlimited HDD Free DDOS Protection24/7 Support, Custom JAR Support, Multicraft Control Panel,  Free Sub-Domain, 4096 MB of RAM
*The exact Vault version you're running*
Newest as on 1/17/18
*ASkyBlock's config.yml file*
https://pastebin.com/0WEmQYcY (Default/Auto-Generated)
*The logs of your server when it crashes*
https://pastebin.com/spDkCEsT

**Comment by NikeStud** [comment]
This may help with your first question:

https://pastebin.com/F2FXtCtM

**Comment by NikeStud** [comment]
@tastybento @Poslovitch

**Comment by tastybento** [comment]
The crash log is being caused by the plugin just asking for a chunk. This should not happen. This could be due to a bug in the server code, a corrupted world, or some other bug. There is nothing we can do in the plugin I'm afraid. 

Things you can try:

1. Fly around the island where this is happening. Then do an orderly shutdown of the server and restart. Maybe the world files are corrupted somehow and it'll fix.
2. Upgrade to a newer server that has bugs fixed.
