### ISSUE TITLE
[Question] About offline mode to online mode

### ISSUE THREAD

**Issue by NelsonHD** [tastybento/ASkyBlock-Bugs-N-Features#604]
Hello :)
My server is going to change from offline mode to online mode, how can i change the offline uuid to online uuid which in database e.g island.yml ? THX :p

**Comment by Poslovitch** [comment]
You basically can't, unless you do it by hand.
Neither can we do it, as we don't have any way to get the old or the new UUID and compare them.

**Comment by tastybento** [comment]
@Poslovitch is correct. All player data is stored by UUID so you would need to do it all by hand. The UUID's are everywhere in the various data files. Sorry, there isn't anything we can do.
