### ISSUE TITLE
Players losing island ownership

### ISSUE THREAD

**Issue by bjunited** [tastybento/ASkyBlock-Bugs-N-Features#605]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12.2

**Plugin version:**
V3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**

**Description of issue. What happened?**
Islands seem to randomly lose there owner however in the config it still says they have an island. This issue has only occured the last few days. Also doing /asadmin unregister and /asadmin register doesn't do anything. The only fix is to have them make a fresh new island. This has happened to 3 or 4 users over the last 72 hours. It just happens when some people login. Also all team members and island owner have no permission to build on the island.

**Steps to make this happen**
Not to sure as it seems too be random

**What do you think should happen?**
Players shouldn't lose their island ownership.

**Comment by tastybento** [comment]
The islands.yml and the player files may be out of sync for some reason, or (and I hope not), someone changed the config.yml file to use a different island distance. 

If you go to an island and do /asadmin info, it'll tell you if the island thinks it is owner by someone. If you do /asadmin info <player> it'll tell you whether the player thinks it owns an island. Try and find out what is happening when it happens.

Another possible remedy is to (take backups before doing this), stop the server, delete islands.yml and restart. The islands.yml file will be regenerated from the player data. If you do this, you'll also need to create the island spawn again if you have it (/asadmin setspawn).

**Comment by bjunited** [comment]
Hello, I will give this a try when I next see it happen. I know for a fact that the distance was not changed in the configuration, so must be a syncronisation issue. Thank you and will reply again when I have info from asadmin info

**Comment by bjunited** [comment]
So it just happened again. When doing /asadmin info on the users island it said that no one owned it. The only fix is to schematic their island and then have them create a new one. I will try what you suggested of removing the islands.yml and starting again with it.

**Comment by bjunited** [comment]
Also when they did /is reset so I could fix it. This happened: 
![image](https://user-images.githubusercontent.com/34009740/35185919-77cdc32a-fe03-11e7-86fe-82d0c1f39b0e.png)

**Comment by UberMC** [comment]
Also happening. Didn't change distance but I did change protectionRange.
My distance is 500.

**Comment by UberMC** [comment]
Versions affected for me
v3.0.7 and v3.0.8.2

**Comment by UberMC** [comment]
Plugin is detected the island as null.

/asadmin info
"This island is not owned by anyone right now"

**Comment by UberMC** [comment]
Work around of removing islands.yml worked for me.

**Comment by tastybento** [comment]
Okay. This is usually caused by the server crashing and the data becoming out of sync. Glad you fixed it.
