### ISSUE TITLE
Plugin is crashing the server

### ISSUE THREAD

**Issue by LilLuxio** [tastybento/ASkyBlock-Bugs-N-Features#608]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

Server Version: 1.8.9

Plugin Version: V3.0.8.2 (Latest

Plugins: DeluxeMenus-1.10.2, EssentialsX-2.0.1, EssentialsXAntiBuild-2.0.1, EssentialsXChat-2.0.1, EssentialsXGeoIP-2.0.1, EssentialsXProtect-2.0.1, EssentialsXSpawn-2.0.1, EssentalsXXMPP-2.0.1, GroupManager, MCCore, MOTDColor, PlaceholderAPI-2.8.2, SkillAPI, TopTenHeads, Vault, ViaVersion-1.3.0, Worldedit-bukkit-6.1, Worldguard-6.2.1

Issue: When the server is ran, it loads up all the plugins and then stops responding, this does not occur when "askyblock" isn't installed, this wasnt happening either previously

**Steps to make this happen**

1. Start Server
2. Server Loads
3. Server stops responding

Server should load up fine but does not.

Here is the latest log file: https://pastebin.com/pkWEyPaD

**Comment by tastybento** [comment]
This crash occurred during the update check to dev.bukkit.org. Curseforge took their servers offline yesterday for a move to AWS and so maybe that was the cause (even so, it shouldn't have crashed). Anyway, they are back online. If it happens again, you can turn off updating in the config.yml.
