### ISSUE TITLE
Starterchest feature

### ISSUE THREAD

**Issue by Joeripoes** [tastybento/ASkyBlock-Bugs-N-Features#609]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
Spigot 1.12
**Plugin version:**
Any
**What other plugins are you using? (do /plugins and paste here)**
Does not matter
**Description of issue. What happened?**
A way to add crate keys from the plugin cratereloaded to the starter chest. these items have a custom name,lore and enchantment
**Steps to make this happen**

1. Change the plugin
2.
3.

**What do you think should happen?**
People start with a crate key on their island in the starterchest

**Comment by Poslovitch** [comment]
This is a feature request, which therefore will be moved on BSkyBlock's issues tracker.
