### ISSUE TITLE
Protect staff members from being expelled or banned by players

### ISSUE THREAD

**Issue by EBatuzay** [tastybento/ASkyBlock-Bugs-N-Features#611]
Some users use /is expel to ban my moderators from his island, making his job hard.
Can you make some node perm, example: island.staff to give a staff inmunity?
Thanks.

**Comment by Poslovitch** [comment]
You should have a look at the `askyblock.mod.*` permissions node, which will solve your problem ;)

Give it (or its sub-permissions) to your staff members, and they'll be able to bypass bans, expels, locks and protection on each island.

**Comment by tastybento** [comment]
Answered.
