### ISSUE TITLE
Require permissions to use a starting schematic

### ISSUE THREAD

**Issue by KillDevlicious** [tastybento/ASkyBlock-Bugs-N-Features#612]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.7.10
**Plugin version:**
latest
**What other plugins are you using? (do /plugins and paste here)**
https://gyazo.com/43c53955a058162cf977329a64ab3fc6
**Description of issue. What happened?**
me probably not being smart
**Steps to make this happen**
have my mind
1. 
2.
3.

Is there a way to set up islands to where you have to have a certain permission? in order to start on it?

**Comment by Poslovitch** [comment]
See the comments of the schematic section in config.yml : 
```yaml
# This section lists all the schematics available
# Settings are:
# show - whether this island will show in the GUI or not. Typically used for partner
#        schematics, but can be used to temporarily hide schematics.
# icon - the icon to show in the GUI. It must be a known Material
# order - the priority for showing in the GUI. Lower numbers are shown first.
# name - a friendly short name for the schematic. Color codes okay.
# description - a longer description. Use | to split lines. Color codes okay.
# filename - the filename of the schematic in the schematic folder
# useDefaultChest - fill a chest on the island with the items in this config. If false
#                   the contents will come from the schematic.
# partnerSchematic - the island that will be pasted in the Nether.
# biome - the biome this island should have. All pasted blocks will have this biome.
# These next settings may cause lag if true. Default is false. Use judiciously.
# pasteentities - if the schematic has entities in it (mobs) this will paste them.
# usephysics - if true, causes lava or water to flow after being pasted.
# pasteair - Only set to true if you need to paste below sea level.
# permission - the permission required to use this schematic. It can be anything you like
# You can add or remove from this list. If this section is missing, only the default
# island works.
```

Each schematic can require players to have a permission in order to use it as a starting island.
Whether they are shown or not if the player doesn't have the permission, is something I don't remember.

**Comment by tastybento** [comment]
> Is there a way to set up islands to where you have to have a certain permission? in order to start on it?

Yes. Use the permission keyword as mentioned above.
