### ISSUE TITLE
'Island Protected'  When island created

### ISSUE THREAD

**Issue by phill46** [tastybento/ASkyBlock-Bugs-N-Features#613]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.8.8
**Plugin version:**
3.0.8.2
**What other plugins are you using? (do /plugins and paste here)**
http://prntscr.com/i6xzet
**Description of issue. What happened?**
People cant build on island also When I move around 2 UUIDS pop up
http://prntscr.com/i6ycwv
**Steps to make this happen**

1. People do /is create make an island
2.Get and axe and try hitting a block
3.Error tell them island protected

**What do you think should happen?**
Somewhere in the permissions. I found that uuid in islands.yml so I could try deleting but im scared everything might be gone cause my server avg is 25 players

**Comment by tastybento** [comment]
Your islands.yml and player's folder are out of sync. Backup the files and then do this:

1. Stop server
2. Delete islands.yml
3. Start server

this will regenerate islands.yml from the player's info.

Also, the command */is create* should never be possible to be used by a player. They make an island by doing /is and then selecting from the GUI.

**Comment by phill46** [comment]
Would it remove the players island that are already made

**Comment by tastybento** [comment]
No. islands.yml is just a cache of the data in the player's folder. Also, like I said, backup, i.e., make copies of the ASkyBlock plugin folder and the world folder before doing anything major like this so that if it fails, you can go back.
