### ISSUE TITLE
Asadmin purge

### ISSUE THREAD

**Issue by XxWill33xX** [tastybento/ASkyBlock-Bugs-N-Features#615]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:** 1.11.2

**Plugin version:** V3.0.8.2

**What other plugins are you using? (do /plugins and paste here)** WorldEdit, MobStacker, ElenoxCore, ElenoxHDV, PermissionsEx, ClearLag, Craftconomy3, ElenoxEventConfigurator, ViaVersion, ElenoxSkyblockV3, BuycraftX, Vault, Citizens, ASkyBlock, ChestShop, CommandNPC, PlotSquared, Multiverse-Core, Shopkeepers, HolographicDisplays, CrateReloaded

**Description of issue. What happened?**

I can not delete the inactive islands. The command / asadmin purge 90 asks me to do / asadmin confirm but nothing happens.

---

Je n'arrive pas a supprimer les îles inactives. La commande /asadmin purge 90 me demande de faire /asadmin confirm mais rien ne se passe.

**Steps to make this happen**

1. /asadmin purge 90
2. /asadmin confirm
3.

**What do you think should happen?**
Suppression of islands

**Comment by Poslovitch** [comment]
Merci pour votre rapport de bug, mais j'ai besoin d'informations supplémentaires (vous pouvez répondre en français, je traduirai en anglais si besoin pour Tastybento) : 
- Quelle est la version exacte du serveur (`/version`)
- Est-ce que des plugins interagissent avec l'API ASkyBlock (je pense notamment à `ElenoxCore` et `ElenoxSkyblockV3` ?
- Quel est la valeur de `maxpurge` dans la config?
- Est-ce que la purge est lancée lorsque des joueurs sont connectés au serveur?

Essayez également de lancer une purge via la console puis envoyez-nous le log, puisque des informations de débug y sont envoyées.

**Comment by XxWill33xX** [comment]
Version: 3.0.8.2
ElenoxCore, interagie pas du tous avec ASkyblock et ElenoxSkyblockV3 interagie seulement sur les récupérations de niveau et joueurs dans les teams.

**Comment by XxWill33xX** [comment]
Commande /asadmin purge 90 indique d'effectuer la commande /asadmin confirm.
Command /asadmin confirm > Rien ne se passe, mais taper deux fois message "Limite de temps atteinte !"
Command /asadmin purge 90 message "La vérification est toujours en cours, attendez qu'elle se termine"

**Comment by tastybento** [comment]
I can't understand everything, but there was an update to the way purge is handled with the latest release that may fix this issue.

**Comment by Poslovitch** [comment]
Sorry, I forgot to translate the answers.

@XxWill33xX La dernière version (3.0.8.5) devrait corriger votre problème.
