### ISSUE TITLE
API

### ISSUE THREAD

**Issue by ryanwoods1706** [tastybento/ASkyBlock-Bugs-N-Features#617]
Trying to hook into this plugin, how am I able to get the bounds of an island? So opposite corners so i can determine if something is in the players island?

**Comment by Poslovitch** [comment]
```java
ASkyBlockAPI.getInstance().locationIsOnIsland(org.bukkit.entity.Player, org.bukkit.Location);
```

This method above would probably suit to your need. Otherwise, you should have a look at the [Javadoc of the ASkyBlockAPI](http://tastybento.github.io/askyblock/com/wasteofplastic/askyblock/ASkyBlockAPI.html).
