### ISSUE TITLE
ASkyBlock Internal Error

### ISSUE THREAD

**Issue by qpslxm** [tastybento/ASkyBlock-Bugs-N-Features#618]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
- 1.8.8

**Plugin version:**
- V 3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**
-MotdManager 
-HiveJumpPads 
-Beast-XpWithDraw 
-RandomPackage 
-PlaceholderAPI0 
-StaffFacilities 
-Arconix 
-MaxBans 
-VoxelSniper 
-MobCoins 
-ViaVersion 
-ZavAutoMessager 
-ChatColor 
-WorldEdit 
-Installer 
-Skript 
-BetterMcmmoStats 
-Essentials 
-ClearLag 
-SkQuery 
-BuycraftX
-Votifier 
-TablistPrefix 
-ProtocolLib 
-NoCheatPlus 
-GuiRedeemMCMMO 
-KitAdder 
-iDisguise 
-HubThat 
-DeluxeMenus 
-EssentialsChat 
-SpawnerUpgrader 
-PermissionsEx 
-FeatherBoard 
-mcMMO 
-Vault 
-GAListener 
-NovaKitGui 
-CrazyCrates 
-SimpleRename 
-HideAndCustomPlugins 
-WorldGuard 
-Spartan 
-AuctionHouse 
-ASkyBlock 
-PlayerVaults 
-BossMobs 
-MonthlyCrates 
-CustomTab 
-LibertyTopBalances 
-LinkItem 
-PureCombat 
-LiteBans 
-CrateReloaded 
-SilkSpawners 
-VoidSpawn 
-Multiverse-Core 
-Citizens 
-HolographicDisplays 
-CitizensCMD 
-SkinsRestorer 
-CommandNPC 
-ShopGUIPlus 
-WarpPortals 
-CrazyEnvoy

**Description of issue. What happened?**
It will always give me this same message when i type a skyblock command "An internal error has occurred while attempting to perform this command"

**Steps to make this happen**

1. type a command such as "/asadmin reload"
2. then it says the thing
3.

**What do you think should happen?**
i think that the problem should be fixed after this as i dont know what is happening

**Comment by qpslxm** [comment]
i also have a small peniiissss

**Comment by qpslxm** [comment]
How do I delete that because that was my sister she is legit so irritating

**Comment by Poslovitch** [comment]
I deleted the abusive comments, please make sure it won't happen again. (tasty : it was his sister who was out of control)

Please provide the logs of your server. We need them to know which error occured.
Please also provide detailled server version (`/version`)

**Comment by qpslxm** [comment]
**Message in console when starting server:**

> [09:03:27 INFO]: [ASkyBlock] Enabling ASkyBlock v3.0.8.2
> [09:03:27 INFO]: [ASkyBlock] Loading entity limits
> [09:03:27 INFO]: [ASkyBlock] HOPPER will be limited to 30
> [09:03:27 WARN]: [ASkyBlock] Unknown material (BEETROOT_BLOCK) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (BLACK_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (BLACK_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (BLUE_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (BLUE_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (BOAT_ACACIA) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (BOAT_BIRCH) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (BOAT_DARK_OAK) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (BOAT_JUNGLE) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (BOAT_SPRUCE) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (BONE_BLOCK) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (BROWN_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (BROWN_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (CHORUS_FLOWER) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (CHORUS_PLANT) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (CONCRETE) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (CONCRETE_POWDER) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (CYAN_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (CYAN_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (END_BRICKS) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (FROSTED_ICE) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (GRASS_PATH) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (GRAY_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (GRAY_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (GREEN_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (GREEN_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (LIGHT_BLUE_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (LIGHT_BLUE_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (LIME_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (LIME_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (MAGENTA_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (MAGENTA_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:27 WARN]: [ASkyBlock] Unknown material (MAGMA) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (NETHER_WART_BLOCK) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (OBSERVER) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (ORANGE_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (ORANGE_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (PINK_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (PINK_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (PURPLE_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (PURPLE_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (PURPUR_BLOCK) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (PURPUR_DOUBLE_SLAB) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (PURPUR_PILLAR) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (PURPUR_SLAB) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (PURPUR_STAIRS) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (RED_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (RED_NETHER_BRICK) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (RED_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (SILVER_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (SILVER_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (WHITE_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (WHITE_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (YELLOW_GLAZED_TERRACOTTA) in blockvalues.yml blocks section. Skipping...
> [09:03:28 WARN]: [ASkyBlock] Unknown material (YELLOW_SHULKER_BOX) in blockvalues.yml blocks section. Skipping...
> [09:03:28 INFO]: [ASkyBlock] Loaded default island schematic.
> [09:03:28 WARN]: Spawner setting of WITHER_SKELETON is unknown for this server. Skipping.
> [09:03:28 INFO]: [ASkyBlock] Loaded default nether schematic.
> [09:03:28 INFO]: [ASkyBlock] Loading schematic The Original (island.schematic) for all players, order 1
> [09:03:28 WARN]: Spawner setting of WITHER_SKELETON is unknown for this server. Skipping.
> [09:03:28 INFO]: [ASkyBlock] Loading schematic NetherBlock Island (nether.schematic) for all players, order 0
> [09:03:28 INFO]: [ASkyBlock] Loading schematic Island Duo (double.schematic) for all players, order 2
> [09:03:28 INFO]: [ASkyBlock] Loading schematic §lBlack §bDiamonds (harder.schematic) for all players, order 3
> [09:03:28 INFO]: [ASkyBlock] Loading offline messages...
> [09:03:28 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!

**Message in console when writing a command:**

> [09:12:58 INFO]: qpslxm issued server command: /asadmin reload
> [09:12:58 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'asadmin' in plugin ASkyBlock v3.0.8.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-76236cb-9cd1111]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-76236cb-9cd1111]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[server.jar:git-Spigot-76236cb-9cd1111]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [server.jar:git-Spigot-76236cb-9cd1111]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [server.jar:git-Spigot-76236cb-9cd1111]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-76236cb-9cd1111]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-76236cb-9cd1111]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-76236cb-9cd1111]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-76236cb-9cd1111]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [server.jar:git-Spigot-76236cb-9cd1111]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-76236cb-9cd1111]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [server.jar:git-Spigot-76236cb-9cd1111]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [server.jar:git-Spigot-76236cb-9cd1111]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
at com.wasteofplastic.askyblock.commands.AdminCmd.onCommand(AdminCmd.java:712) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-76236cb-9cd1111]
... 15 more

**Server Version (In more detail):**

> [09:06:55 INFO]: This server is running CraftBukkit version git-Spigot-76236cb-9cd1111 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Sorry for the late response, ive been really busy lately. If you need anything else about the problem just message me!**

**Comment by Poslovitch** [comment]
Thanks for your answer :)

I will investigate this bug.

**Comment by Poslovitch** [comment]
@tastybento A NPE is thrown in [AdminCmd at line 712](https://github.com/tastybento/askyblock/blob/3.0.8.2/src/com/wasteofplastic/askyblock/commands/AdminCmd.java#L712):
```java
plugin.getPlayerEvents().removeAllTempPerms();
```

I don't understand what could be null there, but I think it is the value returned by `getPlayerEvents()`, because if a NPE would have happened in `removeAllTempPerms()`, we would have had something like this as stacktrace:
>Caused by: java.lang.NullPointerException
at com.wasteofplastic.askyblock.listeners.PlayerEvents.removeAllTempPerms(PlayerEvents.java:???) ~ [?:?]
at com.wasteofplastic.askyblock.commands.AdminCmd.onCommand(AdminCmd.java:712) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-76236cb-9cd1111]
... 15 more

**Comment by tastybento** [comment]
@qpslxm It looks like the plugin is disabled and not working. In the console log you posted I don't see "All files loaded. Ready to play..." at the end. I expect there are actually errors that say something about the plugin not loading.

**Comment by qpslxm** [comment]
Do you need me to give you anymore information about this?

**Comment by tastybento** [comment]
Yes. When you start the server with ASkyBlock on it, do you see "[ASkyBlock] All files loaded. Ready to play..." in the console log? Do you see errors in the console log saying things like that ASkyBlock is disabled?

**Comment by qpslxm** [comment]
It says “schematics have successfully loaded” and then the last thing it says is “Loading offline messages...” it doesn’t say anything else after that

**Comment by qpslxm** [comment]
I really hope this issue gets fixed because this is the only good skyblock plugin there is right now.

**Comment by tastybento** [comment]
Your server has not started correctly. Look at my console log and you'll see there's a lot more to come after it says “Loading offline messages...”.

https://pastebin.com/b0a8CxEP

Can you paste your full log?

**Comment by qpslxm** [comment]
Sure, this is my full server log when it loads up

www.pastebin.com/6sxF7hHm

**Comment by tastybento** [comment]
There should be more after the Done! line, like this:

[22:38:25 INFO]: [ASkyBlock] Silencing command feedback for Ops...
[22:38:25 INFO]: Game rule sendCommandFeedback has been updated to false
[22:38:25 INFO]: [ASkyBlock] If you do not want this, do /gamerule sendCommandFeedback true
[22:38:25 INFO]: [ASkyBlock] Checking for new updates...
[22:38:25 INFO]: [Vault] Checking for Updates ... 
[22:38:25 INFO]: [ASkyBlock] Loading island grid...
[22:38:25 INFO]: [ASkyBlock] Loading islands.yml
[22:38:25 INFO]: [ASkyBlock] Loading warps...
[22:38:25 INFO]: [ASkyBlock] All files loaded. Ready to play...
[22:38:25 INFO]: [ASkyBlock] Metrics loaded.
[22:38:25 INFO]: [Vault] No new version available
[22:38:26 INFO]: [ASkyBlock] No update available.
