### ISSUE TITLE
AcidIsland Schematic Panel Not Working

### ISSUE THREAD

**Issue by doitliketyler** [tastybento/ASkyBlock-Bugs-N-Features#619]
**Server version:**
PaperSpigot 1.12.2

**Plugin version:**
AcidIsland V3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**
https://pastebin.com/raw/xFHCjziz

**Description of issue. What happened?**
I have custom schematics setup and the panel used to work fine but now it doesn't show up when creating an island. I've checked to see if I'm missing any new options but everything looks good to me. What am I missing?

Here is my config: https://pastebin.com/raw/5GJVG46a

**Comment by tastybento** [comment]
Most likely it's due to permissions. If there are no options other than the default, you'll get the default. I see you have a perm on every island so I suspect your player doesn't have permissions to see/use them.

**Comment by doitliketyler** [comment]
Ok...what about OP then? I'm OP and I get the default island and no panel shows up for me.

**Comment by tastybento** [comment]
I do see filename: missing from the default schematic as well.

**Comment by tastybento** [comment]
Also, the schematics section is not indented correctly. It's at the same level as schematicsection:

```
schematicsection:
schematics:
  default:
    icon: GRASS
    order: 1
    name: "Pleasant Plains"
    useDefaultChest: true
```

You need to put 2 spaces in front of all the islands.

**Comment by tastybento** [comment]
If you do /asadmin reload it'll list the islands that are being loaded so you can check them.

**Comment by doitliketyler** [comment]
Awesome. I changed both of those things and they work fine now. Thanks for taking a look. I've been pasting that same schematic section for over a year now so I'm guessing during some update I overlooked the change. Cheers.
