### ISSUE TITLE
Enable invites to be withdrawn or timeout.

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#62]
_From @tastybento on June 21, 2016 6:28_

/is invites and you an see everyone you have invited. Also /is revokeinvite [player] to remove that players invitation or make the invite last for only 24h and after that the invitation will expire

_Copied from original issue: tastybento/askyblock#251_

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#11
