### ISSUE TITLE
Can't light nether portals

### ISSUE THREAD

**Issue by iReligion** [tastybento/ASkyBlock-Bugs-N-Features#620]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
Taco Spigot 1.8

**Plugin version:**
Latest?

**What other plugins are you using? (do /plugins and paste here)**
HiveJumpPads, TreasurePets, KeepItems, CustomOreGen, PlaceholderAPI, PlugMan, AntiAFKPlus, NametagEdit, YoutubeTitle, ChatReaction, NoJoinLeaveMessages, Arconix, DeluxeTags, Quests, SerializationAPI, IngotsBlocks, CondenseWand, ViaVersion, InvRestore, CoreProtect, AnimationLib, WorldEdit, FastCraft, Skript, SellWands, ClearLag, ChatControl, SkQuery, BuycraftX, Votifier, ActionBarAPI, ProtocolLib, GuiRedeemMCMMO, MVdWPlaceholderAPI, NoHungerLoss, AdvanceTab, PermissionsEx, FeatherBoard, PvPingMobCoins, mcMMO, ServerListPlus, GAListener, Vault, DailyRewards, NoHopperCraft, ViaRewind, AnimatedMenu, SimpleRename, TuSKe, VoteParty, SkyblockWorldEdit, WorldGuard, HideAndCustomPlugins, ASkyBlock, LockettePro, ChatItem, ChestCommands, PlayerVaults, GuiBalance, Essentials, HopeChest, BountyHunters, LiteBans, SilkSpawners, Multiverse-Core, Citizens, MergedMob, KitPreview, EssentialsChat, CrazyAuctions, CombatTagPlus, ChestShop, CreativeControlByKubqoA, NoFlyZone, HolographicDisplays, CoinFlip, skRayFall, CommandNPC, EssentialsSpawn, ShopGUIPlus, CrateReloaded, Multiverse-NetherPortals

**Description of issue. What happened?**
Nether Portals used to work. I had it setup to be Vanilla Nether. Player's complained, so I changed to Island Nether. Portals wouldn't generate. I changed it back to Vanilla Nether, and now they still don't generate. 

I've tried installing Multiverse-NetherPortals and linking aSkyblock to world_nether, and that doesn't work, so I think it can possibly be another plugin issue, but I don't know what. It doesn't make sense that it stopped after I made a aSkyblock config change.

**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**
Portals should generate

**Comment by tastybento** [comment]
Maybe fire is disabled? It's a setting in config.yml. After changing the setting, do /asadmin settingsreset all. Also, it may be that lighting portals is disabled via another plugin somehow. There's no need to use Multiverse-NetherPortals.
