### ISSUE TITLE
Pvp enabling not working

### ISSUE THREAD

**Issue by Joeripoes** [tastybento/ASkyBlock-Bugs-N-Features#621]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**1.12.1

**Plugin version:**newest

**What other plugins are you using? (do /plugins and paste here)**

How can I fix it so that people CAN pvp at spawn because now they cant, it build spwn at x 0 z 0. On island people are able to pvp but not on spawn. I typed /is setspawn at this location and then /is settings and pvp allowed, but still not work

**Comment by Poslovitch** [comment]
Thanks for the report

Is the spawn-protection in server.properties set to 0?

**Comment by Joeripoes** [comment]
Yes it's on zero

**Comment by Joeripoes** [comment]
I noticed you can only not pvp in the area with -100 -100 to 100 100

2018-02-07 16:28 GMT+01:00 100% Awesome <joeridukker3@gmail.com>:

> Yes it's on zero
>

**Comment by Joeripoes** [comment]
Is pvp disabled in skyblock spawn by default?

2018-02-07 16:35 GMT+01:00 100% Awesome <joeridukker3@gmail.com>:

> I noticed you can only not pvp in the area with -100 -100 to 100 100
>
> 2018-02-07 16:28 GMT+01:00 100% Awesome <joeridukker3@gmail.com>:
>
>> Yes it's on zero
>>

**Comment by Poslovitch** [comment]
Sorry for the late response.

Can you please send us your config.yml ?

**Comment by Joeripoes** [comment]
[config.txt](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1732895/config.txt)
There

**Comment by tastybento** [comment]
Sorry, I can't replicate this. I used your config.yml and did the following:

1. New world
2. Created island (at 0,0)
3. Did /asadmin unregister tastybento (to remove me from the island)
4. Set the island to spawn (/asadmin setspawn)
5. Make a new island
6. Another player joined and made an island
7. We both went to spawn and could hit each other

You could try and set spawn somewhere else and then put it back. That may help.
