### ISSUE TITLE
Range reset after rejoin

### ISSUE THREAD

**Issue by ElementalShadow** [tastybento/ASkyBlock-Bugs-N-Features#622]
[ASkyBlock] Login range setting: Island protection range changed from 200 to 24 for ElementalShadow due to permission.

How to stop this "Login range settings" I don't want lose island protection range after rejoin.

**Comment by Poslovitch** [comment]
What are the permissions you're given?

It appears that the protection range change when logging in is due to the range permission.
> [ASkyBlock] Login range setting: Island protection range changed from 200 to 24 for ElementalShadow due to permission.

**Comment by ElementalShadow** [comment]
Permission askyblock.island.range.<number>

**Comment by ElementalShadow** [comment]
What is problem?

**Comment by tastybento** [comment]
ElementalShadow has a permission askyblock.island.range.24. Therefore when you join the server, it sets your range to 24. Remove that permission and you'll be fine.
