### ISSUE TITLE
Mob spawner in minishop bug

### ISSUE THREAD

**Issue by Parlamentum** [tastybento/ASkyBlock-Bugs-N-Features#625]
**Server version:** 1.11.2

**Plugin version:** newest

Hi, i recently updated my server from 1.8.8 to 1.11.2 and the skyblock plugin too.
Everything seems to work just fine except for the mob spawner i sell on the minishop which stoped working and worked fine before the update.
Now, every time a player try to buy a spawner, it doesn't work and this error appear in the console https://pastebin.com/bEWdHjZq

**Comment by tastybento** [comment]
Sorry, the mini shop does not support the new meta data definitions required for mob spawners and other items. This is a Minecraft thing, numbers don't work any more and they have to be defined using words like COW, etc. I recommend using a dedicated shop plugin to handle these now.
