### ISSUE TITLE
staff cant build?

### ISSUE THREAD

**Issue by IGDT** [tastybento/ASkyBlock-Bugs-N-Features#627]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version: 1.8.8 and higher**

**Plugin version: ASkyBlock V3.0.8.2**

**What other plugins are you using? (do /plugins and paste here)**
AdminFun/								
AdvancedPortals/							
ArmorStandEditor/							
ASkyBlock/
AUpdater/
AutoMessage/
BossShop/
bStats/
ChatColor2/
Citizens/
ClearLag/
ColoredSigns/
CommandNPC/
CoreProtect/
CratesPlus/
DependencyDownloader/
dtlTraders/
EnjinMinecraftPlugin/
Essentials 
EssentialsGeoIP/
 EssentialsXMPP/
 GlobalMarket/
 GriefPreventionData/
 GUIShop/
 HolographicDisplays/
 iDisguise/
 Info-Board/
 Jail/
 LobbyAPI/
 LobbyCompass/
 Lockette/
 LogBlock/
 MCStatsXYZ/
 MultiWorld/
 NewTag/
 NickNames/
NoCheatPlus/
 NPCAuctions/
 OpenInv/
 Parkour/
 PermissionsEx/
 PixelPrinter/
 PlayerHeads/ 
PluginMetrics/
 RewardVoting/ 
ScoreboardStats/ 
Shopkeepers/ 
SimpleRename/ 
SimpleVoteListener/ 
TablistPrefix/ 
TimTheEnchanter/ 
TreeAssist/
UltimateHeadFinder/ 
Updater/
Vault/
Votifier/ 
WorldEdit/ 
WorldGuard/
**Description of issue. What happened?**
i have a server, when i wanted other staff to build on the askyblock world they cant. they DONT have OP given so should i give it to them to build or not? is there a command that i should give them to let them build on it? a staff member told me it said island protected even we didnt created islands yet
**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**
tell me what i should give to my staff to let them build on it

**Comment by tastybento** [comment]
askyblock.mod.bypass is the permission to bypass protection.
