### ISSUE TITLE
Island Protected (Urgent!)

### ISSUE THREAD

**Issue by AdvancedGP** [tastybento/ASkyBlock-Bugs-N-Features#628]
**Server version:**
Spigot 1.12

**Plugin version:**
V3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**
https://gyazo.com/f4f9a76807be980ac94fa9519558eca1

**Description of issue. What happened?**
When players make an island, there is a random (high) chance that the player will not be able to build on his island or do anything, error message saying "Island Protected" in red. I have done many things like deleting the whole folder, deleting island.yml, deleting the world, and nothing works, distance: 200, protectionRange: 100. i had players try to reset their island many times too.

**Steps to make this happen**

1. /is
2. make an island
3. try to break blocks

**What do you think should happen?**
they should be able to build on their own island.

**Comment by tastybento** [comment]
Have a try with this: https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#when-players-make-an-island-it-says-island-protected-and-they-can-t-do-anything-until-they-restart

**Comment by AdvancedGP** [comment]
Will deleting Island.yml do anything? like delete islands or something.

**Comment by tastybento** [comment]
No.
