### ISSUE TITLE
setProtection method while using API

### ISSUE THREAD

**Issue by bocaratondev** [tastybento/ASkyBlock-Bugs-N-Features#630]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version: ** 1.8.9

**Plugin version: ** 3.0.8.2

**Description of issue. What happened?** 
I'm using the API so that when a specific event fires, the protection size of the player's island will upgrade. I'm trying to use the method setProtectionSize(int) with the Island object. No errors occur, however, after the code runs, the Island size stays the same. I was curious as to what I'm doing wrong, or if this is even possible. I'm trying to set the protection size to int's like 150 and 250.

**Comment by tastybento** [comment]
That's the correct method. But if the owner has a permission to set the range back then it'll kick in next time they log in. Other than that, I can't help unless you share some of your code.
