### ISSUE TITLE
Item required with enchantments

### ISSUE THREAD

**Issue by Gosselk** [tastybento/ASkyBlock-Bugs-N-Features#631]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
spigot 1.12.2
**Plugin version:**
3.0.8.2

**Description of issue. What happened?**
I have tried to make an enchantement to a required items. But is not work... maybe it's the syntax of my item, but i'm not sure, i have no example for this.
"requiredItems: 'DIAMOND_SWORD:DAMAGE_ARTHROPODS:1:1"

thx for help and sorry for my english i'm not a english people ;)

**Comment by tastybento** [comment]
It's not possible, sorry. We'll make it something that can be done in BSkyBlock.

**Comment by Poslovitch** [comment]
That's effectively not possible, and would require a too big change to handle that. You'll have to wait for BSkyBlock
