### ISSUE TITLE
Pigs Give Orange Wool??

### ISSUE THREAD

**Issue by AdvancedGP** [tastybento/ASkyBlock-Bugs-N-Features#633]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12

**Plugin version:**
3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**
https://gyazo.com/f4f9a76807be980ac94fa9519558eca1

**Description of issue. What happened?**
When you kill a pig, they give wool instead of port, orange wool to by exact, one with a lore of "My Egg!" and another with "My Wool!"

**Steps to make this happen**

1. find/spawn pig
2. beat the shit out of it
3. gain wool

**What do you think should happen?**
can you tell me how i can change this, or maybe add a custom mob drops feature.

**Comment by Poslovitch** [comment]
This has nothing to do with ASkyBlock. We never in the code edit mobs' drops.

You should run a test server on your computer and add each plugin one by one until these weird drops start to appear in order to find out which plugin is causing it.

Good luck ;)
