### ISSUE TITLE
Console's Spamming this while I'm in spawn

### ISSUE THREAD

**Issue by Zyrexus** [tastybento/ASkyBlock-Bugs-N-Features#634]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
Paper Spigot, 1.8.8
**Plugin version:**
Latest, V3.0.8.2
**What other plugins are you using? (do /plugins and paste here)**
![image](https://user-images.githubusercontent.com/14060724/36111264-70ea0b96-101d-11e8-84c5-0193ced244a3.png)

**Description of issue. What happened?**
My Console is getting spammed with this when skyblockborder requests to use askyblock, dev told me to contact you;
![image](https://user-images.githubusercontent.com/14060724/36111321-a63bf69c-101d-11e8-81b8-77f96aa59919.png)

**Steps to make this happen**

1. spawn world

**What do you think should happen?**
That it doesn't spam anything or display anything like that, I haven't edited the askyblock config since the server opened (Only things that I `did` was delete islands.yml, and rename some text stuff that gets displayed.)

**Comment by Poslovitch** [comment]
I had a look at the stacktraces, and it definitely looks like the error is not our side, but instead comes from "skyblockborder".

Can you send us more details about this plugin? Can you ask its developper to come here to explain what might be wrong?
