### ISSUE TITLE
Askyblock normal generated end world

### ISSUE THREAD

**Issue by Joeripoes** [tastybento/ASkyBlock-Bugs-N-Features#635]
I have a skyblock world using the Askyblock plugin. Now I wanted to add a Skyblock_the_end world and connect this to my Skyblock world. What I used to do is make a portal at spawn and using mutliverse portals connect this portal to that world.

But this time I want players to make portals themselves. So you buy 12 end portal frames in shop or something and when you create the portal, it works and will bring you to the end. I really do not know how to do this though

**Comment by Poslovitch** [comment]
ASkyBlock doesn't support the End. BSkyBlock will.

We can't help you with using MultiversePortals to allow players to go into a normal End by creating portals themselves, that's not our plugin and we don't know anything about how it works. You'll have to read some documentation or ask for help on forums.

Good luck.
