### ISSUE TITLE
Push blocks outside of is range

### ISSUE THREAD

**Issue by Joeripoes** [tastybento/ASkyBlock-Bugs-N-Features#636]
Some player noticed he could push blocks out of his island range using pistons. He was then no longer able to break those blocks. Is there a way to disable this, like that the piston just wont push if the is range is reached?

**Comment by Poslovitch** [comment]
https://github.com/tastybento/askyblock/blob/master/config.yml#L161
```yaml
# Allow pistons to push outside of the protected area (maybe to make bridges)
allowpistonpush: true
```

Read the config file more carefully next time ;)
