### ISSUE TITLE
Player Head In Control Panel GUI

### ISSUE THREAD

**Issue by j-Daddy** [tastybento/ASkyBlock-Bugs-N-Features#638]
Would like to know the material code to display the players head in the control panel GUI menu?      
eg:
material: head;%player%
What should 'head;%player%' be changed to?
TIA

**Comment by Poslovitch** [comment]
ASkyBlock doesn't support player heads in the GUIs, but that sounds like a possible good addition to BSkyBlock's API (as ASB is no longer receiving feature requests).
