### ISSUE TITLE
Feature Request: /is limits

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#64]
_From @ghost on May 13, 2016 20:16_

This command could show how many island limits a player already has reached (hopper, animals, monsters, tileentities). Would be useful for all players and for admins there could be also the command /asadmin limits <island> to check the limit of a specific player.

_Copied from original issue: tastybento/askyblock#226_

DISPLAY AS GUI

**Comment by Poslovitch** [comment]
_From @Steev93 on July 19, 2016 12:10_

Following

**Comment by Poslovitch** [comment]
Please put it in 3.0.5 milestone

**Comment by Poslovitch** [comment]
_From @tastybento on December 6, 2016 22:36_

Let's move to 3.0.6 so we can release 3.0.5.

**Comment by SaitDev** [comment]
+1 for this. Please

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#58
