### ISSUE TITLE
ASkyBlock nether is buggy, it shows the real nether, not the skyblock nether. HELP!

### ISSUE THREAD

**Issue by RoyAdit88** [tastybento/ASkyBlock-Bugs-N-Features#644]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version: 1.8.8**

**Plugin version:V3.0.8.2**

**What other plugins are you using? (do /plugins and paste here)**
https://imgur.com/a/kO0Df
**Description of issue. What happened?**
When player makes a nether portal, they  teleported to the real nether, not the skyblock nether.
**Steps to make this happen**

1. Make a nether portal
2. Enable it
3. Get into the nether portal

**What do you think should happen?**
You fix this bug. Help me please ><

**Comment by RoyAdit88** [comment]
Help pls ><

**Comment by Poslovitch** [comment]
Please send us your config.yml.

**Comment by RoyAdit88** [comment]
Here, https://pastebin.com/8NNDg7MW

**Comment by Poslovitch** [comment]
Line 201
```yaml
   # New island-style nether. Change to false for standard nether
   newnether: false
```

Change it to true, delete ASkyBlock_nether and you'll be good to go.

**Comment by RoyAdit88** [comment]
OMG, thanks! OwO. I can't believe that kind of this person exist! So kind! OwO

**Comment by Poslovitch** [comment]
You're welcome.
