### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by Infinityy1** [tastybento/ASkyBlock-Bugs-N-Features#645]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.8
**Plugin version:**
LATEST
**What other plugins are you using? (do /plugins and paste here)**
https://gyazo.com/7ce2adfeae3c9bd65e620805d5f4afb8
**Description of issue. What happened?**
Askyblock broke https://gyazo.com/c5b6f4077be86fea1e1e19eb205f4303

**Steps to make this happen**

1. change view-distance in server.properties
2. restart server
3. breaks everything

**What do you think should happen?**
doesnt break everything

**Comment by Poslovitch** [comment]
ASkyBlock doesn't "break" itself for no reason.

Please send us your config.yml and the logs of your server.

**Comment by Infinityy1** [comment]
https://hastebin.com/otocokolib.php - config
https://hastebin.com/enikosewuc.sql - logs

**Comment by Poslovitch** [comment]
I need the full logs please, just having the ASkyBlock part doesn't give me enough information

**Comment by Infinityy1** [comment]
18.02 02:14:33 [Server] INFO Loading jAlts v0.1-STABLE
18.02 02:14:33 [Server] INFO Loading MeapTAB v1.0
18.02 02:14:33 [Server] INFO Loading SimpleAutoBroadcast v1.1.0
18.02 02:14:33 [Server] INFO Loading PlaceholderAPI v2.8.2
18.02 02:14:33 [Server] INFO Loading VoidWorld v1.0
18.02 02:14:33 [Server] INFO Loading ServerBoosters v1.2
18.02 02:14:33 [Server] INFO Loading IP-Check v2.0.7
18.02 02:14:33 [Server] INFO Loading PlugMan v2.1.4
18.02 02:14:33 [Server] INFO Loading NametagEdit v4.1.4
18.02 02:14:33 [Server] INFO Loading MeapJoinQuit v1.0
18.02 02:14:33 [Server] INFO Loading CarlTheCreeper v2.5.5
18.02 02:14:33 [Server] INFO Loading ChatReaction v1.7.1
18.02 02:14:34 [Multicraft] Skipped 73 lines due to rate limit (30/s)
18.02 02:14:34 [Server] INFO ====== USE PAPER ======
18.02 02:14:34 [Server] INFO DOWNLOAD: https://ci.destroystokyo.com/job/PaperSpigot/
18.02 02:14:34 [Server] INFO GUIDE: https://www.spigotmc.org/threads/21726/
18.02 02:14:34 [Server] INFO - This is only a recommendation
18.02 02:14:34 [Server] INFO ==============================
18.02 02:14:34 [Server] INFO Enabling Vault v1.5.3-b37
18.02 02:14:35 [Server] INFO [Economy] Essentials Economy found: Waiting
18.02 02:14:35 [Server] INFO [Permission] PermissionsEx found: Waiting
18.02 02:14:35 [Server] INFO [Permission] SuperPermissions loaded as backup permission system.
SpigotMC - High Performance Minecraft
[GUIDE] Optimizing Spigot - Remove lag, Fix tps & Improve performance!
Last updated 2016-04-04

Spigot has a lot of performance improvements disabled by default, as they often alter the server so it no longer replicates...

18.02 02:14:35 [Server] INFO [Chat] PermissionsEx found: Waiting
18.02 02:14:35 [Server] INFO Enabled Version 1.5.3-b37
18.02 02:14:35 [Server] INFO Enabling Exodus v1.2-b4
18.02 02:14:35 [Server] INFO Enabling ASkyBlock v3.0.8.2
18.02 02:14:35 [Server] ERROR Cannot load plugins/ASkyBlock/config.yml
18.02 02:14:35 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
18.02 02:14:35 [Server] INFO in 'string', line 26, column 4:
18.02 02:14:35 [Server] INFO distance: 500
18.02 02:14:35 [Server] INFO ^
18.02 02:14:35 [Server] INFO expected <block end>, but found Scalar
18.02 02:14:35 [Server] INFO in 'string', line 121, column 18:
18.02 02:14:35 [Server] INFO - "&9[player]'s cow"
18.02 02:14:35 [Server] INFO ^
18.02 02:14:37 [Server] INFO NMS placeholders such as %player_ping% have been enabled!
18.02 02:14:37 [Server] INFO Successfully registered expansion: player
18.02 02:14:37 [Server] INFO Successfully registered expansion: server
18.02 02:14:37 [Server] INFO Successfully registered expansion: statistic
18.02 02:14:37 [Server] INFO Successfully registered expansion: askyblock
18.02 02:14:37 [Server] INFO Successfully registered expansion: carlthecreeper
18.02 02:14:37 [Server] INFO Fetching available expansion list from extendedclip.com...
18.02 02:14:37 [Server] INFO Enabling ServerBoosters v1.2
18.02 02:14:37 [Server] INFO ServerBoosters Version 1.2 Has been Enabled!
18.02 02:14:37 [Server] I
18.02 02:14:35 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
18.02 02:14:35 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
18.02 02:14:35 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
18.02 02:14:35 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
18.02 02:14:35 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:188) [spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
18.02 02:14:35 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:162) [spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
18.02 02:14:35 [Server] INFO at com.wasteofplastic.askyblock.ASkyBlock.onEnable(ASkyBlock.java:272) [askyblock.jar:?]
18.02 02:14:36 [Multicraft] Skipped 142 lines due to rate limit (30/s)
18.02 02:14:36 [Server] INFO Preparing start region for level 1 (Seed: 5717360107172692222)
18.02 02:14:36 [Server] INFO Preparing start region for level 2 (Seed: 5717360107172692222)
18.02 02:14:36 [Server] INFO Enabling jAlts v0.1-STABLE
18.02 02:14:36 [Server] INFO Enabling MeapTAB v1.0
18.02 02:14:36 [Server] INFO MeapTAB Activated by HyperGalactic
18.02 02:14:36 [Server] INFO Enabling SimpleAutoBroadcast v1.1.0
18.02 02:14:37 [Server] INFO SimpleAutoBroadcast configuration successfully loaded 8 announcements.
18.02 02:14:37 [Server] INFO Enabling PlaceholderAPI v2.8.2
18.02 02:14:37 [Server] INFO Placeholder expansion registration initializing...
All i could retreive

**Comment by Infinityy1** [comment]
https://hastebin.com/eruhumikuz.sql

**Comment by tastybento** [comment]
Your config.yml is invalid. You probably have tabs in there instead of spaces. Use a YAML validator to check your config file. Like this one: http://www.yamllint.com
