### ISSUE TITLE
Island upgrade Issues after owner transfership

### ISSUE THREAD

**Issue by Disorbs** [tastybento/ASkyBlock-Bugs-N-Features#646]
**Server version:** 1.12.2 Paper

**Plugin version:** 3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**

**Description of issue. What happened?**
So when an owner of an island transfers it to another island member and then that new owner gets an upgrade (permission) it does not work as it seems the island
is still bound to the previous owner.

**Steps to make this happen**

1.  Transfer the ownership to another island member
2. New owner buys an upgrade (permission) and it does not work even after a relog
3. Old owner must buy it for it to work as its still bound to him for some reason

**What do you think should happen?**
Upgrades should work for the new owner not the old one.

**Comment by tastybento** [comment]
Sorry, I cannot replicate this right now. Some questions:

1. What happens between step 1 and 2 above if you do /asadmin info (name of new leader). Are they mentioned as the true leader of this island? Maybe the island isn't transferring ownership properly.
2. what does the console log say when they relog?
