### ISSUE TITLE
Island Levels are not counting correct

### ISSUE THREAD

**Issue by evrenacigul** [tastybento/ASkyBlock-Bugs-N-Features#647]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
spigot 1.8.8

**Plugin version:**
Latest

**What other plugins are you using? (do /plugins and paste here)**
- AdvancedBan
- AntiWDL
- AnvilColors
- Arconix
- ASkyBlock
- AutoPickup
- AutoRestart-reloaded
- BeastWithDraw
- BetterAlias
- CalenderEvents
- ChatColor+
- ChatGames
- ChatManager
- ChestShop
- Citizens
- ClearChat
- ColorMe
- CombatLogX
- CommandNPC
- Crazy Auctions
- Crazy Crates
- Crazy Envoy
- DeluxeMenus
- DragonHunter
- EnjinMinecraftPlugin
- EpicSpawners
- EssentialsX (all of 'em are 2.0.1)
- EssentialsXAntiBuild
- EssentialsXChat
- EssentialsXGeoIP
- EssentialsXProtect
- EssentialsXSpawn
- Exodus
- HeadDrop
- HealthBar
- HolographicDisplays
- HubKick
- InvRestore
- KitPreview
- KOTH
- LeaderHeads
- Lockette
- Microblocks
- MobStacker
- Multiverse-Core
- MythicMobs
- NoNewChunks
- OpenInv
- Parties
- PermissionsEx
- PlaceholderAPI
- PlayerVaults
- Plugin List
- PluginConstructorAPI
- ProAutoMessagesAD
- ProtocolLib
- RealScoreBoard
- RewardVoting
- SafeTrade
- ShopGUIPlus
- SkinsRestorer
- Skript
- SQLibrary
- Stats
- TimeIsMoney
- TitleManager
- UnioAntiCrash
- Vault
- ViaVersion
- VoidSpawn
- votifier
- WorldBorder
- WorldEdit-bukkit
- WorldGuard

**Description of issue. What happened?**
the island levels is not working correctly, for example; my diamond block gives 1 level, and emerald block has 0.5 level. it counts on diamonds (so its integer), however floating numbers are not working like emerald block does. So if we have placed 5 dia blocks and 10 emerald blocks on our island, we get 5 island level. it was working correctly once. but I dont know where this issue started to happen.

**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**
Explained above.

**Comment by tastybento** [comment]
Please share your blockvalues.yml. You can zip it and drag and drop it to this box, or use pastebin.

**Comment by evrenacigul** [comment]
I uploaded config.yml and blockvalues.yml together.
[askyblock_bug.zip](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1740195/askyblock_bug.zip)

**Comment by tastybento** [comment]
Block values must be an integer (whole number), see like 44 of blockvalues.yml:

> # This section lists the value of a block. Value must be an integer.

So, multiply all the block values by say 1000 and set levelcost to 1000 and that will work.
