### ISSUE TITLE
Offline Mode everyone looses island

### ISSUE THREAD

**Issue by thefudgeishot** [tastybento/ASkyBlock-Bugs-N-Features#649]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**1.8.8**

**Latest**

**Not Needed**

**Askyblock works fine in Online mode but now that its in offline mode Everyone is a different player so like say i log on and do /is when i log in on offline mode i have to create a new island but in online mode i can go back to my real island?**

plz help

**Comment by tastybento** [comment]
Yes, in offline mode the player UUID's are made up by the server and completely different to the Mojang UUIDs. You cannot switch between online<>offline mode and keep islands, it's impossible.
