### ISSUE TITLE
Player dies when going to island

### ISSUE THREAD

**Issue by LittleBrittney** [tastybento/ASkyBlock-Bugs-N-Features#650]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:** 1.8

**Plugin version:** Newest

**What other plugins are you using? (do /plugins and paste here)** https://gyazo.com/08df3c35737485e7168f1b1fc96c34a8

**Description of issue. What happened?**
When a player goes to their island with /is they die, i tried this on both of my island schematics, as well as the default one the plugin comes with.
**Steps to make this happen**

1.  Player types /is and dies

**Comment by tastybento** [comment]
Are you setting up a server for the first time, or were you running fine and suddenly this started to happen?
How do players die? What does the death message say?
Do you have a spawn location set for the ASKyblock world? If so, where is it?
Do you have a world border set up?

**Comment by LittleBrittney** [comment]
This problem is fixed now.
