### ISSUE TITLE
Mobs not spawning!!!

### ISSUE THREAD

**Issue by ItzEddeMC** [tastybento/ASkyBlock-Bugs-N-Features#651]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12.2

**Plugin version:**
3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**
 CoreProtect, Worldedit, EpicEnchant, NoRain, AntiAd, AutoRestart, Essentials, Voxelsniper, EssentialsChat, PermissionEx, BukkitCompat, Plugman, HolographicDisplays, SuperVanish, Vault, EssentialsSpawn, WorldGuard, ASkyblock, Auction, ItemSlotMachine, LiteBans

**Description of issue. What happened?**
The mobs are not spawning, And i have tested /asadmin settingsreset all 

**Steps to make this happen**

1. We tried to do /asAdmin settingsreset all but not work

**What do you think should happen?**

**Comment by tastybento** [comment]
What are your config.yml settings? Zip it up and drag and drop it to this box so we can look at it. Also, when you say "mobs" do you mean, all creates, just not monsters, or just not animals?
If you take a spawn egg and as a normal player try to use it on the island, can you? (Make sure spawn eggs are enabled).

**Comment by ItzEddeMC** [comment]
[config.zip](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/1755438/config.zip)

I mean all creates. And its working whit a spawn spawn egg.

**Comment by ItzEddeMC** [comment]
@tastybento

**Comment by tastybento** [comment]
For some reason the zip cannot be uncompressed. Please paste to pastebin.com.

**Comment by NelsCraft** [comment]
@tastybento

**Comment by tastybento** [comment]
Your config.yml is old - from V3.0.0.3. You need to update to the V3.0.8.2 version. You are missing the complete protection section. See your config.new.yml or see this link for the section you are missing: https://github.com/tastybento/askyblock/blob/master/config.yml#L666

**Comment by NelsCraft** [comment]
Ok
