### ISSUE TITLE
Cmd Reward not working

### ISSUE THREAD

**Issue by MoondostriaDE** [tastybento/ASkyBlock-Bugs-N-Features#652]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

1.12.2

Latest

LuckPerms

The RewardCommand for the different challengebooks are not working: http://prntscr.com/ii224c
Is it my mistake or what I have done wrong? I havent get an error message or something else...

**Comment by tastybento** [comment]
That does not look right for YAML.

Do:

rewardscommands:
- 'lp whatever'
- 'lp foobar'

The - sign must be at the same level as the heading for a YAML list. No space. Also the ' should be after the minus sign but before the lp.

Try that.

**Comment by MoondostriaDE** [comment]
Nope, does not working: http://prntscr.com/iiemae

**Comment by MoondostriaDE** [comment]
Ah it works, thanks for your help =)

**Comment by tastybento** [comment]
Great!

(I just meant "whatever" by foobar) :-)
