### ISSUE TITLE
Askyblock stopped working

### ISSUE THREAD

**Issue by darkmage4** [tastybento/ASkyBlock-Bugs-N-Features#654]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12 - Spigot

**Plugin version:**

1.12 | V3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**
https://i.gyazo.com/c49f0ca4586f999ab97bd03f28f2769e.png

**Description of issue. What happened?**
1 day I am on and playing Skyblock, the next day the plugin isn't installed anymore. (On Multicraft server) I still have all the plugin files, and askyblock world. I've backed up all askyblock files, removed the files, and the plugin, and reinstalled it freshly, and now It wont work. I get /is - - /island does not exist. When it very well should exist. As you can see in the SS above, it shows it's not installed, even though it is. https://i.gyazo.com/d2fe992ffd150afd95230f91652f1f1a.png

**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**

**Comment by darkmage4** [comment]
looked into console, and this is what I get:

[skyBlockHoloStats] Enabling SkyBlockHoloStats v1.3
23.02 21:36:06 [Server] INFO [SkyBlockHoloStats] Hooked into ASkyBlock!
23.02 21:36:06 [Server] ERROR Cannot find dependency. Make sure ASkyBlock/AcidIsland and HolographicDisplays are installed.
23.02 21:36:06 [Server] ERROR Plugin cannot start until dependency errors are solved!
23.02 21:36:06 [Server] INFO [SkyBlockHoloStats] Disabling SkyBlockHoloStats v1.3

**Comment by Poslovitch** [comment]
Glad you solved your problem ;)
Thanks for using ASkyBlock :)
