### ISSUE TITLE
Block limits not applying to the full island after using /asadmin setrange

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#655]
**Server version:** 1.8.8
**Plugin version:** 3.0.8.2

**What other plugins are you using?**
Clear install - only Vault.

**Description of issue:**
*Issue submitted by Heliosard, a french server owner.*
Block limits (the video is about hoppers) only apply within "original" island boundaries.
Once the the protection range of the island is increased using /asadmin setrange, the block limits continue to apply within the "original" island boundaries, but don't withing the new range.
https://youtu.be/L_D6FYLqcIM

**What do you think should happen?** 
Hoppers' limit should apply.

**Comment by tastybento** [comment]
I'm sorry, I can't replicate. I tried with both the permission and the setrange command and the checking expanded. Also, the code uses island minx, minz and protection range values for the island, so I'm not sure how this could happen. If the /asadmin info shows the correct ranges after setrange then it should work. Can you see a bug in the code?
