### ISSUE TITLE
Skyblock border wall

### ISSUE THREAD

**Issue by LittleBrittney** [tastybento/ASkyBlock-Bugs-N-Features#657]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:** 1.8.8

**Plugin version:** Newest

**What other plugins are you using? (do /plugins and paste here)**
https://gyazo.com/6233ef4560ee0dd23520cfb7b3a044bb
**Description of issue. What happened?**
There is a blue border around islands, and a few of my players islands have been created outside this border.
**Steps to make this happen**

1. When a player creates an island, it is surrounded by a blue barrier.
2. Some players islands spawn outside another barrier with no border and they can't break or place blocks on the island.

**Comment by LittleBrittney** [comment]
I just noticed I had worldborder, that fixed the problem with players being able to edit islands, but I still see the border around islands after I restarted the server.

**Comment by tastybento** [comment]
ASkyBlock doesn't have barriers around islands. That was never added as a feature, but some other plugin was created by someone else to do it. So, I don't know how to help. What does the border look like?

**Comment by tastybento** [comment]
No answer.
