### ISSUE TITLE
ERROR IN AcidIsland

### ISSUE THREAD

**Issue by JoaquinMunizaga** [tastybento/ASkyBlock-Bugs-N-Features#658]
**Hola. Tengo un problema con el plugin que no se me carga toda la isla, se queda vacía o algunas veces hasta la mitad de la isla con agua y la otra no**

![image](https://user-images.githubusercontent.com/34643923/36641961-112b6fd4-1a17-11e8-855f-ddd9ea5b36e4.png)

**Comment by tastybento** [comment]
Hola. ¿Has seguido las instrucciones de configuración? Parece que el mundo está mal. Intenta eliminar el mundo y reiniciar.
