### ISSUE TITLE
Lighting

### ISSUE THREAD

**Issue by ItzAntony** [tastybento/ASkyBlock-Bugs-N-Features#659]
I've noticed that when islands are pasted in, there tend to be a lot of lighting bugs. With FAWE and W/E they have a command //fixlighting. What if this was to be run when pasting in the island schematic? I attempted to do this on my island that had a lot of lighting glitches and it seemed to work like a charm.

![lighting](https://user-images.githubusercontent.com/20343506/36645029-b6a30b5a-1a5a-11e8-8dcc-7cb04c90bd6a.gif)

**Comment by tastybento** [comment]
That's a nice idea. I assume that if you add it to the start commands for an island it'll work?

**Comment by ItzAntony** [comment]
I've not tried that (Don't even know where to add island starter commands) The issue is, it would need to select around the schematic pasted in order to actually be able to execute //fixlighting. Not sure if there is a way to do it but it would be awesome if there was because that would fix the whole lighting bugs issue.

**Comment by tastybento** [comment]
Aha. Yes, I see. It’s a bit more tricky.

By the way, the commands are in the config.yml. Just do a search for commands. 

However it would not handle the selecting thing.

**Comment by ItzAntony** [comment]
Would there be a way to add it to BSkyblock? The area of the island schematic would be selected and the command would be run on island creation.

**Comment by Poslovitch** [comment]
That remains to be seen I think. BSkyBlock itself just "prints" an hard-coded island. Schematic support will be in an addon. But that should be easily doable.

**Comment by ItzAntony** [comment]
Epic. Should I create a suggestion on the bskyblock github or just leave it?

**Comment by Poslovitch** [comment]
Go ahead.

**Comment by tastybento** [comment]
Schematic support is via FAWE in BSkyBlock for the addon I'm writing, so this should be automatically done.
