### ISSUE TITLE
Limiting Guardians?

### ISSUE THREAD

**Issue by j-Daddy** [tastybento/ASkyBlock-Bugs-N-Features#660]
**Server version: 1.8.8**

**Plugin version: V3.0.8.2**

How do you limit Guardians in SkyBlock?

**Comment by Poslovitch** [comment]
https://github.com/tastybento/askyblock/blob/master/config.yml#L379

Add this line in the list :
```yaml
GUARDIAN: 123456
```

Here is the full list of available entity types in 1.12.2 : https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
