### ISSUE TITLE
Purge limit does not calculate correctly

### ISSUE THREAD

**Issue by tastybento** [tastybento/ASkyBlock-Bugs-N-Features#661]
When purging on the real server I get the feeling the purging works like this:
/asadmin purge 60
Attempting to purge all islands < island level 30 and more than 60 days offline.
Server looks up all islands, abandoned for more then 60 days.
Finds (e.g.) 300 islands. Because max purge is 100 --> takes the first 100.
Of that first 100 only islands with an island level op 30 are purged. --> only 50 islands have those parameters.
Which means that e.g. only 50 islands are purged

Where as I would expect:
/asadmin purge 60
Attempting to purge all islands < island level 30 and more than 60 days offline.
Server looks up all islands, abandoned for more then 60 days AND islands level is under 30.
Finds (e.g.) 200 islands. Because max purge is 100 --> takes the first 100.
First 100 islands with those parameters are purged.
Leaving 200 - 100 = 100 to do in the next batch.

**Comment by x1p** [comment]
Is this bug fixed in version V3.0.8.3?
I don't see it in the bug fixed list of 3.0.8.3
If so, can someone confirm?
If not, why is this issue closed?

**Comment by tastybento** [comment]
Yes, in V3.0.8.3. Sorry, I forgot to include it in the release notes.
