### ISSUE TITLE
API | TopTen Map doesn't have any entries // null

### ISSUE THREAD

**Issue by RedPawC** [tastybento/ASkyBlock-Bugs-N-Features#662]
**Server version:**
1.12.1

**Plugin version:**
V3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**
CleanroomGenerator, TTA, MVdWPlaceholderAPI, FastAsyncWorldEdit, AdvancedOreGen, VoxelSniper, PermissionsEx, PlugMan, Vault, ProtocolLib, WorldEdit, ASkyBlock, Essentials, goBrush, RedsAPI, Multiverse-Core, WorldGuard, ArmorStandTools, WGRegionEvents, HolographicDisplays, SkyBlock, TouchscreenHolograms

**Description of issue. What happened?**
Trying to use the getLongTopTen() Method. But can't get any results out of it. Just gives back null. Tried both versions getLongTopTen() + getTopTen(). Still doesn't give me any values. 

Checked if there are top islands.  Yes, there are, but sadly the Map just has no entries.

**Comment by tastybento** [comment]
That's odd. What do you see if you call TopTen.getTopTenList() directly?

**Comment by RedPawC** [comment]
Broadcasted it with different was. The Set for example just returned [ ]. But the weird thing ist that your top ten list returns the top players.

**Comment by tastybento** [comment]
Just use TopTen.getTopTenList()  instead then.
