### ISSUE TITLE
Confirmation to /is coop

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#667]
Hello,

I recently got reports about players dying in other islands. I denied dying for visitors but when a visitor come to island, island owner are adding visitor to his coop list. So he can die. Island owner kill him with lava or something else and his items are lost. For this reason i think /is coop command also need an /is accept.

**Comment by tastybento** [comment]
How nasty. I'll add it.

**Comment by UnioDex** [comment]
New toxicity level every day...

**Comment by tastybento** [comment]
Okay, should be fixed with that commit.
