### ISSUE TITLE
Problem: Players don't loose food on their own island

### ISSUE THREAD

**Issue by EnObliO** [tastybento/ASkyBlock-Bugs-N-Features#670]
Hi, 
I've got a problem with the aSkyblock plugin:
My players just says me that they don't loose food only on their island. When they go on a random island they loose food.
Is there any option in the config file ?

Server version: 1.12.2

Plugin version: latest

Do you have any idea ?

Regards
EnObliO

**Comment by Poslovitch** [comment]
Maybe should you check the askyblock.nohunger permission?
