### ISSUE TITLE
Minishop

### ISSUE THREAD

**Issue by ShayBox** [tastybento/ASkyBlock-Bugs-N-Features#672]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12.2

**Plugin version:**
3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**
AntiCropTrample, ASkyBlock, Essentials, EssentialsChat, EssentialsSpawn, HungerKeeperPlus, PermissionsEx, Vault, ViaBackwards, ViaVersion, WorldEdit

**Description of issue. What happened?**
Minishop deletes items if your inventory is full

**Steps to make this happen**

1. Fill inventory
2. Open Minishop
3. Buy something

**What do you think should happen?**
Show an error or put it on the ground

**Comment by tastybento** [comment]
Thanks!
