### ISSUE TITLE
Sweeping edge hurts visitors

### ISSUE THREAD

**Issue by ShayBox** [tastybento/ASkyBlock-Bugs-N-Features#673]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12.2

**Plugin version:**
3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**
AntiCropTrample, ASkyBlock, Essentials, EssentialsChat, EssentialsSpawn, HungerKeeperPlus, PermissionsEx, Vault, ViaBackwards, ViaVersion, WorldEdit

**Description of issue. What happened?**
Sweeping edge hurts visitors

**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**

**Comment by tastybento** [comment]
Very interesting. I'll check into it.

**Comment by tastybento** [comment]
I made a sweeping edge sword and hit a visitor, but I see "Target in no PVP area", so I cannot replicate this issue. How did you do it?

**Comment by ShayBox** [comment]
Hit a mob next to the person

**Comment by tastybento** [comment]
I tried, but I couldn't hurt them too. Maybe this is an edge case. How bad is this?

**Comment by ShayBox** [comment]
Well it kills them... so pretty bad, it adds to the visitors death count,
which lowers the island level, which is pretty bad. just set visitors in
godmode when they're on other peoples islands

**Comment by Poslovitch** [comment]
Server owners may not want visitors to be invincible, although we added an option to do so (search for invinciblevisitors in the config). Setting it to true will by default block every type of damage your visitors will take, but it'll consequently disallow PVP.

You should attach your current config.yml so we can maybe try again to replicate the bug on our side.

Thanks

**Comment by ShayBox** [comment]
Well that's the problem, that config setting doesn't make them invincible
because I was able to kill a visitor using sweeping edge, with that on

**Comment by Poslovitch** [comment]
Please attach your current config.yml so we can maybe try again to replicate the bug on our side.

**Comment by ShayBox** [comment]
I'll reinstall the plugin on a test server and make the config again, I
stopped using it because of tons of bugs, i'll also see if I can reproduce
the death again

**Comment by ShayBox** [comment]
https://hastebin.com/sugoduziba That's the config, re-tested and can still be killed with latest version and that config.

**Comment by TheWranger** [comment]
Try adding ENTITY_SWEEP_ATTACK to the list of blocked damage types under invinciblevisitorsoptions.
