### ISSUE TITLE
Minishop Sorting

### ISSUE THREAD

**Issue by ShayBox** [tastybento/ASkyBlock-Bugs-N-Features#674]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12.2

**Plugin version:**
3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**
AntiCropTrample, ASkyBlock, Essentials, EssentialsChat, EssentialsSpawn, HungerKeeperPlus, PermissionsEx, Vault, ViaBackwards, ViaVersion, WorldEdit

**Description of issue. What happened?**
Setting the number of each minishop item doesn't correspond with the slot it appears in

**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**
item1 should be in the first slot
item10 should be in the first slot second row
item20 first slot third row
etc...

**Comment by tastybento** [comment]
Yes, sorry, the mini shop doesn't support slot definitions. You may want to use a dedicated shop plugin that will enable more sophisticated features because I'm not adding new features to ASkyBlock now.
