### ISSUE TITLE
Deaths on visitor island

### ISSUE THREAD

**Issue by ShayBox** [tastybento/ASkyBlock-Bugs-N-Features#675]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12.2

**Plugin version:**
3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**
AntiCropTrample, ASkyBlock, Essentials, EssentialsChat, EssentialsSpawn, HungerKeeperPlus, PermissionsEx, Vault, ViaBackwards, ViaVersion, WorldEdit

**Description of issue. What happened?**
A visitor dying on someones island still counts towards they're death count on island level

**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**

**Comment by tastybento** [comment]
Unless you have visitor deaths turned off, that would make sense. Any deaths would count against you. Do you have visitor deaths turned off?

**Comment by ShayBox** [comment]
I don't know what you mean, there's no option for visitor deaths. there's visitor invulnerability, that's on. but they can't die, so the death count should not go up

**Comment by tastybento** [comment]
If the **invulnerablevisitor** setting is true, then visitors cannot die and the death count does not go up.

If the **invulnerablevisitor** setting is false, then visitors can die and death count goes up.

Where's the problem?

Are you saying that visitors *can* die when visiting another island? If so, how?

**Comment by ShayBox** [comment]
http://shay.is-your.pet/VaQs.png That setting does not exist
http://shay.is-your.pet/cZCV.png This one is set to true
And I was still able to kill a visitor while having them stand next to a bunch of mobs and I used sweeping  edge, and their death count went up.

**Comment by tastybento** [comment]
I’ll try again. How did you make your sweeping edge sword? What are it’s setting?
