### ISSUE TITLE
Vote Crates 

### ISSUE THREAD

**Issue by howy7214** [tastybento/ASkyBlock-Bugs-N-Features#676]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12
**Plugin version:**
ASkyBlock V3.0.8.2
**Description of issue. What happened?**
Hello

I am just needing help with crates I have a voting crate system to allow players to use in my spawn world on askyblock but they cant use it, I change the region so they can use it but when the server reset it goes to island protected can you help me with this?

Thank you

**Comment by tastybento** [comment]
I'm not sure. You could try enabling Visitor Trading. That may help.
