### ISSUE TITLE
Askyblock settings bug even if I /asadmin settingsreset all

### ISSUE THREAD

**Issue by Tikifirst** [tastybento/ASkyBlock-Bugs-N-Features#680]
ASkyBlock version 3.0.8.2
Server version : 1.8.8

Hi !

I've tried de update Askyblock, and now players can't hurt mob in other player's skyblock / use redstone in other player's skyblock / etc...

I've tried to add them permission to /is settings, but even me, OP and '*' permission player, when I do /is settings in my is, it just shows a map that do nothing when clicked. When I'm outside my is, it shows all the settings but I can't touch them.

I've tried to modify default settings in config.yml and confignew.yml and then /adadmin settingsreset all, also tried /asadmin settingsreset <flagIJustChangedInConfig> for each flag I've changed but nothing happened, I restarted the server, reloaded asskyblock, but nothing changed...

Thx a lot for reading !

**Comment by tastybento** [comment]
I suspect you don't have an up to date config.yml file for your plugin version. Make sure that you are using the latest format. Then do /asadmin settingsreset all. Note that config.new.yml is not actually used - it is just there for you to make into config.yml. Then it will operate.

**Comment by Tikifirst** [comment]
Thanks ! Is ther a way to allow players to have more than 1 island ?


2018-03-20 5:13 GMT+01:00 tastybento <notifications@github.com>:

**Comment by tastybento** [comment]
No, that's not an option. Players must use coop or team up.
