### ISSUE TITLE
ASkyBlock Island Biome Error

### ISSUE THREAD

**Issue by yBarttY** [tastybento/ASkyBlock-Bugs-N-Features#681]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:** 1.8.8

**Plugin version:* 3.0.8.2

**What other plugins are you using? (do /plugins and paste here)** WorldEdit, VoidGenerator, PlaceholderAPI, GroupManager, SkyblockOres, Vault, WorldGuard, ShopGUIPlus, CrazyCrates, ASkyBlock, Essentials, EssentialsChat, EssentialsSpawn, Multiverse-Core, DeluxeChat

**Description of issue. What happened?** Every time someone wants to change the biome of their island, it crashes their island and sends this error to console: https://hasteb.in/himazewe.md

**Steps to make this happen**

1. Someone changes their island biome
2. Sends a very long error in console listed above

**What do you think should happen?** Players should be able to change the island biome without their island crashing and sending errors to console.

**Comment by tastybento** [comment]
The error says your disk has run out of space. Do you have enough disk space left?
