### ISSUE TITLE
ASkyBlock Lag Issues

### ISSUE THREAD

**Issue by Disorbs** [tastybento/ASkyBlock-Bugs-N-Features#682]
**Server version:** 1.12.2

**Plugin version:** 3.0.8.2

**What other plugins are you using?:** https://i.gyazo.com/44449f6c717c1618b6736aa69fbb08aa.png

**Description of issue. What happened?:** Player creates an island or Player makes a welcome sign or Player resets their island the server freezes for 5-10 seconds and times out players.

Example of the server doing fine until i made a sign or reset my island:
https://i.gyazo.com/5b7a78ef321336193f5d89d5895f8c00.png
https://timings.aikar.co/?id=ab302eb3a0474df0bd3feb0c66d8f911

10-30 players online

Island Size: 200x200

**Steps to make this happen:**

1. Make an Island (Lag)
2. Create  Warp (Lag)
3. Reset an island (Lag)

**What do you think should happen?:** Not Lag

**Comment by tastybento** [comment]
Those events are when the plugin is saving something. Maybe it's a disk IO thing. In the report, "Minecraft::ASkyBlock" is referring to the world, not the plugin. The tasks that standout are doVillages which is also related to DiskIO. I did some google searches and this random thing does seem to be around either MySQL or file system saving. It can also come from a server bug, e.g. this **old** bug on Paper: https://github.com/PaperMC/Paper/issues/435. What server version / type are you using? Maybe a newer build will help?

**Comment by Disorbs** [comment]
well im 22 versions behind on this server but i have another skyblock server on the same machine that is updated and still has the same issues.

ill check and update it and ill report back.

**Comment by Disorbs** [comment]
I just reset my island and it froze and the server has been online for 6hrs with only 9 people online

Nope other than the vanilla disable, i use ASkyBlock to almost limit all mobs to 10 and villagers to 20
and golems to 25

10gb ram, i7700k nvme 250gb

3m timings of me doing /is reset
https://timings.aikar.co/?id=77aa02f1f3ae4ee9a266e185a9d81c75

**Comment by tastybento** [comment]
I think I know what's happening. Try the 3.0.8.3c prerelease and see if that helps. https://github.com/tastybento/askyblock/releases/tag/V3.0.8.3c

**Comment by Disorbs** [comment]
okay i think it was a major improvement it does not lag or freeze anymore and got my island created right away, i also got this error - https://hastebin.com/fenipiyawi.sql

**Comment by tastybento** [comment]
Okay, that's a bug. I'll fix it.

**Comment by tastybento** [comment]
Please try https://github.com/tastybento/askyblock/releases/tag/V3.0.8.3e

The lag is coming from obtaining player heads. Spigot made a change where obtaining a head would block the thread due to a network call. That could crash the server if it took too long. Now those are done async and cached.

**Comment by tastybento** [comment]
If you see a crash, post the crash log.

**Comment by Disorbs** [comment]
weird i was barely starting the server and when it finished loading skyblock files it crashed.

https://hastebin.com/qofamajube.md

**Comment by tastybento** [comment]
Wow, Mojang's rate limiting is very strict. Only one head per second...
Try this one. I've switched to obtaining the heads 1 per second.
https://github.com/tastybento/askyblock/releases/tag/V3.0.8.3f

**Comment by Disorbs** [comment]
seems to be working now and the islands reset fast now.

im guesing the spam for loading heads should be normal? 0-300 takes around 10m

**Comment by tastybento** [comment]
I can take out the spam - well, most of it. One head should be 1 second, so 300 should only take 5 minutes. Did it really take 10 minutes?

**Comment by tastybento** [comment]
https://github.com/tastybento/askyblock/releases/tag/V3.0.8.3g

Now with less spam.

Please also check /is level.

Thanks.

**Comment by Disorbs** [comment]
okay is level is fine and this is for is top

https://hastebin.com/hiqejafame.vbs

**Comment by tastybento** [comment]
All the heads haven't loaded yet, so that's why it's not working. Hmmm. Let me think if there's a way to do this.

**Comment by tastybento** [comment]
This should work better. I appreciate you testing it. I don't have access to so many users! 

https://github.com/tastybento/askyblock/releases/tag/V3.0.8.3h

**Comment by Disorbs** [comment]
There is a spam of "EntityDeathEvent" either when the warps were loading or after i logged on.

and some pressure plate debug and right click?

**Comment by tastybento** [comment]
Please try https://github.com/tastybento/askyblock/releases/tag/V3.0.8.3i
This removes debug and made more things async.

**Comment by tastybento** [comment]
Regarding coop - I see what you are saying. Let me look into it.

**Comment by Disorbs** [comment]
also i think the warps also got messed up when clicking on the warps on /is top it goes to someone else
or when i do /is warp <player> it goes to someone else.

as for the coops i re-uploaded the old coop list and it doesnt seem to load them in i guess the update does like them lol

**Comment by tastybento** [comment]
There is still a bug there. The Top Ten and Warps are overlapping in their head meta setting. Also, when using signs instead of heads, the top ten doesn't work. I'll work on it tomorrow!

**Comment by tastybento** [comment]
Fixed with latest builds.
