### ISSUE TITLE
Flint and steel

### ISSUE THREAD

**Issue by moroale02** [tastybento/ASkyBlock-Bugs-N-Features#683]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:*1.12*

**Plugin version:*1.12*

**Description of issue. What happened?*there is a problem that the fire does not light up on the island*

**Steps to make this happen**

1. I add the plugin
2. I create the island
3. I take a lighter and set it on fire and it goes out

**What do you think should happen?*it should stay lit.*

**Comment by tastybento** [comment]
Fire is disabled by default. Change it in the config.yml if you like. Set FIRE: true and then do /asadmin settingsreset FIRE.
