### ISSUE TITLE
Server crash after /is top

### ISSUE THREAD

**Issue by AmazedMender16** [tastybento/ASkyBlock-Bugs-N-Features#684]
**Server version:**
CraftBukkit version git-Spigot-c3093ef-7e94e65 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Plugin version:**
v3.0.8.2

**Description of issue. What happened?**
Server crashed after running the command /is top

https://pastebin.com/JAa5qBqM

**Comment by tastybento** [comment]
Fix is in 3.0.8.3 that is in testing now. It retrieves heads async. There was a change in the server code so the getOwner() call can block too long. You can download it here: https://github.com/tastybento/askyblock/releases/tag/V3.0.8.3c

**Comment by AmazedMender16** [comment]
lever and button use doesnt seem to be in /is settings, so people can use players levers to activate their wheat farm for example and steal their crops

Is there anyway you can add a option to disable this in /is settings?

**Comment by tastybento** [comment]
@AmazedMender16 File a separate issue. If you want levers and buttons, add it to the protection settings for an island.

**Comment by AmazedMender16** [comment]
Where do i exactly add it and how? just write

     # Allow lever or button use
     LEVER_BUTTON: false

Under island protection?
