### ISSUE TITLE
Island Near By Issue.

### ISSUE THREAD

**Issue by BruhItzZain** [tastybento/ASkyBlock-Bugs-N-Features#686]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:  1.8 - 1.12.2 (1.13 When Supported/Released)**

**Plugin version:*  ASkyBlock V3.0.8.2*
 
**What other plugins are you using? Plugins: https://ibb.co/mVycN7 **

**Description of issue. What happened? The Issue Is When A Player Creates A Island And Another Player Creates A Island You Can See Them Both From A Close Distance Which Ain't Good! As Players Can Grief They Steal Without You Knowing Any Other Sort Of Things! So I Was Wondering If I Can Get Help, With This Issue. **

**Steps to make this happen**

1.  2 Or More Players Create A Island
2. Will Be Able To See From A Far Distance 
3.

**What do you think should happen?**
I think that, it shouldn't be able to see each others islands, and be in a different worlds, Thank you for  helping and i hope i get a response and good bye.

**Comment by tastybento** [comment]
First of all, islands are protected from other players by default.

Second, if you want players to not see each other you'll need to reduce the viewing distance in your server settings or make the island distance larger (like 400). BUT YOU CANNOT CHANGE ISLAND DISTANCE MID-GAME! You will need to do a reset if you change the island distance.
