### ISSUE TITLE
Island homes

### ISSUE THREAD

**Issue by AmazedMender16** [tastybento/ASkyBlock-Bugs-N-Features#687]
**Server version:**
CraftBukkit version git-Spigot-c3093ef-7e94e65 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Plugin version:**
v3.0.8.2

**Description of issue. What happend?**
When the island leader sets multiple homes for the island. Party players cannot go to those homes they teleport straight to the default /is go 
Even while using a number behind it they still go to the default home. This does not occur with the island leader

**Comment by tastybento** [comment]
Yes, this is not a bug. Each player sets their own homes.
