### ISSUE TITLE
warps.yml takes 10min to load on latests spigot builds.

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/ASkyBlock-Bugs-N-Features#690]
I come from this: https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/610
Sorry I didn't reply because I decided to use the old spigot version and forget the new versions.

Today I have decided to try it again and I have realized that the server finally loads, but it takes 10minutes to load the warps.yml:

25.03 **07:32:32** [Server] INFO [ASkyBlock] Loading warps...
25.03 07:34:37 [Server] INFO [Metrics] Connection timed out (Connection timed out)
25.03 **07:41:15** [Server] ERROR Spawn eggs must be described by name. Try one of these (not all are possible):
25.03 07:41:15 [Server] ERROR ELDER_GUARDIAN
25.03 07:41:15 [Server] ERROR WITHER_SKELETON
.
.
.

If I delete warps.yml, it load fine. But I guess it will load slow again when warps.yml gets filled again.

This issue doesn't happen on older Spigot Builds (same askyblock version).
I'm using latest askyblock version https://github.com/tastybento/askyblock/releases/tag/V3.0.8.3h

**Comment by tastybento** [comment]
Can you paste in your warps.yml (the big one) to this ticket? You'll need to zip it up.

The warp loading should be async in the latest version you are using. It will load the heads slowly, but it should not block so what you post is weird. I'd like to try and replicate it.

**Comment by tastybento** [comment]
Also, can you share the version that works? I’d like to see what they changed.

**Comment by tastybento** [comment]
Try https://github.com/tastybento/askyblock/releases/tag/V3.0.8.3i

I made a big list for fake UUIDs and it seemed to simulate okay. Let me know if this is faster. Basically, everything is async now so the warp text and heads load gradually.

**Comment by YellowZaki** [comment]
That version loads fast warps.yml but in the server there are huge lag spikes.

**Comment by tastybento** [comment]
Okay, weird... Can you share timings please?

**Comment by YellowZaki** [comment]
The server lags completely when this message appears in console:

[Server] INFO [ASkyBlock] Loading player heads (Rate limit is 1 head/s): 520 to go...

I'll share timings

**Comment by tastybento** [comment]
Okay, I know what's happening.

**Comment by tastybento** [comment]
Can we chat on Discord - https://discord.gg/2j2Zsu - faster than Github.

**Comment by tastybento** [comment]
Fixed in 3.0.8.3. Should be released soon.
