### ISSUE TITLE
askyblock not compatible in luckperms

### ISSUE THREAD

**Issue by ProDash1998** [tastybento/ASkyBlock-Bugs-N-Features#692]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12.2
**Plugin version:**
lastes
**What other plugins are you using? (do /plugins and paste here)**
luckperms askybclock vault essential multiversecore
**Description of issue. What happened?**
Askyblock not checking permission negation (/lp group default askyblock.island.*) and playes can using this command. I have blocking command in played and giving permission vips
**Steps to make this happen**

1.  use command /lp group default permission set (permission) deny
2.
3.

**What do you think should happen?**

**Comment by tastybento** [comment]
It looks like you are using the wrong command to negate a permission. It is not:

/lp group default permission set (permission) deny

It is:

/lp group default permission set (permission) (true/false)

Providing a value of "false" will negate the permission.

See: https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission
