### ISSUE TITLE
Help, players can place blocks on islands and idk how to fix it

### ISSUE THREAD

**Issue by H1DD3NxN1NJA** [tastybento/ASkyBlock-Bugs-N-Features#696]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version: 1.8.8

**Plugin version: 3.0.8.2

**What other plugins are you using? (do /plugins and paste here)**

**Description of issue. What happened?
Players can place blocks on other players islands and i cant find a solution to fix it

**Steps to make this happen**

1. go to a players island
2. place a block
3. islands griefed

**What do you think should happen?**
players shouldnt place blocks on other players islands without being added

**Comment by H1DD3NxN1NJA** [comment]
Config.yml: https://pastebin.com/hxvdvHW6

**Comment by tastybento** [comment]
They can place blocks because on line 765:

     # Players can place blocks
     PLACE_BLOCKS: true

Set that to false. Then do **/asadmin settingsreset all**
Or you can add it to the island: section.
