### ISSUE TITLE
Homestead Challenge not working on 1.12.x

### ISSUE THREAD

**Issue by tastybento** [tastybento/ASkyBlock-Bugs-N-Features#697]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12.2

**Plugin version:**
3.0.8.3

**What other plugins are you using? (do /plugins and paste here)**
N/A

**Description of issue. What happened?**
Homestead does not detect item.

**Steps to make this happen**

1. Collect items
2. Try to complete homestead
3. Says items are not there

**What do you think should happen?**
It should work.

**Comment by poma123** [comment]
This issue is still present. (version 3.0.8.4)

**Comment by tastybento** [comment]
Which part fails?

**Comment by tastybento** [comment]
I just tested 3.0.8.**4** again and it seems to work for me. I'd like to know which item is not working for you @poma123

**Comment by poma123** [comment]
![image](https://user-images.githubusercontent.com/25465545/38328067-33963198-384a-11e8-94c8-7939195d8760.png)
The items in the challenges.yml:
![image](https://user-images.githubusercontent.com/25465545/38328092-438be9b2-384a-11e8-88ae-da857ff2ead4.png)

**Comment by tastybento** [comment]
Yes, works for me. So what's different? Where are you getting the plugin from? Also what specific server type are you using? Can you try https://github.com/tastybento/askyblock/releases/tag/3.0.8.4c?

<img width="565" alt="screen shot 2018-04-04 at 3 26 19 pm" src="https://user-images.githubusercontent.com/4407265/38338025-a3bb5db4-381c-11e8-8181-0bcc7eb1a4a9.png">

**Comment by poma123** [comment]
On this morning the plugin auto-downloaded and updated to the latest (3.0.8.5) version from spigot, and now its working. Thanks, the issue is now solved.
