### ISSUE TITLE
Change allowspawneggs to be island-specific as well as global.

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#70]
_From @tastybento on December 17, 2015 20:56_

allowspawneggs is currently a global setting. If it is allowed, players should be able to allow visitors to use eggs or not on their island.

_Copied from original issue: tastybento/askyblock#142_

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#74
