### ISSUE TITLE
Top Ten Skins are gone

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#700]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.8.8
**Plugin version:**
3.0.8.3 (latest on Spigot)

**Description of issue. What happened?**
I upgraded from 3.0.8.3purge to latest version and this problem started to happen. 

Here what top ten looks like:
http://prntscr.com/iz39ib

**Comment by Poslovitch** [comment]
Heads are now loaded async when they are needed, this helps avoid a crash-issue which was making the server hanging when getting heads due to changes in the server code.
You just have to wait for the heads to show up.
