### ISSUE TITLE
Item duplication bug with cooping

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#701]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.8.8
**Plugin version:**
3.0.8.3purge
**What other plugins are you using? (do /plugins and paste here)**
I have a plugin when you broke a spawner it automatically sends it to your inventory synchronously if event is not cancelled.

**Description of issue. What happened?**
If you give a player coop and when he broke spawner use /is coop <name> and /is uncoop <name> immediately, items will be duplicated in inventory. I don't know if this bug can happen without my custom spawner plugin. 

Also with latest version cooping is happening with confirmation. So it will be harder to do this bug but still if there is something async with cooping that can be an issue.

**Steps to make this happen**
I captured a video. First he only have 1 spawner. After bug has done he has 2. https://youtu.be/99vP8dx14Aw

**What do you think should happen?**
I think cooping is async. So it needs to be sync. (I might be total wrong i don't know.)

**Comment by UnioDex** [comment]
Found more data. If you start breaking when coop and finish without cooping the item will come to you but will not broken. It is probably related with my spawner plugin but still i wanted to inform.

**Comment by UnioDex** [comment]
I added this litte code to my plugin's BlockBreakEvent and problem is solved.:
```if (asb != null) {
			if (!ASkyBlockAPI.getInstance().playerIsOnIsland(player)) {
				event.setCancelled(true);
				return;
			}
		}```

**Comment by Poslovitch** [comment]
Great!
