### ISSUE TITLE
Not recognising CMI's economy

### ISSUE THREAD

**Issue by TheWranger** [tastybento/ASkyBlock-Bugs-N-Features#703]
**Server version:**
1.12.2
**Plugin version:**
V3.0.8.4 (Running AcidIsland)
**Description of issue. What happened?**
AcidIsland (and I'm guessing ASkyBlock too) doesn't recognise CMI's economy.
[02:14:06 WARN]: [AcidIsland] Could not set up economy! - Running without an economy.

I've also opened an issue with CMI.
https://github.com/Zrips/CMI/issues/184

**Comment by tastybento** [comment]
We use Vault, so if CMI isn't enabled via Vault then that's probably why.
