### ISSUE TITLE
Change permissions for island owner in Server Manager

### ISSUE THREAD

**Issue by Baw-Appie** [tastybento/ASkyBlock-Bugs-N-Features#704]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:** 1.12.2

**Plugin version:** 3.0.8.3

**What other plugins are you using? (do /plugins and paste here)**
Plugins (71): BawAccount, WordFilter, GroupManager, VoidWorld, PlugMan, BawService, FarmProtect, BetonQuest, VoxelSniper, NoteBlockAPI, AntiJoinBot, IPLog, CoreProtect, JukeBox, WorldEdit, OpenInv, Essentials, NBTEditor, ClearLag, AdvancedBan, SmartBackup, ProtocolLib, GattSK, iDisguise, WildSkript, EssentialsChat, EffectLib, TriggerTool2, Vault, ProtocolSupport, ClientStats, WorldGuard, ASkyBlock, LockettePro, ProtocolSupportLegacySupport, EssentialsSpawn, MagicSpells, Skript, InvSK, skDragon, IllegalStack, SkQuery, Multiverse-Core, SkStuff, TreasureChest, Citizens, ColoredTags, Shopkeepers, skUtilities, ProtocolSupportStuff, ChestShop, AuthMe, ExtrasSK, HolographicDisplays, SkriptJSON, WolvSK, Holograms, SkinsRestorer, skRayFall, MythicMobs, Quests, MoreFish, Minigames, SkUniversal, BedwarsRel, Skellett, Minigames-Regions, Skywars, Umbaska, SharpSK, TuSKe

**Description of issue. What happened?**
If an island owner is blocked on the server
The administrator of the server can not change the leader of the island.

Sorry, I can not speak English well.
**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**

**Comment by tastybento** [comment]
Kick all the team members using the admin command, then add them to the new leader.
