### ISSUE TITLE
Players Islands "Protected"

### ISSUE THREAD

**Issue by Tyleeeer** [tastybento/ASkyBlock-Bugs-N-Features#706]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.12.2
**Plugin version:**
1.1.1
**What other plugins are you using? (do /plugins and paste here)**
can't show to public so DM if required
**Description of issue. What happened?**
Player islands are protected they can't build or break
**Steps to make this happen**

1. Restarted The Server
2. Some islands got protected
3. Then We don't know how to fix we tried everything

**What do you think should happen?**
It should get fixed (I don't know)

**Comment by tastybento** [comment]
Is the plugin version really 1.1.1? Hopefully not!

Often I see this error when the island distance in config.yml has been changed mid-game. If so, I recommend you reset or change the startx and startz values in config.yml to something big so new islands are made far, far away from the others so they don't overlap.
