### ISSUE TITLE
Is it possible to use the classic SkyBlock island?

### ISSUE THREAD

**Issue by ioixd** [tastybento/ASkyBlock-Bugs-N-Features#707]
Not that I have a problem with the current sphere look, but I'd like to emulate the classic feel of SkyBlock. Is there anyway I could set it to generate the island from [the original SkyBlock map?](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/maps/1473433-surv-skyblock) Thank you in advance.

**Server version:** 1.12.2

**Plugin version:** 3.0.8.3

**What other plugins are you using? (do /plugins and paste here)** SetHome, WorldEdit, PermissionsEx, ChatControl, LongChat, SignWarper, Vault, WorldGuard, ASkyBlock, PlotSquared, Multiverse-Core, DiscordSRV, Multiverse-Portals

**Comment by tastybento** [comment]
Yes. Just make the island how you like, then use WorldEdit to save it as a schematic. Then put it in the schematics folder of ASkyBlock. Either overwrite the old island, or create a new one and define it in the schematicsection of config.yml (at the end). Make sure that your island has one bedrock block in the middle of it. 

There is a video here: https://youtu.be/IAurS45Uhy4

**Comment by ioixd** [comment]
Thanks!

I know feature requests aren't allowed but would you consider making this possible without using schematics? Like an option in the config? Thanks.

**Comment by Poslovitch** [comment]
Well, providing an option in config would likely result in people don't know what they're doing and coming here to say "hey, mine custom islands no longer working, can you fix him asap pls".
In my opinion, it's better to let the users config it by themselves, although it might be interessant to provide this as a default schematic on BSB's schematics addon. Why do you think about it @tastybento ?

**Comment by tastybento** [comment]
I definitely want to include it in the BSB island options.
