### ISSUE TITLE
/is top broken

### ISSUE THREAD

**Issue by ScuroK** [tastybento/ASkyBlock-Bugs-N-Features#708]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
Spigot 1.12.2
**Plugin version:**
V3.0.8.4

**Description of issue. What happened?**
When i do /is top if sometimes doesnt show anything at all or it shows the wrong islands (for example new ones). 
Only way to fix it is to manually generate the toplist via command. But next day the toplist was gone again.
We have a very large player-database. Maybe thats why? Maybe you could add a purge option for old playerdata aswell not only the islands?

**Steps to make this happen**
/is top

**What do you think should happen?**
should automatically show the correct top list

**Comment by tastybento** [comment]
Bad bug. Fixed.

https://github.com/tastybento/askyblock/releases/tag/3.0.8.4c
