### ISSUE TITLE
Can't Chance Color code for Challenges

### ISSUE THREAD

**Issue by drnikolas** [tastybento/ASkyBlock-Bugs-N-Features#709]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:** 1.8.8 spigot

**Plugin version:** latest

**What other plugins are you using? (do /plugins and paste here)** can't show to public so DM if required

**Description of issue. What happened?** You can't chance the color codes for the challenges .... I want to full chance the color codes for challenges how I can do that?? I want to chance the name for green to something else .... I want to chance the "All requ......" from red to something else ....

**Steps to make this happen**

1. go to the plugin folders open askyblock
2. go to the challenges folder 
3. Edit and save

**What do you think should happen?** You should be able to full chance the color codes

**Comment by tastybento** [comment]
This is ASkyBlock, everything is customizable!

Look in the locale files. For example in the en-US.yml file in the challenges section, you can do:
itemTakeWarning: "&aAll required items|are taken when you|&9complete this challenge!"

The | symbol = new line

In challenges.yml you can colorize the description like this:

description: '&cCreate &d1 block &eof &fglass'
