### ISSUE TITLE
Makeleader commands

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#71]
_From @YellowZaki on November 16, 2015 22:51_

There are options to set commands when a user leaves an island, restart an island and when the user start a new island, but there isn't an option to set command for a user that have just got an island by makingleader him. Right now, when a user A type /is makeleader B, the leave commands are executed for B.

_Copied from original issue: tastybento/askyblock#127_

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#60
