### ISSUE TITLE
Island restarts

### ISSUE THREAD

**Issue by Owner-Arnaw** [tastybento/ASkyBlock-Bugs-N-Features#710]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.8
**Plugin version:**
V3.0.8.5
**What other plugins are you using? (do /plugins and paste here)**
AnimationLib, WorldEdit, TitleMotd, Essentials, PlaceholderAPI, PacketListenerApi, ClearLag, MessageAnnouncer, MapManager, ActionHealth, WorldGuard, ProtocolLib, OldCombatMechanics, NoPluginPlus, EssentialsProtect, EssentialsChat, EssentialsGeoIP, PermissionsEx, EssentialsAntiBuild, SimpleAPI, Vault, EssentialsSpawn, MassiveCore, ScoreboardPlus, AnimatedMenu, CrazyCrates, AnimatedFrames, Jobs, CreativeGates, SimplePets, Citizens, ASkyBlock, ShopChest, CommandNPC, ProtocolSupport, Multiverse-Core, SkinsRestorer, ProtocolSupportLegacySupport, TAB, ProtocolSupportStuff, HolographicDisplays
**Description of issue. What happened?**
In the config.yml and config.new.yml i set  to -1(unlimited restart islands) but doesn't work
**Steps to make this happen**

1. /is restart
2./is confirm
3. You have 1 restart left

**What do you think should happen?**
I don't know

**Comment by tastybento** [comment]
Run /asadmin clearresetall to set everyone to the new setting you just put in config.

BTW, config.new.yml is not actually used by anything - it's just there for you to look at.
