### ISSUE TITLE
Fakeplayer doesen't work 

### ISSUE THREAD

**Issue by elleven11** [tastybento/ASkyBlock-Bugs-N-Features#711]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version: 1.7.10 (KCauldron, FTB Infinity Evolved Skyblock)**

**Plugin version: V3.0.8.5**

**What other plugins are you using? (do /plugins and paste here)
 Plugins (12): PermissionsEx, PlugMan, WorldEdit, Vault, Essentials, EssentialsSpawn, ItemRestrict, EssentialsChat, WorldGuard, ASkyBlock, Multiverse-Core**

**Description of issue. What happened?
Yeah soo, i put in fakeplayer these:

```
   fakeplayers:
   - [CoFH]
   - [BuildCraft]
   - ComputerCraft
```

but none of these work, when i try whit like worldguard it works whit the same names, but whit asb it doesen't. GIF of a mining well: https://gyazo.com/6cf7e4e314205a35d1726cdcd7b37b5f (This is the same for querries, autonomous activators [CoFH] and turtles [ComputerCraft])

Also, if i set the autonomous activator to place blocks it does the same.
**

**Steps to make this happen**

1. Open a modpack server whit the mods i mentioned
2. Make an island
3. Try to break something whit BuildCraft's querry or whatever else

**What do you think should happen?**
Break/Place the blocks?

**Comment by elleven11** [comment]
Also, how do i disable challenges? i already have a quest plugin and i dont need those.

**Comment by tastybento** [comment]
This will need some debugging. Please run this version: https://github.com/tastybento/askyblock/releases/tag/fakeplayers1

Then look in your console for **DEBUG: block placed by ** followed by the name of the fake player that is placing the block. Let me know what it says. That name should be incur list of fake players. If it already is, then maybe your config.yml syntax is wrong. Paste your config so I can check it.

In regards to challenges, use permissions. Give your players the default negative perm -askyblock.challenges.

**Comment by tastybento** [comment]
Any luck?

**Comment by md5sha256** [comment]
Getting the EXACT same issue as OP, 

Server version: KCauldron version 1.7.10-R0.1-SNAPSHOT

**Plugins**
Plugins (11): PermissionsEx, GUIShop, WorldEdit, HolographicDisplays, Essentials, Vault, EssentialsSpawn, EssentialsChat, WorldGuard, ASkyBlock, SilkSpawners

**Description of issue. What happened?**
My config.yml has this: 

```
   fakeplayers:
   - [CoFH]
   - [BuildCraft]
```

My console is showing this: (I used the Debug Version)
[ASkyBlock] DEBUG: block placed by [CoFH]

My syntax should be correct yet. 
Config.yml: https://hastebin.com/ozetoxezuk.yaml
