### ISSUE TITLE
[Support Request] ChestShop x ASB

### ISSUE THREAD

**Issue by RajOG** [tastybento/ASkyBlock-Bugs-N-Features#713]
Hey, this isn't really a bug report, but more like a support request. I was wondering what portion of the ASB config handled sign interactions, as right now whenever a player tries to right/left click a sign, it returns a message saying that only a Co-Oped Island Member may do that

**Comment by tastybento** [comment]
There's no special sign handling, only block protection, i.e, stopping someone from block breaking. Also, I don't recognize that error message. Need more info...
