### ISSUE TITLE
island corrupt

### ISSUE THREAD

**Issue by DesmenNarco** [tastybento/ASkyBlock-Bugs-N-Features#714]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.8.8

**Plugin version:**
3.0.8.3

**What other plugins are you using? (do /plugins and paste here)**
sTablist, NoDupe, noHopperCraft-Desmen, HungerKeeperPlus,reward voting,cratekey, tagsgui,clearlag,permascoreboard,buycraftx,votifier,nightvision,kitadder,fastAsyncworldedit,knockbackeditor1.8, Essentials chat, spawnerupgrades,permissionsex,hcteamsfreeze,customcrates,no_explosions,expierence bottle,vault,simplerename,dailybonus,essentials_kitgui,auctionhouse,ASkyblock,Playervaults,Autosell,multiverise core,coloredtags,IslandFly,sellStick,Holographicdisplays,worldguard,mobstacker,skyblockHolostats,silkspawners,guishop

**Description of issue. What happened?**
when i reload the server my islands disapear

**Steps to make this happen**

1.  reload
2. wait 
3. poof

**What do you think should happen?**
islands should not disapear

**Comment by CoolLord22** [comment]
Well, to my understanding you're not supposed to /reload anyways... it's been known to break stuff https://www.spigotmc.org/threads/server-command-reload.50037/

**Comment by tastybento** [comment]
Post console logs of the shutdown and start up showing the errors. There will be errors for sure if what you say is happening is happening.
