### ISSUE TITLE
Island levels are calculating wrong

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#715]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:**
1.8.8

**Plugin version:**
3.0.8.5

**Description of issue. What happened?**
Island levels are calculating wrong in one island. I couldn't find more islands that have this issue but if i find i will add here.

**Steps to make this happen**

https://youtu.be/8zXloT4I_Mw (uploading, it'll be ready in 15-20 minutes.)

In video i did these;
- Showed the info of nearest high level island. And recalculate the level.
- Showed the info of the buggy island. And recalculate the level.
- There is no way that island is 150k level. It should be 1000 maximum.

**What do you think should happen?**
It might calculate blocks from near islands but i don't know actually.

**More data:**
In config;
island.distance = 110
island.protectionRange = 108 (There is no island has more than this protection range.)

**Comment by tastybento** [comment]
Run the admin level command in the console and it'll give you a full report on why the level is what it is.

Do /asadmin level (name of player)

**Comment by UnioDex** [comment]
Here is the output:
https://pastebin.com/537bcaAj

Diamond blocks and lapis blocks seems wrong.

**Comment by tastybento** [comment]
Without seeing the island, I would not know if this is right or not. If you do /asadmin info (name of player) are the protection ranges correct? I'd go to those coords and have a look around. There should be a stack of diamond blocks around somewhere in that space.

**Comment by UnioDex** [comment]
I checked and i am really confused.

Here what i did:
- I first checked Protection Range coords. And it was OK. Everything was correct.
- Then i checked Islands Limits and it was wrong. I teleport myself to limits and selected as position in WorldEdit. And then i turned the area to stone with //set 1 and it set stone right island not players island. Not the island between protection range.
- And the strange part is right island also have no any diamond blocks so level shouldn't be that high.

I might be wrong while doing this checks. So i recorded. Here the video:
https://youtu.be/n2n2bansLzQ

**Comment by tastybento** [comment]
It's difficult for me to see on the video because the text is small and fast, but here's some things you can try:

Do /asadmin info (name of player)
compare the results to doing
/asadmin info
when on the island. If it is different, then the islands.yml and player files are out of sync for some reason.

Also, when you run **asadmin level (player)** in the console log, you should see this at the top:

Level Log for island at (location)
Island owner UUID = xxx

Can you confirm that the location in the report matches where you are searching?

Right now, I think the best idea would be for you to share with me this world file, the ASkyBlock folder and the player's yml file (not all of the player files, just this one). I'll fire up a copy and run debug on it to find out what is going on.

**Comment by UnioDex** [comment]
/asadmin info <player>, /asadmin info result comparison (it is equal): http://prntscr.com/j3gxbc
/asadmin level <player> output: http://prntscr.com/j3h04o

All locations are matches.

I can share my world with you but i'm not sure if you want it. Because it is 50 GB. If you are ok with big file i can compress, upload it and send.

**Comment by tastybento** [comment]
Yes, I'm fine with the file size. Please also upload your config.yml file, islands.yml file and the player's yml file. That should be enough for me to replicate.

**Comment by UnioDex** [comment]
Sent you with PM from Spigot.

**Comment by tastybento** [comment]
Found the problem. It was counting into the next door island.

**Comment by tastybento** [comment]
Big thanks by the way!

**Comment by UnioDex** [comment]
You're welcome. Thank you for keeping this plugin updated!
