### ISSUE TITLE
[ONLY PAPERSPIGOT] /asadmin purge not deleting islands from the world

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/ASkyBlock-Bugs-N-Features#716]
**Server version:**

PaperSpigot 1.12.2

**Plugin version:**

3.0.8.5

**Description of issue. What happened?**

Yesterday I did a purge of a lot of islands and then I did /asadmin purge users. Then I did /asadmin purge unowned and it showed there was 9000 islands unowned, which is a lot.

I ran the purge for the first 500 islands and I was checking all the coordinates where the island was supposed to be deleted. But any islands was being deleted in the world, although they were dissapearing from islands.yml. So, how can I delete those islands?

Now, I'm not sure if the islands from the first purge were deleted (because /asadmin purge days doesn't show the coordinates, only the playername so I couldn't go to the island.)

**EDIT**: I have recovered the coordinates of a user whose island was supposed to be deleted and the island hasn't been deleted, only his userfile has been changed to hasIsland:false.

Idea for a solution:

Once purge is fixed:
A option to scan all the world and save the islands coordinates (it detects the bedrock) without owner to a file. Then, /asadmin unowned would delete those islands.

**Comment by tastybento** [comment]
The purge occurs async and to delete that many islands would take a very long time. It could literally take hours. If you stop the server before the islands are deleted, then they will not be removed. I suggest you try again with just a few islands and then see if they are deleted okay, and then build from there.

**Comment by YellowZaki** [comment]
One question, how are unowned island counted? Are they added to islands.yml when the plugin finds a island (by detecting the bedrock) with no owner?

**Comment by tastybento** [comment]
Its done when a player tries to make a new island. When you restart the server, the plugin will search from the startx, startz coordinates in config.yml. If it sees any blocks within a +/- 5 block radius around the location in x or z and from y=10 to y=255, it will mark the spot as occupied and add it to the islands.yml file with an owner of null.
So, to "force" a scan, all you need to do is start the server and create a new island. If you have some many, that initial request could take a while!
Then run the purge unowned and they will be removed one by one.

**Comment by tastybento** [comment]
BTW, I just tested with PaperSpigot and a few islands and all the islands were deleted. What are your island distance and protection range settings? Note that until you see something like this, the islands will not be deleted:

[17:47:59 INFO]: Finished purging of inactive islands.
[17:47:59 INFO]: Now waiting...
[17:48:44 INFO]: [ASkyBlock] Finished biome change for  (PLAINS)
[17:48:45 INFO]: [ASkyBlock] Finished biome change for  (PLAINS)
[17:48:46 INFO]: [ASkyBlock] Finished biome change for  (PLAINS)
[17:48:47 INFO]: [ASkyBlock] Finished biome change for  (PLAINS)
[17:48:48 INFO]: [ASkyBlock] Finished biome change for  (PLAINS)
[17:48:57 INFO]: [ASkyBlock] Finished island deletion
[17:48:58 INFO]: [ASkyBlock] Finished island deletion
[17:48:59 INFO]: [ASkyBlock] Finished island deletion
[17:49:00 INFO]: [ASkyBlock] Finished island deletion
[17:49:01 INFO]: [ASkyBlock] Finished island deletion

**Comment by tastybento** [comment]
BTW, I found an issue with purging that may have caused the server to run too slowly.

**Comment by YellowZaki** [comment]
It must be a paperspigot setting what is causing it. On Spigot, island deletion from world is fine.
