### ISSUE TITLE
Question to the Command /is invite 

### ISSUE THREAD

**Issue by Diserix** [tastybento/ASkyBlock-Bugs-N-Features#717]
Hey i have a Question to the Command /is invite <Player>

If I send an invitation to a player he gets it but I want that if he gets the message / ai [accept / reject] should be changeable. Unfortunately, I find in the locale message file no message with it. is it wanted? If it does not exist, I would be happy if this message is changeable.

Kind regards,
Ralf/Diserix

**Comment by tastybento** [comment]
I answered on spigot, but the text "/ ai [accept / reject] " is a command and cannot be changed because commands are fixed.
