### ISSUE TITLE
Island delete bypass Island custom range

### ISSUE THREAD

**Issue by YellowZaki** [tastybento/ASkyBlock-Bugs-N-Features#719]
**Server version:**

Spigot 1.12.2

**Plugin version:**

3.0.8.5

My settings:
```
   distance: 120
   protectionRange: 100
```

**Description of issue. What happened?**

Island A has a protection range of 120.
Island B has a protection range of 100.

If I delete Island B, this happens:

![2018-04-09_14 06 10](https://user-images.githubusercontent.com/13599841/38497169-7c4d5cea-3c00-11e8-8df1-3322f6e8910a.png)

This problem doesn't occur on another side of the Island A when I delete Island C.

**Comment by tastybento** [comment]
What are the island coordinates of island A and B?

**Comment by YellowZaki** [comment]
Island A center coordinates: 720, -1080
Island B center coordinates: 720, -960
