### ISSUE TITLE
Add ability to block incoming invitations.

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#72]
_From @tastybento on August 16, 2015 17:44_

_Copied from original issue: tastybento/askyblock#72_

**Comment by Poslovitch** [comment]
Please put it in 3.0.5 milestone. I ll work on it @tastybento

**Comment by Poslovitch** [comment]
_From @tastybento on December 6, 2016 22:37_

Let's move to 3.0.6 so we can release 3.0.5.

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#61
