### ISSUE TITLE
Nether - Homestead challenge

### ISSUE THREAD

**Issue by AmazedMender16** [tastybento/ASkyBlock-Bugs-N-Features#721]
**Server version:**
git-Spigot-b6ecf3b-fb423b8 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Plugin version:**
3.0.8.3

**Description of issue. What happened?**
The challenge seems to be buggy players are receiving the following text messages. https://imgur.com/a/gLVcA

**Comment by tastybento** [comment]
A fix was put into 3.0.8.5. Please try it.
