### ISSUE TITLE
Players can not break blocks or do anything On there island when created "Island Protected" 

### ISSUE THREAD

**Issue by BruhItzZain** [tastybento/ASkyBlock-Bugs-N-Features#722]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:*1.8 - 1.12.2*

**Plugin version:* V3.0.8.5*

**What other plugins are you using? (do /plugins and paste here)* https://ibb.co/dLcF4x
https://ibb.co/cH7F4x
https://ibb.co/gJshjx
https://ibb.co/kQYoPx
https://ibb.co/nzveWc
https://ibb.co/bKF2jx*

**Description of issue. What happened?* When players execute command: /Is and then they try break blocks or do anything on there island and it says "Island Protected" *

**Steps to make this happen* /Is When created island or /Island*

1. 
2.
3.

**What do you think should happen?* You are allowed to do stuff break blocks open chests and do stuff etc on your island.,*

**Comment by tastybento** [comment]
If you are starting a world from scratch, do a full reset: stop the server, delete everything in the ASkyBlock folder except for config.yml, and also delete the ASkyBlock and ASkyBlock_nether world folders. Then restart.

If this is an upgrade of a system that previously was running, then you probably have changed the island distance setting in config.yml to make it different from before.
