### ISSUE TITLE
Broken Update: AcidIsland

### ISSUE THREAD

**Issue by doitliketyler** [tastybento/ASkyBlock-Bugs-N-Features#726]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper 1.12.2

**Plugin version:**
V3.0.8.6

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
V3.0.8.5

**Description of issue. What happened?**
Getting a console error and the plugin won't load: https://pastebin.com/raw/s6fz7ssZ

**Steps to make this happen**
1. Update from V3.0.8.5 to V3.0.8.6

**What do you think should happen?**
No console error and plugin should load.

**Comment by tastybento** [comment]
Sorry! Please redownload from Spigot. I just uploaded the correct file.
