### ISSUE TITLE
AcidIsland Broken!

### ISSUE THREAD

**Issue by ScuroK** [tastybento/ASkyBlock-Bugs-N-Features#727]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.12.2
**Plugin version:**
V3.0.8.6

After updating today, all commands dont work anymore! Pls fix

**Comment by ScuroK** [comment]
when i do /acid it retunds "/acid" in chat. if i do /is it tells me i cant use that command now.

**Comment by tastybento** [comment]
Sorry! Please redownload from Spigot. I just uploaded the correct file.

**Comment by ScuroK** [comment]
thx alot!! :D
