### ISSUE TITLE
Problem to declare TIPPED_ARROW in challenges

### ISSUE THREAD

**Issue by x1p** [tastybento/ASkyBlock-Bugs-N-Features#728]
I try to make new challenge with enchanted arrows.
So far I tried:
TIPPED_ARROW:STRENGTH:1:NOTEXTENDED:LINGER:1
TIPPED_ARROW:STRENGTH:1:NOTEXTENDED:NOSPLASH:1
TIPPED_ARROW:STRENGTH:1:NOTEXTENDED::1

None of the above seem to work. What is the correct format in this plugin?
Using askyblock 3.0.8.2

**Comment by tastybento** [comment]
That is not actually supported. Sorry. I'll look into putting it into BSkyBlock.

**Comment by x1p** [comment]
-_-
