### ISSUE TITLE
People can push blocks outside island zone by using Pistons

### ISSUE THREAD

**Issue by xion87** [tastybento/ASkyBlock-Bugs-N-Features#730]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper 1.8.8

**Plugin version:**
V3.0.8.4

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?** 
not relevant

**Description of issue. What happened?**
People
**Steps to make this happen**

1. push any block with pistons or slime
2. the block will go outside the island

**What do you think should happen?**
being blocked

**Comment by YellowZaki** [comment]
Have you set `   allowpistonpush: false`?

**Comment by Poslovitch** [comment]
Set this in config : 
```yaml
allowpistonpush: false
```
