### ISSUE TITLE
Translation variable

### ISSUE THREAD

**Issue by x1p** [tastybento/ASkyBlock-Bugs-N-Features#733]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot
**Plugin version:**
3.0.8.6
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
upgrade
**Description of issue. What happened?**
the variable text [challenge] of "challangeCompleted" is not fully resolved into the given challenge

**Steps to make this happen**

1. /asadmin completechallenge player123 booklet4ch1
shows:
`Player has fulfilled [challenge]`

**What do you think should happen?**
I would expect that the variable `[challenge]` would be filled in with booklet4ch1

BTW: the commands on the website https://dev.bukkit.org/projects/skyblock/pages/commands
`/asadmin completechallenge <challengename> <player>`
`/asadmin resetchallenge <challengename> <player>`
should be:
`/asadmin completechallenge <player> <challengename>`
`/asadmin resetchallenge <player> <challengename>`

**Comment by tastybento** [comment]
The reason why the placeholder is not being used is because you have the wrong placeholder. It should be [challengename]:

```
completechallenge: 
  challangeCompleted: "Challenge: [challengename] has been completed for [name]"
```

Thanks for the tip on dev Bukkit. I switched the ordering of the parameters a while ago and forgot to update that site.
