### ISSUE TITLE
Negetive Island LevelHandicap

### ISSUE THREAD

**Issue by CodaMacroft** [tastybento/ASkyBlock-Bugs-N-Features#736]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot-1.8.8

**Plugin version:**
ASkyBlock V3.0.8.2

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?** I don't remember.

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)** Prefer not to say.

**Description of issue. What happened?**
Well, I have big Custom Islands on my server. So, some of these islands are bigger than others. So, when a player selects a big island, they have a pretty high island level by default. I would like to remove this default island level by giving the player a negative handicap to pretty much negate the island level that would be estimated when they choose a big island.

**Steps to make this happen**
1. Build a big island
2. Put big island in schematics list in config.yml
3. Start up server and select that schematic 
4. do the command /is level

**What do you think should happen?**
When doing /is level, your island level will be large because of the bigger island by default.

**Comment by Poslovitch** [comment]
I think this might help : https://github.com/tastybento/askyblock/blob/master/config.yml#L971

**Comment by CodaMacroft** [comment]
It will not allow me to set a negative value which is what I need to do.

**Comment by CodaMacroft** [comment]
Alright, What I'm requesting is a feature where I CAN put negative values to remove some of the island levels. Just a so that ASkyBlock does not calculate the schematics default blocks.

**Comment by Poslovitch** [comment]
That's exactly what levelHandicap does. Specify it to a *positive* value corresponding on the schematic default blocks and it will get substracted from the total levels.

Here is an example : 
```
levelHandicap: 70

# Calculating island level...
Total blocks: 9456
Total points: 1367032
Levels: 13670
Final (and effective) level: 13600
```

**Comment by CodaMacroft** [comment]
Alright. Thanks.
