### ISSUE TITLE
ASkyBlock | Upgrades permissions issue

### ISSUE THREAD

**Issue by FedericoGB25** [tastybento/ASkyBlock-Bugs-N-Features#737]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Plugin version:**
3.0.8.6

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
Upgrade from 3.0.8.1

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
Hi, I have a problem with Range, Members, Generators and Houses permissions.
When I try to open the upgrades menu (I use DeluxeMenus) it tells me that I have everything unlocked (I checked in the permissions, but there is nothing)
The upgrades are based on the permissions of the ASkyBlock plugin.
DeluxeMenus is only used to view the upgrade level.
Only recently gave me this problem. (DeluxeMenus tells you that you have unlocked an upgrade when it detects that the player has permission.
Rechecking the permissions, I see that no one has them (I tried to put the backup of DeluxeMenus when the permissions were still working)
It should be a problem with ASkyBlock

How can I solve?
Thank you

**What do you think should happen?**
This issue is very recently, (I have tried to downgrade at the old version, but nothing)

**Comment by tastybento** [comment]
Sorry, I have no idea and I do not completely understand the problem. Can you explain another way?
