### ISSUE TITLE
Villagers despawning in AcidIsland

### ISSUE THREAD

**Issue by ScuroK** [tastybento/ASkyBlock-Bugs-N-Features#738]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.12.2
**Plugin version:**
V3.0.8.6

One of our players always loose her villagers.  After she returned today the villagers were gone again.

config:
https://pastebin.com/EZdG6TQz

anything in my config cause this??

**Comment by Poslovitch** [comment]
Please have a look at this ticket first : https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/283
That might resolve your problem.
