### ISSUE TITLE
Heads are not showing even warpheads is true

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#739]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
1.8.8 Taco

**Plugin version:**
3.0.8.7a

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
Upgrade

**Description of issue. What happened?**
general.warpheads: true but /is top heads are not showing.

**Comment by tastybento** [comment]
Also, you should restart the server to get the heads to work if you use that setting.

**Comment by tastybento** [comment]
https://github.com/tastybento/askyblock/releases/tag/3.0.8.7b
