### ISSUE TITLE
Admin command to make a leader

### ISSUE THREAD

**Issue by Poslovitch** [tastybento/ASkyBlock-Bugs-N-Features#74]
_From @tastybento on August 7, 2015 15:1_

_Copied from original issue: tastybento/askyblock#68_

**Comment by Poslovitch** [comment]
_From @SwiftSwamp on March 19, 2017 20:27_

This would be great to have.

**Comment by Poslovitch** [comment]
Must be done for 4.0. So much owners are waiting for it.

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#44
