### ISSUE TITLE
Player break & Block pick up

### ISSUE THREAD

**Issue by Nacholebraa** [tastybento/ASkyBlock-Bugs-N-Features#740]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**

**Plugin version:**

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
This is a current build of the plugin, we are running spigot on the most recent version as well. We have the proper "Vault" Plugin installed as well.
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
Players are playing and are able to make and island but cannot do anything once they have made there island. They are lacking the ability to pick up items as well as, break anything. 

![screen_shot_2018-04-19_at_5 41 12_pm](https://user-images.githubusercontent.com/36382273/39020046-81afd266-43f9-11e8-9b0f-17c297160ba6.png)

**Steps to make this happen**

1. Player would hit a block on there island
2. Player would try and pick up a block
3.

**What do you think should happen**

**Comment by tastybento** [comment]
That error is coming from EssentialsAntiBuild, not ASkyBlock. Either remove EssentialsAntiBuild or give your groups essentials.build and/or "build: true". Good luck!
