### ISSUE TITLE
doChunkUnload Lag Issues

### ISSUE THREAD

**Issue by laodev** [tastybento/ASkyBlock-Bugs-N-Features#741]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.** 1.8.8

**Plugin version:** 3.0.8.6

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?** 

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)** https://i.gyazo.com/45b15f68ed192da615e70fa6a78eca5d.png

**Description of issue. What happened?** 
Massive lag spikes occur and its very difficult to diagnose when. It seems to be happening randomly. Here's the timings report: https://timings.aikar.co/?id=bd02a72ae5a04c98a6069af78697a2c1

**Steps to make this happen**
 No Clue

**What do you think should happen?**

**Comment by tastybento** [comment]
Lag spikes may still be to do with the head loading. Even with the previous release there could be issues. As a result, I'm removing heads completely with 3.0.8.7. You can try a pre-release here to see if that helps: https://github.com/tastybento/askyblock/releases/tag/3.0.8.7b
