### ISSUE TITLE
Command for unbanning players

### ISSUE THREAD

**Issue by x1p** [tastybento/ASkyBlock-Bugs-N-Features#742]
Somehow a player has banned someone from his island long time ago. Now he wants him unbanned. There is no help or wiki documentation available for this command nor an admin can unban a player for him.
There is some text in the translation file about this so I guess there must be some command for that.

**Comment by tastybento** [comment]
/is unban (name) should work. If the player does /is help, it should be in the help.

**Comment by x1p** [comment]
Cant get it to work even with OP.

But is there a asadmin command for an admin  to do it for players?

**Comment by tastybento** [comment]
Player must execute the command themselves and have the askyblock.island.ban permission. They should be able to see the command in help if they have the permission. There is no admin command for this, sorry. If you really want to do it for them have a look in their player file and delete the offending uuid.

**Comment by x1p** [comment]
That was exactly what I did. But before editing the player file, the player must be offline. Only thought that had to be another way.

**Comment by tastybento** [comment]
It's a good request. I'll include it in BSkyBlock.
