### ISSUE TITLE
Sub-Control-Panels Error

### ISSUE THREAD

**Issue by Coniculls13** [tastybento/ASkyBlock-Bugs-N-Features#745]
**Server Version:** Most recent version of Spigot as of 24 April 2018.

**Plugin Version:** ASkyBlock 3.0.8.6

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?** No

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)** AsyncWorldEditInjector, PermissionsEx, AsyncWorldEdit, VoidGenerator, Vault, Essentials, EssentialsSpawn, EssentialsChat, WorldEdit, ASkyBlock, Multiverse-Core, WorldGuard

**Description of issue. What happened?** I created a 'sub-panel' with the intent for it to handle warps. I gave a button in the main control panel the next-section value of the sub-panel. An error is registered in the console when I click this button & in-game the control panel GUI simply closes.

**Steps to make this happen**

1. Create a Sub-Panel
2. Assign Sub-Panel to a button within the Control Panel
3. Use the button on the Control Panel.

**What do you think should happen?** Be fixed?

**Extra:** Error in console: https://pastebin.com/6ssz1qMq
                 controlpanel.yml: https://pastebin.com/HAiqYFEc

**Comment by tastybento** [comment]
Sorry for the late reply - I just reviewed this. So, what you put in your controlpanel.yml is logical, but actually nextsection is the panel name, not the yaml header. So this is what you need:

nextsection: '§7[§b§lBR§7] §3Server Warps'

I would change it to be like you assumed, but there's too many legacy servers out there with this approach so it'd break.
