### ISSUE TITLE
FAWE conflict with ASB

### ISSUE THREAD

**Issue by JordyvdBolt** [tastybento/ASkyBlock-Bugs-N-Features#746]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper build 1402 and also Spigot latest

**Plugin version:**
latest

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
New install

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
afkTerminator, AlwaysDay, AnimatedNames, AreaShop, ASkyBlock, AuctionHouse, AutoBroadcast, BattleLevels, BlocksHub, boosCooldowns, ChatControl, ChatLog, Citizens, CleanroomGenerator, ClearLag, ColoredAnvils, ColouredSigns, CommandNPC, CraftBook, CrateReloaded, CustomGUI, DeluxeChat, DontPutItHere, EchoPet, Essentials, Essentials_KitGUI, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, FeatherBoard, GAListener, GuiRedeemMCMMO, HolographicDisplays, InfinityDispensers, Interactables, InventoryFull, LeaderHeads, LibsDisguises, LogBlock, mcMMO, MinePacks, MineResetLite, MineSecure, Multiverse-Core, Multiverse-NetherPortals, MVdWPlaceholderAPI, NightVision, NoCheatPlus, NoWeather, OldCombatMechanics, OnTime, PermissionsEx, Pinata, PlaceholderAPI, PlugMan, PortalCommands, PremiumVanish, ProtocolLib, ProtocolSupport, SexyPEX, ShopGUIPlus, SignShop, SilkSpawners, Spectator, Stickers, Tab, TimeIsMoney, TitleManager, ToDoList, TradePlus, TrailGUI, TrashCan, TreeAssist, TryMe, Vault, ViaVersion, VoidGenerator, VoidSpawn, Votifier, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldReset, zxSlotMachine

**Description of issue. What happened?**
When a user wants to change something with WorldEdit, the user gets the message it is outside his allowed region. Everything goes thru FAWE, and the user has the permissin fawe.ASkyBlock. When the user does anything with WE on his island, the user can not place or brake anything anymore, only access his chests. After a server restart the player can build again. It does not need to happen that the island get corrupted, because we only restart once a day.

**Steps to make this happen**

1.  Make WE region
2. //set

**What do you think should happen?**
Changes in the protection code?

![fawe](https://user-images.githubusercontent.com/38701442/39205211-5715e892-47fa-11e8-9d1c-eb62c967be89.png)

**Comment by JordyvdBolt** [comment]
The [WorldEdit] tag is my change to the FAWE locale file, so it is not WorldEdit itself.

**Comment by tastybento** [comment]
I’m confused. Askyblock does not use WorldEdit or WG at all. If you are getting errors from WE I recommend you delete all the regions in the sky world.

**Comment by JordyvdBolt** [comment]
The problem is between FastAsyncWorldEdit that uses the protection of ASkyblock. WorldEdit itself has nothing to do with it. Something is not right between FastAsynWorldEdit and ASkyblock because ASkyblock does not, I think, connect right with FastAsyncWorldEdit to give the ASkyblock region (built in protection) to FastAsyncWorldedit.

**Comment by tastybento** [comment]
Okay, let's break this down piece by piece. Firstly, ASkyBlock does not directly call FAWE in any way. FAWE is using the ASkyBlock API to determine if a player is on an island or not. You can see this in their code [here](https://github.com/boy0001/FastAsyncWorldedit/blob/master/bukkit/src/main/java/com/boydti/fawe/bukkit/regions/ASkyBlockHook.java).

You wrote:
> When a user wants to change something with WorldEdit, the user gets the message it is outside his allowed region.

This error comes from FAWE and I'm not sure why you'd see it unless the protection size that the island has is wrong somehow. You'll need to check the island limit by doing both **/asadmin info** when your player is on the island (to get the island specs) and **/asadmin info (playername)** to see what the player's protection range says. They should be the same. If they are the same and the player is inside the protection limits and they get this error, then let me know what the details are.

> When the user does anything with WE on his island, the user can not place or break anything anymore, only access his chests.
What error does the player when they try to break things?

**Comment by tastybento** [comment]
I managed to replicate this issue. It looks like FAWE is setting the island owner to null somehow. Actually, I tried with a version of ASkyBlock from Nov 2017 and the issue was still there, so I'm not sure if this has ever worked. I only just found out it was a feature of FAWE because of your bug report.

I'll try and do some investigation. I did find one bug, which stops the island from becoming unowned, but FAWE thinks the region is not owned by the player so the action is cancelled. I may have to build my own FAWE to find out what is going on. So, under investigation...

**Comment by JordyvdBolt** [comment]
I am pleased to see you could replicate the issue. Hope soon to hear if there is a solution for this. For now I am very gratefull you take time to help with this issue!

**Comment by JordyvdBolt** [comment]
^accidentally closed the issue.

**Comment by tastybento** [comment]
I'm having problems compiling FAWE - it's a huge project that requires forge and other items - right now it doesn't compile. I may just need to file a ticket on their github and hope they can look at it.

**Comment by JordyvdBolt** [comment]
I hope they will work with you. You found the problem with FAWE? It wouldn't be a big problem for them if you have a solution. Hope they will coop.

Anyway, an other thanks to you!

**Comment by JordyvdBolt** [comment]
The developer of FAWE updated FAWE, but now the problem with removing the owner from the island is back. Could there be something wrong with FAWE?

**Comment by tastybento** [comment]
I just tried the latest FAWE with the latest ASkyBlock (https://github.com/tastybento/askyblock/releases/tag/3.0.8.8) and do the following:

1. //pos1
2. //pos2
3. //set stone

I get an "Outside World" error and nothing happens. I don't know what this error means.

Here are my permissions:
>pex user tastybento
[17:43:59 INFO]: '5988eecd-1dcd-4080-a843-785b62419abb/tastybento' is a member of:
[17:43:59 INFO]:    default (not ranked)
[17:43:59 INFO]: tastybento's permissions:
[17:43:59 INFO]: 1) worldedit.region.set (own)
[17:43:59 INFO]: 2) worldedit.selection.pos (own)
[17:43:59 INFO]: 3) fawe.askyblock (own)
[17:43:59 INFO]: 4) askyblock.settings.* (own)
[17:43:59 INFO]: 5) essentials.* (own)
[17:43:59 INFO]: 6) askyblock.coop (own)
[17:43:59 INFO]: 7) essentials.spawn (own)
[17:43:59 INFO]: tastybento's options:
[17:43:59 INFO]:   name = "tastybento"

**Comment by JordyvdBolt** [comment]
Uhm, there is nothing to be tested anymore. You fixed it! Players can now use WE on their island, and the island will stay owned by them! I will do more testing to make sure it stays like this, but I am very confident it will keep working.

You are the best! Will keep you updated.

**Comment by JordyvdBolt** [comment]
Do you have the restricted option in FAWE at true? And I have the islands range on 256 and the protection also on 256. Maybe there is something? As far I know it works fine! You can come and take a look at our server if you want I have it on a test server on our network.
