### ISSUE TITLE
 Solid block found during long search - adding to islands.yml /is issue

### ISSUE THREAD

**Issue by Cocaina-Ricky** [tastybento/ASkyBlock-Bugs-N-Features#747]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
S[igot
**Plugin version:**
Latest
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
New Installation
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
Everytime I type in /is or /island, it comes up with the location selector like grass / little flower and obsidian block and then when I click either one, it just crashes the entire server
**Steps to make this happen**

1. Type /is or /island
2. Press on any block
3. Server Crashes

**What do you think should happen?**
Obviously work?

**Comment by tastybento** [comment]
Hmm. If this is a new install then make sure you delete the world folders. It looks like the world is not a void so it cannot find any spot for your island.
