### ISSUE TITLE
IllegalArgumentException: No enum constant org.bukkit.block.Biome.COLD_TAIGA

### ISSUE THREAD

**Issue by Foorack** [tastybento/ASkyBlock-Bugs-N-Features#749]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper version git-Paper-1299 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Plugin version:**
3.0.5.4

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
We don't remember. AFAIK I think it is a new install.

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
This error randomly posts in console. We are **not** running v1.9, we are running v1.12.2 and I am sure COLD_TAIGA already is in the config.yml file.
![ekrankopio de 2018-04-27 18-20-54](https://user-images.githubusercontent.com/5008081/39373529-2d07383a-4a48-11e8-915a-f57bc8bd79e1.png)

**Steps to make this happen**

1.  This error is posted randomly in console.
2.
3.

**What do you think should happen?**

This exception shouldn't happen.

**Comment by tastybento** [comment]
If COLD_TAIGA is in the config file, then it is the wrong biome name for 1.12.x The correct name is TAIGA_COLD. See https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Biome.html#TAIGA_COLD

Just change the config.yml to use TAIGA_COLD and you should be good to go.
