### ISSUE TITLE
Falling outside the borders of own island.

### ISSUE THREAD

**Issue by Segysmundo** [tastybento/ASkyBlock-Bugs-N-Features#751]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper 1403, for Minecraft 1.12.2
**Plugin version:**
V3.0.8.6
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
New install.
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
N/A
**Description of issue. What happened?**
I set invincible visitors to true so when they fall to the void in other islands or the spawn they won't lose anything. But if they are expanding the borders of their own island and fall off the edge they exit their limits and won't lose anything when falling. Since they are technically outside of their island.

They can abuse this to safely expand their island close to their borders since they won't lose anything when falling.

Can something be done about this?
**Steps to make this happen**
N/A

**What do you think should happen?**
Players should properly die and lose items and exp when falling outside of the limits of their island as long as it's not the spawn or somene else's island.

**Comment by tastybento** [comment]
Ha! Players are endlessly ingenious. I'll look into this.
