### ISSUE TITLE
Permission askyblock.island.range.<number> not working

### ISSUE THREAD

**Issue by hacalios** [tastybento/ASkyBlock-Bugs-N-Features#752]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
1.8.8 Spigot
**Plugin version:**
ASkyBlock V3.0.8.6
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
new install
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
PlaceholderAPI, PlugMan, GuiCreationTool, AlwaysDay, MineblaOreGenerator, AntiCraft, TigerReports, CombatLog, ClearLag, ProtocolLib, MVdWPlaceholderAPI, FastAsyncWorldEdit, SpawnerUpgrader, PermissionsEx, FeatherBoard, Vault, UEAntiTab, TigerReportsSupports, PlayerPoints, Spartan, ChestCommands, CMIEInjector, WorldEdit, AnimatedNames, LiteBans, Citizens, TradeMe, CrazyAuctions, WorldGuard, ASkyBlock, CommandNPC, PremiumVanish, SilkSpawners, Multiverse-Core, Shopkeepers, MoreVaultPlus, BlockParticles, CustomOreGen, NoFlyZone, HolographicDisplays, CMI, SkinsRestorer, LeaderHeads, ShopGUIPlus, TitleManager, CrazyEnchantments, MobHunting, CrateReloaded, ProQuests, CrazyEnvoy, ProQuests-Packages
**Description of issue. What happened?**
Permission askyblock.island.range.<number> not happened, it's give player permission but the protection of island is not change and i use throw chestcommand to give player permission
**Steps to make this happen**

1. player click to chestcommands and it's give player permission
2. nothing happened with thier island

**What do you think should happen?**
i think this is a bug

**Comment by tastybento** [comment]
The player needs to relog to get the new range with permissions. Try that (log out, then log in).

**Comment by hacalios** [comment]
Fixed Thanks
But you can make that permission update when i leave ASkyblock world or something please
That fixed but it makes some bugs with my world border addon for askyblock using your api

**Comment by tastybento** [comment]
You will need to give the player a reset permission, such as the default size if you want it to go back. If the player hands the island over to another player, it will get that player's permission.

I can't comment on 3rd plugins, sorry.  They'll need to check the island size.
