### ISSUE TITLE
Admin bypass

### ISSUE THREAD

**Issue by AmazedMender16** [tastybento/ASkyBlock-Bugs-N-Features#754]
**Server version**
CraftBukkit version git-Spigot-b6ecf3b-fb423b8 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Plugin version:**
ASkyBlock version 3.0.8.6

Would love to see an option for admins to not have permanent bypass enabled! A command like /asadmin bypassprotection. Should enable or disable the bypass

**Comment by AmazedMender16** [comment]
Sad that it wont be added! Will love to see it on bskyblock :) its quite annoying right now since if a admin has the bypass he can bypass lile literally everything even the bounderies of their islands

**Comment by dazedtracers** [comment]
Is it possible to add the nodes via same # system in used to identify island.settings for players to plugin.yml in .jar file to allow individual bypass.nodes? Though I might someday try it but easier to just ask the source I suppose. :-)

**Comment by tastybento** [comment]
The issue is that in order to use the command you'll need another permission (bypass.set?). But, after thinking about this I'm not actually sure what the benefit is of this. Is it just so that admins don't accidentally bypass protections?

I can add this, it's just a simple add, but I'd like to clear up the use-case. Let me know.

**Comment by AmazedMender16** [comment]
Its so admins dont have permanent bypass. So they also play like everyone else, within the island limits. For example if they have the bypass they cant build endlessly size of their island

**Comment by tastybento** [comment]
Okay, but it would be their own honor that they would run that command? It's okay if that's just it. I can enable it. All the command will do will add the perm or remove the perm.

**Comment by tastybento** [comment]
Okay, gotcha.
