### ISSUE TITLE
[ERROR] [ASkyBlock] Something went wrong saving files!

### ISSUE THREAD

**Issue by andrewkm** [tastybento/ASkyBlock-Bugs-N-Features#755]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1632
**Plugin version:**
v3.0.8.6
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
Unsure how to answer this. I've been running on this version for a while.
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
On request via private means.
**Description of issue. What happened?**
Server stop generated:
https://pastebin.com/raw/a9RLXTDJ

First time this has happened, seems rare, curious if any insight as to why it happened can be given.
Perhaps restart command related?

**Steps to make this happen**

1. Stop server?
2.
3.

**What do you think should happen?**
Not get the error 🥇

**Comment by tastybento** [comment]
Something changed during shutdown to the player data. This may result in some player files not being fully up to date. I did have code in there to try to avoid it, but it didn't work in this case. I've updated the code to use a better approach curtesy of Google Guava. I'll include it in the next release.
