### ISSUE TITLE
chest access

### ISSUE THREAD

**Issue by IGDT** [tastybento/ASkyBlock-Bugs-N-Features#757]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
spigot1.8.8
**Plugin version:**
 ASkyBlock V3.0.8.2
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
/
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
- adminfun
- alphachest
- ArmorStandEditor
- askyblock
- auctionhouse
- banknotes
- bargamble
- bountyhunters
- bstats
- buycraftx
- chatcolor
- chestshop
- citizens
- clearlag
- coloredsigns
- commandnpc
- commandsigns
- cratesplus
- crazyenchantments
- ctsncplus
- essentials
- holographicsdisplays
- idisguise
- jail
- leakparkour
- litebans
- lockette
- melroulette
- openinv
- permissionex
- shopguiplus
- silkspawners
- simplefreeze
- superbvote
- supervanish
- timtheenchanter
- touchscreenholograms
- tta
- ultimateheadfinder
- updater
- vault
- votifier
- worldedit
- worldguard
**Description of issue. What happened?**
1. when players try to acces to the chest of cratesplus at the spawn they get a chat: Island protected, they have the cratesplus permission, wordguard has chest-access allow in the spawn region/but there are 2 regions at the spawn(1for spawn and 1 for pvp in the spawn), chest-access in config of askyblock is set to true for players islands and spawn
![2018-05-03_19 36 29](https://user-images.githubusercontent.com/36332464/39593160-5511eaee-4f09-11e8-9e01-727b5311daab.png)

these are the given perms to defaults:
    - askyblock.island.*
    - askyblock.team.create
    - askyblock.team.kick
    - askyblock.team.makeleader
    - askyblock.team.join
    - askyblock.intopten
    - askyblock.island.controlpanel
    - askyblock.island.maxhomes.1
    - askyblock.team.maxsize.6
    - askyblock.coop
    - askyblock.settings.CHEST
    - askyblock.island.range.200
**Steps to make this happen**

1. players try to use vote crate(have perm)
2. get a chat report: Island protected
3. Can't access the vote chest

**What do you think should happen?**
explaining what permissions i forgot to give/change the config

**Comment by dazedtracers** [comment]
../plugins/askyblock/config.yml
  World:
     Chest: false

Make true will allow access to all chests in /is spawn and other "common" areas of the world. Plugin still works properly, correct? Just the squawk in chat is the complaint?
..or tell me to butt out ;-)

**Comment by tastybento** [comment]
Hmm, if this island is set to be the ASkyBlock spawn then you should just be able to do /is settings and click the chest to allow all players to open chests. So, first thing to check is if that works. Does it?
