### ISSUE TITLE
Internal Server error when player tries to create island.

### ISSUE THREAD

**Issue by doitliketyler** [tastybento/ASkyBlock-Bugs-N-Features#760]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
1.12.2

**Plugin version:**
AcidIsland V3.0.8.6

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
Upgrade V3.0.8.5

**Description of issue. What happened?**
https://pastebin.com/raw/tpyQjT3s

**Steps to make this happen**
1. Use /is command to create an island

**What do you think should happen?**
An island should be created.

**Comment by tastybento** [comment]
This looks like world-save corruption. The chunks that the server is trying to load are corrupted, or did not save correctly. The best fix is to use a backup of the world where the chunks are not corrupted. Alternatively, you may be able to fix it with region fixer. (Google **minecraft "java.lang.IndexOutOfBoundsException: Index: 1, Size: 1" chunk** and you'll see this issue has been around for years with Minecraft).
