### ISSUE TITLE
Askyblock Timings High

### ISSUE THREAD

**Issue by mk9395** [tastybento/ASkyBlock-Bugs-N-Features#761]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Paperspigot 1.10.2

**Plugin version: V3.0.8.6

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)** : https://i.imgur.com/PguKyna.png

**Description of issue. What happened?**

My current timings are so much error on askyblock, and I feel there is a lag happening from askyblock? So how can I fix this problem

My hardware : CPU i7 - 6700k / 15gb of ram for server

Timings : https://timings.aikar.co/?id=882ecd7cb54b4c569d7db51de4da2bd4

**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**

**Comment by tastybento** [comment]
ASkyBlock **world** maybe, but not the plugin.

Please read the FAQ.
https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#i-get-a-lot-of-lag-from-askyblock

From your timings, it looks like you have lots of pistons and hoppers in the world. Players are making machines to automate farming. You can disable redstone in the config.yml for offline players. Make your you have a good AFK detector running to kick AFK players.

Good luck!
