### ISSUE TITLE
API Request: ToptenCalculatedEvent

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#762]
I want to show top 10 islands in my website. For this reason i want to send top 10 data to MySQL every time topten calculated.

Event only needs getTopTenIslands().

Thanks.

**Comment by tastybento** [comment]
You should use: https://tastybento.github.io/askyblock/com/wasteofplastic/askyblock/events/IslandPostLevelEvent.html
The top ten is recalculated every time there is a level calculation.
