### ISSUE TITLE
Nether portals disappearing?

### ISSUE THREAD

**Issue by ScuroK** [tastybento/ASkyBlock-Bugs-N-Features#763]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigit 1.12.2
**Plugin version:**
V3.0.8.7

Recently i found some players lost the nether portals in the nether world. it was just gone and i have no clue why. the one in the overworld was still there.

any ideas?

**Comment by tastybento** [comment]
No idea at all. You mean the obsidian portal has been removed? If so, that sounds like vandalism by the players themselves or a mod or something. There's nothing in the ASKyBlock code to remove portals like that, sorry.
