### ISSUE TITLE
unnecessary permission for command /is coopaccept

### ISSUE THREAD

**Issue by wlq69** [tastybento/ASkyBlock-Bugs-N-Features#765]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
1.12.2 PaperSpigot (last build)
**Plugin version:**
V3.0.8.6
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
V.3.8.5
**Description of issue. What happened?**

On my server only VIP group have a permission askyblock.coop, befeore an update that fixed instant request, players with this permission could invite everyone to coop. Now they can only invite those who are in the  same group, because command /is coopaccept needs askyblock.coop to work.

**Comment by tastybento** [comment]
Fixed in 6169f87 commit.

**Comment by tastybento** [comment]
Pre-release here:
https://github.com/tastybento/askyblock/releases/tag/3.0.8.9b
