### ISSUE TITLE
Is Settings cannot be changed

### ISSUE THREAD

**Issue by Inspectiver** [tastybento/ASkyBlock-Bugs-N-Features#766]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.10
**Plugin version:**
Latest
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
No
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
When you type /island settings you cannot change the settings for your island, only view the defaults. I have given users the askyblock.settings.* permission, but to no luck.
**Steps to make this happen**

1. /Island Settings

**What do you think should happen?**
It should allow you to change the setting for your island.

**Comment by tastybento** [comment]
If the player cannot toggle the setting then they do not have the permission. Check your permissions again. Sorry.
