### ISSUE TITLE
problem /is settings

### ISSUE THREAD

**Issue by HumriPupek** [tastybento/ASkyBlock-Bugs-N-Features#768]
Hello, 
server - spigot version 1.12
version ASkyBlock - v3.0.8.8
New install plugin. not upgrade.

if I use the command /is settings
So I do not see all the settings. see picture
How is it possible?

Thx =)
![2018-05-13_16 29 28](https://user-images.githubusercontent.com/39240314/39969123-c4aa5f5a-56d7-11e8-9d8b-a3ff6aff93d0.png)

**Comment by Inspectiver** [comment]
I am having this issue too.

**Comment by tastybento** [comment]
Are you using the latest config file version?

The settings a player can see on an island are determined by this section here: https://github.com/tastybento/askyblock/blob/master/config.yml#L786

If they are not in that list, then they will not be shown.

If you have items in that list that are not being shown, share your config file. (Drag and drop to this box).

**Comment by HumriPupek** [comment]
Oh, now I get it! :D
I had to write to the island. what do I want to do right now in settings from the world.
Thank you solved :)

**Comment by tastybento** [comment]
Great!
