### ISSUE TITLE
Island size not upgrading (askyblock.island.range.<number>)

### ISSUE THREAD

**Issue by tastybento** [tastybento/ASkyBlock-Bugs-N-Features#77]
_From @cloakfox on March 31, 2017 15:11_

Hello,

I am currently selling the option for my users to upgrade their island size from 150x150 to for example 200x200. The standard size is 150. So by giving them the permission askyblock.island.range.200
Should effectively upgrade their island by 50x50. Except this does not work on already created islands. It only works if you create a new island.

I am currently using ASkyblock V3.0.5.4
On PaperSpigot 1.8.8

Skype: cloakfox (from the netherlands)

_Copied from original issue: tastybento/askyblock#602_

**Comment by tastybento** [comment]
_From @cloakfox on March 31, 2017 15:12_

Max distance is set at 350 in my config file.

**Comment by tastybento** [comment]
_From @Poslovitch on March 31, 2017 15:57_

First of all, You should update to 3.0.6.1 ;)

**Comment by tastybento** [comment]
_From @cloakfox on March 31, 2017 16:2_

There is nothing in the changelogs/update notes that indicates this issue is fixed in versions after 3.0.5.4
Updating is also genuinely a pain in the ass, since I have to redo my configs each config.

**Comment by tastybento** [comment]
@cloakfox - the player will see the change when they next login. It is reported in the "news" that the change has been made. Can you confirm that you don't see this?

**Comment by cloakfox** [comment]
I can't find anything related to "News" but I can confirm that after relogging the increased size works.

Thanks,
