### ISSUE TITLE
WarpSigns lag spikes

### ISSUE THREAD

**Issue by Gaurav99** [tastybento/ASkyBlock-Bugs-N-Features#770]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper 1.12.2
**Plugin version:**
3.0.8.6

**Description of issue. What happened?**
No idea what's causing it specifically, but we seem to be getting periodic lag spikes that last about 10 seconds.  Upon inspecting timings, we found that it had something to do with WarpSigns -- https://i.imgur.com/EPUWwsJ.png

It doesn't give any more details than that.  Any idea what's causing this / how to fix it?

Thanks

**Comment by tastybento** [comment]
Yup, this is why 3.0.8.8 came out. Recent versions of Spigot server have changed how heads get loaded from Mojang and they now block. Trying to obtain them async is difficult and error-prone. Options are to use an older version (so I have heard) or not use heads - thus the latest version of ASkyBlock.
