### ISSUE TITLE
How do I get my Custom Ore Generator Plugin to work with both Askyblock and AcidIsland

### ISSUE THREAD

**Issue by jenaus** [tastybento/ASkyBlock-Bugs-N-Features#772]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**

**Plugin version:**
AcidIsland V3.0.8.6
ASkyBlock V3.0.8.6
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
Just want to know why the CustomOreGen plugin is not working with my AcidIsland but is working with Askyblock if they are on the same server. 

Is there something in either of the configs that allow me to change this or what do you suggest?
**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**

**Comment by tastybento** [comment]
I am not the author of CustomOreGen plugin, sorry. I recommend you ask that author.

**Comment by jenaus** [comment]
ok thank you
