### ISSUE TITLE
i can takie itms for gui

### ISSUE THREAD

**Issue by ProDash1998** [tastybento/ASkyBlock-Bugs-N-Features#773]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.** paperspigot 1.12.2

**Plugin version:** lastes

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?** --

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
 Plugins (9): AntiDrop, ASkyBlock, Essentials, Jobs, LuckPerms, Multiverse-Core, Vault, WorldEdit, WorldGuard -testing server

**Description of issue. What happened?**
i can take items in defauld world (is settings)
**Steps to make this happen**

1. i tp to defautd world
2. use command /is settings
3. take items

**What do you think should happen?**

**Comment by tastybento** [comment]
This is a FAQ: https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#players-can-take-the-items-heads-out-of-the-challenges-settings-control-warps-guis-help
