### ISSUE TITLE
PAPI Placeholder error - %acidisland_team_size%

### ISSUE THREAD

**Issue by TheWranger** [tastybento/ASkyBlock-Bugs-N-Features#777]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper 1.12.2 Build 1418
**Plugin version:**
AcidIsland v3.0.8.8 (Also effects ASkyBlock to my knowledge)
**Description of issue. What happened?**
%acidisland_team_size% Gives 0 when on a solo island. Haven't tested yet on a co-op island so it might also be displaying one less with co-ops too.
**Steps to make this happen**

1. Have an island
2. Test the placeholder %acidisland_team_size%
![image](https://user-images.githubusercontent.com/24642838/40268417-415ccd80-5bb0-11e8-8586-fabc69006316.png)

**What do you think should happen?**
Give the full amount of members.

**Comment by tastybento** [comment]
That would be correct. No team = no team members.

**Comment by TheWranger** [comment]
But wouldn't it make more sense for it to be 1 by default? Some players might find it confusing if it's 0.

**Comment by tastybento** [comment]
In BSkyBlock we changed it to work that way, but ASkyBlock tracks owner and then team members separately. The placeholder plugin author could change it if they wanted, but ASkyBlock API just provides the raw data. I suggest this would be a request for the placeholder author.
