### ISSUE TITLE
Issue/Trouble using ASkyBlockAPI

### ISSUE THREAD

**Issue by wsaada19** [tastybento/ASkyBlock-Bugs-N-Features#779]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.8.8
**Plugin version:**
Recent
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
Just askyblock, vault and this custom plugin
**Description of issue. What happened?**
I've been trying to make an item that can change the island level but am having trouble getting it to work.  I've called calculateIslandLevel() and am fetching the IslandPreLevelEvenet and then using setLongIsland from the event to increase the level by one.  This is not changing the island level.   At times it's printed out the value having increased by one in the event handler but then when I call island level the level is back to where it was.  Is there something I am missing?  Or is this operation not possible from another plugin?

**Comment by tastybento** [comment]
The API basically enables you to substitute the built-in island level with your own system for players, but not change the internal level calculations. So, when the player does **/island level** you show them what you want, but ASkyBlock won't keep a track on what you showed them. You have to trap the level request every time and use your own level calculation setting.

**Comment by wsaada19** [comment]
Got it, thanks for the quick response!
