### ISSUE TITLE
A whole lot of bugs

### ISSUE THREAD

**Issue by tastybento** [tastybento/ASkyBlock-Bugs-N-Features#78]
_From @TheWranger on March 31, 2017 14:47_

1. Snow deals acid damage, therefore making snowy islands a non-existant thing.
2. If a player resets their island in a non-AcidIsland world, their inventory won't be reset with them.
3. The island fly system seems buggy as when players teleport to their island from another world, they cannot fly.

Version: Latest of everything.

_Copied from original issue: tastybento/askyblock#601_

**Comment by tastybento** [comment]
I'll look at these. For #2 are you using a per world inventory plugin?

**Comment by tastybento** [comment]
@TheWrangler - for number 1, falling snow causes acid damage, just like falling rain does. Snow on the ground does not cause damage.

**Comment by tastybento** [comment]
Can't replicate the island fly issue right now or the snow. The other item is fixed.

**Comment by TheWranger** [comment]
I'm not sure if it counts or not, but I'm using Multiverse for #2

**Comment by tastybento** [comment]
I fixed #2. Thanks.
