### ISSUE TITLE
ASkyblock issue

### ISSUE THREAD

**Issue by Bigbang32** [tastybento/ASkyBlock-Bugs-N-Features#780]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.*Spigot 1.8.8*

**Plugin version:*Lastest*

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?*Not an upgrade*

**Description of issue. What happened?*Whenever I do /island or /is it says "/island help" when I run /asadmin it says "/asadmin"*

**Comment by tastybento** [comment]
Sounds like the plugin isn't installed properly. Did you install Vault? Check your console logs for errors on start up.
