### ISSUE TITLE
Issue with trees in the nether

### ISSUE THREAD

**Issue by TheWranger** [tastybento/ASkyBlock-Bugs-N-Features#781]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paperspigot 1.12.2 #1423
**Plugin version:**
AcidIsland V3.0.8.8
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
Upgraded from V3.0.8.7 however did not notice the bug until now.
**Description of issue. What happened?**
Normal trees cannot grow in the Nether. This is non-vanilla behavior.
**Steps to make this happen**

1. Set `nethertrees` to `false` in config.yml
2. Try to grow a tree in the nether using bonemeal. Make sure it has a light level of 8 or above and has plenty of space.

**What do you think should happen?**
Normal trees should be able to grow perfectly fine.

**Comment by tastybento** [comment]
Sorry, I can replicate this. I just tested and I can grow regular trees fine in the nether if nethertrees are false. The code is so simple in this regards that I cannot imagine how AcidIsland would be blocking it. It there is another plugin involved, maybe that's having an effect on the process.

**Comment by TheWranger** [comment]
Alright, I'll have to do some more testing to see what plugin is colliding with AcidIsland.
