### ISSUE TITLE
Dropper does not drop water bucket item in nether

### ISSUE THREAD

**Issue by Wows233** [tastybento/ASkyBlock-Bugs-N-Features#783]
**Server version**: spigot-1.12.2 git-Spigot-2086bb0-d0a3620
**Plugin version**: 3.0.9.8

**Issus**
Dropper does not drop water bucket item in nether

**Steps to make this happen**
Go to the Askyblock nether world and put water bucket in **dropper** then power it

**What do you think should happen?**
The water bucket item should be dropped

**Comment by tastybento** [comment]
Thanks for the report!
