### ISSUE TITLE
Fly Toggles off

### ISSUE THREAD

**Issue by Broanater** [tastybento/ASkyBlock-Bugs-N-Features#786]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.12.2

**Plugin version:**
3.0.8.3

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
When my players are flying on their island and fly outside of their region essentials fly is toggled off and they fall.

**Steps to make this happen**

1. Turn on /fly
2. Fly outside of island

**What do you think should happen?**

**Comment by tastybento** [comment]
Yes, that's how it works, by design. If you want to give them a grace period then change the config setting:

```
   # Players with askyblock.islandfly permission can fly on their island. This setting is
   # how many seconds the player keeps fly mode while flying outside his island before it
   # is removed (and they fall).
   # Negative value will be considered as 0.
   flytimeoutside: 0
```

**Comment by Broanater** [comment]
Would it be possible to add an option to disable this feature? Because I want my players to just be able to fly.

**Comment by Broanater** [comment]
We do use essentials fly. my players don't have askyblock.islandfly

**Comment by tastybento** [comment]
They must have it somehow because the code to disable flying is never run unless they do. Check your perms.
