### ISSUE TITLE
Stop regening previously generated maps

### ISSUE THREAD

**Issue by MismatchedSocks** [tastybento/ASkyBlock-Bugs-N-Features#787]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot-2086bb0-d0a3620 (MC: 1.12.2) 

**Plugin version:**
3.0.8.8

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
New install.

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
See:
Steps to make this happen.

**Description of issue. What happened?**
I am trying to make a custom skyblock map with a barrier layer below 9 stone layers below 10 water layers below islands. I did this using cleanroom generator and worldborder to render a map, then renamed that maps folder to ASkyBlock. That went successfully and the map looked great, but whenever an island is created ASkyBlock 'erases' everything within the island distance (I set it to 250), instead of leaving the water, stone, and barriers below the islands.
![2018-05-24_13 52 11](https://user-images.githubusercontent.com/38669418/40511272-5f187dce-5f5c-11e8-9b46-c66a78d0bdd9.png)

**Steps to make this happen**
1) Download cleanroomgenerator/multiverse/askyblock/world border
2) Create a map with some blocks (/mv create mapname normal -g CleanroomGenerator:.1,barrier,9,stone,10,water
3) Use world border to generate all the chunks (and to set a border, I used a 50,000*50,000 block map). To do this you'd set a border then use /wb <mapname> fill <SpeedIUsuallyUse10000> 
4) Rename the created map to ASkyBlock
5) Fly around your created map to show there are no unloaded chunks
6) Create an island for yourself, or use /island reset
7) Fall into nothingness.

**What do you think should happen?**
I would like to keep the generated map, and place the island schematic in without regenerating the chunks within island distance.

**Comment by tastybento** [comment]
Add useowngenerator: true to the general section of config.yml.

**Comment by tastybento** [comment]
By the way, you may want to set sea level to 19 or so and then in blockvalues.yml tell it to ignore level calculation of any blocks below sea level. This will force players to mine the blocks below before getting credit for them. Alternatively, you can set the level handicap to include the value of the lower layers.
