### ISSUE TITLE
AcidIsland: pasting air

### ISSUE THREAD

**Issue by TheWranger** [tastybento/ASkyBlock-Bugs-N-Features#788]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paperspigot 1.12.2 #1427
**Plugin version:**
AcidIsland V3.0.8.8
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
Upgrade from V3.0.8.7
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
Noteable plugins are WorldEdit, FastAsyncWorldEdit and React.
**Description of issue. What happened?**
`pasteair:false` is not working and air is still being pasted anyway.
**Steps to make this happen**

1.  Test using this island http://www.mediafire.com/file/t147jes5jxigepy/skyblock.schematic
2. Make sure `pasteair` is set to false

**What do you think should happen?**
No air should be pasted

**Comment by tastybento** [comment]
Huh.

This feature was never actually "turned on". (It was put into the code Aug 6, 2015 in Version 2.9.5.1 but always commented out.)

Currently, air is never pasted if blocks are above sea level and air is always pasted if blocks are below sea level. This works for most use cases. I'll uncomment the code and that will enable air blocks to be ignored below sea level.
