### ISSUE TITLE
Island Level not showing up. [/is level]

### ISSUE THREAD

**Issue by Suprreme** [tastybento/ASkyBlock-Bugs-N-Features#790]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.** 

SPIGOT 1.8.8

**Plugin version:**

THE NEWEST ONE OUT NOW

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**

no

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

 26.05 12:04:06 [Server] INFO Plugins (55): PlaceholderAPI, PlugMan, FastCraftPlus, Arconix, AntiPortalTrapping, ViaVersion, Tablist, StaffPlus, Coupons, Actionbar, VoteRoulette, Essentials, ClearLag, BarGamble, BuycraftX, Votifier, ProtocolLib, MVdWPlaceholderAPI, FastAsyncWorldEdit, iDisguise, EssentialsChat, DeluxeMenus, SpawnerUpgrader, PermissionsEx, FeatherBoard, NoWeather, Vault, CrazyCrates, AntiCommandTab, Item2Chat, Trading, VoteParty, ASkyBlock, EssentialsSpawn, MyCommand, TitleManager, WorldEdit, LiteBans, Multiverse-Core, VoidSpawn, Citizens, KitPreview, CrazyAuctions, MineResetLite, BlockParticles, CustomOreGen, HolographicDisplays, WorldGuard, LeaderHeads, CommandNPC, CommandRegions, CRegionsPlus, SilkSpawners, StackMob, ShopGUIPlus

**Description of issue. What happened?**

So before it was all working fine,. then one day i logged on and when i did /is level this message showed up: "Skyblock >> Island Level Is"

**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**

The island level should show up

**Comment by tastybento** [comment]
Your text in the local does not include the [level] placeholder, so there is no place for the level to be put. This was a change made quite a while ago. Quick fix, add [level] to your locale text. For example:

"Island level is [level]"
