### ISSUE TITLE
Issue with bed explosions

### ISSUE THREAD

**Issue by TheWranger** [tastybento/ASkyBlock-Bugs-N-Features#791]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paperspigot 1.12.2 #1427
**Plugin version:**
AcidIsland V3.0.8.8
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
Upgrade from V3.0.9.7
**Description of issue. What happened?**
Bed explosions don't spawn fire
**Steps to make this happen**

1. Place a bed down in the nether
2. Interact with it

**What do you think should happen?**
Bed explosions should spawn fire like they do in vanilla.

**Comment by tastybento** [comment]
Beds in the nether are treated like TNT, so if TNT damage is disabled, then they will do nothing. You'll need to set allowtntdamage: true if you want them to explode.

**Comment by TheWranger** [comment]
Beds are exploding perfectly fine, the issue is that they aren't spawning fire like they do in vanilla.

**Comment by TheWranger** [comment]
@tastybento I have tnt damage disabled and im still able to blow up beds in the nether.

**Comment by tastybento** [comment]
Yes, beds will explode, but do not cause any block damage if TNT damage disabled.

 If you want fire, then you probably need to turn on fire or fire_spread. I'm not sure which would be required in this case, maybe FIRE_SPREAD. You'll need to add FIRE and FIRE_SPREAD to the island protection settings and then set them to be true/allowed through the GUI. If you want to apply this to all islands, then set them to be true in the world settings and do /asadmin settingsreset all.

**Comment by TheWranger** [comment]
Okay, settings FIRE to true was able to fix this issue, but won't this now mean that visitors can start fires using flint and steel on others peoples islands?
