### ISSUE TITLE
Massive lag on is delete

### ISSUE THREAD

**Issue by JamieSinn** [tastybento/ASkyBlock-Bugs-N-Features#794]
https://timings.aikar.co/?id=ca33ed2772674e97b23d81a3cb401889

This is from a default island.

**Comment by tastybento** [comment]
This is from a recurring 1 second timer that deletes the blocks around the edge of an island bit by bit. The additional blocks are deleted depending on the island distance and whether the distance lines up with a chunk boundary or not. You can see it takes about 30 seconds and this is shown also in the console log. The timings report measures it as a task taking 30 seconds, but it's not accurate in terms of actual lag. The task deletes a few blocks, then quits until the next second it is called. So actual lag is diminished by this approach.
So, this is how it is designed to work and is not a bug.
