### ISSUE TITLE
Question about hoppers

### ISSUE THREAD

**Issue by TheWranger** [tastybento/ASkyBlock-Bugs-N-Features#796]
Does hopper inventory protection rely on _InventoryMoveItemEvent_? I want to know whether it's safe to disable the event through paperspigot or not.

disable-move-event
default: false
description: Completely disables the InventoryMoveItemEvent for hoppers. Dramatically improves hopper performance but will break protection plugins and any others that depend on this event.

**Comment by tastybento** [comment]
Not for my plugin no.

**Comment by TheWranger** [comment]
ok, thanks
