### ISSUE TITLE
/is invite bypasses vanish

### ISSUE THREAD

**Issue by NxDs** [tastybento/ASkyBlock-Bugs-N-Features#798]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
TacoSpigot 1.8
**Plugin version:**
3.0.8.6
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
Upgrade, the version right before
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
You're not checking with player1.canSee(player2) (which is standard bukkit API) when sending out /is invites and probably other commands too, this means players are able to know if staff are online and vanished
**Steps to make this happen**

1. Use any vanish plugin and go in vanish
2. Use any account that can't see vanished players
3. /is invite \<vanished player>

**What do you think should happen?**
It should say that the player is offline

**Comment by tastybento** [comment]
Thanks.
Fixed for invite, coop, expel, ban.
