### ISSUE TITLE
Spawn Area

### ISSUE THREAD

**Issue by Inspectiver** [tastybento/ASkyBlock-Bugs-N-Features#799]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
1.12 spigot
**Plugin version:**
latest
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
no
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
When I type /asadmin setspawn, it doesn't actually cover the entire spawn area.
**Steps to make this happen**

1. /asadmin setspawn

**What do you think should happen?**
it should cover the entire spawn area.

**Comment by tastybento** [comment]
Set spawn sets the spawn location, but the spawn island still is set to the regular island grid. If you want to extend the range further, then do /asadmin setrange <range> while on the island to cover whatever you need to.
