### ISSUE TITLE
Add option to desactivate challenges

### ISSUE THREAD

**Issue by tastybento** [tastybento/ASkyBlock-Bugs-N-Features#8]
_From @Poslovitch on March 26, 2017 13:38_

Like "useEconomy" or "useMinishop"

_Copied from original issue: tastybento/askyblock#588_

**Comment by tastybento** [comment]
This is already possible using permissions.

**Comment by tastybento** [comment]
_From @Poslovitch on March 27, 2017 4:26_

Yes, but like the minishop it looks more «clean»

**Comment by tastybento** [comment]
Okay, if you want to add it. :-)

**Comment by Poslovitch** [comment]
Handled in #10
