### ISSUE TITLE
[Request] Ocean Biome and Mob limit adjustment

### ISSUE THREAD

**Issue by tastybento** [tastybento/ASkyBlock-Bugs-N-Features#80]
_From @Kritex on March 30, 2017 21:12_

- I think more biome (Ocean, etc.) should be added to plugin. The Reason is new farming techniques and supply will be gathered in this way. 

- Mob limits are having an issue. Limits in config are not working properly. (Version V3.0.5.4)

_Copied from original issue: tastybento/askyblock#599_

**Comment by tastybento** [comment]
_From @SaitDev on March 31, 2017 4:24_

3.0.5.4 doesnt have island mob limit. Its just mob limit in a chunk.
Use newest version https://www.spigotmc.org/resources/askyblock.1220/

**Comment by Poslovitch** [comment]
I will add some of these new biomes in the default config. But don't forget you can add them by yourself too ;)
