### ISSUE TITLE
Top ten bug?

### ISSUE THREAD

**Issue by Milan09NL** [tastybento/ASkyBlock-Bugs-N-Features#801]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc: Spigot 1.12.2

**Plugin version: V3.0.8.8

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened? my top 10 is created with axes (diamond/gold atm)

**Steps to make this happen**

1.  bug?
2. install
3. 

**What do you think should happen? idk

how to change the axes to another item?

**Comment by tastybento** [comment]
That is what the plugin offers. There is not a way to change the trophy items right now.
