### ISSUE TITLE
Island Reset Not Functioning

### ISSUE THREAD

**Issue by xXSKILLS2015Xx** [tastybento/ASkyBlock-Bugs-N-Features#805]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.8.8

**Plugin version:**
Latest (v3.0.8.8)

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
Upgrade, earlier version was giving the same issues. The earlier version was (v3.0.8.6)

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
SimpleAutoBroadcast, PlaceholderAPI, PlugMan, FastCraftPlus, ChatReaction, Arconix, CrispyChatControl, CustomHeads, AntiPortalTrapping, ViaVersion, ViaBackwards, Actionbar, Essentials, PlayerMention, ClearLag, ArmorStandEditor, Hub, BarGamble, BuycraftX, ProtocolLib, DeathMessagesPrime, FastAsyncWorldEdit, DeluxeMenus, EssentialsChat, SpawnerUpgrader, PermissionsEx, NoWeather, CCM2, Vault, ViaRewind, CrazyCrates, ClearChat, FastAsyncVoxelSniper, Item2Chat, Trading, HideAndCustomPlugins, EssentialsProtect, VoxelSniper, EssentialsSpawn, MyCommand, WorldEdit, AcidIsland, LiteBans, Multiverse-Core, SexyPEX, Citizens, KitPreview, CrazyAuctions, MineResetLite, CustomOreGen, HolographicDisplays, HolographicDisplaysPatch, WorldGuard, CommandNPC, CommandRegions, CRegionsPlus, SilkSpawners, ChestShop, ArmorStandTools

**Description of issue. What happened?**
Every time I type /ai reset or /is reset it says "Teleporting you to your island. (/ai help for more info)"

**Steps to make this happen**

1. Type /ai reset

**What do you think should happen?**
It should say type the command again, then once I do it should allow me to pick another island type from the islands menu.

**Comment by tastybento** [comment]
Are you saying that you see nothing at all? Are there any console logs or errors? Do you usually have multiple islands for players to choose from or just one?

**Comment by xXSKILLS2015Xx** [comment]
When I type the reset command it teleports me to my island and says "Teleporting you to your island. (/ai help for more info)". There are no console logs or errors when this issue is replicated. And I have multiple islands for my players which is why this is weird for me to experience.

**Comment by tastybento** [comment]
Is this true for everyone or just you? Often the best approach is just to completely delete the player by doing /asadmin delete <player>. That should clear out any weird stuff.

**Comment by xXSKILLS2015Xx** [comment]
Alright, I'll try a few things. Worse case scenario I use a newer server version, delete the plugin folder, or other. Thanks for your help Tastybento, that's all I have for you today :) Thanks for your gracious and generous support.
