### ISSUE TITLE
/is value broken as of latest commit.

### ISSUE THREAD

**Issue by andrewkm** [tastybento/ASkyBlock-Bugs-N-Features#808]
@tastybento @JamieSinn 

The latest commit https://github.com/tastybento/askyblock/commit/23b95330125184ff72f94797c9a9e3eadab08ded breaks the regular **/is value** when you have an item in your hand, or when you have nothing in your hand.

**/is value** In game error:
https://i.imgur.com/eXipvHV.png

**/is value** Holding dirt:
https://pastebin.com/raw/6xB7kAVH

**/is value** Holding nothing:
https://pastebin.com/raw/Cqj4Legj

**/is value dirt**
https://i.imgur.com/66nEp8B.png (Works)

The only way to now use **/is value** is with the item name in the command (**/is value dirt**) which does work.

**Comment by JamieSinn** [comment]
https://github.com/tastybento/askyblock
