### ISSUE TITLE
[Request] Add the ability to change island header

### ISSUE THREAD

**Issue by tastybento** [tastybento/ASkyBlock-Bugs-N-Features#81]
_From @google32465 on March 30, 2017 11:32_

Currently there is no option to change the island help header. It currently displays ASkyblock V3.0.6.1. Can you add the ability to change it please. 

Thanks

_Copied from original issue: tastybento/askyblock#598_

**Comment by tastybento** [comment]
This was actually intentional. I don't want it ever not to say that. It basically lists the name of the plugin and the version number so that players can tell what version of the game they are playing.
@google32465 - can you tell me why you want this?

**Comment by google32465** [comment]
I want this feature not because i don't want to support the plugin. It is the fact it doesn't match with any messages we use on our network. What if you add /island about and add all the info in there. @tastybento

**Comment by Poslovitch** [comment]
It's exactly what i thought of some days ago.
Add a command like /asb or /ai which sends the player all data about the plugin : name, contributors etc...

**Comment by tastybento** [comment]
**/is about** exists already, we can add the info there. Okay, accepted.
