### ISSUE TITLE
[Idea] Make more editable /c

### ISSUE THREAD

**Issue by Yhenko** [tastybento/ASkyBlock-Bugs-N-Features#811]
Hi..
Bad english, sorry.

That, make more editable the challengs info, like this: 

https://i.gyazo.com/17c80065d12358e2c3797f0759914c85.png

or tell me how can i make that xd

**Comment by Poslovitch** [comment]
It has already been suggested for BSkyBlock.
We're no longer adding feature into ASB, as we will be dropping it very soon.

But you can still use ChestCommands to do that. Or FeatherMenus or any plugins that allow to create menus.
