### ISSUE TITLE
Guardians do not spawn

### ISSUE THREAD

**Issue by pmyers123** [tastybento/ASkyBlock-Bugs-N-Features#812]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
1.12.2

**Plugin version:**
3.0.8.8
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
new install
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
multiverse, vault, core protect, custom recipes
**Description of issue. What happened?**
We have not been able to get any guardians to spawn
**Steps to make this happen**
I took the seed, plugged it into amidst to locate where guardian temples were in the world. Changed the biome to deep ocean, and filled in water from y=0 to y=62 where the temple is located in the regular world with the seed. squid spawn like crazy, but no guardians spawn. I'm hearing this is the norm for askyblock. why is this and how do we get guardians to spawn? the world difficulty is on 2, not peaceful.

**What do you think should happen?**
guardians should spawn

**Comment by tastybento** [comment]
I don't know. I don't do anything specific to stop them. I'd guess it's something related to whether the underwater temples are created naturally or not because Guardians do not spawn in general unless those exist.
