### ISSUE TITLE
Question: How does island purge work?

### ISSUE THREAD

**Issue by andrewkm** [tastybento/ASkyBlock-Bugs-N-Features#815]
In regards to:

```
   # Islands below this level will be removed if they are abandoned and admins issue the purge command
   abandonedislandlevel: 10
   # Maximum number of islands to purge in one go. Don't make this too big because if you
   # stop the server mid run, you may end up with incompletely deleted islands
   maxpurge: 500
```

1.When you issue the purge command does it just delete all islands below level 10?
2. Is there a number of days a user needs to be offline before this considers them as abandoned?
3. Does this purge command delete the YML files out of the ASkyBlock/players folder (as that folder gets quite big).

**Comment by tastybento** [comment]
1. No
2. Yes
3. No

When you issue the purge command, you give it a number of days, e.g., 30. This means that any players who have not logged in within 30 days AND have an island under level 10 will be scheduled for purging. The command will tell you how many that is and you will then be able to confirm. Note that there is a limit to the number done (500) in one go. 

I recommend you issue the purge command with a few different day values starting with something large and then getting smaller, like 120, 90, etc. and see how it goes.

**Comment by andrewkm** [comment]
Is there any way we can clean the YML files. A purge for that would be really nice, the amount of files is really slowing our backup system :(

@tastybento any advice on this?

**Comment by tastybento** [comment]
There is not a way. It's aggravatingly difficult to do this in ASkyBlock because the island deletion is async and can take an arbitrary amount of time, after which the player's file is saved. It could be done, but it's a lot of programming to add. This is being addressed in BSkyBlock. You could write an offline app or plugin that scans each YAML file for the lines below and then deletes the file:

```
hasIsland: false
hasTeam: false
```

This basically means the player has no island and is not in a team.

**Comment by andrewkm** [comment]
@tastybento man I badly wish you included a config option that would purge empty users on server startup.

11,000+ files and growing is causing a mess when it comes to backups lol.
I cry.

**Comment by tastybento** [comment]
The way forward is BSkyBlock and MySQL (or MongoDB). Big servers will not be using YAML files for data with BSB. So, there is a plan and it's taking up much of my time developing right now. ASkyBlock is in maintenance mode only right now.

**Comment by andrewkm** [comment]
Ah makes sense. Hopefully BSkyBlock has some friendly conversions as part of it. XD
