### ISSUE TITLE
Question about API

### ISSUE THREAD

**Issue by theCarso** [tastybento/ASkyBlock-Bugs-N-Features#816]
Server Version: Spigot 1.8

Plugin Version 3.0.8.8

Hey! I am currently adding some cool features to my server using the ASkyBlock api, and looking into it I noticed that Island#getMembers() returns coop, members, and the owner of the island. I am attempting to get the members without coop people, so I am using the getCoopIslands(Player) method. However, this method returns a Set of Locations, and I was wondering how to use this to check if a player is cooped into an island. Thanks!

**Comment by tastybento** [comment]
That is kind of missing from the API class. You can use:

CoopPlay.getInstance().getCoopPlayers(Location)
