### ISSUE TITLE
Can we revisit #807 - NPE from YAML Save

### ISSUE THREAD

**Issue by andrewkm** [tastybento/ASkyBlock-Bugs-N-Features#817]
Can we please revisit:
https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/807

To implement the suggestion by @aikar
It would really help prevent having major issues in the future.

> I would suggest saving to a temp file instead, and delete the previous and rename temp to new on successful write, to avoid data loss at least.

**Comment by tastybento** [comment]
Closing as we'll discuss on #807
