### ISSUE TITLE
Add placeholders to cp lore

### ISSUE THREAD

**Issue by tastybento** [tastybento/ASkyBlock-Bugs-N-Features#82]
_From @tastybento on January 29, 2017 18:21_

Add placeholders for level, biome, number of island members to CP lore entries.
From: https://www.spigotmc.org/threads/a-skyblock.30325/page-169#post-2196802

_Copied from original issue: tastybento/askyblock#484_

**Comment by Poslovitch** [comment]
Duplicate of #16, closing
