### ISSUE TITLE
Island Top 10 - Wrong levels

### ISSUE THREAD

**Issue by iBradyy** [tastybento/ASkyBlock-Bugs-N-Features#820]
Paperspigot 1.12.2 (1433)

3.0.8.8

We have been using this version since it has been came out.

Island Top 10 does not show the correct levels.

**Steps to make this happen**

1. I did /asadmin info <the number one island> it showed "Island level: 2044"
2. When I did /is top, it says that the number one island is at level 63751.

We used ASkyBlock in the past and we have cleared all data because of a full reset. Somehow it is still showing old island levels from before the reset in the /is top. It only occures for number 1, 2 and 3 on the top list.

**Comment by tastybento** [comment]
Top Ten is stored in topten.yml. You can either delete it and let it be generated organically as players do /is level, or you can delete the top 3 islands you think are wrong. Maybe when you did the reset this file was not deleted.

**Comment by iBradyy** [comment]
Hi,

I have already removed the file and ran /asadmin topten. This did not solve the issue.
Even when I let the Top 1 player execute the command /is level it just says 2044. But it will still show up as 63751 on the top. Also, in the topten.yml it says 63751.

![51414](https://user-images.githubusercontent.com/14994117/41545683-0d04ef44-731c-11e8-8735-7ded74fb3f74.png)
![82951](https://user-images.githubusercontent.com/14994117/41545686-0e87a4f6-731c-11e8-823b-45dfe00b3af2.png)
