### ISSUE TITLE
Inconsistent startup message color.

### ISSUE THREAD

**Issue by andrewkm** [tastybento/ASkyBlock-Bugs-N-Features#821]
Just a random thing I noticed that is super low priority and just slightly hurts the OCD:
https://i.imgur.com/CQKoTEt.png

Inconsistent coloring. Would be nice to just remove all colors from startup. :)

**Comment by tastybento** [comment]
Don't say I never do anything for you!!! :-)

**Comment by andrewkm** [comment]
Thank you so much :)
