### ISSUE TITLE
My /is top shows items & tools instead of playerheads?

### ISSUE THREAD

**Issue by Jakka12** [tastybento/ASkyBlock-Bugs-N-Features#824]
Server Version: CraftBukkit version git-Spigot-2086bb0-8cc5a7e (MC: 1.12.2)

Plugin version: V3.0.8.8

Is this a new install or upgrade? New Install

Description of issue: Whenever I do /is top (Yes I have tried resetting it) it shows blocks/tools instead of player heads

**Comment by tastybento** [comment]
Yes, player heads were removed in the last version because they caused server crashes.

**Comment by Jakka12** [comment]
Ah okay

**Comment by Jakka12** [comment]
Ah, well i tried that but didn't have that option in my config?

**Comment by Poslovitch** [comment]
That's a "secret" option. That's why you have to add it by yourself.

**Comment by Jakka12** [comment]
Alright, thank you a ton! Finally figured it out :)
