### ISSUE TITLE
Askyblock Please fix this bug ASAP

### ISSUE THREAD

**Issue by Lightsabre800** [tastybento/ASkyBlock-Bugs-N-Features#826]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot + Bukkit 1.12.2
**Plugin version:**
Latest
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
No I did not upgrade 
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
 WorldEdit, HungerKeeperPlus, EggCatcher, ColoredSigns, VarietyLuckyBlocks, VoidWorld, Vehicles, ClearLag, ChatControl, SetSpawn, NametagEdit, BuycraftX, WorldGuard, LaunchPadPlus, NoCheatPlus, ItemNameTags, DeluxeTags, CustomEnchants, SuperTrails, SpawnerUpgrader, WelcomeWarpSigns, PermissionsEx, CS-CoreLib, ViaVersion, Vault, Essentials, BeastWithDraw, SilkSpawners, KitAdder, GUIShop, Essentials_KitGUI, Citizens, ASkyBlock, SimplePrefix, PlayerVaults, ASkyBlock-IslandBorder, CustomOreGen, Multiverse-Core, DiscordSRV, HolographicDisplays, CratesPlus

**Description of issue. What happened?**
The issue is that when any player types /is  it says : 
![Uploading Screen Shot 2018-06-21 at 5.27.01 pm.png…]()
(if you can't see it it says : That warp is not safe right now. Try again later.
**Steps to make this happen**

1.  Read this post
2. Try to fix it
3. Eventually do it

**What do you think should happen?**
when you do /is you see a sky block Gui that allows you to choose the normal island the hardcore island and the double island you click it and it generates the island that you can play sky block on.

**Comment by Poslovitch** [comment]
You sounds very, very rude and disrespectful there. What if your problem is more likely a FAQ?

**Comment by Lightsabre800** [comment]
Sorry I was in a hurry to write this

**Comment by tastybento** [comment]
It's not a bug - the player's island is not safe to warp to - maybe it's been deleted, or maybe your database has been corrupted. I recommend you try using a backup of your world/data. Apart from that I'm not sure what to say.
