### ISSUE TITLE
Possible to sort island settings?

### ISSUE THREAD

**Issue by Jakka12** [tastybento/ASkyBlock-Bugs-N-Features#827]
Plugin version: V3.0.8.8

Hey is it possible to sort the island settings (in the GUI) with the current version, or could some sort of "order" system perhaps be added? Like (Order: 1)   etc.

**Comment by Poslovitch** [comment]
We're no longer adding features into ASkyBlock. However, that is something that is already planned for BSB.

**Comment by Jakka12** [comment]
Oh nice, I used the Bskyblock thingy, but it seems like it still in a pretty early state haha, will it be possible to have islands sized example 99x99x256 in bskyblock?

**Comment by Poslovitch** [comment]
That's right. BSB is still under heavy development, but we are focusing on releasing a stable alpha version alongside 1.13's release. That's impossible to have not-even island ranges : it would make the island center be an imaginary point between 4 blocks. And, for data-security reasons, we have to keep the island center as bedrock).

**Comment by Jakka12** [comment]
I was just wondering because another plugin (IslandWorld) is capable of doing so, also how would it be an imaginary point if let's say there are 48 blocks on each side of bedrock? (sorry just wondering since i have done it before with IslandWorld though IslandWorld is not as good as ASkyBlock when it comes to everything else haha :p

**Comment by Poslovitch** [comment]
I'll have a look at how IslandWorld did this. If it's as secure as our current "anti-data-loss" system and doesn't need too much changed to the current BSB codebase, then I'll consider implementing it.

**Comment by Jakka12** [comment]
Alright nice, now that we are talking here anyways - is there any way to disable the island coop confirmation? or is that only in the older versions of ASkyBlock?

**Comment by Poslovitch** [comment]
I thought we added a config option for that. I'm not sure.
However, that's better to have the confirmation. It makes it safer for the visitors.

**Comment by Jakka12** [comment]
Hmm, true (well not with my settings) would it be possible to have an option for that though? Since else downgrading seems like the only fix

**Comment by Poslovitch** [comment]
Downgrading is the worse thing you could ever do.

I suggest you to open a new ticket to ask for an option. Or wait for BSkyBlock :)
