### ISSUE TITLE
Feature request - option to choose whether to accept coops or not

### ISSUE THREAD

**Issue by Jakka12** [tastybento/ASkyBlock-Bugs-N-Features#828]
Hi, I would like if an option allowing me to choose whether players have to accept being cooped or not :)

**Comment by Jakka12** [comment]
Bump? could this at least be answered?

**Comment by tastybento** [comment]
We're not accepting feature requests - sorry. It'll be an option in BSkyBlock, but in ASkyBlock it is what it is now.
