### ISSUE TITLE
Skyblock breaking Slimefun

### ISSUE THREAD

**Issue by FoxWithSox** [tastybento/ASkyBlock-Bugs-N-Features#830]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

Spigot 1.12.2 latest build

Askyblock version 3.0.8.8

upgrade from previous version

**Description of issue. What happened?**

Skyblock is causing slimefun to not work

here is the pastebin with the errors

https://pastebin.com/McbeY1En

**Comment by tastybento** [comment]
Responded on Spigot. Will be fixed in 3.0.8.9. Try the prerelease if you like.
