### ISSUE TITLE
Build/break error

### ISSUE THREAD

**Issue by Owner-Arnaw** [tastybento/ASkyBlock-Bugs-N-Features#832]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
-1.8-1.12 Spigot

**Plugin version:**
ASkyBlock V3.0.8.5

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
No,is not a new upgrade

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
 AnimationLib, WorldEdit, TitleMotd, Essentials, PlaceholderAPI, PacketListenerApi, ClearLag, DisableJoinMessage, Lobby, Hub, OnlyProxy, MessageAnnouncer, MapManager, ActionHealth, ProtocolLib, WorldGuard, OldCombatMechanics, NoPluginPlus, IPWhitelist, EssentialsProtect, EssentialsChat, EssentialsAntiBuild, SimpleAPI, Vault, UltraPermissions, EssentialsSpawn, MassiveCore, ScoreboardPlus, TitleManager, AnimatedMenu, CrazyCrates, AnimatedFrames, Jobs, CreativeGates, SimplePets, Citizens, ASkyBlock, ShopChest, CommandNPC, ProtocolSupport, Multiverse-Core, SkinsRestorer, ProtocolSupportLegacySupport, ProtocolSupportStuff, HolographicDisplays

**Description of issue. What happened?**
Users can't break or build in her islands

**Steps to make this happen**

1.  player go to island
2. can't build/break
3.

**What do you think should happen?**
I don't know but here is the config file http://www.mediafire.com/file/v7jd43kxu8tn4i9/config.yml/file

**Comment by tastybento** [comment]
Please read the FAQ for this question.
