### ISSUE TITLE
Players can't craft Trapped Chests

### ISSUE THREAD

**Issue by alnoise** [tastybento/ASkyBlock-Bugs-N-Features#834]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

Spigot 1.8.8

V3.0.8.8

New install

Players can not craft Trapped Chests. Even with the askyblock.craft.* permission

**Steps to make this happen**

1. Install plugin
2. Give player all craft perms with askyblock.craft.*
3. Have a member try to craft a trapped chest

Players should be able to craft those I think..

**Comment by tastybento** [comment]
There's no blocking of trapped chests in ASkyBlock. The craft permission is for Enderchests. I just tested on 1.8.8 and I can craft them fine. What error do you see when you try to craft one? It's most likely some other plugin.
