### ISSUE TITLE
Spawners as Island Level!

### ISSUE THREAD

**Issue by 1TheCoolKid** [tastybento/ASkyBlock-Bugs-N-Features#836]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot
**Plugin version:**
3.0.8.3
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
When we add spawners to the block values for island level they do not work. I was wondering why?
**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**

**Comment by tastybento** [comment]
What are you adding exactly? As spawners are not actually craftable, they are not usually counted. It's not possible to differentiate between spawner types, just the block should work though. i.e., MOB_SPAWNER

**Comment by 1TheCoolKid** [comment]
Basically I want to add an iron golem spawner to it. So what ould I do with that. I Use silkspawners

**Comment by tastybento** [comment]
You can only add MOB_SPAWNER in general and you cannot specify the type of mob-spawer because that's a type of meta data that is not collected during level calculations. Sorry.
