### ISSUE TITLE
Unhandled exception executing commands

### ISSUE THREAD

**Issue by N0tMyFaultOG** [tastybento/ASkyBlock-Bugs-N-Features#837]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Thermos 1.7.10-1614.57

**Plugin version:**
ASkyBlock v3.0.8.8

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

![](https://i.imgur.com/myUZi4m.png)

**Description of issue. What happened?**

The player were unable to teleport (`/is`) to their island. Neither a staff member was able to teleport to their island with the given command (`/asadmin tp <name>`)
Player: https://hasteb.in/lufogeci.kot
Staff: https://hasteb.in/efirolik.kot

**Steps to make this happen**

I'm unsure where the issue is, but I can tell, there is no spectator mode in 1.7.10
(`Caused by: java.lang.NoSuchFieldError: SPECTATOR`)

**What do you think should happen?**
A fix to prevent this. Or a little workaround.

**Comment by Poslovitch** [comment]
1.7.10 is not supported on ASkyBlock :/

**Comment by N0tMyFaultOG** [comment]
![](https://i.imgur.com/Mx1j7KV.png)
We're using ASkyBlock for our 1.7.10 modded sky packs, sad that we can't use it again if it doesn't get patched :(

**Comment by Poslovitch** [comment]
This is not up to date. We dropped 1.7.10 support as of 3.0.5, as far as I can remember.
Which Modded "Sky" pack are you using? Maybe there is an alternative running on 1.12.

**Comment by tastybento** [comment]
Fixed.
