### ISSUE TITLE
FastAsyncWorledit crashes ASkyblock

### ISSUE THREAD

**Issue by alexvermaning0** [tastybento/ASkyBlock-Bugs-N-Features#840]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
1.12.2
**Plugin version:**
3.0.8.8
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
3.0.8.8
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
[18:26:19 INFO]: Plugins (49): GhostBuster, VoteRoulette, WorldEdit, FastCraft,
PlaceholderAPI, DisableJoinMessage, PlugMan, Votifier, VoteParty, ProtocolLib, W
orldGuard, Arconix, MVdWPlaceholderAPI, DeluxeMenus, SpawnerUpgrader, Permission
sEx, FeatherBoard, NoWeather, AntiPortalTrapping, Vault, MyCommand, ProtocolSupp
ort, Actionbar, CrazyCrates, ChestShop, Essentials, ArmorStandTools, CommandRegi
ons, AntiCommandTab, Item2Chat, CRegionsPlus, Trading, SilkSpawners, Citizens, A
SkyBlock, CrazyAuctions, EssentialsChat, CommandNPC, EssentialsSpawn, UltimateKi
ts, ShopGUIPlus, TitleManager, CustomOreGen, BarGamble, Multiverse-Core, MineRes
etLite, BlockParticles, HolographicDisplays, FastAsyncworldedit
**Description of issue. What happened?**
the plugin crashed when i installed FastAsyncworldedit
**Steps to make this happen**
1.  put the plugins in the server
2. start the server
3. done

**What do you think should happen?**
that the plugin works

**Comment by TheWranger** [comment]
FastAsyncWorldEdit works fine for me, could you post an error code or something?
