### ISSUE TITLE
Not being teleported on island reset

### ISSUE THREAD

**Issue by TheWranger** [tastybento/ASkyBlock-Bugs-N-Features#841]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
PaperSpigot 1427 MC:1.12.2
**Plugin version:**
AcidIsland V3.0.8.8
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
New install
**Description of issue. What happened?**
Changed AcidIsland's world generator to CleanroomGenerator by following all the steps on the wiki and now when a player is in the island world and they reset their island, the old island is deleted but the new one doesn't generate. Works fine when the player is in a different world and resets.
**Steps to make this happen**

1.  Switch the world generator to CleanroomGenerator by following the steps on the wiki and using the command `/mvcreate AcidIsland normal -g CleanroomGenerator:3,sand,46,water`
2. Generate a new island
3. Reset your island while still in the island world.

**What do you think should happen?**
The new island should generate.

**Comment by TheWranger** [comment]
I also have my AcidIsland world set to `islands`, but I doubt this makes a difference.

**Comment by tastybento** [comment]
Any console log?

**Comment by TheWranger** [comment]
No console error, but I realised that the issue isn't that the new island is generating, it's just that the player isn't being teleported to the new island. Bug doesn't seem to happen every time, either.

**Comment by TheWranger** [comment]
ok, so it only happens with schematic islands.

**Comment by tastybento** [comment]
Are you using the useowngenerator: true flag in config.yml?

**Comment by TheWranger** [comment]
yes, I am

**Comment by TheWranger** [comment]
https://pastebin.com/KnqFbXjX

**Comment by tastybento** [comment]
I just tested and I can't replicate this. I teleport fine whether I'm using the regular or temple island. Weird. By the way, if you are going to do this you need to make sure the island distance is a factor of 16 blocks, e.g. 192, otherwise during deletion, the CleanroomGenerator cannot do its stuff on those chunks around the edge and the plugin will generate void or water instead.
