### ISSUE TITLE
Acid Rain setting off AntiCheat

### ISSUE THREAD

**Issue by TheWranger** [tastybento/ASkyBlock-Bugs-N-Features#842]
When jumping around in acid rainfall, the rain can set off anticheat false positives for Spartan (https://www.spigotmc.org/resources/spartan-anticheat-advanced-detections-hack-blocker.25638/) and likely other anticheats too.
Solutions:
1. Add option to disable the knockback taken from acid rainfall, thus allowing for a workaround for people like me that have this issue.
2. Update API with methods that would allow anticheat devs to recognize acid rainfall and develop patches.

**Comment by tastybento** [comment]
There's no specific way to disable knock back so the only thing I can do for you is add some events that fire when players get acid damage or acid rain damage.
