### ISSUE TITLE
coop players cannot place or break any blocks

### ISSUE THREAD

**Issue by FiRe33Gaming** [tastybento/ASkyBlock-Bugs-N-Features#845]
Server Version: 1.11

Askyblock v 3.0.8.8

latest version

WolrdEdit worldguard, Essentials : 2x , XMPP , GroupManager , Spawn , Chat
ASkyblock 

I invite my friends to my island but they can't place or break block , nothing worldguard region 

I don't know what is happen

Sorry if there are any vocabulary errors, I am French
FiRe33Gaming

**Comment by tastybento** [comment]
Hmm, weird. We have a French Discord help channel - try https://discord.gg/Rku5DD

**Comment by FiRe33Gaming** [comment]
ok thx
