### ISSUE TITLE
The reset and start commands of config.yml

### ISSUE THREAD

**Issue by Tinkergolem** [tastybento/ASkyBlock-Bugs-N-Features#846]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.12.1
**Plugin version:**
V3.0.8.8
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
This was a new install, I deleted the entirety of the previous version(jar, plugin folder, and worlds) to make sure it wasn't an upgrade issue
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
WDLCompanion, PerWorldPlugins, NametagEdit, Spawner, BetonQuest, EpicWorldGenerator, CoreProtect, Skript, MythicMobsPatcher, ArmorStandEditor, ChatControl, SkQuery, ProtocolLib, LibsDisguises, Vouchers, FastAsyncWorldEdit, TabPrefixPlus, iDisguise, PexTabListPlus, PermissionsEx, CS-CoreLib, mcMMO, CustomHelp, Vault, FastAsyncVoxelSniper, PlaceholderAPI, PerWorldInventory, SignColors, ASkyBlock, ChatItem, VoxelSniper, WorldEdit, Essentials, SexyMotd, BeastWithDraw, BuildingGame, goBrush, AcidIsland, BountyHunters, Multiverse-Core, Citizens, EssentialsChat, DeluxeMenus, Mulltiverse-Portals, DuelMe, HolographicDisplays, WorldGuard, Slimefun, MythicMobs, EssentialsProtect, EssentialsAntiBuild, WeatherMan, Multiverse-NetherPortals, CommandNPC, EssentialsSpawn, CratesPlus, WorldGuardExtraFlags, TitleManager, RandomCoords, MythicMobExtension, MultiWorldMoney, ServerTutorialPlus, Jobs, TNTRun, SilkSpawners, dtlTraders, ShopChest, PlayEffect, ProRecipes, MythicArtifacts, ProtectionLib, FurnitureLib, FurnitureMaker, DiceFurniture
**Description of issue. What happened?**
Unable to get the resetcommand and startcommand section of the config to work. I'm trying to add a command to change the player's prefix using permisssionsEx when they reset or start their island. I tried adding the given example as well, but nothing occurred.
**Steps to make this happen**
Make sure to have permissionsEx and
1. Add this into the config in the respected section
```
   resetcommands:
   - "pex user [player] prefix &7[&aStarter&7] ASkyBlock"
   - "pex user [player] prefix &7[&aStarter&7] ASkyBlock_nether"
   - "kit tools [player]"
```
2. Shut down the server
3. Start the server back up
4. Enter the server
5. Do /is
6. After creating the island, do /is reset followed by /is confirm
7. Say hi in chat to check for prefix

**What do you think should happen?**
I wanted the player to receive a prefix when reseting or starting a new island.

**Comment by tastybento** [comment]
Does the player receive the tool kit? Does the pex command usually work in the console? i.e., without ASkyBlock, can you change the player's prefix okay? I've had issues with PEX prefixes before so that's why I'm asking.

**Comment by tastybento** [comment]
So, the general issue is that the commands are not executing for you. If you are testing as Op, or have the askyblock.command.newexempt , askyblock.command.resetexempt or askyblock.* perms then the commands will not execute. Try as a regular player without those perms. I just tested on a clean install and it all works fine.

**Comment by Tinkergolem** [comment]
Thanks, I will be sure to try it once able to. By the way, is there a way for some OP to execute the commands without needing to de-op themselves? I have some staff who regularly play the server who have this status, but require OP to carry out some duties. If there's no option/way, then I'm fine with this as the only solution.

**Comment by tastybento** [comment]
You have to give yourself the negative permission, for example -askyblock.command.newexempt. Then even if you are Op, you will be read as not having that perm. That's actually the best way to test this - give yourself these negative perms and you should see the command execute.

**Comment by Tinkergolem** [comment]
Ok, I tried the negative versions, but still had no result. I then de-oped and gave myself a member rank which still didn't execute the commands. Any options?

**Comment by tastybento** [comment]
At this point, I suspect your YAML. Paste in (zipped up) a copy of your config.yml so I can check if it works for me.

**Comment by Tinkergolem** [comment]
[http://www.mediafire.com/file/7kgaxjkroaukk43/config.zip](url)

**Comment by tastybento** [comment]
Works fine. Well, at least the balance and kit commands do. Like I say, I've always had issues with pex prefixes (by the way, how does issuing the command twice do anything? Doesn't the last one overwrite the first?). At this point, it's likely some other plugin or config issue. I suggest you do a clean install with ASkyBlock, Vault and PEX and confirm it all works. Then add the other plugins one by one.
