### ISSUE TITLE
Accepting /is invite teleportation issue

### ISSUE THREAD

**Issue by LordSheep** [tastybento/ASkyBlock-Bugs-N-Features#848]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
1.12.2
**Plugin version:**
ASkyBlock V3.0.8.8
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
New install
**Description of issue. What happened?**
I have allowfallingteleport: false and resetinventory: false. When accepting a /is invite and joining someone's island while on your island at the edge of a block your island deletes and you can't get teleported because it says you can't teleport when falling. You then die and lose everything.  
**Steps to make this happen**
1. Go to edge of block at your island.
2. Accept an invite to someone else's island.
3. Island deletes, you fail to teleport, and you die.

**Comment by tastybento** [comment]
Please try https://github.com/tastybento/askyblock/releases/tag/V3.0.8.9g and tell me if that fixes the problem.

**Comment by LordSheep** [comment]
Tried that version and there seems to be no issue. The player can now teleport fine while standing on edge of a block. Can that version be used for my server?

**Comment by tastybento** [comment]
Yes. I'm going to release it now officially.
