### ISSUE TITLE
Failing to start

### ISSUE THREAD

**Issue by TheWranger** [tastybento/ASkyBlock-Bugs-N-Features#849]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper 1487
**Plugin version:**
AcidIsland V3.0.8.9
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
Upgrade from V3.0.8.8
**Description of issue. What happened?**
Plugin fails to load on server startup.
https://pastebin.com/kjNxcD7y
**Steps to make this happen**

1. Start the server with AcidIsland V3.0.8.9

**What do you think should happen?**
Plugin should start up.

**Comment by tastybento** [comment]
Do you have a custom island schematic? If so, please share it (zip up and drag/drop into this ticket).

Otherwise, I can't replicate right now. I'm not sure why you'd see that error.

**Comment by TheWranger** [comment]
Found the issue; happens when adding `pasteair` open to `default` island.
