### ISSUE TITLE
slimefun not running

### ISSUE THREAD

**Issue by crston** [tastybento/ASkyBlock-Bugs-N-Features#850]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
1.12.2
**Plugin version:**
lastest version
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
3.0.8.6
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**

**Steps to make this happen**

1. slimefun enhanecd workbench not running
2.
3.

**What do you think should happen?**

**Comment by Poslovitch** [comment]
This bug is not related to ASkyBlock nor Slimefun. Repost it on CSCoreLib's bug tracker.
