### ISSUE TITLE
PlayerQuitEvent (Timings)

### ISSUE THREAD

**Issue by Darko266** [tastybento/ASkyBlock-Bugs-N-Features#851]
Hello,

Why is this like that ?
I'm using Spigot 1.8.8 and the latest 3.0.8.9 
![screenshot_1](https://user-images.githubusercontent.com/20874142/42410732-fceb772c-81ee-11e8-9c22-a792ab5cef4e.jpg)

**Comment by Poslovitch** [comment]
31ms sounds not that much at all.
Can you please share us the full timings?

**Comment by Darko266** [comment]
The issue has been fixed.
