### ISSUE TITLE
API Problem

### ISSUE THREAD

**Issue by Heliosard** [tastybento/ASkyBlock-Bugs-N-Features#852]
The latest version, V3.0.8.9, always returns "null" with getOwner().
In addition, an important event is missing in the IslandPreDeleteEvent API to retrieve information from the island before it is deleted.

Thank you for doing what is necessary as soon as possible.

**Comment by tastybento** [comment]
Sorry, can't replicate. This works fine:

player.sendMessage("Owner = " + ASkyBlockAPI.getInstance().getOwner(player.getLocation()));

In regards to additional events, if you're a programmer, quickest way would be to write what you want and do a pull request.

**Comment by Fleodas** [comment]
I have this issue with that code:

`// PLACE_BLOCK flag
    @EventHandler (ignoreCancelled = true)
    void onBlockPlace(BlockPlaceEvent event) {
        Island island = ASkyBlockAPI.getInstance().getIslandAt(event.getBlock().getLocation());
        Player player = event.getPlayer();

        if (island == null) return;

        if (!isCached(island.getOwner(), player)) {
            event.setCancelled(true);
            return;
        }

        int flagSetting = flags.get(island.getOwner()).get("place_blocks");
        int playerRank = PlayerRank.getPlayerRank(player, island);

        if (playerRank <= flagSetting)
            event.setCancelled(true);
    }`*

I get a correct island object with V3.0.8.8 and null island object with V3.0.8.9.

**Comment by tastybento** [comment]
Thanks for the report.

**Comment by tastybento** [comment]
Fixed in commit 70a3ea638fff8420ddcc1499a97b219be1dfe353
