### ISSUE TITLE
Challenges don't look for the right Island Level

### ISSUE THREAD

**Issue by Max2124** [tastybento/ASkyBlock-Bugs-N-Features#854]
My Server Version is Spigot 1.12.1

ASkyBlock v3.0.8.9

This is a new Install of my ASkyBlock Server.
I created new challenges and normaly all of them are working unluckly not all are working as they should.
One Quest Book I made was made only for all of our challenges where you require an spezial amount of Island Level, but a player who just has 10 Island Level is able to complete a challenge which requires 25 Island Level, and thats happening with all Island Level challenges. I wanted that Players need a spezial amount of Island Level for Spezial challenges, unluckly I don't know what am I doing wrong or isn't it possible? Because I know Servers where that is possible, so I'm not sure whats wrong with my challenges.

I would be happy about a answer from you, 
Thanks ;)

**Comment by tastybento** [comment]
Post your challenges.yml so we can look at it. Drag and drop the file to this ticket (you may have zip beforehand).

**Comment by tastybento** [comment]
By the way, challenges can be inventory or level but not both. You cannot create inventory challenges that require you to have a minimum island level.

**Comment by Max2124** [comment]
[challenges.zip](https://github.com/tastybento/ASkyBlock-Bugs-N-Features/files/2174274/challenges.zip)

I hope I send it in right format.

**Comment by tastybento** [comment]
I see the problem. Use:

requiredItems: 25

not

requiredItems: '25'

If you use quotes, the value becomes a string, with an integer value of zero. So you have to use the actual value with no quotes.

Enjoy!

**Comment by Max2124** [comment]
Thanks now it is working. ;)
