### ISSUE TITLE
first island not claimed by person

### ISSUE THREAD

**Issue by LTG123** [tastybento/ASkyBlock-Bugs-N-Features#855]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**server version: spigot mc 1.12.2**

**Plugin version: latest**

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before? it's a new server.. first time using this plugin**

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here) TopLite, WorldEdit, ColoredSigns, WildTP, PlaceHolderAPI, PacketListenerAPI, clearlag, worldborder, buycraftx, votifier, voteparty, solevirtchat, worldguard, arconix, mvdwplaceholderapi, ipwhitelist, permissionsex, dynamicsigns, epicworldgenerator, featherboard, chatwithstaff, vault, galistener, mycommand, protocolsupport, ezrankspro, bungeetablistplus, rankvouchers, essentials, acidisland, silkspawners, multiverse-core, deluxechat, discordSRV, essentialsprotect, kitpreview, essentialschat, viaversion, essentialsspawn, enjinminecraftplugin, shopguiplus, crazyenchantments, protocollib, holographicdisplays, litebans, leaderheads, cratesplus**

**Description of issue. What happened? well everytime that if a new player wants to create a island.. they can't build on it because it says that this island is protected so i went to someone that reported it and did '/acid info' and it told me that this island is not even owned by anyone.. so every time i need to tell the new players to reset their island again so they can finally play**

**Steps to make this happen**

1. 
2.
3.

**What do you think should happen? that if they do /is.. that they can start playing and not have to reset their island first in order to play**

**Comment by tastybento** [comment]
Weird. Is the island always at the same location? E.g. 0,0? 
What happens if when it happens you just register the player to that island by doing /asadmin register <name>? Does it still occur?

**Comment by LTG123** [comment]
i don't know how to check the location.. first time using this plugin
i can do that but then again.. what if i'm not available or not online? the new players that joined can't play untill i'm back?

**Comment by LTG123** [comment]
oh wait when i registered someone it said 0.0

**Comment by LTG123** [comment]
oh when i register someone.. they still can't build

**Comment by tastybento** [comment]
Okay, here's the best approach -

1. Stop the server
2. Make a copy of the ASkyBlock folder, e.g., ASkyBlock_backup - this is just in case
3. Delete the file islands.yml (you can only do this when the server is stopped)
4. Restart the server. The file will be recreated from player file information. 

I suspect the island.yml file is out of sync for some reason so clearing it should work.

**Comment by LTG123** [comment]
let me try

**Comment by LTG123** [comment]
yes it worked thank you so much man awesome
