### ISSUE TITLE
Blockvalues

### ISSUE THREAD

**Issue by Mickael5425** [tastybento/ASkyBlock-Bugs-N-Features#856]
good evening this problem is settled? How do I make this change?

https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/731

**Comment by tastybento** [comment]
Yes, it's in the latest release. You can set negative block values now. Try it.

**Comment by Mickael5425** [comment]
It does not work I have to change something for that?

**Comment by tastybento** [comment]
Sorry, it's a bug. I thought I'd made the change, but I had not. It will be in 3.0.9.1
