### ISSUE TITLE
IslandPreLevelEvent doesn't return the right points to next level

### ISSUE THREAD

**Issue by Cristaling** [tastybento/ASkyBlock-Bugs-N-Features#86]
If I have reached the necessary points for a level exactly, event.getPointsToNextLevel() will return 0 instead the points necessary for the next level.

Example:

I need 2000 points for a level. At 2000 points, the event would return level 1 but 0 points to next level. The expected number would be 2000 to reach level 2.

**Comment by Poslovitch** [comment]
Replicated on 3.0.6.1
Working on a fix for 3.0.6.2

**Comment by Poslovitch** [comment]
This bug is odd:
![img](http://puu.sh/v5GPD/09a22ea0c8.png)

I'll try to see if I can add a double check to be sure the result won't be 0.

**Comment by Poslovitch** [comment]
Will be fixed in https://github.com/Poslovitch/askyblock/commit/45c489ddc73044fe7fb3741fca520734b89f5e5c

**Comment by Cristaling** [comment]
Are you sure rechecking there will fix it? Isn't the right value caused by some code later in the calculation process, so it will be 0 in both cases?

**Comment by Poslovitch** [comment]
As I saw, it calculates the required points based on the actual island level. But it looks sometimes it's not updated. So another calculation with adding 1 level should fix it
