### ISSUE TITLE
Will aSkyBlock supports Minecraft 1.13?

### ISSUE THREAD

**Issue by AconTM** [tastybento/ASkyBlock-Bugs-N-Features#860]
Hey,

i have a simple question :) Will ASkyBlock supports Minecraft/Spigot 1.13? Because, md5 says:
"if your plugin targets native 1.13 support it will NOT be able to run on < 1.13" :/

- AconTM

**Comment by AconTM** [comment]
and will BSkyBlock contains new features or (for beginn) only 1.13 support?

**Comment by Poslovitch** [comment]
BSB will technically contains less features, but that's due to the addons system.
And, as I said, it will only offiicially support the latest Minecraft version. We won't add the multi-version handling. That's too much of a pain.

**Comment by AconTM** [comment]
i want to update my network fast as i can ^^ so it´s perfect for us :D
