### ISSUE TITLE
Player Can't place Lava

### ISSUE THREAD

**Issue by jenaus** [tastybento/ASkyBlock-Bugs-N-Features#861]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

Spigot 1.12

**Plugin version:**

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**

Plugins (63): ItemCase, PluginConstructorAPI, PlaceholderAPI, HyperLinks, Craftconomy3, PlugMan, WishingWells, BetterChairs, ChatReaction, Arconix, DeluxeTags, VoxelSniper, ViaVersion, ViaBackwards, CoreProtect, LuckPerms, AnimationLib, AnimatedScoreboard, SkyBlockLottery, OwnGarden, ClearLag, AdvancedBan, MessageAnnouncer, Votifier, NoCheatPlus, MVdWPlaceholderAPI, FastAsyncWorldEdit, VoidGenerator, LandClaiming, mcMMO, GAListener, Vault, CrazyCrates, VoteParty, ASkyBlock, UltimateBossBar, WorldEdit, CrazyEnchantments, Greenhouses, MultiChatBridge, Essentials, AnimatedNames, AcidIsland, Multiverse-Core, EssentialsChat, Multiverse-Portals, EnjinMinecraftPlugin, CustomOreGen, Holograms, WorldGuard, EssentialsXMPP, ActionAPI, EssentialsProtect, Multiverse-Inventories, Multiverse-SignPortals, EssentialsGeoIP, EssentialsAntiBuild, PetBlocks, EssentialsSpawn, Multiverse-EssentialsSupport, Jobs, EpicSpawners, ShopGUIPlus

**Description of issue. What happened?**

Some of my beta testers are not able to place lava. Before we were having issues for them to break or place anything on their islands, I followed the directions from the FAQ and it worked good. However, now this issue arises. Also is there any way to set keep inventory for the players on their island (not the visitors)?

**Steps to make this happen**

1. 
2.
3.

**What do you think should happen?**

**Comment by tastybento** [comment]
Are the beta testers on their own island? Or are they visitors?
What do those island settings say about placing lava?
What error message do the players see?

For keeping inventory, there is not an option for players and not visitors. You just have the overall gamerule for keeping inventory.

**Comment by jenaus** [comment]
They have their own islands.

I jave reset their (as in deleted ingame) their islands but it still says
this. It says "you are not permitted to interact with..  "

**Comment by tastybento** [comment]
That error is from Essentials AntiBuild. It sounds like it is your problem. I recommend you remove it.

**Comment by jenaus** [comment]
OK. I will give that a try. Thanks

**Comment by jenaus** [comment]
I will let you know if that works.
