### ISSUE TITLE
Welcome Warp Sign Break Bug

### ISSUE THREAD

**Issue by UnioDex** [tastybento/ASkyBlock-Bugs-N-Features#862]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper 1.8.8

**Plugin version:**
3.0.8.7

**Description of issue. What happened?**
https://youtu.be/GlKNrPGQ3Oo

Normally players can't break other players' signs. But if they break the block below that sign, they can destroy the warp.

**Comment by tastybento** [comment]
Yeah, there's no much I can do about that. If the player can break blocks, then they can do that. I can't keep the sign floating above an empty hole. :-) The only option would be to check if a warp sign is above any block being broken, which I don't want to do because that's a lot of checking.
