### ISSUE TITLE
Island Top Gui Glitch

### ISSUE THREAD

**Issue by LegameMc** [tastybento/ASkyBlock-Bugs-N-Features#863]
Server verion: 1.8.8 spigot

Plugin Version: 3.0.8.9

Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?
Askyblock  3.0.4.9

Description of issue. What happened?
Player can take out the items from askyblock top 10 gui menu.
Also, my island language is english, why does it (top 10 island) show chinese language to me?
I removed askyblock.island.topten permission from player but they still can use /is top .

![image](https://user-images.githubusercontent.com/41326473/42810978-ee248e9a-89eb-11e8-9db9-959ec1176775.png)
![image](https://user-images.githubusercontent.com/41326473/42810985-f38ae578-89eb-11e8-889d-00ab5076c0f9.png)

**Comment by tastybento** [comment]
Please read FAQ about any item removal from GUI's. It's usually caused by other plugins.

Top Ten is a shared GUI (same for everyone) so it's not localized and shows the system language.

**Comment by LegameMc** [comment]
How do i disable player to use “/is top”, i tried to remove askyblock.island.topten permission but they still can use the commad

**Comment by tastybento** [comment]
Give them the negative permission. For example:

/pex user tastybento add -askyblock.island.topten

Notice the minus sign.
