### ISSUE TITLE
Controlpanel GUI question

### ISSUE THREAD

**Issue by Adamv21** [tastybento/ASkyBlock-Bugs-N-Features#864]
I dont know where to submit a question else then here so i'll just ask.

Is it possible to make empty spaces in the control panel?
If so, how?

Thanks in advance!

**Comment by imawizzard** [comment]
you can try this 
[Nuumber]:
      material: 
      description: ''
      command: ''
      nextsection:

I did it so:  9:
      material: Stained_glass_pane
      description: ''
      command: ''
      nextsection: ''  
my white space is then a glass
