### ISSUE TITLE
SkyBlock /Is Problem

### ISSUE THREAD

**Issue by BruhItzZain** [tastybento/ASkyBlock-Bugs-N-Features#866]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? PaperSpigot Version: 1.8 - 1.13** 

**Plugin version:* V3.0.9*

**I used V3.0.8?**

**(Optional) Plugins: (63) ChatColor2, CobbleOres, PlaceholderAPI, CombatTimer, SudoPlusPlus, TitleWelcomeMessage, AntiWeather, TrollBoss, MOTD, ViaVersion, Tablist, StaffList, Actionbar, AnimationLib, WorldEdit, DisplayItem, HackedServer, ClearLag, AdvancedBan, FreezeGUI-PREMIUM, BuycraftX, Votifier, ProtocolLib, MVdWPlaceholderAPI, Vouchers, AdvancedOreGen, ObsidianBreaker, MultiWorlds, Rename, SpawnerUpgrader, PermissionsEx, FeatherBoard, StaffChat, Vault, Trading, WorldGuard, Spartan, NoPlugins, AuctionHouse, ASkyBlock, WelcomeBookRecoded, PlayerVaults, UltimateBossBar, Essentials, TimedFly, Jobs, SilkSpawners, Multiverse-Core, Citizens, BankNote, EssentialsChat, BuySpawners, Lottery, ChestShop, NoFlyZone, HolographicDisplays, MakeYourOwnCommands, EssentialsProtect, CommandNPC, EssentialsSpawn, CratesPlus, ShopGUIPlus, PremiumVanish**

**Description of issue. What happened?**

**Steps to make this happen**

1. Execute Command /Is Or /Island
2. This Error Message Appears If Executed Commnd
3. Clicking On NPC's That Has The /Island Command Added On It Shows The Same Error Message

**What do you think should happen?*
So what happend here is for the past few days i've been trying everything and anything to fix this but no nothing so what happend is If me staff or players execute the command /island to get to your island This message appears in chat: https://ibb.co/eFWCEJ
https://ibb.co/ngVTod and before August the 17th my server release! could you help me fix this Or update your plugin from this bug fix.*

**Comment by Poslovitch** [comment]
Check FAQ.
https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions

**Comment by BruhItzZain** [comment]
Useless nothing that i found could help.

**Comment by Poslovitch** [comment]
Then, I need the following :

1. Exact PaperSpigot version (/version)
2. Logs from the start of the server

**Comment by tastybento** [comment]
You need to share the console logs that show the error. The in-game error you screen shotted is telling you there's an error, now you need to go to the console log of your server and find out what it is. 

My first guess is that the plugin has not actually started running properly at all.
