### ISSUE TITLE
Team bugg

### ISSUE THREAD

**Issue by imawizzard** [tastybento/ASkyBlock-Bugs-N-Features#867]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
spigot: 1.12.2
**Plugin version:**
3.0.8.9
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
new install
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
CoreProtect, LuckPerms, WorldEdit, ColoredSigns, HeadLeaderBoards, ChatKleur, PlaceholderAPI, ChatControl, PlugMan, BlockedCommands, NametagEdit, BuycraftX, WorldGuard, CommandSpy, VoidGenerator, WelcomeWarpSigns, EasyWarp, Vault, ProtocolSupport, SpawnerShop, Essentials, BurkeyShop, SafeTrade, InfoBoardReborn, ASkyBlock, EssentialsXMPP, EssentialsProtect, EssentialsGeoIP, EssentialsChat, EssentialsSpawn, Multiverse-Core, HolographicDisplays, SkyBlockHoloStats, CratesPlus

**Description of issue. What happened?**
when a player1 do /is invite [player2] , player2 is an member of player1's island.
when player1 leaves player2can do nothing.
when i look in the playerdatafile player1 has no team
**Steps to make this happen**

1. /is invite
2. [rejoin]

**What do you think should happen?**
that player2 kan do stuff when player1 leaves or rejoin.

**Comment by Poslovitch** [comment]
Try to use https://github.com/tastybento/askyblock/releases/tag/V3.0.9.1a

**Comment by tastybento** [comment]
Sorry, I can't replicated this issue right now. I recommend you delete player1 using **/asadmin delete player1** to clear that player's data completely.
