### ISSUE TITLE
Challenge GUI Configuration help

### ISSUE THREAD

**Issue by FlailoftheLord** [tastybento/ASkyBlock-Bugs-N-Features#868]
Spigot 1.12.2  1.8-1.13

ASkyBlock: V3.0.9

its a new installation, as in: this is the only version of ASKyblock we have had on the server.

this is more of a help than an issue...
so under the locale Config for messages, in challenges section, is there a way to make the lore multiline???
like some of it is so long it trails off the page... i have some screenshots if u dont believe me... 
[ScreenShot of Challenge GUI]( https://imgur.com/a/dBEP0ss)

Ive tried doing this:
but it still spilces it into one long line...
  Example: |
     &ctext line one
     &ctext line two

is there another format that im missing???

i want it to be all compact so you can read the whole thing without it trailing off the page...

This is with standard quotes  like   
Example: "very long string of text"
![2018-07-20_18 23 18](https://user-images.githubusercontent.com/41513161/43036195-b146ea40-8cca-11e8-87b9-4649ee7eb6bc.png)
this is when i put:
  Example: |
     &ctext line one
     &ctext line two
![2018-07-21_09 44 15](https://user-images.githubusercontent.com/41513161/43036196-b153e33a-8cca-11e8-9096-f1c164282634.png)

**Comment by Poslovitch** [comment]
Try using \n or | inline. ASB's l18n doesn't support multi-lines YAML String values.

**Comment by FlailoftheLord** [comment]
Not working, could you give me an example?

**Comment by tastybento** [comment]
@FlailoftheLord Do it like this:

```
  challengeList:
    glassmaker:
      friendlyname: 'Glass Maker'
      description: 'Create 1|block of glass|next line|&cnextline'
```

**Comment by FlailoftheLord** [comment]
yes that worked thanks!!!
