### ISSUE TITLE
Split the message from IslandPreLevelEvent to another event

### ISSUE THREAD

**Issue by Cristaling** [tastybento/ASkyBlock-Bugs-N-Features#87]
In order to implement an alternative level calculation it would be required to have 2 separate events for level calculation and player level message.

An example of why this would be required (implementing an exponential level calculation):

[PasteBin](https://pastebin.com/BTY8uTN2)

A suggestion would be an option to only cancel the player message.

**Comment by Poslovitch** [comment]
The exponential level calculation is on the way, I'm currently working on ;)
I'll look for spliting this event into what you suggested ;)

**Comment by Cristaling** [comment]
Any chance we could get the event split Faster than 4.0?

It shouldn't take much change in the calculation process. Just make another event and call it before the message.

**Comment by Poslovitch** [comment]
I missed-click, sorry. I originally intended to put this in 3.0.6.2 milestone ^^
So yes, it will come faster than 4.0 ;)

**Comment by Poslovitch** [comment]
Done
