### ISSUE TITLE
EntityDamageByEntity failed cast.

### ISSUE THREAD

**Issue by JamieSinn** [tastybento/ASkyBlock-Bugs-N-Features#872]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper
**Plugin version:**
https://github.com/tastybento/askyblock/commit/9acfc0afcbe6fbc6fc565755b368968225ebe7a4 is currently what we're using 

https://pastebin.com/raw/4tY8wkfQ

Need to check instanceof before casting.

**Comment by tastybento** [comment]
Yep, got it out of order. Fixed in 3.0.9.2.
