### ISSUE TITLE
Players being unassigned from their islands

### ISSUE THREAD

**Issue by DeJayDevelopment** [tastybento/ASkyBlock-Bugs-N-Features#873]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
PaperSpigot 1.8.8 (4c7641d)

**Plugin version:**
3.0.9

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**

Fresh installation

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

N/A

**Description of issue. What happened?**
Players are almost seemingly randomly being removed from their islands, they must be purged from their team and the owner has to be /asadmin register'ed.

**Steps to make this happen**

1. ?

**What do you think should happen?**

This should not be the behaviour of the plugin and I am more than happy to help debug or offer assistance in development wherever it is required. GitHub issues or a Discord conversation is all the same to me. 😄

**Comment by DeJayDevelopment** [comment]
It seems to be when the island leader of the top island logs off to a larger team (4+ players). However I'm still working on narrowing the issue down myself, it's quite strange. 

I feel as though data is being poorly handled on disconnect causing this.

**Comment by tastybento** [comment]
You should upgrade to 3.0.9.2. That fixes a bug where when players of a team join the game, they can "strip" the leader of their island. The issue occurs if the team player has an island location in their file that is wrong. When they join, the plugin looks at the island location of the player, the team island location and says - this is wrong, need to sync and takes the one in the player's file, and that messes up the setting for the leader. It only affects teams.
If you look through your logs, I expect you will see some errors that says **login: mismatch** and then a message.
The latest version fixes these issues.

**Comment by DeJayDevelopment** [comment]
Updated as instructed, no issues just yet. @Fatalz32 might have luck with their own ticket 🤔

**Comment by Fatalz32** [comment]
It seems to still be happening to teams and solo players. I am using the latest version of the plugin. yould you like a list of the plugins to see if anything could be making this happen?

**Comment by Fatalz32** [comment]
I updated to 3.0.9.2 and it was still happening. I just saw it was updated to 3.0.9.3 so I will see if that helps.

**Comment by tastybento** [comment]
@Fatalz32 Can you try https://github.com/tastybento/askyblock/releases/tag/3.0.9.4a?
