### ISSUE TITLE
Lava Turns into Obsidian

### ISSUE THREAD

**Issue by religionkappa** [tastybento/ASkyBlock-Bugs-N-Features#874]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
TacoSpigot 1.8.8

**Plugin version:**
Latest

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
New Install

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
When generating an island, any lava converts either into obsidian (source) or cobblestone (flow block)

**Steps to make this happen**

1. Schematic has lava
2. Generate an island

**What do you think should happen?**
Lava should remain as is.

Example: https://imgur.com/a/UIjEJNO

**Comment by tastybento** [comment]
Just to confirm - this is with AcidIsland and the lava is being placed below sea-level, correct? Can you share a test schematic that you know has this issue (zip it and drag and drop into this box).

**Comment by religionkappa** [comment]
I'll message you via Spigot my configuration file (so the water matches up, and it's not a huge air pocket), and the schematic (just for sake of keeping my project private, and not making it open to the public). 

But to confirm, AcidIsland and below sea-level, yes.

**Comment by tastybento** [comment]
Okay, give me some time on this one. Bit busy right now.

**Comment by religionkappa** [comment]
@tastybento Gonna bump.

**Comment by tastybento** [comment]
This seems to work. Try this: https://github.com/tastybento/acidisland/releases/tag/V3.0.9.5
