### ISSUE TITLE
Island Biomes???

### ISSUE THREAD

**Issue by FlailoftheLord** [tastybento/ASkyBlock-Bugs-N-Features#876]
Using the latest version from spigotmc.org  dont remember the number.
 Im wondering if its actually possible to add new biomes to the list...
so ive tried already entering the name of the biome as specified in the already created ones...
it all looks fine... and then in the console it says "Could not parse biome (biome name) using default instead."
... are there a set list of biome names i should be using? or just the default minecraft ones, im not sure how to go about adding new biomes, Here is the setup i used to add a new one:

SNOWY_TAIGA:
    icon: SAPLING:1
    friendlyname: "&f&lIcyHills"
    description: "&bIce and Snow... perfect place to chill... to death"
    cost: 800

not sure if thats correct but its in the same formatting as the other biomes,

**Comment by tastybento** [comment]
Hmm. I don't know what server you have, but you will find Biome names in the server API Javadoc. Try this one:
https://github.com/Bukkit/Bukkit-JavaDoc/blob/master/src/main/java/org/bukkit/block/Biome.java

They change the names, unfortunately!
