### ISSUE TITLE
Players Can't Build on Their Island!

### ISSUE THREAD

**Issue by WxCked** [tastybento/ASkyBlock-Bugs-N-Features#879]
**Server Version:**
 >> CraftBukkit version 1.8-R0.1-SNAPSHOT

**Plugin Version:**
 >> Latest: V3.0.9.3

**Earlier Plugin Version:**
>> Version: 3.0.9

**Plugins:**
KitsPreview, MinionsFree, NoCraftThat, CustomOreGen, GroupManager, PlaceholderAPI, PlugMan, CommandSpy, ChatReaction, Arconix, DeluxeTags, CustomDrops, MobCoins, PassiveMobs, ClaimLevels, ViaVersion, Tablist, HideStream, ClearLag, WorldBorder, BuycraftX, MessageAnnouncer, ProtocolLib, PhantomAntiDupe, FastAsyncWorldEdit, Vouchers, DeluxeMenus, DisableWither, Lottery, AutoSave, CustomHelp, mcMMO, MotdManager-Reloaded, Vault, EpicRename, MoneyPouch, AuctionHouse, ASkyBlock, PlayerVaults, PluginHiderPlus, WorldEdit, Essentials, LinkItem, BeastWithDraw, Banknotes, AutoSell, LiteBans, Multiverse-Core, KitAdder, Citizens, EssentialsChat, SellChest, HolographicDisplays, AurifexBorder, SkyblockWorldEdit, WorldGuard, LockettePro, CommandNPC, EssentialsSpawn, MobStacker2, CrateReloaded, SilkSpawners, ChestShop, CombatTagPlus, ShopGUIPlus

**Issue:**
Players can not build on their own island

**Steps to make this happen**
Not sure how but it's an issue that needs to be resolved

**Comment by tastybento** [comment]
Try this: https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#when-i-do-asadmin-info-on-an-island-or-acid-info-it-says-the-island-is-unowned-but-it-is-owned-why
