### ISSUE TITLE
[Request] KeepInv disabled when dying between islands

### ISSUE THREAD

**Issue by SpaZMonKeY777** [tastybento/ASkyBlock-Bugs-N-Features#88]
If you currently enable KeepInventory when you die on another island, you also keep your inventory if you die BETWEEN islands as well. This is rather annoying as players can simply build a platform covering the entire base of their island, and now they never need to worry about losing items ever.

Would it be possible to to disable the KeepInv range so it's ONLY on other islands and not the gaps in between? Or at least have a config option for KeepInv on dying between islands. I prefer to keep the option on, but don't want players to have no fear of the void lol. Thanks!

**Comment by Poslovitch** [comment]
Can you tell us what server version & plugin version are you using?

**Comment by tastybento** [comment]
I'll fix this.
