### ISSUE TITLE
Players can't break/place blocks or do anything in nether world 

### ISSUE THREAD

**Issue by YaBoiAce** [tastybento/ASkyBlock-Bugs-N-Features#880]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.** PaperSpigot 1.8.8
![image](https://user-images.githubusercontent.com/22438504/43454274-62d5a9ae-94b4-11e8-813f-e6cf6619ce3f.png)

**Plugin version:** 3.0.9.3

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?** Upgrade, used to have 3.0.9.0 (I think)

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

![image](https://user-images.githubusercontent.com/22438504/43454371-b6c76e58-94b4-11e8-9e67-dab978a62ec0.png)

**Description of issue. What happened?**

When players teleport to the nether world using their nether portal, they can't do anything in the world - can't place nor break blocks. There is no error nor message. Upon disabling the plugin - they can. 

**Steps to make this happen**

1. Make nether portal
2. Teleport through
3. Try to break/place blocks.

**What do you think should happen?**

They should be able to break/place blocks in the nether world, this worked last update.

**Comment by tastybento** [comment]
I tested on Spigot1.8.8 and I can't find an issue. Generally, if there is no error when players are trying to break things, then it is another plugin interfering because ASkyBlock will always give an error. I realize that disabling the ASKyBlock enables them, so that's weird. I'm not sure what to do here except maybe try and see if removing any other protection-related plugins helps.

**Comment by YaBoiAce** [comment]
Please close this issue, found the issue;

It was the Island Border plugin I was using, I contaacted the developer and he fixed the bug.

Thank you for your help and apologies for mis-using your issue system!
