### ISSUE TITLE
Attempt to safe teleport to a null location

### ISSUE THREAD

**Issue by vnvyvu** [tastybento/ASkyBlock-Bugs-N-Features#881]
**Server version**: 1.12.2

**Plugin version**: v3.0.9.3

**Problem**:

- I encountered problems when I customized schematic island
- I placed the bedrock on the bottom
- I placed the sponge (spawnblock)
- I can not teleport to the island
- Appears this line in the console :

[Askyblock] Attempt to safe teleport to a null location!

**Comment by tastybento** [comment]
The location is null for some reason.  I assume "bedblock" means "bedrock"? 
Make sure you can use normal islands.

**Comment by vnvyvu** [comment]
sr, it is bedrock

**Comment by tastybento** [comment]
If you do not use your custom island, does it work? I recommend you do a full delete of the player and then try (/asadmin delete playername).

**Comment by vnvyvu** [comment]
I did it, it does not work, I try it again a lot of times
I have currently updated to the latest version, it still

**Comment by tastybento** [comment]
So, this is not an issue with island schematics then. It is an issue with the location of the player's island. If you delete the player completely and use the standard schematic, does it work?

**Comment by vnvyvu** [comment]
it works well
I tried deleting config
It worked well with the new schematic
It seems I have misconfigured somewhere

**Comment by vnvyvu** [comment]
This problem has been resolved!
Cause: The value of "islandlevel: " is too large

**Comment by vnvyvu** [comment]
I do not understand "islandlevel:"
I set it to 200
But I can still level up to 300 (>200)

**Comment by Poslovitch** [comment]
`islandlevel` defines the y coordinate of the bedrock block. It should be within the minimum and maximum y coordinate of a Minecraft world (0 and 255).

**Comment by Poslovitch** [comment]
> I misunderstood it would limit the island level (the comment in config file does not specify this)
It does : 
- https://github.com/tastybento/askyblock/blob/master/config.yml#L9
```yaml
# 3. islandLevel (general section) - the height you want your islands to float
```
- https://github.com/tastybento/askyblock/blob/master/config.yml#L49
```yaml
 # Island level - the height of the island.
```

Glad to help.
