### ISSUE TITLE
Weird error messages about minishop.yml

### ISSUE THREAD

**Issue by JarlPenguin** [tastybento/ASkyBlock-Bugs-N-Features#883]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.12.2
**Plugin version:**
3.0.9.1 RC
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
New install
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
Log: https://hasteb.in/helapabe.md
Plugins:  ClearLag, LuckPerms, ChatControl, Vault, MobArena, ASkyBlock, Essentials, EssentialsSpawn, EssentialsChat, MineCordBot
**Description of issue. What happened?**
There was a series of weird errors/warns in the console.
**Steps to make this happen**
IDK
**What do you think should happen?**
No errors should appear.

**Comment by Poslovitch** [comment]
You're using a Release Candidate.

Please update to 3.0.9.3.

**Comment by JarlPenguin** [comment]
Nope, am still getting the issue.
https://hasteb.in/yawabeja.md

**Comment by tastybento** [comment]
The format of the item in the minishop.yml is incorrect. Check that the potion one is correct.

**Comment by JarlPenguin** [comment]
Ah, ok, will see.

**Comment by JarlPenguin** [comment]
ok, so now i have every thing working, except for lapis. can anyone help me?
   item9:
      material: DYE
      extra: 4
      quantity: 1
      price: 2000
      sellprice: 1000
      description: '&9the power of enchanting'

**Comment by tastybento** [comment]
Lapis is INK_SACK:4.
