### ISSUE TITLE
Players randomly deleted from island team (but are still in the team)

### ISSUE THREAD

**Issue by N0tMyFaultOG** [tastybento/ASkyBlock-Bugs-N-Features#884]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
git-Spigot-2086bb0-2f3ed3b (MC: 1.12.2)

**Plugin version:**
ASkyBlock 3.0.9.2

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
![](https://i.imgur.com/jxeBexR.png)

**Description of issue. What happened?**
Sometimes players are randomly removed from the island (without a reason) and also removed from the player's island settings. They do not appear on `/asadmin info`, neither are assigned as members in the /players/ folder. I'll attach some screenshots below. The command I used is written in the chatbox on the screenshot.
![](https://i.imgur.com/7FU7LDV.png)
![](https://i.imgur.com/xGcYlzr.png)
![](https://i.imgur.com/1jLlGdi.png)
It's a bit hard to explain but it simply removes members from players islands.

**Comment by tastybento** [comment]
You should update to 3.0.9.3 because there was a bug that was causing this kind of thing, but some admins are reporting it still happening. I have made 3.0.9.4 here: https://github.com/tastybento/askyblock/releases/tag/3.0.9.4a

This is exactly the same as 3.0.9.3 but turns off async saving. I'd like to double check that this is not causing the problem, so please try it and see if you still see issues.

**Comment by Heliosard** [comment]
Hello, I have some news about ASkyBlock v3.0.9.3.
We have discovered that some calls to the API to retrieve the leader of an island are incorrect. In play, when the leader of an island disconnects, it happens that all members of the island are expelled without reason. This is a serious problem that must be corrected.

Screen for API's bug: https://i.imgur.com/XCplqD1.jpg

**Comment by tastybento** [comment]
Can you explain more what the screenshot is showing? Is this the result of a player who was a team leader logging in and finding out they are not a leader anymore?

**Comment by tastybento** [comment]
I think it's the async saving. Please try 3.0.9.4 and see how that works for you.

**Comment by N0tMyFaultOG** [comment]
I'm using 3.0.9.4 now, let's see if this will fix it...

**Comment by TheWranger** [comment]
I'm getting something similar to this with players being uncoop'd randomly after server restarts.
A player will be uncoop'd from all islands they were coop'd on.

**Comment by tastybento** [comment]
@TheWranger are you using persistent coops? I.e., is that setting on or off in config.yml?

We'll get to the bottom of this!

**Comment by TheWranger** [comment]
Yes, coops are persistent

**Comment by tastybento** [comment]
@N0tMyFaultOG Any success? Still a problem?

**Comment by N0tMyFaultOG** [comment]
Nope, seems working now.

**Comment by tastybento** [comment]
Cool thanks.
