### ISSUE TITLE
When players teleport to their islands, they face south rather than looking at the welcome sign.

### ISSUE THREAD

**Issue by FaZeMLG** [tastybento/ASkyBlock-Bugs-N-Features#885]
**Server version:** Spigot 1.12.2

**Plugin version:** v3.0.9.3

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?** Fresh install

**Issue:** When players teleport to their islands, they face south rather than looking at the welcome sign (like the default island schematics) when using a custom island schematic.

**Comment by tastybento** [comment]
Yes, there's not much I can do about that. I only teleport to the location and don't do a search for any particular sign. Sorry.
