### ISSUE TITLE
Skyblock Challenges

### ISSUE THREAD

**Issue by Vuhx** [tastybento/ASkyBlock-Bugs-N-Features#889]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
1.8.8 Spigot

**Plugin version:**
Latest Download

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
Install

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
Plugins (70): PluginConstructorAPI, PlaceholderAPI, DeluxeCommands, PlugMan, LuckyBlock, AntiDupe, SpongeCommands, ChatReaction, SuperTrails, ItemID, ChatManager, CoreProtect, CustomHelpMessage, CustomList, FastCraft, Skript, Essentials, FreeCamDupePatch, PacketListenerApi, JellyLegs, AntiWDL, NightVision, KitAdder, MVdWPlaceholderAPI, FastAsyncWorldEdit, Vouchers, VoidGenerator, DeluxeMenus, EssentialsChat, PermissionsEx, FeatherBoard, ExperienceBottle, KOTH, Vault, EZBlocks, CrazyCrates, SimpleRename, Trading, ASkyBlock, PlayerVaults, ViaVersion, EssentialsSpawn, WorldEdit, HologramAPI, CombatLog, Multiverse-Core, ProtocolLib, VoidSpawn, WhatIsIt, NoCheatPlus, BankNote, goPaint, Multiverse-Portals, ServerListPlus, BlockParticles, CustomOreGen, Parties, HolographicDisplays, WorldGuard, MythicMobs, ServerSigns, PlayMoreSounds, LiteBans, WarpPortals, Magic, ChestShop, TokenEnchant, NoFlyZone, Quests, SilkSpawners

**Description of issue. What happened?**
I want challenges to output commands when players complete them, yet for some reason I can't get any commands to work.
https://hastebin.com/ugabeyiset.bash
I've tried setting "rewardcommands" to "commands", and removed the ' ' brackets from the command. Yet nothing will work.

**Steps to make this happen**

1. 
2.
3. N/A ?

**What do you think should happen?**

I want commands to output once a player completes a challenge.

**Comment by tastybento** [comment]
Make sure you don't have the permissions that prevent commands from being run:

      askyblock.command.*:
        description: Event commands will not be run for players with this perm

If you have * or askyblock.* perm then commands will not be run for you.
