### ISSUE TITLE
Permission to bypass flytimeoutside

### ISSUE THREAD

**Issue by wasder** [tastybento/ASkyBlock-Bugs-N-Features#89]
I have island fly (via ASB) and global fly (other plugin) for different ranks on my server. 
Players with global fly have to manually activate /fly anytime they leave someone's island.

**Comment by Poslovitch** [comment]
Will be done for 4.0 ;)

**Comment by tastybento** [comment]
@Poslovitch How will you know they have fly with the other plugin?

**Comment by Poslovitch** [comment]
I will just do a check for a perm like "x.bypassflylimit", and so the plugin won't remove flymode

**Comment by tastybento** [comment]
This issue was moved to tastybento/bskyblock#75
