### ISSUE TITLE
Team member bugs

### ISSUE THREAD

**Issue by LegameMc** [tastybento/ASkyBlock-Bugs-N-Features#891]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.12.2

**Plugin version:**
Askyblock 3.0.9
Note: I'm using old version because the lastest version caused more bugs , such as island leader cant break/ place block, it say island protected 

**Description of issue. What happened?**
Player A = island owner
Player B = invited by A (/is invite)
Player B couldn't break block at the island (it say island protected ) when Player A leave the server. Also when /asadmin info, player B is not show in the team list but Player B type "/is " is teleport to Player A island.

**Steps to make this happen**

1.  leader leave server
2. team member cant break block, they got removed from team list but /is still can teleport to the island

**Comment by tastybento** [comment]
This is a known bug with 3.0.9. You do need to upgrade to the latest version.
