### ISSUE TITLE
Skyblock players being able to grief others islands.

### ISSUE THREAD

**Issue by FarmingWizard** [tastybento/ASkyBlock-Bugs-N-Features#892]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.** Spigot 1.8-1.12.2

**Plugin version:**  V3.0.9.4

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?** New install

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)** 

**Description of issue. What happened?** Basically there are two things that are happening. The first is that when players /is warp to others islands they are able to destroy their things and take things out of their chests. The other problem is the island borders. The island border are shown as a certain size and are bigger than the actual islands are.

**Steps to make this happen**

1. /is warp (player name)
2. players then destroy island
3.

**What do you think should happen?**
The island border should be set to the correct size that the island is instead of being bigger and players should not be able to destroy and build on others islands and take their items

**Comment by tastybento** [comment]
This could be due to a few reasons. One reason could be the islands.yml file is corrupted and needs deleting.

Do players see any error when they break blocks as visitors?
