### ISSUE TITLE
can do /is or /is go once an island has been created

### ISSUE THREAD

**Issue by Callum703** [tastybento/ASkyBlock-Bugs-N-Features#893]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

`06.08 04:54:04 [Server] ERROR [ASkyBlock] Attempt to safe teleport to a null location!
06.08 04:54:19 [Server] ERROR Could not pass event InventoryClickEvent to ASkyBlock v3.0.9.4
06.08 04:54:19 [Server] INFO org.bukkit.event.EventException: null
06.08 04:54:19 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
06.08 04:54:19 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
06.08 04:54:19 [Server] INFO Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'island' in plugin ASkyBlock v3.0.9.4
06.08 04:54:19 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:244) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at com.wasteofplastic.askyblock.util.Util.runCommand(Util.java:573) ~[?:?]
06.08 04:54:19 [Server] INFO at com.wasteofplastic.askyblock.panels.SchematicsPanel.onInventoryClick(SchematicsPanel.java:152) ~[?:?]
06.08 04:54:19 [Server] INFO at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source) ~[?:?]
06.08 04:54:19 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
06.08 04:54:19 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
06.08 04:54:19 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO ... 15 more
06.08 04:54:19 [Server] INFO Caused by: java.lang.StackOverflowError
06.08 04:54:19 [Server] INFO at java.util.zip.Inflater.<init>(Inflater.java:102) ~[?:1.8.0_161]
06.08 04:54:19 [Server] INFO at java.util.zip.Inflater.<init>(Inflater.java:110) ~[?:1.8.0_161]
06.08 04:54:19 [Server] INFO at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:108) ~[?:1.8.0_161]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.RegionFile.a(SourceFile:210) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.RegionFileCache.d(RegionFileCache.java:81) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:62) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:21) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:1) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:336) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.getChunkAt(World.java:333) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.getChunkAtWorldCoords(World.java:329) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.getType(World.java:810) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.e(SourceFile:161) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.onPlace(SourceFile:96) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:512) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:378) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.e(SourceFile:221) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.onPlace(SourceFile:96) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:512) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:378) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.e(SourceFile:221) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.onPlace(SourceFile:96) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:512) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:378) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.e(SourceFile:221) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.onPlace(SourceFile:96) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:512) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:378) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.e(SourceFile:221) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.onPlace(SourceFile:96) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:512) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:378) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.e(SourceFile:221) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.onPlace(SourceFile:96) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:512) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:378) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.e(SourceFile:221) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.onPlace(SourceFile:96) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:512) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:378) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.e(SourceFile:221) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.onPlace(SourceFile:96) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:512) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:378) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.e(SourceFile:221) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.onPlace(SourceFile:96) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:512) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:378) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.e(SourceFile:221) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.onPlace(SourceFile:96) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:512) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:378) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.e(SourceFile:221) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.onPlace(SourceFile:96) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:512) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:378) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.e(SourceFile:221) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.onPlace(SourceFile:96) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:512) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:378) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.e(SourceFile:221) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.BlockChest.onPlace(SourceFile:96) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:512) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]
06.08 04:54:19 [Server] INFO at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:378) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-b9f1615]`

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.12.2
**Plugin version:**
ASkyBlock v3.0.9.4
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
New
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
CoreProtect, PlayerHeads, LuckPerms, WorldEdit, SimpleEnchanter, Staff, CombatLog, ClearLag, PlugMan, NoPluginViewer, BuycraftX, WorldSpawn, Lockette, WorldGuard, VPNGuard, EnhancedBalTop, MobStacker, VoxelSniper, BossBarMessage, PassiveMobs, TicketRedeemer, ProtectionStones, Vault, StaffPlus, MoneyNote, ChestShop, Essentials, VaultChatFormatter, Jackpot, SimpleRename, SilkSpawners, GUIShop, Citizens, ASkyBlock, PlayerVaults, Multiverse-Core, DiscordSRV, HolographicDisplays, CratesPlus
**Description of issue. What happened?**
type /is to create an island then when I try to do /is or /is go it doesn't work
**Steps to make this happen**

1. Make a new island with /is
2.type in /is or /is go

**What do you think should happen?**
Teleport me to an is

**Comment by tastybento** [comment]
Looks like the various data files were not deleted when doing a reset. i.e., the player's island info is referring to a non-existent world. I recommend you follow the FAQ steps for resetting, i.e., stop the server (very important), then delete everything in the ASKyBlock folder except for config.yml , then restart.
