### ISSUE TITLE
Can't reset island after invited some guy in party

### ISSUE THREAD

**Issue by xion87** [tastybento/ASkyBlock-Bugs-N-Features#894]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper 1.8.8
**Plugin version:**
3.0.99.4
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
3.0.9

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
Basicall the player can't reset the ilsand because it say there are some member in party, but on island there are no members (on the file instead i see himself also as member)
This player invited 2 friend and then kicked them for reset, but it stuck here

**Comment by tastybento** [comment]
Use the admin command to delete the player.

**Comment by xion87** [comment]
yeah i fixed it by make me inviting in his island and give me the leader...is the same issue with API when you change owner, the new owner will be added also as party member
