### ISSUE TITLE
Insland bug?

### ISSUE THREAD

**Issue by ninomato** [tastybento/ASkyBlock-Bugs-N-Features#895]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
TacoSpigot 1.8.8
**Plugin version:**
Latest (3.0.9.4)
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
well, idk
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**

**Description of issue. What happened?**
Well, when i log in the server the console starts to spam A LOT (my log file take 200mb in 10 seconds)
**Steps to make this happen**

1. The bug only happens with me, with the other players no
2. When i log in the server this erros starts to SPAM in console: https://hastebin.com/boqayixebi.css
3.

**What do you think should happen?**
well, idk, how can i fix it?

**Comment by tastybento** [comment]
Delete your character, maybe? Try /asadmin delete (youname). 

It looks like there's some conflict between island data and your world. When you upgraded, did you keep the same island distance?
