### ISSUE TITLE
Mooshroom Spawn Eggs

### ISSUE THREAD

**Issue by NyteriaRising** [tastybento/ASkyBlock-Bugs-N-Features#896]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version:** Running 1.12.2 Spigot bungeecord server
**Plugin version:** Most recent

So been trying to add Mooshroom spawn eggs to the minishop. All other eggs work but when i try to add mooshroom i can't for the life of me get it to work. 

This is what is in the minishop.yml:

   item24:
      material: MONSTER_EGG
      quantity: 1
      extra: mooshroom
      price: 20000
      description: Mooshroom

Do you know what is meant to be put in extra to make it a mooshroom egg?

**Comment by Poslovitch** [comment]
Use the entity types from Bukkit : https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html

**Comment by NyteriaRising** [comment]
Thankyou!
