### ISSUE TITLE
Players can do /island Anywhere.

### ISSUE THREAD

**Issue by Bagsdto75** [tastybento/ASkyBlock-Bugs-N-Features#897]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Spigot 1.12.2
**Plugin version:**
1.12.2
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
No
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
Cant Copy and Paste
**Description of issue. What happened?**
Players are Allowed to do /island Anywhere on the server
**Steps to make this happen**

1. ?
2.
3.

**What do you think should happen?**
They can only do /island in The Skyblock World

**Comment by tastybento** [comment]
That is normal operation. If you wish to restrict commands to a specific world, then you need to use a permissions plugin that can do that.
