### ISSUE TITLE
Askyblock reset

### ISSUE THREAD

**Issue by CoolPanda101** [tastybento/ASkyBlock-Bugs-N-Features#898]
**Server version? Spig 1.8.8

**Plugin version:** Latest

**Description of issue. What happened?**
I need to completely reset all players skyblock data
I followed these steps
Go to the ASkyBlock plugin folder (plugins/askyblock)
Delete the players folder.
Delete the islands.yml, messages.yml, topten.yml files
delete the locale folder 
(Optional) delete the schematics folder if you want to remove the schematics (DIDNT DO)
Delete the world folders in your server folder, they are usually called ASkyBlock, and ASkyBlock_nether
Restart
 So after doing all of that in game when I type /is it says that warp is not safe right now try again later and /is level works when there should be no islands

**Comment by CoolPanda101** [comment]
08 05:33:29 [Server] INFO UUID of player PandaIsland is c30ef4c1-89f0-4af8-ae10-9f868787f5cd
17.08 05:33:29 [Server] WARN [ASkyBlock] *** Duplicate or overlapping islands! ***
17.08 05:33:29 [Server] WARN [ASkyBlock] Island at (400, 1600) conflicts with (400, 1600)
17.08 05:33:29 [Server] WARN [ASkyBlock] Accepted island is unowned.
17.08 05:33:29 [Server] WARN [ASkyBlock] Denied island is owned by PandaIsland
17.08 05:33:29 [Server] WARN [ASkyBlock] c30ef4c1-89f0-4af8-ae10-9f868787f5cd.yml
17.08 05:33:29 [Server] WARN [ASkyBlock] Recommend that the denied player file is deleted otherwise weird things can happen. might help

**Comment by tastybento** [comment]
You didn't delete everything. Basically, delete *everything* in the ASkyBlock folder except the config.yml *and* make sure you delete everything when the server is shutdown.
