### ISSUE TITLE
Reset TopTen

### ISSUE THREAD

**Issue by AdvancedGP** [tastybento/ASkyBlock-Bugs-N-Features#899]
**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
1.12.2
**Plugin version:**
3.0.9
**Description of issue. What happened?**
I am trying to reset my topten, i deleted all files in the players holder, deleted name-uuid, deleted topten, deleted warps, delete islands, deleted islandnames, and deleted the ASkyBlock world. but for some reason the topten remains the same. i would change the numbers in topten, restart, and nothing is changed, in config its to what i change it to, but when i do /asadmin topten, it goes back to the same old numbers even in config.
**What do you think should happen?**
it should fully reset topten.

**Comment by tastybento** [comment]
Stop server, then delete files.
