### ISSUE TITLE
Flying bug

### ISSUE THREAD

**Issue by DeKingOfDe** [tastybento/ASkyBlock-Bugs-N-Features#900]
Hello, I am currently making a server with SkyBlock in it. Aperantly, every player can fly in his island and I don't want that to happen. Any way to fix this?

**Comment by DeKingOfDe** [comment]
Fun fact, this report is the 900th report. XD

**Comment by CoolPanda101** [comment]
hey dude you need to remove the essentials.fly from default from

**Comment by DeKingOfDe** [comment]
essentials.fly isn't even in default
