### ISSUE TITLE
setIslandLevel Method

### ISSUE THREAD

**Issue by SpaceTR** [tastybento/ASkyBlock-Bugs-N-Features#902]
setIslandLevel method doesnt work.

My test code: ASkyblockAPI.getInstance().setIslandLevel(p.getUniqueId(),100);

**Comment by FurkannM** [comment]
Yeah. setIslandLevel method has a weard bug.

**Comment by tastybento** [comment]
This method will not work unless you trap the level calculation events and cancel them. In other words, even if you set the level, as soon as you do /is level, it'll overwrite it.
