### ISSUE TITLE
Negativ island-level

### ISSUE THREAD

**Issue by AconTM** [tastybento/ASkyBlock-Bugs-N-Features#905]
Hey, 

i have changed my island-level to an "Ore-Level" it means the only blocks to lvl up are ore-blocks. I have only 1 Question:

Why is the island-level of this user "-9" ??
http://i.epvpimg.com/IBSfdab.png

he shoud have island-level "0" but he have "-9".. here are my Config section:
http://haste.pixelcurse.net/inelifadur.yml

I have the newest version of aSkyBlock, my Server is on version 1.12.2..

i hope you understand my problem..

**Comment by AconTM** [comment]
The only method wich i have to work with the level system is this class:
http://haste.pixelcurse.net/mosofobasa.java

**Comment by tastybento** [comment]
You can do asadmin level in the console to get a full level report that will explain. It’s probably either the player’s deaths or the island handicap.
