### ISSUE TITLE
TopTen GUI bugs with Items

### ISSUE THREAD

**Issue by Max2124** [tastybento/ASkyBlock-Bugs-N-Features#910]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

Spigot 1.12.1

Using Version: V3.0.9.4

It's an upgrade from earlier version. Earlier version: V3.0.8.9

First issue is that any player get take out the items from the gui and place it in it somewher else but also put it in the inventory. And the second issue is that it doesn't shows the players head(just ores, blocks and axes).

I think the GUI should not let taken items out of it happening and that if it's possible that the server admins can config the types of items for each ranking place itself.

**Comment by tastybento** [comment]
Please read the ASkyblock FAQ on items being taken out of a GUI. Also, the latest version does not use heads anymore due to Mojang limits.
