### ISSUE TITLE
challenges bug please help

### ISSUE THREAD

**Issue by laithalshabi** [tastybento/ASkyBlock-Bugs-N-Features#911]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
1.9

**Plugin version:**
the last one

**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**
idk but its old
**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
KitsPreview, BlockParticles, GiveAll, PlaceholderAPI, PlugMan, PlayTime, NametagEdit, Friends3_0, aAntiSpam, SuperTrails, ViaVersion, CraftingStore, HideStream, WorldEdit, AutoBroadcast, ClearLag, Votifier, ProtocolLib, AntiWDL, MVdWPlaceholderAPI, AdminEssentials, DeluxeMenus, PermissionsEx, FeatherBoard, SuperbVote, AutoSave, CustomHelp, MineResetLite, Vault, ServerListPlus, DailyRewards, ChatGames, Trading, HolographicDisplays, WorldGuard, ASkyBlock, ShopGUIPlus, CombatLog, Essentials, GiveInfoBook, HeadDatabase, CrateReloaded, PlayerVaultsGUI, Citizens, CrazyAuctions, EssentialsChat, EssentialsGeoIP, CommandNPC, EssentialsSpawn, TitleManager

**Description of issue. What happened?**
i can hold the challenges items and set it in my inv
challenges not workin 

**Steps to make this happen**

1. /asc
2.press in any challenge
3.i can hold it and set it in my inv and i didnt get any challenges

**What do you think should happen?**
idk

**Comment by laithalshabi** [comment]
oh Essentials is the problem but i need it please fix it please

**Comment by Poslovitch** [comment]
Took me two secs : https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#players-can-take-the-items-heads-out-of-the-challenges-settings-control-warps-guis-help

**Comment by laithalshabi** [comment]
i try that
and when i remove essentials its work fine
but i need essentials soo please help

**Comment by Poslovitch** [comment]
Then that's a bug on Essentials's side, we can't do anything more about it, sorry.

**Comment by laithalshabi** [comment]
oh
