### ISSUE TITLE
Redstone lag

### ISSUE THREAD

**Issue by xion87** [tastybento/ASkyBlock-Bugs-N-Features#914]
Thank you for filing a bug report. Please complete these sections to help speed resolution.

**Server version? Remember to say if it is Spigot/Bukkit/Paper etc.**
Paper 1.8.8

**Plugin version:**
3.0.94
**Is this a new install or upgrade from earlier plugin version? If upgrade, what version did you use before?**

**(Optional) What other plugins are you using now? (do /plugins and paste text from the console log here)**
LuckPerms, WorldEdit, Skript, PlaceholderAPI, PandaWire, FarmLimiter, SimpleTPA, MVdWPlaceholderAPI, Nicky, iConomy, FeatherBoard, EasyWarp, ViaVersion, Vault, TitleManager, SafeTrade, ProtocolLib, AAC, ASkyBlock, CrazyAuctions, ConditionalCommands, ItemFrameShops, CustomPayloadFixer, Swapper, ChatControl, AACAdditionPro, HolographicDisplays

**Description of issue. What happened?**
HIgh lag after a user logged with redstone macchines on they island

**Steps to make this happen**
https://timings.aikar.co/?id=4e5ebe11e5444638b0c32842a83d442e

**Comment by Poslovitch** [comment]
It's not the plugin, it's the world. Try to find plugins that could help to reduce the load of the redstone or optimize your server by configuring spigot.yml and bukkit.yml accordingly.

**Comment by xion87** [comment]
urgh i didn't noticed that...
