### ISSUE TITLE
Players could move tamed animals to spawn island and leave them there.

### ISSUE THREAD

**Issue by wasder** [tastybento/ASkyBlock-Bugs-N-Features#94]

**Comment by tastybento** [comment]
You mean like dogs?

**Comment by wasder** [comment]
Yes.

**Comment by tastybento** [comment]
What would be the desired outcome/action. What is the problem that occurs by this?

**Comment by wasder** [comment]
Players could leave pets with nametags on spawn to advertise something for example.
I thinks a protection option to forbid right click on tamed animals will do.
