### ISSUE TITLE
DeluxeChat not formating properly 

### ISSUE THREAD

**Issue by IFNTig** [tastybento/ASkyBlock-Bugs-N-Features#99]
ok, askyblock is doing :
plugin.getPlayers().getIslandLevel(playerUUID);

**Comment by IFNTig** [comment]
if this is causing nullpointer exception, that means either 'plugin', or 'plugin.getPlayers()' is null 

add that

**Comment by tastybento** [comment]
Sorry, I don't understand. What is the issue? The title and your comments don't make sense to me.

**Comment by tastybento** [comment]
No answer.
